### ISSUE TITLE
googleapiclient.errors.ResumableUploadError: <HttpError 403 "The user's Drive storage quota has been exceeded.">

### ISSUE THREAD

**Issue by charliedgabriel** [sabeechen/hassio-google-drive-backup#10]
Please add info about your configuration here, along with a brief description of what you were doing and what happened.  Detail is always helpful for investigating an error.  You can enable verbos logging by setting {"verbose": true} in your add-on configuration and including that here.  :

Traceback (most recent call last):
  File "/app/backup/engine.py", line 83, in doBackupWorkflow
    self._checkForBackup()
  File "/app/backup/engine.py", line 296, in _checkForBackup
    self.drive.saveSnapshot(to_backup, self.hassio.downloadUrl(to_backup), self.folder_id)
  File "/app/backup/drive.py", line 100, in saveSnapshot
    status2, drive_response = self._retryDriveServiceCall(request, func=lambda a: a.next_chunk())
  File "/app/backup/drive.py", line 151, in _retryDriveServiceCall
    raise e
  File "/app/backup/drive.py", line 146, in _retryDriveServiceCall
    return func(request)
  File "/app/backup/drive.py", line 100, in <lambda>
    status2, drive_response = self._retryDriveServiceCall(request, func=lambda a: a.next_chunk())
  File "/usr/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/googleapiclient/http.py", line 927, in next_chunk
    raise ResumableUploadError(resp, content)
googleapiclient.errors.ResumableUploadError: <HttpError 403 "The user's Drive storage quota has been exceeded.">

**Comment by sabeechen** [comment]
This means you ran out of space in Google Drive.  By default you only get 15GB shared between Google Drive, Mail, and Photos.  If something in Google Drive is taking up the space, you can go to the Google Drive [quota page ](https://drive.google.com/drive/quota to see what it is).  To see how your storage space is used across all those Google projects, go [here](https://drive.google.com/settings/storage).  You'll either need to:
* Buy more storage form Google
* Store fewer snapshots
* Free up space in Drive/Gmail/Photos
* Make your snapshots smaller (see [this tip](https://github.com/sabeechen/hassio-google-drive-backup#will-this-fill-up-my-google-drive--why-are-my-snapshots-so-big))

I'll keep this open to remind me to surface a better error message when the add-on gets this exception from Drive.

**Comment by sabeechen** [comment]
The latest version (v0.6) reports this error correctly and displays the advice above for how to fix it.
