### ISSUE TITLE
Is your Patreon link down?

### ISSUE THREAD

**Issue by DannyFeliz** [sabeechen/hassio-google-drive-backup#1014]
https://www.patreon.com/sabeechen

![image](https://github.com/sabeechen/hassio-google-drive-backup/assets/5460365/6b4aed97-7bc6-4e2d-87cd-ce6b84ab5b78)

**Comment by sabeechen** [comment]
Thanks for pointing that out.  Patreon must have changed something at some point.  Fixed now to:
https://patreon.com/stephenbeechen
