### ISSUE TITLE
Old snapshots not visible

### ISSUE THREAD

**Issue by ivorco** [sabeechen/hassio-google-drive-backup#103]
The add on worked great and backup up different snapshots to a directory in my google drive.
Now reinstalled hassio and installed the addon, moved the snapshots to the new directory, but they don't show on the addon's snapshot list.
Nothing about that in the documentation.

**Comment by sabeechen** [comment]
Are you using your own client id and secret (eg from [this guide](https://github.com/sabeechen/hassio-google-drive-backup/blob/master/LOCAL_AUTH.md))?  If so, you have to use the same client id and secret on the new and old installation for them to see eachother's files.

Its part of Google Drive's security model, the files created with one client id can only be seen by that client id.  I'll update the docs to indicate that.

**Comment by orc886** [comment]
I can't remember when I used in the old install
What's funny, that I stumbled upon later, is that copying those backup files using a samba sever to the HA backup directory doesn't show them in the snapshots view.
So I'm not so sure that is the issue.

Anyway, is there a way to change that id?
Maybe copy it from one backup file to another?

**Comment by sabeechen** [comment]
Did you press the refresh button on the snapshot page in Home Assistant after you copied over the snapshots?  Sometimes it won't see them until you've forced it to refresh its cache.  Thats the only way I know of to get them back in the system.

**Comment by orc886** [comment]
More than once, didn't work

**Comment by sabeechen** [comment]
Thats very strange.  You might be able to figure out whats going wrong if you check the supervisor logs after you refresh the snapshots page (Hass.io > System > System Logs).  Often times errors get spit out there.   Also just to be sure, I'm talking about the refresh button on the snapshot page, not the one in your browser.
 
![image](https://user-images.githubusercontent.com/21026774/66069049-e15ed400-e50b-11e9-854c-bcf102309a65.png)

**Comment by orc886** [comment]
I tried refreshing from the add on screen, this screen, tried restarting
I'm not sure why, maybe the backup was partial, maybe something else
Right now I restored the backup from the yaml files individually

**Comment by m90att** [comment]
I cannot see backups in the front end that I've copied to the backup folder using samba.  I have tried 3 separate backups, I have rebooted the pi but they are still not there.

**Comment by sabeechen** [comment]
Do you see them in the Hass.io snapshots page?  You can reach it form the main Home Assistant UI ("Hass.io" > Snapshots").  The addon can only interact with snapshots that Hass.io recognizes.  If you don't see your snapshots there, try clicking the refresh icon at the top right of that Snapshots page and then looking at the supervisor logs ("Hass.io" > "System" > System Logs" > "Refresh") to see if it printed any errors.

When it finds snapshots, you'll see a log message like:
```
19-11-03 12:57:32 INFO (MainThread) [hassio.snapshots] Found 1 snapshot files
```

When it has problems, you'll see something like:
```
19-11-03 13:00:20 INFO (MainThread) [hassio.snapshots] Found 2 snapshot files
19-11-03 13:00:20 ERROR (MainThread) [hassio.snapshots.snapshot] Can't read snapshot tarfile /data/backup/corrupt_file.tar: truncated header
```

**Comment by m90att** [comment]
Hi, thanks for your reply. No I don't see them in the Hass.io snapshots page.  I've checked the log as you suggested and found the following errors:

`19-11-03 13:19:01 INFO (MainThread) [hassio.snapshots] Found 2 snapshot files
19-11-03 13:19:01 ERROR (MainThread) [hassio.snapshots.snapshot] Can't read snapshot tarfile /data/backup/c8b7a8ec.tar: unexpected end of data
19-11-03 13:19:01 ERROR (MainThread) [hassio.snapshots.snapshot] Can't read snapshot tarfile /data/backup/101.2 Update.tar: unexpected end of data`

Do you know what these mean?

**Comment by sabeechen** [comment]
That most likely means the snapshot files are corrupt, Hass.io can't read them.  Were they created by this addon and downloaded form Google Drive?  That could be a serious bug for me, though I've never seen it happen before.

I'd try at least downloading them again from where you originally got them, could be they only got partially downloaded or partially uploaded (eg why hass.io expects them to be bigger).  I've had problems with the samba addon in the past where it only partially uploads a file.  You should be able to check the file size to make sure it matches, or doing an MD5 hash of it to be totally sure.

You could also try opening them.  Its just a regular tarfile, so you could use 7zip to read them on windows or any archive manager on linux/mac.  If another application can decompress the snapshot that would likely mean something else is wrong with how Hass.io is reading it.

**Comment by m90att** [comment]
Hi, yes they were created with this addon on a different raspberry pi but the same version of hass.io.

I've created a partial one on the source installation (rpi 3) and have been able to get that to show up in the target installation (rpi 4) via uploading from the google drive addon.  I've tried restoring from it but am now waiting for it to come back online...it's been about 25 minutes so far and still nothing.

**Comment by dogmatic69** [comment]
I've come across this error too. I'm trying to restore a backup from around the same time (september 2019) and get the error in the logs. (I manually moved it from drive to hassio as it is not picked up in drive either)

```
19-11-03 13:19:01 ERROR (MainThread) [hassio.snapshots.snapshot] Can't read snapshot tarfile /data/backup/filename.tar: unexpected end of data
```

I can open the file just fine on linux and windows so it is not corrupt. I've made a snapshot of a new install and compared to the one I want to restore and the layout very different. 

Any idea how I can restore my backup from 2019?

**Comment by dogmatic69** [comment]
Ok, found that the homeassistant.tar within the archive is corrupt. Seems that there was some issues, perhaps due to space and this is the result:
Don't really understand how the backups can be so drastically different day to day

![image](https://user-images.githubusercontent.com/94674/93667570-45fda080-fa87-11ea-95f9-2e48c0fa296c.png)

**Comment by sabeechen** [comment]
I'm closing out old bugs and I don't think there is anything more I can do for this one.  If someone wold like more help with this feel free to reopen it and I'll do what I can.
