### ISSUE TITLE
add on not starting - no obvious errors

### ISSUE THREAD

**Issue by pawellygan** [sabeechen/hassio-google-drive-backup#1044]
Hi!

I used to use this add on before with no issues. Not long ago I removed it and now after reinstall - it stopped working.
Logs don't show anything odd... What this could be ?

<img width="882" alt="Screenshot 2024-05-21 at 15 25 04" src="https://github.com/sabeechen/hassio-google-drive-backup/assets/45388740/d203594e-c707-419c-b8aa-0b587f5e7a96">

**Comment by sabeechen** [comment]
thats a really odd message to see.  Do you see anything in the [supervisor logs](https://github.com/sabeechen/hassio-google-drive-backup?tab=readme-ov-file#im-getting-weird-errors--where-do-i-look-for-more-detils-about-an-error-supervisor-logs)?

**Comment by pawellygan** [comment]
> supervisor logs

<img width="571" alt="Screenshot 2024-05-29 at 17 47 38" src="https://github.com/sabeechen/hassio-google-drive-backup/assets/45388740/49ff2b6b-5172-4e52-a01c-d6c8ee322364">
<img width="1441" alt="Screenshot 2024-05-29 at 17 51 41" src="https://github.com/sabeechen/hassio-google-drive-backup/assets/45388740/1c7e83e7-0fc8-4f1a-ab10-4896908d49ce">

Logs below / or above

**Comment by pawellygan** [comment]
problem solved itself. Plugin is working again
