### ISSUE TITLE
Encryption of backups

### ISSUE THREAD

**Issue by lenisko** [sabeechen/hassio-google-drive-backup#106]
Hey there!

Any plans to support encryption of backups with `secret` or `pub-key` before sending to gdrive?

Cheers

**Comment by lenisko** [comment]
Ignore me...
>snapshot_password (default: None): When set, snapshots are created witha password. You can use a value from your secrets.yaml by prefixing the password with "!secret". You'll need to remember this password when restoring snapshots.

**Comment by sabeechen** [comment]
Glad you found it!
All the settings can also be modified from within the add-on (see the gear icon at the top of the page).
