### ISSUE TITLE
An unexpected error occurred: 404 Client Error: Not Found for url: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives

### ISSUE THREAD

**Issue by rikmaris** [sabeechen/hassio-google-drive-backup#109]
Traceback (most recent call last):
  File "/app/backup/coordinator.py", line 102, in _sync
    self._buildModel().sync(self._time.now())
  File "/app/backup/model.py", line 120, in sync
    self._syncSnapshots([self.source, self.dest])
  File "/app/backup/model.py", line 192, in _syncSnapshots
    from_source: Dict[str, AbstractSnapshot] = source.get()
  File "/app/backup/drivesource.py", line 73, in get
    self._info.drive_folder_id = self.getFolderId()
  File "/app/backup/drivesource.py", line 70, in getFolderId
    return self._getParentFolderId()
  File "/app/backup/drivesource.py", line 169, in _getParentFolderId
    self._folderId = self._validateFolderId()
  File "/app/backup/drivesource.py", line 188, in _validateFolderId
    return self._findDriveFolder()
  File "/app/backup/drivesource.py", line 196, in _findDriveFolder
    for child in self.drivebackend.query("mimeType='" + FOLDER_MIME_TYPE + "'"):
  File "/app/backup/driverequests.py", line 156, in query
    response = self.retryRequest("GET", URL_FILES + "?" + urlencode(q), is_json=True)
  File "/app/backup/driverequests.py", line 278, in retryRequest
    response.raise_for_status()
  File "/usr/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives

An unexpected error occurred: 404 Client Error: Not Found for url: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives

**Comment by sabeechen** [comment]
This typically means the snapshot folder has become inaccessible.  Some reasons that might happen:
- You deleted or trashed the snapshot folder.
- You changed the permissions on the snapshot folder in a way that made the addon lose access.
- You reauthorized the addon with Google Drive using a account or credentials
- You deauthorized the addon in your Google Account settings.

In all of these cases, the addon should try again, create a new snapshot folder, and upload snapshots there from then on.  Is the addon still displaying this error now?

**Comment by sabeechen** [comment]
I'm closing this out due to age, but feel free to reopen it if you think there is something I can help with.
