### ISSUE TITLE
Can't start addon

### ISSUE THREAD

**Issue by Shepard1sga** [sabeechen/hassio-google-drive-backup#12]
Hello! I instal this addon in my Hass.io. I configured the addon, but I can not run it
{
  "max_snapshots_in_hassio": 4,
  "max_snapshots_in_google_drive": 15,
  "days_between_snapshots": 1,
  "use_ssl": false,
  "snapshot_time_of_day": "03:00"
}
Error is: 
not a valid value for dictionary value @ data['options']. Got {'max_snapshots_in_hassio': 4, 'max_snapshots_in_google_drive': 15, 'days_between_snapshots': 1, 'use_ssl': False, 'snapshot_time_of_day': '03:00'}

**Comment by gunslingr** [comment]
Exactly the same thing happening here, I just installed it, reset the configuration to default and got the same error with defaulted config
I've also tried encapsulating the values in quotes  as shown in the directions (and how my other configs are) But to no avail:
{
  "max_snapshots_in_hassio": "4",
  "max_snapshots_in_google_drive": "4",
  "days_between_snapshots": "3",
  "use_ssl": "false"
}

not a valid value for dictionary value @ data['options']. Got {'max_snapshots_in_hassio': '4', 'max_snapshots_in_google_drive': '4', 'days_between_snapshots': '3', 'use_ssl': 'false'}

**Comment by sabeechen** [comment]
I'd made a mistake in the add-on configuration that was live for a few hours.  If you
* uninstall the add-on
* Go to the "add-on store" page in Hass.io and click the refresh icon in the top right
* reinstall the add-on

You should see the error go away.  The refresh from the add-on store page may not be necessary, I can't figure out how Hass.io caches add-on configuration.

**Comment by sabeechen** [comment]
Please re-open if you still run into trouble.
