### ISSUE TITLE
Need new option to stop containers before snapshot

### ISSUE THREAD

**Issue by Hedgehog57** [sabeechen/hassio-google-drive-backup#121]
Hello,

Thanks for a great work with Google Drive backup.

It's not a bug, but some kind of feature request.

For example one have history database in MySQL/MariaDB running in the container. When snapshot is created MySQL container is included in. When one try to run HASSIO after restoring MySQL container doesn't work. Problem is MariaDB require gracefull shutdown before taking snapshot.

This is a link to an issue in hassio-addons:
https://github.com/home-assistant/hassio-addons/issues/667

What we need?

We need an option. A list of containers which need to be shutted down before snapshot is taken. Google Drive Backup plugin shoud/could shutdown those containers, take snapshot, and start them back.

Hope You will understand my writing. I'm not too lazy to explain my hopes. ;)

**Comment by sabeechen** [comment]
Yikes, I've been using Maria DB recently for my personal instance and hadn't even considered this. 

- Ideally, the maria DB addon would be tolerant to snapshots on its own (eg doing a recovery automatically if the DB gets corrupted like this).
- Barring that, it would be better for this to be a built-in feature of Hass.io.  For example an option the addon maintainer adds that tells Hass.io to stop the addon while taking its snapshot.

If for some reason all that were impossible, I'd add the functionality to my add-on.  I'll wait a little bit on the discussion to see if someone who knows more about the addon proposes a solution.

**Comment by sabeechen** [comment]
Took me a while to get to this, but I've added this functionality in v0.101.3, which I just released.  You can choose addons to stop while snapshotting in the addon's settings (use the web-ui).  Let me know if you run into any problems with it.

**Comment by homeoneautomacao** [comment]
maybe it's a good idea to put in settings a time in seconds to set to wait for addons to finish. Ex: stop addons, wait 60 seconds, and then start the backup. Not always, but some restores are still corrupting, maybe not enough time for mariadb to stop properly before starting the backup.
