### ISSUE TITLE
An unexpected error occurred: 400 Client Error: Bad Request for url: https://www.googleapis.com/oauth2/v4/token

### ISSUE THREAD

**Issue by gojonny** [sabeechen/hassio-google-drive-backup#128]
Please add some information about your configuration and the problem you ran into here. More info really helps speed up debugging, and if you don't make it clear whats happening you're much more likely to get snarky comment from the dev before he helps.  Remember that its just one guy back here doing all of this and he's not *really* under any obligation to put up with your shit if you're disrespectful.  If english isn't your first language, don't sweat it.  Just try to be clear and I'll do the same for you.  Some things you might consider including:
 * What were you doing when the problem happened?
 * A screenshot if its something visual.
 * What configuration options are you using with the add-on?
 * What logs is the add-on printing out?  You can see the detailed logs by clicking "Logs" at the top right of the web-UI.
 * Are there any problematic logs from the Hassio supervisor?  You can get to them from the Home Assistant Interface from "Hass.io" > "System" > "System Log"
 

Traceback (most recent call last):
  File "/app/backup/coordinator.py", line 103, in _sync
    self._buildModel().sync(self._time.now())
  File "/app/backup/model.py", line 120, in sync
    self._syncSnapshots([self.source, self.dest])
  File "/app/backup/model.py", line 192, in _syncSnapshots
    from_source: Dict[str, AbstractSnapshot] = source.get()
  File "/app/backup/drivesource.py", line 73, in get
    self._info.drive_folder_id = self.getFolderId()
  File "/app/backup/drivesource.py", line 70, in getFolderId
    return self._getParentFolderId()
  File "/app/backup/drivesource.py", line 169, in _getParentFolderId
    self._folderId = self._validateFolderId()
  File "/app/backup/drivesource.py", line 187, in _validateFolderId
    if self._verifyBackupFolderWithQuery(folder_id):
  File "/app/backup/drivesource.py", line 165, in _verifyBackupFolderWithQuery
    raise e
  File "/app/backup/drivesource.py", line 154, in _verifyBackupFolderWithQuery
    folder = self._get(id)
  File "/app/backup/drivesource.py", line 192, in _get
    return self.drivebackend.get(id)
  File "/app/backup/driverequests.py", line 151, in get
    return self.retryRequest("GET", URL_FILES + id + "/?" + urlencode(q), is_json=True)
  File "/app/backup/driverequests.py", line 301, in retryRequest
    send_headers = self._getHeaders(refresh=refresh_token)
  File "/app/backup/driverequests.py", line 80, in _getHeaders
    "Authorization": "Bearer " + self.getToken(refresh=refresh),
  File "/app/backup/driverequests.py", line 140, in getToken
    raise e
  File "/app/backup/driverequests.py", line 137, in getToken
    resp = self.retryRequest("POST", URL_AUTH, is_json=True, data=data, auth_headers=self._getAuthHeaders(), cred_retry=False)
  File "/app/backup/driverequests.py", line 355, in retryRequest
    response.raise_for_status()
  File "/usr/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.googleapis.com/oauth2/v4/token

An unexpected error occurred: 400 Client Error: Bad Request for url: https://www.googleapis.com/oauth2/v4/token

**Comment by sabeechen** [comment]
I'd like to help, but please answer at least some of the questions from the template.  Just including the error message doesn't help me understand much.

The error message indicates that Google is rejecting the request to authenticate you.  The first thing I'd like you to try is reathenticating the addon with Google Drive.  You can do this by going to "Actions" > "Reauthorize with Google Drive" from the addon UI and following the instructions on the screen.

If that doesn't work, it would be helpful to know:
- Is the error still happening?  This is an error communicating with Google Drive, often these problems are transient and resolve themselves.
- Did you just install the add-on, or was it running fine for a while and this just started happening randomly?
- Were you doing anything with the add-on when the error started happening?
- Have you tried restarting the addon, home assistant, or Hass.io?

**Comment by sabeechen** [comment]
Closing this out due to age, but feel free to reopen if you think I can help more.
