### ISSUE TITLE
Error when restoring a snapshot

### ISSUE THREAD

**Issue by sabeechen** [sabeechen/hassio-google-drive-backup#130]
SnowmanUT had trouble restoring a snapshot created and restored by the addon, details in [this post](https://community.home-assistant.io/t/hass-io-add-on-hass-io-google-drive-backup/107928/201?u=sabeechen).  He tried:
- Uploading it from Drive
- Copying it directly to the /backup folder (renamign and not renaming).

When uploading, the addon gave this error:
```
Traceback (most recent call last):
File “/app/backup/uiserver.py”, line 523, in handleError
return call()
File “/app/backup/uiserver.py”, line 439, in
return self.handleError(lambda: self._upload(slug))
File “/app/backup/uiserver.py”, line 442, in _upload
self._coord.uploadSnapshot(slug)
File “/app/backup/coordinator.py”, line 122, in uploadSnapshot
self._withSoftLock(lambda: self._uploadSnapshot(slug))
File “/app/backup/coordinator.py”, line 211, in _withSoftLock
return callable()
File “/app/backup/coordinator.py”, line 122, in
self._withSoftLock(lambda: self._uploadSnapshot(slug))
File “/app/backup/coordinator.py”, line 134, in _uploadSnapshot
created = self._model.source.save(snapshot, self._model.dest.read(snapshot))
File “/app/backup/hasource.py”, line 215, in save
raise UploadFailed()
backup.exceptions.UploadFailed
```

**Comment by sabeechen** [comment]
After copying the snapshot to your backup folder and clicking refresh, do you see any errors printed out to Hassio supervisor logs?  You can get to it by going to "Hass.io" > "System" > "System Log" from the main Home assistant interface.

I suspect the tar file may have gotten corrupted when it was uploaded.  Woudl you be willing to share the snapshot file with me?  I understand you may not want to for privacy's sake, but if so you could share the file on drive with stpehen@beechens.com

**Comment by SnowmanUT** [comment]
I figured out the snapshot was corrupt in logs and through further investigation of trying to make other snapshots. The issue was I was running hasio in a VM qcow2 image in unraid and the image was maxed out so the snapshot would error out when creating one and apparently made a corrupt one as well. I ended up deleted all old images to make room in VM to make 1 good image and got it to work in new instance of Hass.io which is why I was doing it in the first place to move it to larger VM image.

**Comment by sabeechen** [comment]
Its a bummer that Hass.io doesn't clean up the corrupted snapshot, that doesn't leave my addon with a way of knowing that the snapshot actually failed.

Regardless, I'm glad you were able to get things working again.  Thanks for getting back to me.
