### ISSUE TITLE
Internal Server Error on authentication

### ISSUE THREAD

**Issue by nicolas-fricke** [sabeechen/hassio-google-drive-backup#133]
I am getting a 500 Internal Server Error when trying to connect the add-on to my Google Drive after a fresh Hass.io install.

![image](https://user-images.githubusercontent.com/1423331/69921697-d6d1a400-1494-11ea-9f83-20c9af37c041.png)

**Steps to reproduce:**
1. Install and enter Hass.io on a Raspberry Pi 3
1. Install and start the Hass.io Google Backup plugin
1. Open the plugin UI
1. Click on the _"Authenticate with Google Drive"_ button
1. The page it redirects to shows the error

The page I get redirected to is of the format:
```
https://philosophyofpen.com/login/backup.py?redirectbacktoken=http%3A%2F%2Fhassio.local%3A8123%2Fapi%2Fhassio_ingress%2F<redacted>%2Ftoken
```

_Note: I replaced the actual hash between (`hassio_ingress%2F` and `%2Ftoken`) of my installation with `<redacted>`_.

Both, the app and Hass.io are still on their default settings and two days ago I could still connect the add-on to Google Drive without any issues.

**Versions:**
_Hass.io Google Backup:_ 0.99.0
_Home Assistant:_ 0.102.3
_Hass.io supervisor:_ 192
_HassOS:_ 2.12

Not sure if this is in some way related to https://github.com/sabeechen/hassio-google-drive-backup/issues/69 ?

**Comment by sabeechen** [comment]
Thanks for bringing this to my attention, my server for connecting with Google Drive ran out of memory.  Not sure how long its been like that :(
You should be able to authenticate now.

Note to others: this shouldn't affect your ability to use the addon after authenticating.  The server is only used for the initial setup.

**Comment by nicolas-fricke** [comment]
Thanks for looking into this – yes, everything seems to work normal again now :)

And also a huge thank you for this very useful add-on! 🤗🎉

**Comment by jmartnav** [comment]
I'm having the same issue just now. Can you take a look? Will the local authentication work instead?
Thank you very much.

**Comment by fillwe** [comment]
Got the same error right now as well!

**Comment by ddjobe** [comment]
Just got the same error.

**Comment by jmartnav** [comment]
It works!!!!! Thanks a lot.

**Comment by jmartnav** [comment]
> I'm having the same issue just now. Can you take a look? Will the local authentication work instead?
> Thank you very much.



> I'm having the same issue just now. Can you take a look? Will the local authentication work instead?
> Thank you very much.

It works now. Thanks a lot¡¡¡¡¡

**Comment by fillwe** [comment]
Works for me again, thanks!

**Comment by sabeechen** [comment]
Server went down for a bit but came back up on its own.  I'll be moving toward better infrastructure in the future so this should be the last time it goes down.

**Comment by Chr1stian** [comment]
Is it down again @sabeechen ? Because I just got the same error

**Comment by thiagotmaa** [comment]
I have the same problem

**Comment by sabeechen** [comment]
Yup it ran into the same problem again.  Its fixed now, and THIS should be the last time it happens ;)

**Comment by thiagotmaa** [comment]
> Sim, ele teve o mesmo problema novamente. Está consertado agora, e ESTA deve ser a última vez que isso acontece;)


Thank you very much, it worked 100%
