### ISSUE TITLE
problem with binary sensore snapshot stale

### ISSUE THREAD

**Issue by legolas0802** [sabeechen/hassio-google-drive-backup#14]
I installed this wonderful addon on hassio 32bit 0.90.2, hassos 2.10, hassio supervisor 152. It works all perfectly excluded the binary sensor which is always false, so I can't get notifications. I don't know how to be useful in the attractiveness of the binary sensor I read device class: problem

**Comment by sabeechen** [comment]
I'm not quite sure what you're asking but....
* The sensor becomes true if your snapshots are stale, eg if there is some problem backing them up to Google Drive or creating them in Home Assistant.  See this [FAQ](https://github.com/sabeechen/hassio-google-drive-backup#i-never-look-at-ha-notifications--can-i-show-information-about-backups-in-my-home-assistant-interface) for some ways to use it, if thats what you're looking for.
* The attribute [device_class = "problem"](https://www.home-assistant.io/components/binary_sensor/#device-class) indicates that the sensor reports a problem.  Convention is that when the sensor is "True", that means there is a problem.  When the sensor is false, that means the snapshots are up to date. 
* If you don't like any of this, you can always hide or change the appearance of the entity by [customizing it](https://www.home-assistant.io/docs/configuration/customizing-devices/).

**Comment by sabeechen** [comment]
If you'd like to test triggerring the sensor, you can go to the "States" Developer Tool (on the right of the UI, the icon kind of looks like "<>").  From there you can set the state for the sensor to True.

**Comment by legolas0802** [comment]
now everything is clear to me, I was hoping to be able to receive a notification when the backup was completed. Instead the sensor logic provides a notification in case of problems

**Comment by sabeechen** [comment]
With the latest release (v0.8), You could also trigger an automation off of the 'last_snapshot' attribute of the 'sensor.snapshot_backup' sensor the add-on publishes.  This is the date of the latest snapshot it can find, so it changes any time a new one is started by the add-on or anywhere else.
