### ISSUE TITLE
HTTP 403 Error while uploading a snapshot to Google Drive

### ISSUE THREAD

**Issue by Znatniy-Zveryuga** [sabeechen/hassio-google-drive-backup#140]
Traceback (most recent call last):
  File "/app/backup/coordinator.py", line 103, in _sync
    self._buildModel().sync(self._time.now())
  File "/app/backup/model.py", line 145, in sync
    upload.addSource(self.dest.save(upload, self.source.read(upload)))
  File "/app/backup/drivesource.py", line 117, in save
    for progress in self.drivebackend.create(bytes, file_metadata, MIME_TYPE):
  File "/app/backup/driverequests.py", line 262, in create
    raise e
  File "/app/backup/driverequests.py", line 248, in create
    partial = self.retryRequest("PUT", location, headers=headers, data=data, patch_url=False)
  File "/app/backup/driverequests.py", line 341, in retryRequest
    response.raise_for_status()
  File "/usr/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=redacted

An unexpected error occurred: 403 Client Error: Forbidden for url: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=redacted

**Comment by sabeechen** [comment]
This means for some reason Google denied the addon access to your Google Drive.  I'd try two things right off the bat:
1. Restart the add-on, see if it work then.  This often fixes things.
2. If not, then within the addon go to "Actions" -> "Reauthorize Google Drive" and follow the instructions on the page to re-link Google Drive with the addon.

**Comment by sabeechen** [comment]
Closing this out due to age but if you think there is more I can do to help, feel free to reopen.

**Comment by Znatniy-Zveryuga** [comment]
I have a version: the backup file name is too long. A synchronization failure occurred with such files which had a very big name, for example: "made such amendments, added such automation, so-and-so date, version hass.io so-and-so"
