### ISSUE TITLE
Add HACS Support

### ISSUE THREAD

**Issue by daconrad0** [sabeechen/hassio-google-drive-backup#144]
Is is possible to add HACS Support so updates will be easier to manage.   Love this add-on.

**Comment by sabeechen** [comment]
This is my first time seeing HCAS, but iiuc it runs just on Home Assistant.  This addon is pretty tightly coupled to Hass.io's features.  It basically just calls Hass.io snapshot service and then syncs the results to Google Drive.  It wouldn't be able to do much without Hass.io.
