### ISSUE TITLE
An unexpected error occurred: 404 Client Error: Not Found for url: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives

### ISSUE THREAD

**Issue by ajgc96** [sabeechen/hassio-google-drive-backup#148]
Please add some information about your configuration and the problem you ran into here. More info really helps speed up debugging, and if you don't make it clear whats happening you're much more likely to get snarky comment from the dev before he helps.  Remember that its just one guy back here doing all of this and he's not *really* under any obligation to put up with your shit if you're disrespectful.  If english isn't your first language, don't sweat it.  Just try to be clear and I'll do the same for you.  Some things you might consider including:
 * What were you doing when the problem happened?
 * A screenshot if its something visual.
 * What configuration options are you using with the add-on?
 * What logs is the add-on printing out?  You can see the detailed logs by clicking "Logs" at the top right of the web-UI.
 * Are there any problematic logs from the Hassio supervisor?  You can get to them from the Home Assistant Interface from "Hass.io" > "System" > "System Log"
 

Traceback (most recent call last):
  File "/app/backup/coordinator.py", line 103, in _sync
    self._buildModel().sync(self._time.now())
  File "/app/backup/model.py", line 120, in sync
    self._syncSnapshots([self.source, self.dest])
  File "/app/backup/model.py", line 192, in _syncSnapshots
    from_source: Dict[str, AbstractSnapshot] = source.get()
  File "/app/backup/drivesource.py", line 73, in get
    self._info.drive_folder_id = self.getFolderId()
  File "/app/backup/drivesource.py", line 70, in getFolderId
    return self._getParentFolderId()
  File "/app/backup/drivesource.py", line 169, in _getParentFolderId
    self._folderId = self._validateFolderId()
  File "/app/backup/drivesource.py", line 189, in _validateFolderId
    return self._findDriveFolder()
  File "/app/backup/drivesource.py", line 197, in _findDriveFolder
    for child in self.drivebackend.query("mimeType='" + FOLDER_MIME_TYPE + "'"):
  File "/app/backup/driverequests.py", line 170, in query
    response = self.retryRequest("GET", URL_FILES + "?" + urlencode(q), is_json=True)
  File "/app/backup/driverequests.py", line 355, in retryRequest
    response.raise_for_status()
  File "/usr/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives

An unexpected error occurred: 404 Client Error: Not Found for url: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives

**Comment by sabeechen** [comment]
It looks like you're running an older version of the addon, so please make sure you update if thats the case.   Did you read the text at the top of the bug before you submitted this?  Please provide me with some information about what was happening when you saw the error.  Did you just install the addon?  Was it working for a while and then stopped?  Are you able to get to the snapshot folder?

As a first step, I'd suggest that you update and then try "Actions" -> Reauthorize google drive" from the addon web-ui to reconnect it with google drive
