### ISSUE TITLE
IP resolution for Home Assistant Server

### ISSUE THREAD

**Issue by Malklor** [sabeechen/hassio-google-drive-backup#151]
I am getting this error in my logs for the snapshots state sensor

Error on call https://1.1.1.1:8123/api/states/binary_sensor.snapshots_stale: [Errno 104] Connection reset by peer

I replaced my IP 1.1.1.1 but my configuration is using Clourdflare origin certificates to protect my Home Assistant server as a result my domain I connect to Home Assistant resolves to an external IP that is protected by host name. 

It appears as if your script resolving my host name to IP and this is causing it to fail to connect as the hostname doesn't match the certificate so Cloudflare rejects the connection.

In addition the port 8123 is not externally accessible so this won't work.

I see two options

1. Configuration for external host names that does not pass port
2. Configuration to override the IP to a local IP (although not sure how that would work if orgin cert would reject this)

**Comment by ercsey** [comment]
Same issue here using with ubuntu + docker + Hass.io.

> 20-02-12 05:14:15 ERROR (MainThread) [hassio.homeassistant] Error on call http://172.30.32.1:8123/api/states/binary_sensor.snapshots_stale: [Errno 104] Connection reset by peer

**Comment by sabeechen** [comment]
The addon doesn't get any control over the IP address used to contact Home Assistant, its actually a proxy provided by Hass.io within the isolated addon network.  Its not a request that goes to the "real" network and should be getting resolved internally ([see here](https://developers.home-assistant.io/docs/en/hassio_addon_communication.html#home-assistant) for details).   I'm assuming that error message is being printed in the supervisor logs?  This would imply that Hass.io itself is having trouble reaching the Home Assistant server.  Is there anything custom about your network setup that might be causing this?  Usually the proxy goes to an address like 172.30.X.X on the internal docker network, 1.1.1.1 is an extremely suspicious IP Address.

**Comment by sabeechen** [comment]
Closing this for now, but feel free to reopen if there is more I can help with.
