### ISSUE TITLE
constant authenticating snapshop.stale

### ISSUE THREAD

**Issue by tukadafoonday** [sabeechen/hassio-google-drive-backup#152]
Anyone know why I get authentication logs constantly with this addon?

because of this I frequently have the container ip address on the banned ip's.

here's just a small section of my log file - https://paste.ubuntu.com/p/5n429P8JtV/

My setup is I3 intel NUC, proxmox, vm ubuntu server, hassio on a generic linux machine.

hassio version 105.2

Thank you!

**Comment by sabeechen** [comment]
You have debug logs turned on and Home Assistant [logs to debug](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/http/auth.py#L127) when someone authenticates, so what you're seeing is expected.  You can:
* Ignore it
* Log only to info instead (I think thats the default)
* Change the logging for homeassistant.components.http.auth to something higher (eg info). See [these instructions](https://www.home-assistant.io/integrations/logger/).
* Disable publishing the snapshot stale sensor (see addon [settings](https://github.com/sabeechen/hassio-google-drive-backup#example-turn-off-notifications-and-staleness-sensor))
