### ISSUE TITLE
Unable to authenticate - server error

### ISSUE THREAD

**Issue by zerocritical** [sabeechen/hassio-google-drive-backup#153]
![Screenshot_20200216-093327_Chrome](https://user-images.githubusercontent.com/55267791/74596209-3442bd80-50a0-11ea-8f1a-e9e524598818.jpg)
A server error is displayed when trying to authenticate. Screenshot attached.

**Comment by fillwe** [comment]
Got the same error, more people reporting the same issue here https://github.com/sabeechen/hassio-google-drive-backup/issues/133

**Comment by sabeechen** [comment]
I seems the server went down for a bit but came back up on its own.  I'll be moving to better infrastructure in a while, which should pretty much eliminate my downtime.
