### ISSUE TITLE
Home Assistant database corrupted after backup has been restored

### ISSUE THREAD

**Issue by elbueno222** [sabeechen/hassio-google-drive-backup#154]
After restoring one of the backups generated with this tool I have started to receive a lot of errors about the database being corrupted. I have executed this command to try to fix the database:
`sqlite3 ./home-assistant_v2.db “.dump” | sqlite3 ./home-assistant_v2.db.fix`
But the output file was empty, so I have deleted the database (loosing all the historic data). This is one example of the errors:
ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.DatabaseError) database disk image is malformed

**Comment by sabeechen** [comment]
The addon actually uses just uses Hass.io's services to create and restore the snapshot, so its almost certainly the case that Hass.io caused this corruption.  Unfortunately it doesn't always do a great job of making sure files are in a good state before adding them to a snapshot file and so a lot of things can go wrong depending on exactly what was being written at the time of the snapshot.  For example, the MariaDB addon will always get its DB corrupted if you try to snapshot it ([related bug](https://github.com/home-assistant/hassio-addons/issues/667), but they're working on it).

If you'd like to try and take a crack at recovering the database further, I was able to find some potentially helpful guidance [here ](https://www.froebe.net/blog/2015/05/27/error-sqlite-database-is-malformed-solved/).

**Comment by elbueno222** [comment]
> The addon actually uses just uses Hass.io's services to create and restore the snapshot, so its almost certainly the case that Hass.io caused this corruption. Unfortunately it doesn't always do a great job of making sure files are in a good state before adding them to a snapshot file and so a lot of things can go wrong depending on exactly what was being written at the time of the snapshot. For example, the MariaDB addon will always get its DB corrupted if you try to snapshot it ([related bug](https://github.com/home-assistant/hassio-addons/issues/667), but they're working on it).
> 
> If you'd like to try and take a crack at recovering the database further, I was able to find some potentially helpful guidance [here ](https://www.froebe.net/blog/2015/05/27/error-sqlite-database-is-malformed-solved/).

Thank you for the quick response
