### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by ryanvoorspoels** [sabeechen/hassio-google-drive-backup#155]
Internal Server Error external domain (philosophyofpen.com

**Comment by sabeechen** [comment]
My server went down for a bit.  Should be back up.  I'm moving to some better hosting in the near future so apologies if it comes up again before then.

**Comment by HyggeJJ** [comment]
I get this error quite often, when I try to authenticate with google.
For example I get it right now, which makes it impossible to restore an image :-(

**Comment by ryanvoorspoels** [comment]
If you want to restore an image you can do that.
If you install a clean image from homeassistant and you activate ftp on it.
You can download your backup from google drive put it in the folder backup and restart homeassistant.
If done you can now go to supervisor snapshots and there you will find your backup under Available snapshots click on it and restore selected.
if not, wait until Sabeechen solves the problem with the server.

**Comment by HyggeJJ** [comment]
Thanks a lot for the information. I am totally new to Hassio, so everything is pretty difficult at the moment. Though, I have a Google backup that I would like to restore.
How do I enable FTP, to download the backup from Google Drive? The only thing I found in the Add-on store was a FTP Server, but not a FTP client?
 
> 
> @HyggeJJ
> 
> If you want to restore an image you can do that.
> If you install a clean image from homeassistant and you activate ftp on it.
> You can download your backup from google drive put it in the folder backup and restart homeassistant.
> If done you can now go to supervisor snapshots and there you will find your backup under Available snapshots click on it and restore selected.
> if not, wait until Sabeechen solves the problem with the server.
> 
> Or use your own api : https://github.com/sabeechen/hassio-google-drive-backup/blob/master/LOCAL_AUTH.md

**Comment by ryanvoorspoels** [comment]
> 
> 
> Thanks a lot for the information. I am totally new to Hassio, so everything is pretty difficult at the moment. Though, I have a Google backup that I would like to restore.
> How do I enable FTP, to download the backup from Google Drive? The only thing I found in the Add-on store was a FTP Server, but not a FTP client?
> 
> > @HyggeJJ
> > If you want to restore an image you can do that.
> > If you install a clean image from homeassistant and you activate ftp on it.
> > You can download your backup from google drive put it in the folder backup and restart homeassistant.
> > If done you can now go to supervisor snapshots and there you will find your backup under Available snapshots click on it and restore selected.
> > if not, wait until Sabeechen solves the problem with the server.
> > Or use your own api : https://github.com/sabeechen/hassio-google-drive-backup/blob/master/LOCAL_AUTH.md

No Problem! You install the FTP plugin in the addon screen.
Then you go to configuration in the ftp server.
you can choose a username and password and from allow_chmod to ssl: I put everything on true.
You safe the configuration and start the plugin.

When the ftp server is activated you can go to windows explorer  - this PC - add a network connection: ftp://IP_ADRES_HOMEASSISTAN and the username and password that you have chosen. (only if you use windows ask google for ftp connections if you use another system)

If the connection is open you wil see the backup folder. You can download your backup from google drive and put it into the folder. Don't unzip it!
Then restart homeassistant and follow the steps in my earlier message.
