### ISSUE TITLE
[Enhancement] download to hassio

### ISSUE THREAD

**Issue by FrancYescO** [sabeechen/hassio-google-drive-backup#157]
Actually the download will start just a browser download, could be usefull to download the backup locally where hassio is running ipotetically to start a restore on a new installed instance of hassio

**Comment by sabeechen** [comment]
If the snapshot is in Google Drive but not Home Assistant, you can select "Upload" from the "ACTION" menu to do just that.  I'd preemptively agree that "Upload" is a misleading thing to call it.  I *really* should give it a different name but I haven't been able to think of one short enough to fit in the menu.  I'm open to suggestions, lol.
