### ISSUE TITLE
An unexpected error occurred: 403 Client Error: Forbidden for url: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives

### ISSUE THREAD

**Issue by DejavuDmitry** [sabeechen/hassio-google-drive-backup#158]
Please add some information about your configuration and the problem you ran into here. 
More info really helps speed up debugging, if you don't even read this and help me understand what happened, I probably won't help you.  
Remember that its just one guy back here doing all of this.  
If english isn't your first language, don't sweat it.  Just try to be clear and I'll do the same for you.  Some things you might consider including:
 * What were you doing when the problem happened?
 * A screenshot if its something visual.
 * What configuration options are you using with the add-on?
 * What logs is the add-on printing out?  You can see the detailed logs by clicking "Logs" at the right of the web-UI.
 * Are there any problematic looking logs from the Hassio supervisor?  You can get to them from the Home Assistant Interface from "Hass.io" > "System" > "System Log"
 

Traceback (most recent call last):
  File "/app/backup/coordinator.py", line 109, in _sync
    self._buildModel().sync(self._time.now())
  File "/app/backup/model.py", line 127, in sync
    self._syncSnapshots([self.source, self.dest])
  File "/app/backup/model.py", line 205, in _syncSnapshots
    from_source: Dict[str, AbstractSnapshot] = source.get()
  File "/app/backup/drivesource.py", line 86, in get
    self._info.drive_folder_id = self.getFolderId()
  File "/app/backup/drivesource.py", line 79, in getFolderId
    return self._getParentFolderId()
  File "/app/backup/drivesource.py", line 204, in _getParentFolderId
    self._folderId = self._validateFolderId()
  File "/app/backup/drivesource.py", line 230, in _validateFolderId
    return self._findDriveFolder()
  File "/app/backup/drivesource.py", line 238, in _findDriveFolder
    for child in self.drivebackend.query("mimeType='" + FOLDER_MIME_TYPE + "'"):
  File "/app/backup/driverequests.py", line 173, in query
    response = self.retryRequest("GET", URL_FILES + "?" + urlencode(q), is_json=True)
  File "/app/backup/driverequests.py", line 344, in retryRequest
    response.raise_for_status()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives

An unexpected error occurred: 403 Client Error: Forbidden for url: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives

**Comment by sabeechen** [comment]
Sorry its taken me so long to get back on this, but Ive just released a new version of the addon (0.101.0) that uses a mostly new authentication mechanism that should resolve this if you attempt to reauthorize the addon with Google Drive.  I'm closing this for now, but feel free to reopen it if you continue to see problems with the new version.
