### ISSUE TITLE
Exception: Request to Hassio failed, HTTP error: <Response [400]> Message: {"result": "error", "message": null}

### ISSUE THREAD

**Issue by xt16johnny** [sabeechen/hassio-google-drive-backup#16]
Hello, 
I am having some problems with this add-on. 

This started on my first installation of the add-on. I had assumed it was my lack of reading the instructions and not enabling 'use_ssl', as making that true and restarting it fixed the issue. However a few days pass and now this has started raising itself again. 

The web interface for the G.Drive Backup shows the below, and the latest backup has not been uploaded - shows 'waiting'. 

Running HASS 0.91.2 on a Pi 3, HassOS 2.10. 

> Traceback (most recent call last):
>   File "/app/backup/engine.py", line 92, in doBackupWorkflow
>     self._checkForBackup()
>   File "/app/backup/engine.py", line 278, in _checkForBackup
>     self._purgeHaSnapshots()
>   File "/app/backup/engine.py", line 271, in _purgeHaSnapshots
>     self.hassio.deleteSnapshot(oldest_hassio)
>   File "/app/backup/hassio.py", line 124, in deleteSnapshot
>     self._postHassioData(delete_url, {})
>   File "/app/backup/hassio.py", line 170, in _postHassioData
>     return self._validateHassioReply(requests.post(url, headers=HEADERS, json = json_data))
>   File "/app/backup/hassio.py", line 153, in _validateHassioReply
>     raise Exception('Request to Hassio failed, HTTP error: {0} Message: {1}'.format(resp, resp.text))
> Exception: Request to Hassio failed, HTTP error: <Response [400]> Message: {"result": "error", "message": null}

Thanks very much for your time.

**Comment by sabeechen** [comment]
Closing this out because I haven't heard back in a while and I suspect you're home assistant instance was just unreachable briefly (for whatever reason).  Feel free to reopen if you can get me some more information to work off of.
