### ISSUE TITLE
ERROR Unable to reach Home Assistant (HTTP 502).  Is it restarting?

### ISSUE THREAD

**Issue by BertrumUK** [sabeechen/hassio-google-drive-backup#162]
I noticed yesterday that the stale sensor was not clearing and the logs were showing a 502 error and there is no binary sensor being enabled even though it has not been disabled in the settings

03-07 17:04:09 INFO Starting server on port 8099
03-07 17:04:09 INFO Server started
03-07 17:04:09 INFO Syncing Snapshots
03-07 17:05:14 INFO Syncing Snapshots
03-07 17:11:25 ERROR Unable to reach Home Assistant (HTTP 502).  Is it restarting?

![Firefox_Screenshot_2020-03-07T17-16-35 873Z](https://user-images.githubusercontent.com/22644029/76147762-938c6000-6097-11ea-8a49-7d4a70e1c340.png)

The snapshots appear to be working as normal and I can access them from within Ingress

![Firefox_Screenshot_2020-03-07T17-19-02 683Z](https://user-images.githubusercontent.com/22644029/76147801-cfbfc080-6097-11ea-95da-3081df152756.png)

Here are the most recent logs

03-07 17:04:09 INFO Starting server on port 8099
03-07 17:04:09 INFO Server started
03-07 17:04:09 DEBUG Sync requested by Coordinator
03-07 17:04:09 INFO Syncing Snapshots
03-07 17:04:09 DEBUG Making Hassio request: http://hassio/snapshots
03-07 17:04:09 DEBUG Making Hassio request: http://hassio/snapshots/d7d07b31/info
03-07 17:04:09 DEBUG Making Hassio request: http://hassio/snapshots/deca2d13/info
03-07 17:04:09 DEBUG Making Hassio request: http://hassio/snapshots/7cfdbcb5/info
03-07 17:04:09 DEBUG Making Hassio request: http://hassio/snapshots/e8bf77cb/info
03-07 17:04:09 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/
03-07 17:04:10 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/
03-07 17:04:30 DEBUG Making Hassio request: http://hassio/addons/self/info
03-07 17:04:30 DEBUG Making Hassio request: http://hassio/info
03-07 17:04:30 DEBUG Making Hassio request: http://hassio/homeassistant/info
03-07 17:04:30 DEBUG Making Hassio request: http://hassio/supervisor/info
03-07 17:05:14 DEBUG Making Hassio request: http://hassio/addons/self/options
03-07 17:05:14 DEBUG Sync requested by UI Server
03-07 17:05:14 INFO Syncing Snapshots
03-07 17:05:14 DEBUG Making Hassio request: http://hassio/snapshots
03-07 17:05:14 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/
03-07 17:05:15 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files
03-07 17:11:25 ERROR Unable to reach Home Assistant (HTTP 502).  Is it restarting?

I have restarted Hassio, rebooted the Pi4 , deleted the add-on and added it back and reauthenticated with Google but It still shows this 502 error

**Comment by sabeechen** [comment]
The addon talks to Home Assistant through a proxy that [Hass.io provides](https://developers.home-assistant.io/docs/hassio_addon_communication/#home-assistant-core), and a HTTP 502 error means Hass.io is having trouble serving that proxy.  Do you see any errors in the supervisor log that get printed at the same time as the log message from the addon?  You should be able to see it by going to "Supervisor" > "System" > "System Log".

**Comment by BertrumUK** [comment]
Yes, here are the logs 

20-03-07 19:23:40 ERROR (MainThread) [supervisor.homeassistant] Can't update Home Assistant access token!
20-03-07 19:23:40 ERROR (MainThread) [supervisor.api.proxy] Authenticate error on API for request states/binary_sensor.snapshots_stale
20-03-07 19:28:45 ERROR (MainThread) [supervisor.homeassistant] Can't update Home Assistant access token!
20-03-07 19:28:45 ERROR (MainThread) [supervisor.api.proxy] Authenticate error on API for request states/binary_sensor.snapshots_stale
20-03-07 19:33:50 ERROR (MainThread) [supervisor.homeassistant] Can't update Home Assistant access token!
20-03-07 19:33:50 ERROR (MainThread) [supervisor.api.proxy] Authenticate error on API for request states/binary_sensor.snapshots_stale
20-03-07 19:38:55 ERROR (MainThread) [supervisor.homeassistant] Can't update Home Assistant access token!
20-03-07 19:38:55 ERROR (MainThread) [supervisor.api.proxy] Authenticate error on API for request states/binary_sensor.snapshots_stale
20-03-07 19:44:00 ERROR (MainThread) [supervisor.homeassistant] Can't update Home Assistant access token!
20-03-07 19:44:00 ERROR (MainThread) [supervisor.api.proxy] Authenticate error on API for request states/binary_sensor.snapshots_stale

**Comment by BertrumUK** [comment]
![image](https://user-images.githubusercontent.com/22644029/76151436-0e13aa80-60ad-11ea-9b06-c16356063a98.png)
20-03-07 19:49:38 INFO (MainThread) [supervisor.homeassistant] Detect a running Home Assistant instance
20-03-07 19:50:25 INFO (SyncWorker_3) [supervisor.docker.interface] Stop addon_cebe7a76_hassio_google_drive_backup application
20-03-07 19:50:27 INFO (SyncWorker_3) [supervisor.docker.interface] Clean addon_cebe7a76_hassio_google_drive_backup application
20-03-07 19:50:29 INFO (SyncWorker_14) [supervisor.docker.addon] Start Docker add-on sabeechen/hassio-google-drive-backup-armv7 with version 0.100.0
20-03-07 19:50:31 INFO (MainThread) [supervisor.api.security] /homeassistant/info access from cebe7a76_hassio_google_drive_backup
20-03-07 19:50:31 INFO (MainThread) [supervisor.api.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
20-03-07 19:50:31 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-03-07 19:50:31 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
20-03-07 19:50:31 INFO (MainThread) [supervisor.api.security] /snapshots/d7d07b31/info access from cebe7a76_hassio_google_drive_backup
20-03-07 19:50:31 INFO (MainThread) [supervisor.api.security] /snapshots/deca2d13/info access from cebe7a76_hassio_google_drive_backup
20-03-07 19:50:31 INFO (MainThread) [supervisor.api.security] /snapshots/7cfdbcb5/info access from cebe7a76_hassio_google_drive_backup
20-03-07 19:50:31 INFO (MainThread) [supervisor.api.security] /snapshots/e8bf77cb/info access from cebe7a76_hassio_google_drive_backup


OK - this is fixed now - it was the IP ban causing the issue.

Thanks again for a great add-on 👍
