### ISSUE TITLE
unable to start Google-Drive-backup service

### ISSUE THREAD

**Issue by bwanajag** [sabeechen/hassio-google-drive-backup#164]
When I click "start" to start the GDB service, nothing happens.  I get the following in the logs.

`20-03-12 06:24:42 ERROR (SyncWorker_3) [supervisor.docker] Can't create container from addon_cebe7a76_hassio_google_drive_backup: 404 Client Error: Not Found ("No such image: sabeechen/hassio-google-drive-backup-amd64:0.100.0")`

**Comment by bwanajag** [comment]
I started with a fresh install of homeassistant to see if that would help before restoring from a snapshot.  This time I could not even add the Google-Drive-backup repository.  I received the following error.
`20-03-12 08:53:11 ERROR (MainThread) [supervisor.store.git] Can't clone https://github.com/sabeechen/hassio-google-drive-backup repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone --depth=1 --recursive --shallow-submodules -v https://github.com/sabeechen/hassio-google-drive-backup /data/addons/git/cebe7a76
  stderr: 'Cloning into '/data/addons/git/cebe7a76'...
POST git-upload-pack (192 bytes)
POST git-upload-pack (201 bytes)
fatal: unable to open /data/addons/git/cebe7a76/.git/objects/pack/tmp_pack_8SpUNg: No such file or directory
fatal: index-pack failed
'.
20-03-12 08:53:11 ERROR (MainThread) [supervisor.store] Can't load from repository https://github.com/sabeechen/hassio-google-drive-backup`

**Comment by sabeechen** [comment]
I've had some users run into this problem before ([other bugs](https://github.com/sabeechen/hassio-google-drive-backup/issues?q=is%3Aissue+fatal%3A+index-pack+failed)).  Here is the TL;DR:
- We've never been able to identify precisely what fixes it.
- Everyone who has encountered it has been able to fix it (eventually).
- It seems like its a bug in how Hass.io uses Git.  Something like Hass.io runs a git command that fails, but it leaves behind temporary files (or something) that make future commands fail.
- Some combination of restarting Hass.io or the host machine seems to do the trick.

If you're able to determine what *exactly* gets around this error, I'd be very grateful.  This comes up relatively often and I'd like to be able to provide more specific guidance, or even better fix it in Hass.io.  I've never been able to reproduce it on one of my Dev machines, it seems to happen only randomly.

Regarding the first error you saw, I'm not sure whats causing it.  That image is definitely present on Docker Hub ([sabeechen//hassio-google-drive-backup-amd64:0.100.0](https://hub.docker.com/layers/sabeechen/hassio-google-drive-backup-amd64/0.100.0/images/sha256-c977956fb4e92289cae417eafee83df8ad2da54baad1992e1bed425755725223?context=repo)), which is where Hass.io should be trying to download it from.

**Comment by bwanajag** [comment]
Sorry, I have nothing to offer as to a reason for the error; I tried again after restarting and it added the repository.  Didn't do anything but restart and try again.  Once the repository loaded, I was able to install the add-on and it started working...

**Comment by sabeechen** [comment]
Thanks that is good info, I suspect restarting the host will always resolve it.
