### ISSUE TITLE
Suggestion: backup in low priority mode

### ISSUE THREAD

**Issue by GoSpursGoNL** [sabeechen/hassio-google-drive-backup#165]
Yesterday my HA became unresponsive when this addon was creating a backup. Would it be possible to have the backup process run in low CPU priority mode, to prevent hogging CPU/disk IO?

I have a RPi3 in combination with an SSD.

**Comment by sabeechen** [comment]
Home Assistant actually does the work of creating the snapshot, so it would have to be implemented in [the supervisor](https://github.com/home-assistant/supervisor).  I'll take a look to see how much work it might be to implement it there, maybe it would be simple to add an option?

I think most people work around this by setting the time of day for the snapshot to the early morning.

**Comment by GoSpursGoNL** [comment]
I disabled backups for the Plex community addon and now my backup size now went from 2,3GB to 6MB. So the backup process is finished in half a minute or so, no longer causing high CPU load on the Pi.

**Comment by sabeechen** [comment]
Great, because taking a look at the Supervisor source I don't think I could implement this very well there.
