### ISSUE TITLE
Feature Request: Add Password to Snapshots

### ISSUE THREAD

**Issue by nhorvath** [sabeechen/hassio-google-drive-backup#17]
It would be nice to be able to add a password to the snapshots to protect the files at rest.
Thanks for the great addon!

**Comment by sabeechen** [comment]
This is included in the latest v0.8 release.  You can set a password for snapshots in the "Settings" menu at the top right, or by setting the [`snapshot_password` config option](https://github.com/sabeechen/hassio-google-drive-backup#example-use-a-password-for-snapshot-archives).
