### ISSUE TITLE
An unexpected error occurred: HTTPConnectionPool(host='hassio', port=80): Max retries exceeded with url: /snapshots (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f67c58b4be0>: Failed to establish a new connection: [Errno 111] Connection refused'))

### ISSUE THREAD

**Issue by sdnxpt** [sabeechen/hassio-google-drive-backup#172]
Please add some information about your configuration and the problem you ran into here. 
More info really helps speed up debugging, if you don't even read this and help me understand what happened, I probably won't help you.  
Remember that its just one guy back here doing all of this.  
If english isn't your first language, don't sweat it.  Just try to be clear and I'll do the same for you.  Some things you might consider including:
 * What were you doing when the problem happened?
 * A screenshot if its something visual.
 * What configuration options are you using with the add-on?
 * What logs is the add-on printing out?  You can see the detailed logs by clicking "Logs" at the right of the web-UI.
 * Are there any problematic looking logs from the Hassio supervisor?  You can get to them from the Home Assistant Interface from "Hass.io" > "System" > "System Log"
 

Traceback (most recent call last):
  File "/app/backup/coordinator.py", line 109, in _sync
    self._buildModel().sync(self._time.now())
  File "/app/backup/model.py", line 127, in sync
    self._syncSnapshots([self.source, self.dest])
  File "/app/backup/model.py", line 205, in _syncSnapshots
    from_source: Dict[str, AbstractSnapshot] = source.get()
  File "/app/backup/hasource.py", line 174, in get
    for snapshot in self.harequests.snapshots()['snapshots']:
  File "/app/backup/harequests.py", line 63, in snapshots
    return self._getHassioData(self.config.get(Setting.HASSIO_URL) + "snapshots")
  File "/app/backup/harequests.py", line 132, in _getHassioData
    return self._validateHassioReply(self._client.get(url, headers=self._getHassioHeaders()))
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='hassio', port=80): Max retries exceeded with url: /snapshots (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f67c58b4be0>: Failed to establish a new connection: [Errno 111] Connection refused'))

An unexpected error occurred: HTTPConnectionPool(host='hassio', port=80): Max retries exceeded with url: /snapshots (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f67c58b4be0>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by sabeechen** [comment]
This means your addon is having trouble connecting to the supervisor, which is unusual because they should be running on the same "internal" virtual network.
- Was this transient or did it resume syncing successfully soon after?
- Did you just install the addon or has it been working previously?

**Comment by sdnxpt** [comment]
1. I think it was transient, seems it synced successfully after.
2. It's been working previously.
