### ISSUE TITLE
Backup docker container in the same machine

### ISSUE THREAD

**Issue by ricreis394** [sabeechen/hassio-google-drive-backup#173]
Hello, This addon is amazing, very useful. Thanks for your hard work.

I'm here to ask you one thing, is it possible to also backup docker containers which aren't HA Addons?
I use a few containers that help HA but doesn't exist as an addon. It would be perfect if I can combine them into the same backup of HA

**Comment by sabeechen** [comment]
The addon uses the Home Assistant Supervisor to create the backup, so it will only backup the things that normally get backed up when you create a snapshot.  This means it can't backup "regular" containers running alongside Home Assistant.

 There is one small caveat that might work for you: local addons get backed up.  Its actually pretty simple to [create a local addon](https://developers.home-assistant.io/docs/hassio_addon_tutorial), any container can be an addon.  You could either define the DockerFile for your container in the addon directory (as that tutorial directs) or you could write a config that pulls a public image.  For example, if I put the config below into a config.json inside a directory in /addons/test_local_addon:
```json
{
  "name": "Test Local Addon",
  "version": "addonversion",
  "slug": "unique_name_for_addon",
  "description": "Test addon that runs locally",
  "arch": ["armhf", "armv7", "aarch64", "amd64", "i386"],
  "startup": "application",
  "boot": "auto",
  "url": "https://url/that/could/point/anywhere",
  "options": { },
  "schema": { },
  "ports": { },
  "image": "somerepo/mytestcontainer"
}

```
This would create an "addon" that runs the public image somerepo/mytestcontainer:addonversion.   You'd then install from the Supervisor's "Addon Store" page like any other addon. Most of the common features docker has can be expressed in the [addon config](https://developers.home-assistant.io/docs/hassio_addon_config#add-on-config]), so theres a good chance this would meet your need.  I often use this myself when I want to have a container running alongside my home assistant server but also want it to get backed up properly.  Kind of nice that it also integrates cleanly into the Home Assistant interface too.

If the container also exposes a web-ui, you can take a look at the "ingress" variables available to get the web-ui proxied through Home Assistant's authentication and UI.

**Comment by ricreis394** [comment]
Thanks for the info, I'll absolutely look into that
Cheers
