### ISSUE TITLE
Cant install through HACS

### ISSUE THREAD

**Issue by rootrsa** [sabeechen/hassio-google-drive-backup#175]
This is the error I am getting

An error occurred while processing
Exception: HacsException
Message: Repostitory structure for v0.98.1 is not compliant
Could not add this repository, make sure it is compliant with HACS.

**Comment by rootrsa** [comment]
Was installing incorrect way.. apppologies

**Comment by sabeechen** [comment]
No worries. If anyone else runs into this in the future, the addon can only be installed from the Supervisor's Add-on store.  The addon can't be installed through HACS, it requires the supervisor.
