### ISSUE TITLE
Possible issue with mounts in /share folder when backuping

### ISSUE THREAD

**Issue by mrvnklm** [sabeechen/hassio-google-drive-backup#178]
I use the Hassio Plex Plugin and due to how its designed, I need to mount my media folder in /share which seems to cause the backup to hang.

Is it possible to exclude folders from `share` while still including `share` in the backup? Or could you add a functionality to automatically exclude mounted folders in the backup?

`
20-04-23 07:50:23 INFO (MainThread) [supervisor.snapshots] Partial-Snapshot 0a38c6ef start
20-04-23 07:50:23 INFO (MainThread) [supervisor.snapshots] Snapshot 0a38c6ef store Add-ons
20-04-23 07:50:23 INFO (MainThread) [supervisor.addons.addon] Build snapshot for add-on core_configurator
20-04-23 07:50:23 INFO (MainThread) [supervisor.addons.addon] Build snapshot for add-on a0d7b954_unifi
20-04-23 07:50:23 INFO (MainThread) [supervisor.addons.addon] Build snapshot for add-on cebe7a76_hassio_google_drive_backup
20-04-23 07:50:23 INFO (MainThread) [supervisor.addons.addon] Build snapshot for add-on a0d7b954_bitwarden
20-04-23 07:50:23 INFO (MainThread) [supervisor.addons.addon] Build snapshot for add-on 773cbd65_tasui
20-04-23 07:50:23 INFO (MainThread) [supervisor.addons.addon] Build snapshot for add-on a0d7b954_sonweb
20-04-23 07:50:23 INFO (MainThread) [supervisor.addons.addon] Build snapshot for add-on a0d7b954_tor
20-04-23 07:50:23 INFO (MainThread) [supervisor.addons.addon] Build snapshot for add-on a0d7b954_motioneye
20-04-23 07:50:23 INFO (MainThread) [supervisor.addons.addon] Build snapshot for add-on core_mosquitto
20-04-23 07:50:23 INFO (MainThread) [supervisor.addons.addon] Build snapshot for add-on a0d7b954_airsonos
20-04-23 07:50:23 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_configurator
20-04-23 07:50:23 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon 773cbd65_tasui
20-04-23 07:50:23 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon cebe7a76_hassio_google_drive_backup
20-04-23 07:50:23 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_airsonos
20-04-23 07:50:23 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_mosquitto
20-04-23 07:50:24 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_motioneye
20-04-23 07:50:24 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_sonweb
20-04-23 07:50:27 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_tor
20-04-23 07:50:27 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_bitwarden
20-04-23 07:50:34 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_unifi
20-04-23 07:50:34 INFO (MainThread) [supervisor.snapshots] Snapshot 0a38c6ef store folders
20-04-23 07:50:34 INFO (SyncWorker_38) [supervisor.snapshots.snapshot] Snapshot folder addons/local
20-04-23 07:50:34 INFO (SyncWorker_32) [supervisor.snapshots.snapshot] Snapshot folder homeassistant
20-04-23 07:50:34 INFO (SyncWorker_15) [supervisor.snapshots.snapshot] Snapshot folder ssl
20-04-23 07:50:34 INFO (SyncWorker_1) [supervisor.snapshots.snapshot] Snapshot folder share
20-04-23 07:50:34 INFO (SyncWorker_38) [supervisor.snapshots.snapshot] Snapshot folder addons/local done
20-04-23 07:50:37 INFO (SyncWorker_15) [supervisor.snapshots.snapshot] Snapshot folder ssl done
20-04-23 07:51:15 INFO (SyncWorker_32) [supervisor.snapshots.snapshot] Snapshot folder homeassistant done
`

**Comment by sabeechen** [comment]
I'll be attempting to add support for this into a release in the future, but I have trouble giving an estimate of when because I've got a few other higher priority things I've got to knock out first.  Just know I'm working toward it.  I'm not 100% sure the supervisor will let me do it.

**Comment by sabeechen** [comment]
It turns out the supervisor only lets you include or exclude the 4 root level folders from a snapshot wholly (see[ the code](https://github.com/home-assistant/supervisor/blob/5fdc340e580805cfdcc5a2b1662948ba8d0bf4a7/supervisor/snapshots/validate.py#L36)).  In order for me to allow this in the addon, they'd need to implement it in the supervisor.  For now, I can't add this feature.
