### ISSUE TITLE
Google Drive 70% full Snapshots says drive is full

### ISSUE THREAD

**Issue by rlust** [sabeechen/hassio-google-drive-backup#179]
I am using the current release of Hassio.Snapshots, and getting message that Google Drive is full, but when I go to drive it shows I have 30% available.

Any ideas?
Thanks, I love the easy of use of this plugin!

**Comment by sabeechen** [comment]
My best guess is that you don't have enough space to store an entire snapshot.  Are you certain that 30% is big enough to store it?  In the add-on you should be able to see how big your most recent snapshot is.  Some people have snapshots several GB in size, which can quickly exhaust Drive's free allotment.

**Comment by alpdmrel** [comment]
I had the same warning pop up and I couldn't figure out at first but I made a manual permanent backup ant the size of the backup was 12GB for some reason. That was the reason I had that alert. May you have a similar issue.

**Comment by sabeechen** [comment]
Closing this for now, but feel free to reopen if you think there is some other way I can help.
