### ISSUE TITLE
can't add repository on hassio 0.109.3 (fresh install)

### ISSUE THREAD

**Issue by andker87** [sabeechen/hassio-google-drive-backup#183]
I know it sounds like a "stupid" issue, but hassio can't get the repository. I needed to install hassio from scratch, and when i put the repository indicated in the instructions, hassio can't integrate it. other addon repositories work perfectly.
home assistant 0.109.3 on raspberry pi 3b+ - fresh install

**Comment by sabeechen** [comment]
Can you tell me what the supervisor logs say when you try to add the repository?  Any problems it runs into should print an error message there.

Historically, a [lot](https://github.com/sabeechen/hassio-google-drive-backup/issues/62) [of](https://github.com/sabeechen/hassio-google-drive-backup/issues/161) [people](https://github.com/sabeechen/hassio-google-drive-backup/issues/127) have run into this issue (or at least issues with similar effects).  Although I've never been able to get a solid answer on *exactly* what fixes it, for most it seems like restarting Home Assistant's host machine fixes it.

**Comment by andker87** [comment]
Unfortunately I didn't copy what exactly the log said, however if I remember well the problem was related to the inability to reach the addon and read its contents. now I'm on a new instance of hassio, and everything works perfectly, the addon was added at the first try

**Comment by sabeechen** [comment]
Bummer, everyone who had this problem ended up solving it without knowing exactly why.  Glad you're not having trouble anymore though.  Cheers!

**Comment by paalex** [comment]
@sabeechen here's a log from the same issue that I had. I've tried adding and removing a few times and eventually it worked on the 5th trial... Not sure why, I didn't restart Hass to make it work

```
20-06-07 00:58:48 INFO (MainThread) [supervisor.store.git] Clone add-on https://github.com/sabeechen/hassio-google-drive-backup repository
20-06-07 00:58:56 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/git/cebe7a76 repository
20-06-07 00:58:56 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/cebe7a76/repository.json: [Errno 2] No such file or directory: '/data/addons/git/cebe7a76/repository.json'
20-06-07 00:58:56 WARNING (MainThread) [supervisor.store.data] Can't read repository information from /data/addons/git/cebe7a76/repository.json
20-06-07 00:58:56 INFO (MainThread) [supervisor.store] Load add-ons from store: 65 all - 0 new - 0 remove
20-06-07 00:58:58 INFO (MainThread) [supervisor.store.git] Remove custom add-on repository https://github.com/sabeechen/hassio-google-drive-backup
20-06-07 00:59:02 INFO (MainThread) [supervisor.store] Load add-ons from store: 65 all - 0 new - 0 remove
20-06-07 00:59:06 INFO (MainThread) [supervisor.store.git] Clone add-on http://github.com/sabeechen/hassio-google-drive-backup repository
20-06-07 01:03:57 ERROR (MainThread) [supervisor.store.git] Can't clone https://github.com/sabeechen/hassio-google-drive-backup repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone --depth=1 --recursive --shallow-submodules -v https://github.com/sabeechen/hassio-google-drive-backup /data/addons/git/cebe7a76
  stderr: 'Cloning into '/data/addons/git/cebe7a76'...
POST git-upload-pack (192 bytes)
POST git-upload-pack (201 bytes)
fatal: unable to open /data/addons/git/cebe7a76/.git/objects/pack/tmp_pack_yR68Qb: No such file or directory
fatal: index-pack failed
'.
20-06-07 01:03:57 ERROR (MainThread) [supervisor.store] Can't load from repository https://github.com/sabeechen/hassio-google-drive-backup
20-06-07 01:03:57 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/2c12253f/repository.json: [Errno 2] No such file or directory: '/data/addons/git/2c12253f/repository.json'
20-06-07 01:03:57 WARNING (MainThread) [supervisor.store.data] Can't read repository information from /data/addons/git/2c12253f/repository.json
20-06-07 01:03:57 INFO (MainThread) [supervisor.store] Load add-ons from store: 65 all - 0 new - 0 remove
20-06-07 01:05:43 INFO (MainThread) [supervisor.store] Load add-ons from store: 66 all - 1 new - 0 remove
```

**Comment by sabeechen** [comment]
Thanks for the update.  I still suspect this is a bug somewhere in Git, or a bug somewhere in how Home Assistant uses Git.  I suspect something gets cached and then corrupted, and it doesn't work until either git clears the cache automatically or you restart the machine which accomplishes the same thing.
