### ISSUE TITLE
 Error while backing up

### ISSUE THREAD

**Issue by Darisman** [sabeechen/hassio-google-drive-backup#186]
**Hi, thank you for this add-on**
can you please check this problem that I'm facing

This is the log:

`05-08 06:40:04 DEBUG Making Hassio request: http://hassio/addons/self/info
05-08 06:40:05 DEBUG Making Hassio request: http://hassio/info
05-08 06:40:05 DEBUG Making Hassio request: http://hassio/homeassistant/info
05-08 06:40:05 DEBUG Making Hassio request: http://hassio/supervisor/info
05-08 06:40:05 INFO Starting server on port 8099
05-08 06:40:05 INFO Server started
05-08 06:40:05 DEBUG Sync requested by Coordinator
05-08 06:40:05 INFO Syncing Snapshots
05-08 06:40:05 DEBUG Making Hassio request: http://hassio/snapshots
05-08 06:40:05 DEBUG Making Hassio request: http://hassio/snapshots/fb1f2f74/info
05-08 06:40:05 DEBUG Making Hassio request: http://hassio/snapshots/dcd84846/info
05-08 06:41:38 INFO Saving new Google Drive credentials
05-08 06:41:39 DEBUG Sync requested by GoogleDrive
05-08 06:41:39 INFO Syncing Snapshots
05-08 06:41:39 DEBUG Making Hassio request: http://hassio/snapshots
05-08 06:41:39 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
05-08 06:41:39 DEBUG Google Drive credentials expired.  We'll retry with new ones.
05-08 06:41:41 DEBUG Requesting refreshed Google Drive credentials
05-08 06:41:41 DEBUG Making Google Drive request: https://www.googleapis.com/oauth2/v4/token
05-08 06:41:42 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
05-08 06:41:42 DEBUG Google Drive credentials expired.  We'll retry with new ones.
05-08 06:41:46 DEBUG Requesting refreshed Google Drive credentials
05-08 06:41:46 DEBUG Making Google Drive request: https://www.googleapis.com/oauth2/v4/token
05-08 06:41:47 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
05-08 06:41:47 DEBUG Google Drive credentials expired.  We'll retry with new ones.
05-08 06:41:55 DEBUG Requesting refreshed Google Drive credentials
05-08 06:41:55 DEBUG Making Google Drive request: https://www.googleapis.com/oauth2/v4/token
05-08 06:41:56 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
05-08 06:41:56 DEBUG Google Drive credentials expired.  We'll retry with new ones.
05-08 06:41:58 DEBUG Making Hassio request: http://hassio/addons/self/options
05-08 06:42:12 DEBUG Requesting refreshed Google Drive credentials
05-08 06:42:12 DEBUG Making Google Drive request: https://www.googleapis.com/oauth2/v4/token
05-08 06:42:13 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
05-08 06:42:13 DEBUG Google Drive credentials expired.  We'll retry with new ones.
05-08 06:42:16 DEBUG Making Hassio request: http://hassio/addons/self/info
05-08 06:42:16 DEBUG Making Hassio request: http://hassio/info
05-08 06:42:16 DEBUG Making Hassio request: http://hassio/homeassistant/info
05-08 06:42:16 DEBUG Making Hassio request: http://hassio/supervisor/info
05-08 06:42:45 DEBUG Requesting refreshed Google Drive credentials
05-08 06:42:45 DEBUG Making Google Drive request: https://www.googleapis.com/oauth2/v4/token
05-08 06:42:45 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
05-08 06:42:46 ERROR    
Traceback (most recent call last):   
  File "/app/backup/coordinator.py", line 109, in _sync   
    self._buildModel().sync(self._time.now())   
  File "/app/backup/model.py", line 127, in sync   
    self._syncSnapshots([self.source, self.dest])   
  File "/app/backup/model.py", line 205, in _syncSnapshots   
    from_source: Dict[str, AbstractSnapshot] = source.get()   
  File "/app/backup/drivesource.py", line 86, in get   
    self._info.drive_folder_id = self.getFolderId()   
  File "/app/backup/drivesource.py", line 79, in getFolderId   
    return self._getParentFolderId()   
  File "/app/backup/drivesource.py", line 204, in _getParentFolderId   
    self._folderId = self._validateFolderId()   
  File "/app/backup/drivesource.py", line 230, in _validateFolderId   
    return self._findDriveFolder()   
  File "/app/backup/drivesource.py", line 238, in _findDriveFolder   
    for child in self.drivebackend.query("mimeType='" + FOLDER_MIME_TYPE + "'"):   
  File "/app/backup/driverequests.py", line 173, in query   
    response = self.retryRequest("GET", URL_FILES + "?" + urlencode(q), is_json=True)   
  File "/app/backup/driverequests.py", line 344, in retryRequest   
    response.raise_for_status()   
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status   
    raise HTTPError(http_error_msg, response=self)   
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives   
   

05-08 06:42:46 INFO I'll try syncing again right now
05-08 06:42:47 DEBUG Sync requested by Coordinator
05-08 06:42:47 DEBUG Sync requested by UI Server
05-08 06:42:47 INFO Syncing Snapshots
05-08 06:42:47 DEBUG Making Hassio request: http://hassio/snapshots
05-08 06:42:47 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
05-08 06:42:47 DEBUG Google Drive credentials expired.  We'll retry with new ones.
05-08 06:42:49 DEBUG Requesting refreshed Google Drive credentials
05-08 06:42:49 DEBUG Making Google Drive request: https://www.googleapis.com/oauth2/v4/token
05-08 06:42:50 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
05-08 06:42:50 DEBUG Google Drive credentials expired.  We'll retry with new ones.
05-08 06:42:53 INFO Sending error report (see settings to disable)
05-08 06:42:53 DEBUG Making Hassio request: http://hassio/addons/self/options
05-08 06:42:54 DEBUG Requesting refreshed Google Drive credentials
05-08 06:42:54 DEBUG Making Google Drive request: https://www.googleapis.com/oauth2/v4/token
05-08 06:42:55 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
05-08 06:42:55 DEBUG Google Drive credentials expired.  We'll retry with new ones.
05-08 06:43:03 DEBUG Requesting refreshed Google Drive credentials
05-08 06:43:03 DEBUG Making Google Drive request: https://www.googleapis.com/oauth2/v4/token
05-08 06:43:04 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
05-08 06:43:05 DEBUG Google Drive credentials expired.  We'll retry with new ones.
05-08 06:43:21 DEBUG Requesting refreshed Google Drive credentials
05-08 06:43:21 DEBUG Making Google Drive request: https://www.googleapis.com/oauth2/v4/token
05-08 06:43:21 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
05-08 06:43:22 DEBUG Google Drive credentials expired.  We'll retry with new ones.
05-08 06:43:54 DEBUG Requesting refreshed Google Drive credentials
05-08 06:43:54 DEBUG Making Google Drive request: https://www.googleapis.com/oauth2/v4/token
05-08 06:43:55 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
05-08 06:43:55 ERROR    
Traceback (most recent call last):   
  File "/app/backup/coordinator.py", line 109, in _sync   
    self._buildModel().sync(self._time.now())   
  File "/app/backup/model.py", line 127, in sync   
    self._syncSnapshots([self.source, self.dest])   
  File "/app/backup/model.py", line 205, in _syncSnapshots   
    from_source: Dict[str, AbstractSnapshot] = source.get()   
  File "/app/backup/drivesource.py", line 86, in get   
    self._info.drive_folder_id = self.getFolderId()   
  File "/app/backup/drivesource.py", line 79, in getFolderId   
    return self._getParentFolderId()   
  File "/app/backup/drivesource.py", line 204, in _getParentFolderId   
    self._folderId = self._validateFolderId()   
  File "/app/backup/drivesource.py", line 230, in _validateFolderId   
    return self._findDriveFolder()   
  File "/app/backup/drivesource.py", line 238, in _findDriveFolder   
    for child in self.drivebackend.query("mimeType='" + FOLDER_MIME_TYPE + "'"):   
  File "/app/backup/driverequests.py", line 173, in query   
    response = self.retryRequest("GET", URL_FILES + "?" + urlencode(q), is_json=True)   
  File "/app/backup/driverequests.py", line 344, in retryRequest   
    response.raise_for_status()   
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status   
    raise HTTPError(http_error_msg, response=self)   
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives   
   

05-08 06:43:55 INFO I'll try syncing again in 10 seconds
05-08 06:43:56 DEBUG Sync requested by UI Server
05-08 06:43:56 INFO Syncing Snapshots
05-08 06:43:56 DEBUG Making Hassio request: http://hassio/snapshots
05-08 06:43:56 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
05-08 06:43:57 DEBUG Google Drive credentials expired.  We'll retry with new ones.
05-08 06:43:59 DEBUG Requesting refreshed Google Drive credentials
05-08 06:43:59 DEBUG Making Google Drive request: https://www.googleapis.com/oauth2/v4/token
05-08 06:44:00 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
05-08 06:44:00 DEBUG Google Drive credentials expired.  We'll retry with new ones.
05-08 06:44:04 DEBUG Requesting refreshed Google Drive credentials
05-08 06:44:04 DEBUG Making Google Drive request: https://www.googleapis.com/oauth2/v4/token
05-08 06:44:05 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
05-08 06:44:06 DEBUG Google Drive credentials expired.  We'll retry with new ones.
05-08 06:44:14 DEBUG Requesting refreshed Google Drive credentials
05-08 06:44:14 DEBUG Making Google Drive request: https://www.googleapis.com/oauth2/v4/token
05-08 06:44:14 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
05-08 06:44:15 DEBUG Google Drive credentials expired.  We'll retry with new ones.
05-08 06:44:31 DEBUG Requesting refreshed Google Drive credentials
05-08 06:44:31 DEBUG Making Google Drive request: https://www.googleapis.com/oauth2/v4/token
05-08 06:44:32 INFO Saving new Google Drive credentials
05-08 06:44:32 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
05-08 06:44:33 DEBUG Google Drive credentials expired.  We'll retry with new ones.
05-08 06:45:05 DEBUG Requesting refreshed Google Drive credentials
05-08 06:45:05 DEBUG Making Google Drive request: https://www.googleapis.com/oauth2/v4/token
05-08 06:45:05 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
05-08 06:45:06 ERROR    
Traceback (most recent call last):   
  File "/app/backup/coordinator.py", line 109, in _sync   
    self._buildModel().sync(self._time.now())   
  File "/app/backup/model.py", line 127, in sync   
    self._syncSnapshots([self.source, self.dest])   
  File "/app/backup/model.py", line 205, in _syncSnapshots   
    from_source: Dict[str, AbstractSnapshot] = source.get()   
  File "/app/backup/drivesource.py", line 86, in get   
    self._info.drive_folder_id = self.getFolderId()   
  File "/app/backup/drivesource.py", line 79, in getFolderId   
    return self._getParentFolderId()   
  File "/app/backup/drivesource.py", line 204, in _getParentFolderId   
    self._folderId = self._validateFolderId()   
  File "/app/backup/drivesource.py", line 230, in _validateFolderId   
    return self._findDriveFolder()   
  File "/app/backup/drivesource.py", line 238, in _findDriveFolder   
    for child in self.drivebackend.query("mimeType='" + FOLDER_MIME_TYPE + "'"):   
  File "/app/backup/driverequests.py", line 173, in query   
    response = self.retryRequest("GET", URL_FILES + "?" + urlencode(q), is_json=True)   
  File "/app/backup/driverequests.py", line 344, in retryRequest   
    response.raise_for_status()   
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status   
    raise HTTPError(http_error_msg, response=self)   
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives   
   

05-08 06:45:06 INFO I'll try syncing again in 20 seconds
05-08 06:45:06 DEBUG Sync requested by GoogleDrive
05-08 06:45:06 INFO Syncing Snapshots
05-08 06:45:06 DEBUG Making Hassio request: http://hassio/snapshots
05-08 06:45:06 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
05-08 06:45:07 DEBUG Google Drive credentials expired.  We'll retry with new ones.
05-08 06:45:09 DEBUG Requesting refreshed Google Drive credentials
05-08 06:45:09 DEBUG Making Google Drive request: https://www.googleapis.com/oauth2/v4/token
05-08 06:45:10 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
05-08 06:45:10 DEBUG Google Drive credentials expired.  We'll retry with new ones.
05-08 06:45:14 DEBUG Requesting refreshed Google Drive credentials
05-08 06:45:14 DEBUG Making Google Drive request: https://www.googleapis.com/oauth2/v4/token
05-08 06:45:15 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
05-08 06:45:15 DEBUG Google Drive credentials expired.  We'll retry with new ones.
05-08 06:45:23 DEBUG Requesting refreshed Google Drive credentials
05-08 06:45:23 DEBUG Making Google Drive request: https://www.googleapis.com/oauth2/v4/token
05-08 06:45:24 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
05-08 06:45:24 DEBUG Google Drive credentials expired.  We'll retry with new ones.
05-08 06:45:40 DEBUG Requesting refreshed Google Drive credentials
05-08 06:45:40 DEBUG Making Google Drive request: https://www.googleapis.com/oauth2/v4/token
05-08 06:45:41 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
05-08 06:45:41 DEBUG Google Drive credentials expired.  We'll retry with new ones.
05-08 06:46:13 DEBUG Requesting refreshed Google Drive credentials
05-08 06:46:13 DEBUG Making Google Drive request: https://www.googleapis.com/oauth2/v4/token
05-08 06:46:14 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
05-08 06:46:14 ERROR    
Traceback (most recent call last):   
  File "/app/backup/coordinator.py", line 109, in _sync   
    self._buildModel().sync(self._time.now())   
  File "/app/backup/model.py", line 127, in sync   
    self._syncSnapshots([self.source, self.dest])   
  File "/app/backup/model.py", line 205, in _syncSnapshots   
    from_source: Dict[str, AbstractSnapshot] = source.get()   
  File "/app/backup/drivesource.py", line 86, in get   
    self._info.drive_folder_id = self.getFolderId()   
  File "/app/backup/drivesource.py", line 79, in getFolderId   
    return self._getParentFolderId()   
  File "/app/backup/drivesource.py", line 204, in _getParentFolderId   
    self._folderId = self._validateFolderId()   
  File "/app/backup/drivesource.py", line 230, in _validateFolderId   
    return self._findDriveFolder()   
  File "/app/backup/drivesource.py", line 238, in _findDriveFolder   
    for child in self.drivebackend.query("mimeType='" + FOLDER_MIME_TYPE + "'"):   
  File "/app/backup/driverequests.py", line 173, in query   
    response = self.retryRequest("GET", URL_FILES + "?" + urlencode(q), is_json=True)   
  File "/app/backup/driverequests.py", line 344, in retryRequest   
    response.raise_for_status()   
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status   
    raise HTTPError(http_error_msg, response=self)   
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives   
   

05-08 06:46:14 INFO I'll try syncing again in 40 seconds
05-08 06:46:55 DEBUG Sync requested by Coordinator
05-08 06:46:55 INFO Syncing Snapshots
05-08 06:46:55 DEBUG Making Hassio request: http://hassio/snapshots
05-08 06:46:55 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
05-08 06:46:55 DEBUG Google Drive credentials expired.  We'll retry with new ones.
05-08 06:46:57 DEBUG Requesting refreshed Google Drive credentials
05-08 06:46:57 DEBUG Making Google Drive request: https://www.googleapis.com/oauth2/v4/token
05-08 06:46:58 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
05-08 06:46:58 DEBUG Google Drive credentials expired.  We'll retry with new ones.
05-08 06:47:02 DEBUG Requesting refreshed Google Drive credentials
05-08 06:47:02 DEBUG Making Google Drive request: https://www.googleapis.com/oauth2/v4/token
05-08 06:47:03 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
05-08 06:47:03 DEBUG Google Drive credentials expired.  We'll retry with new ones.
05-08 06:47:11 DEBUG Requesting refreshed Google Drive credentials
05-08 06:47:11 DEBUG Making Google Drive request: https://www.googleapis.com/oauth2/v4/token
05-08 06:47:12 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
05-08 06:47:12 DEBUG Google Drive credentials expired.  We'll retry with new ones.
05-08 06:47:28 DEBUG Requesting refreshed Google Drive credentials
05-08 06:47:28 DEBUG Making Google Drive request: https://www.googleapis.com/oauth2/v4/token
05-08 06:47:29 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
05-08 06:47:29 DEBUG Google Drive credentials expired.  We'll retry with new ones.
`

**Comment by sabeechen** [comment]
Thanks for providing the logs, thats pretty strange and I've never seen it before.  It looks like the addon is requesting refreshed credentials form Google Drive, getting them without a problem, and then Google is rejecting them right away.  I suspect something weird is going on with your Google account.

Something that might help me figure this out:
* Do you use your own google credentials? (eg did you authorize with drive following [these steps](https://github.com/sabeechen/hassio-google-drive-backup/blob/master/LOCAL_AUTH.md).
* Is your google account managed by a custom domain (eg a GSuite or Google Apps account)?

Things you can try:
* If you haven't tried already, Go to "ACTIONS" -> "Reauthorize Google Drive" to re-link the addon with Google Drive.
* Go to [https://myaccount.google.com](https://myaccount.google.com) then click "Security" and then "Manage Third-party Access".  You should see something like this below it:
![image](https://user-images.githubusercontent.com/21026774/81434552-90f3c880-9123-11ea-92c5-4b8aa113c409.png)
  If not, something is wrong.  You can try clicking "Revoke access" under that entry and reauthorizing with Drive again.
* Try creating a new account with Google Drive and authorizing the addon with the new account.  That would definitely tell us if the problem is just with your account.

**Comment by Darisman** [comment]
Thanks, I changed the account and now it's working, the first account was indeed managed by a custom domain

**Comment by sabeechen** [comment]
There are probably some settings in your domain that make that account fail, there are a lot of restrictions that domains can add to their users that make various features fail.  I don't have a gsuite domain to experiment with, so if you're ever able to identify what caused this for the managed accout I'd be curious to know so I could provide a better guidance in the error dialog.  Glad you were able to get things working!
