### ISSUE TITLE
no auto snapshot

### ISSUE THREAD

**Issue by unbreakmat** [sabeechen/hassio-google-drive-backup#188]
Worked for a couple of days but now for 2 days no snapshot are made and uploaded
google drive is 1.9 gig of 15 filled so thats not the problem
hassio has 17gig free 

tried yesterday the reauthorise and worked directly (but dont want to do this every time :s ) 
no errors in the log 

im not shure what is causing this (what can i provide you for more info???)

drive log:
05-13 02:31:14 INFO Syncing Snapshots
05-13 02:31:14 DEBUG Making Hassio request: http://hassio/snapshots
05-13 02:31:14 DEBUG Requesting refreshed Google Drive credentials
05-13 02:31:14 DEBUG Making Google Drive request: https://www.googleapis.com/oauth2/v4/token
05-13 02:31:14 DEBUG Making Google Drive request: https://www.googleapis.com/drive/XXXXXXXXXXXXXXXXXXXXXXXXXXXXX 

when i opened this link (i refactored it for privacy ) i got this=
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "dailyLimitExceededUnreg",
    "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
    "extendedHelp": "https://code.google.com/apis/console"
   }
  ],
  "code": 403,
  "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
 }
}

**Comment by unbreakmat** [comment]
update: normally the snapshot should start at 4Am
no it is 4.31am and it is finally starting the snapshot, why did this take 31 min to start????

**Comment by sabeechen** [comment]
Are you sure you have it set to take daily snapshots? The default unless you changed it is once every 3 days.  Are you seeing any errors in the logs, or is the error you posted only happen when you go to the link in the browser?

I've had an issue a couple others run into where the time a snapshot gets taken drifts a couple seconds every day, by 31 minutes of drift is the most I've ever seen.  Have you set the time of day for the snapshot? If not it will drift a little bit ever day (but still happen mostly on schedule).  This will mostly likely be fixed an an update soon.  What timezone are you in?

**Comment by unbreakmat** [comment]
hi 

daily snapshot is really necesairy because i make daily big changes
as you can see i have an enormous drift time
![image](https://user-images.githubusercontent.com/63264046/82123449-c3dc3300-9799-11ea-924d-5baa6062f4d9.png)

no errors in the logs, nor in hassio itself nor in google drive

time of day is 04:00 for the snapshots
timezone europe/brussels (utc+1)

**Comment by unbreakmat** [comment]
follow up of drifts: 
![image](https://user-images.githubusercontent.com/63264046/82752898-a0307280-9dc1-11ea-8e71-e9855a9f8f4b.png)

**Comment by muditsinhal** [comment]
I seem to have a similar issue with my backups. The snapshot time of the day is set to 00:32, however the actual snapshots are taken and backed up after a long delay. Although, so far the backups have never failed. Central European Summer Time (GMT +2).

![ha](https://user-images.githubusercontent.com/66184605/83339373-7c8f8f80-a2cd-11ea-9bf0-9a204e2e3301.png)
![drive](https://user-images.githubusercontent.com/66184605/83339376-80bbad00-a2cd-11ea-9557-211f9412cacc.png)

**Comment by sabeechen** [comment]
There is definitely something wrong in the addon, but I've had a hell of a time figuring out what it is.  In all my testing, I've been unable to reproduce anything close to this strange drift.  Enough people are reporting it that I suspect the issue is pretty widespread.
