### ISSUE TITLE
Onedrive?

### ISSUE THREAD

**Issue by larronni** [sabeechen/hassio-google-drive-backup#189]
What about adding Microsoft OneDrive as an alternative storage location?

**Comment by sabeechen** [comment]
[See FAQ](https://github.com/sabeechen/hassio-google-drive-backup#will-this-ever-upload-to-dropboxftpsmbmyfavoriteprotocol)
Probably not, but I know people want it.  I don't have the time at the moment to implement support, but we'll see!
