### ISSUE TITLE
HTTP 500 Error on Authenticating with Google Drive

### ISSUE THREAD

**Issue by krkeegan** [sabeechen/hassio-google-drive-backup#190]
![image](https://user-images.githubusercontent.com/3046315/82081893-eb4cd600-969b-11ea-99ac-37052ec907eb.png)

**Comment by Baldorian44** [comment]
I agree on that @krkeegan, have same issue

**Comment by sabeechen** [comment]
My server ran into some problems. but it should be back up now.  Every once in a while I have to kick it to get it going again :)
I'll be fixing this permanently in an update in the near future.

**Comment by krkeegan** [comment]
Awesome, thanks
