### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by woody4165** [sabeechen/hassio-google-drive-backup#191]
Hi

I'm getting internal server error while trying to authenticate for first time.

I see there were two closed issues, but I see this error now.
Is the server down or is it something from my side?

Thanks

**Comment by lbouriez** [comment]
+1, impossible to authenticate :/

**Comment by sabeechen** [comment]
No, its on my side.  My server gets into a bad state every once in a while and I have to manually restart it.  I'll be fixing this permanetly in an update soon, but for now its back up.

**Comment by sabeechen** [comment]
Also @dannytsang if you get a 403 for the manual auth, make sure you're following the directions carefully.  There are *a lot* of little things you can miss that cause problems, unfortunately all Google will do to tell you something isn't right is return a permission denied (403).

I'll run through the steps tomorrow to make sure they're up-to-date just in case.

**Comment by dannytsang** [comment]
Thanks @sabeechen but don't worry. I was trying to use the alternative method because easier method was giving me this error.
