### ISSUE TITLE
Error « 401: Unauthorized »

### ISSUE THREAD

**Issue by xingpao** [sabeechen/hassio-google-drive-backup#194]
Hi Stephen, Right after having granted access to my google drive, I get the following message « 401: Unauthorized« .
The same message appears if I try to read the logs by clicking in the top button in the setting window. 
Already tried reboot for both hassio and the add-on.
Here is an extract of the log from the system :
20-05-24 17:41:29 INFO (MainThread) [supervisor.api.security] /snapshots/79147d7e/info access from cebe7a76_hassio_google_drive_backup
20-05-24 17:42:23 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None
20-05-24 17:42:41 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None
20-05-24 17:43:34 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None
20-05-24 17:44:42 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None
20-05-24 17:44:48 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None

One more thing : I come from another add on (the one from Scott mc cauley).
Thanks for your support!

**Comment by sabeechen** [comment]
This is most definitely a problem with the supervisor.  Its in charge of managing the ingress tokens (which are used to access the UI), the addon can't do anything about it.  Could you restart the supervisor, try to access the UI once its up and see what errors the supervisor logs?  I suspect it will have better info right after startup.

**Comment by xingpao** [comment]
I’ve restarted the supervisor after the last update. Here is my log :
20-05-26 19:33:04 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-05-26 19:33:31 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-05-26 19:45:54 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
20-05-26 19:51:06 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None

**Comment by Eyeball753** [comment]
Hi @Xingpao,

Using a Firefox private window to grant access to my Google Drive fixed it. 
I had the exact same error, but without anything in the logs. I suspect one of my add-ons was interfering with it. 
Hope this helps.

**Comment by xingpao** [comment]
> Hi @xingpao,
> 
> Using a Firefox private window to grant access to my Google Drive fixed it.
> I had the exact same error, but without anything in the logs. I suspect one of my add-ons was interfering with it.
> Hope this helps.

I finally tried this. I have :
- opened a private window in safari for iOS 
- launched home assistant thanks to the IP 192....
- open the web ui
- authorised again google drive

And the it works ! At one moment, I’ve seen that the add on was trying to connect to something like hassio..../...ingress.... and I think this is where the problem is in the add on.
Many thanks eyeball753!

**Comment by sabeechen** [comment]
Closing this for now, let me know if you or anyone else run into any other problems.

**Comment by ckolumbus** [comment]
Might this be related to home-assistant/supervisor#3021 ? If so it is due to a bug in Firefox not forwarding session cookies to sites within iframes.
