### ISSUE TITLE
Add configuration to set hassio url

### ISSUE THREAD

**Issue by douglasjam** [sabeechen/hassio-google-drive-backup#198]
It seems the newest hassio change its hostname from hassio to homeassistant.local,
therefore it's not possible to start the addon anymore

I could not find a way to configure it in the docs

I suggest adding a config for this, so we can support both old a new homeassistant, plus in case someone renames the hostname by itself and it won't break.

`Traceback (most recent call last):
  File "/app/backup/__main__.py", line 57, in main
    ha_source.init()
  File "/app/backup/hasource.py", line 227, in init
    self._refreshInfo()
  File "/app/backup/hasource.py", line 244, in _refreshInfo
    self.self_info = self.harequests.selfInfo()
  File "/app/backup/harequests.py", line 70, in selfInfo
    return self._getHassioData(self.config.get(Setting.HASSIO_URL) + "addons/self/info")
  File "/app/backup/harequests.py", line 132, in _getHassioData
    return self._validateHassioReply(self._client.get(url, headers=self._getHassioHeaders()))
  File "/app/backup/harequests.py", line 98, in _validateHassioReply
    resp.raise_for_status()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://hassio/addons/self/info
06-12 11:45:44 CRITICAL Unable to reach Hassio supervisor.
06-12 11:45:44 CRITICAL `

**Comment by sabeechen** [comment]
This error is happening on Home Assistant's internal docker network, not over your normal network.  Users can't change the hostname on that network, its internal to how Home Assistant works.  The 403 error (HTTP "forbidden") means the request is making it through, but for some reason Home assistant isn't recognizing the addon.

Could you try restarting the supervisor and then starting the addon?

**Comment by douglasjam** [comment]
You are more than right, it works now after a reboot, thank you.

**Comment by sabeechen** [comment]
No problem, The supervisor can get into a weird state after updates.  Its supposed to keep track of the authentication token between addons and the supervisor across updates, but sometimes it just doesn't and the only way to recover is to restart things.
