### ISSUE TITLE
Cannot add repo to HACS

### ISSUE THREAD

**Issue by DrJohnT** [sabeechen/hassio-google-drive-backup#199]
When I try to add this repo to HACS  I get the error "Repostitory structure for v0.98.1 is not compliant"

![2020-06-15 22_14_05-HACS - Home Assistant](https://user-images.githubusercontent.com/10464775/84706830-94197a00-af55-11ea-90b0-aa393246bd10.png)

**Comment by sabeechen** [comment]
This isn't an HACS plugin.  It's a Home Assistant (formerly Hass.io) addon.  You install the add-on from Home Assistant's add-on store.
