### ISSUE TITLE
Exception: Request to Hassio failed, HTTP error: <Response [400]> Message: {"result": "error", "message": null}

### ISSUE THREAD

**Issue by sotatech** [sabeechen/hassio-google-drive-backup#20]
Hi,
I just installed this, but I'm getting an error. It creates the snapshot OK, I'm running home assistant 0.91.4. 
Thanks!

Traceback (most recent call last):
  File "/app/backup/engine.py", line 96, in doBackupWorkflow
    self._checkForBackup()
  File "/app/backup/engine.py", line 314, in _checkForBackup
    self._purgeHaSnapshots()
  File "/app/backup/engine.py", line 300, in _purgeHaSnapshots
    self.hassio.deleteSnapshot(oldest_hassio)
  File "/app/backup/hassio.py", line 164, in deleteSnapshot
    self._postHassioData(delete_url, {})
  File "/app/backup/hassio.py", line 247, in _postHassioData
    return self._validateHassioReply(requests.post(url, headers=self.config.getHassioHeaders(), json=json_data))
  File "/app/backup/hassio.py", line 225, in _validateHassioReply
    raise Exception('Request to Hassio failed, HTTP error: {0} Message: {1}'.format(resp, resp.text))
Exception: Request to Hassio failed, HTTP error: <Response [400]> Message: {"result": "error", "message": null}

**Comment by sabeechen** [comment]
This means the add-on ran into a problem when it asked Hassio to delete an old snapshot.  The add-on won't be able to create new snapshots until it cleans otu the old ones.   Hassio always just returns HTTP 400 when it runs into an error, but more specific messages are usually put in the supervisor logs.  Could I have you:
* Click "Sync Now" in the web UI, and wait until the "Done" notification comes up.
* From Home Assistant, got to "Hassio" > "System" >"System Log"> "Refresh".  Does anything show up there?
* If not, could you attach a copy of the logs from the add-on?  You should see a link to download them in the webUI where it shows the error message.

**Comment by sotatech** [comment]
After Sync Now I get:

19-04-17 15:25:52 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
19-04-17 15:25:52 INFO (MainThread) [hassio.api.security] /snapshots/4a8c5772/info access from cebe7a76_hassio_google_drive_backup
19-04-17 15:25:52 INFO (MainThread) [hassio.api.security] /snapshots/f0e162c0/info access from cebe7a76_hassio_google_drive_backup
19-04-17 15:25:52 INFO (MainThread) [hassio.api.security] /snapshots/f8470b53/info access from cebe7a76_hassio_google_drive_backup
19-04-17 15:25:52 INFO (MainThread) [hassio.api.security] /snapshots/8a89763d/info access from cebe7a76_hassio_google_drive_backup
19-04-17 15:25:52 INFO (MainThread) [hassio.api.security] /snapshots/46004ad2/info access from cebe7a76_hassio_google_drive_backup
19-04-17 15:25:52 INFO (MainThread) [hassio.api.security] /snapshots/f7970d0e/info access from cebe7a76_hassio_google_drive_backup
19-04-17 15:25:52 INFO (MainThread) [hassio.api.security] /snapshots/5c1bcec0/info access from cebe7a76_hassio_google_drive_backup
19-04-17 15:25:52 INFO (MainThread) [hassio.api.security] /snapshots/28a67203/info access from cebe7a76_hassio_google_drive_backup
19-04-17 15:25:52 INFO (MainThread) [hassio.api.security] /snapshots/de4851f3/info access from cebe7a76_hassio_google_drive_backup
19-04-17 15:25:52 INFO (MainThread) [hassio.api.security] /snapshots/e8fd8c2b/info access from cebe7a76_hassio_google_drive_backup
19-04-17 15:25:54 INFO (MainThread) [hassio.api.security] /snapshots/5c1bcec0/remove access from cebe7a76_hassio_google_drive_backup
19-04-17 15:25:54 ERROR (MainThread) [hassio.snapshots] Can't remove snapshot 5c1bcec0: [Errno 2] No such file or directory: '/data/backup/5c1bcec0.tar'

**Comment by sotatech** [comment]
I've checked the backup folder and that file doesn't exist.

**Comment by sotatech** [comment]
So I decided to reboot the computer and now I can see that it is uploading snapshots. Thanks for your help and the add-on!

**Comment by sabeechen** [comment]
Strange, thats an error being reported by the OS ([for reference](https://github.com/home-assistant/hassio/blob/cecad526a298cf395aae0721b3b9cf2b030f35e6/hassio/snapshots/__init__.py#L82)).

I'd suspect that somehow hassio had a stale cache of its own snapshots.  I might add some logic to make hassio refresh its cache before I ask it to delete.  I'm glad you were able to resole it, thanks for calling this to my attention!
