### ISSUE TITLE
Feature request: Do not keep any backup locally

### ISSUE THREAD

**Issue by Mincka** [sabeechen/hassio-google-drive-backup#200]
Hello!

When there is very limited space locally, it could be useful to only keep backups on Google Drive.
In my case, I don't have space for more than one backup so I need to cleanup the last one to get a new one.

Currently, it is not possible to set "0" for "Snapshots in Home Assistant", as it will disable the snapshot cleanup.
"The maximum number of snapshots to keep locally in Home Assistant, or 0 to disable cleanup of old snapshots entirely."

I have two ideas to solve this:
**1) Use "1" for unlimited instead of "0"**

Would it be possible to use "-1", instead of "0" to disable cleanup?
"0" and "-1" would make sense for local snapshot but also for "Snapshots in Google Drive".

Few examples of the possible settings:
Snapshots in Home Assistant: 0
Snapshots in Google Drive: 0
-> Do not backup anything

Snapshots in Home Assistant: 1
Snapshots in Google Drive: 0
-> Backup locally but no upload ("Enable Google Drive Upload" option is then not needed anymore)

Snapshots in Home Assistant: 0
Snapshots in Google Drive: -1
-> Unlimited uploads on Google Drive but cleanup locally after successful upload

Snapshots in Home Assistant: -1
Snapshots in Google Drive: -1
-> Do not cleanup anything

**2) New option: Automatic local cleanup after upload**
Or maybe just another checkbox in the options "Cleanup the local Home Assistant snapshot after its successful upload on Google Drive".

**Comment by TychoWerner** [comment]
I want this aswell!

**Comment by sabeechen** [comment]
I just released v0.104.1 of the addon with this feature.  You can find it by opening the addon's settings in the web-ui.

To update the addon go to:
`Supervisor` > `Add-on Store` > Click the `...` in the top right > `Refresh`
and you should see the new version.

Kindly re-open this bug if you continue to run into trouble after updating and I'll do what I can about it.
