### ISSUE TITLE
feature: use own domain for google auth vs 'pens'

### ISSUE THREAD

**Issue by strangerting** [sabeechen/hassio-google-drive-backup#202]
write a short how-to and tools for the configuration of using <generic owned domain> rather than your pens domain.

I appreciate it involves some setup on the google side but may be better in the long run?  

Or perhaps speak to Frenck and get its setup via the nabucasa domain?

**Comment by inverse** [comment]
This would be amazing. watching.

**Comment by sabeechen** [comment]
I'm on it.  I've got a domain set up for it and everything.  Soon new users (and all future reauthorizations with Google Drive) will go through https://habackup.io/ (".io" domains are so hot right now).  Just gotta get everything else finished with the latest version. 

So ... great idea!

**Comment by sabeechen** [comment]
I've done this in the latest release, 0.101.0.  You can got to "Add-on Store" - > Click the 3 dots > "Reload" to make Home Assistant see the latest version.

Also if you're trying to use your own google application credentials, I've already got detailed instructions up [here](https://github.com/sabeechen/hassio-google-drive-backup/blob/master/LOCAL_AUTH.md).
