### ISSUE TITLE
IOS app (Hamburger menu) back feature request

### ISSUE THREAD

**Issue by passie** [sabeechen/hassio-google-drive-backup#205]
Not sure if this is a real issue or a feature request, but I give it a shot. 

I'm really happy with this add-on and use it quite allot.
One thing which is annoying me, is that if I use the add-on via the IOS app. I'm unable to go back via the hamburger icon.

![hamburger](https://user-images.githubusercontent.com/1913849/86637839-914ef980-bfd6-11ea-87f5-60e88de63850.png)
 
I have to close the app to go back to the main screen. Would it be possible to add this feature in a future release, so the this add-on is user-friendly for IOS user in near future release?

PS: I tried to search the issue to find out if this is already requested. But I couldn't find it. If so feel free to close this one.

**Comment by sabeechen** [comment]
I don't have an iOS device to test this, but it looks like the same thing is happening in the Android app.  I'll see if I can figure it out.

**Comment by passie** [comment]
I got some advise from another topic, where they mention swiping from the left. 
This brings back the menu as well. (I did not knew about this)
If this is ok with you guys as well, i'm happy to close this issue as a non-issue.
Let me know.

**Comment by sabeechen** [comment]
looking at this a little more now, it seems like every addon has this problem.  Moreover in the Home Assistant web interface clicking back often open up another sidebar menu (again, with any addon).  I suspect Home assistant is doing something weird with its Iframes here, but it isn't something I'm going to be able to resolve with this addon.
