### ISSUE TITLE
Repostitory structure for v0.98.1 is not compliant

### ISSUE THREAD

**Issue by thinx0r** [sabeechen/hassio-google-drive-backup#206]
I'm trying to add the repo to a fresh home assistant installation in hacs and get the error: Repostitory structure for v0.98.1 is not compliant

Can someone please give me a hint what am I missing?

<img width="439" alt="Screenshot 2020-07-08 at 20 33 08" src="https://user-images.githubusercontent.com/66439409/86957382-ee73b800-c15a-11ea-925c-fde290b0e425.png">

**Comment by sabeechen** [comment]
This isn't a HACS plugin, you have to install it through the Home Assistant Supervisor's (formerlly Hassio) add-on interface.
