### ISSUE TITLE
homeassistant back-up not including the .storage folder

### ISSUE THREAD

**Issue by jgbalcombe** [sabeechen/hassio-google-drive-backup#207]
Hi,

Great and useful product - thank you!

However, noticed that the .storage folder isn't being stored within the homeassistant archive. Not sure if this is by design. But (like me) my lovelace configuration isn't been backed up as a result.

Is this something I've done wrong? missing some sort of configuration?

Thanks!

**Comment by sabeechen** [comment]
Make sure you don't have partial snapshots turned on, but most likely you've run into [this bug](https://github.com/home-assistant/supervisor/issues/1633) in the Home Assistant supervisor.  This addon uses the supervisor to actually make snapshots, so issues it has often end up getting reported here.    If some of your snapshots have the homeassistant archive and others don't this is definitely it.  You'd also be able to see an error printed in the supervisor's log when a snapshot missing the folder is made.

A [fix](https://github.com/home-assistant/supervisor/pull/1795) has been made for the issue, but I'm not sure if its made it into a Home Assistant release yet.

**Comment by sabeechen** [comment]
I think this got resolved in Home Assistant/The supervisor, but let me know if you still think there is something wrong in the addon.
