### ISSUE TITLE
decrypt error

### ISSUE THREAD

**Issue by dodepier** [sabeechen/hassio-google-drive-backup#208]
Hello,

My SD card fault. So I try to restore a snapshot on a new installation 0.112.4 (Hassio). However, I do get an error when I try to restore the snapshot. The snapshots are password protected. I did try around 5 snapshot also the frist one (1 year old).All snapshots give the same error. I did try 'wipe and restore' and 'restore selected'. What does this error mean?

```
20-07-13 08:08:33 INFO (MainThread) [supervisor.snapshots] Restore 8a2c66a0 run Home-Assistant
20-07-13 08:08:33 ERROR (MainThread) [supervisor.snapshots] Restore 8a2c66a0 error
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/snapshots/__init__.py", line 232, in do_restore_full
    snapshot.restore_homeassistant()
  File "/usr/src/supervisor/supervisor/snapshots/snapshot.py", line 464, in restore_homeassistant
    self.homeassistant[ATTR_REFRESH_TOKEN]
  File "/usr/src/supervisor/supervisor/snapshots/snapshot.py", line 208, in _decrypt_data
    data = padder.update(decrypt.update(b64decode(data))) + padder.finalize()
  File "/usr/local/lib/python3.7/site-packages/cryptography/hazmat/primitives/padding.py", line 144, in finalize
    lib.Cryptography_check_pkcs7_padding)
  File "/usr/local/lib/python3.7/site-packages/cryptography/hazmat/primitives/padding.py", line 89, in _byte_unpadding_check
    raise ValueError("Invalid padding bytes.")
ValueError: Invalid padding bytes.
```

UPDATE:

It seems that hassio does not check capitals in password but if not correct gives this error during the restore process. I did check my password and did a full restore :)

**Comment by sabeechen** [comment]
I've never seen this error before, but it looks a lot like data corruption.  Is it possible the hard drive this was stored on was bad and corrupted the archive before it got uploaded to Google Drive?  I'd expect that to be pretty rare, but it does happen.  The addon itself depends on the Home Assistant Supervisor to create the snapshot, restore it, etc.  It only copies the unmodified snapshot archive Home Assistant gives it into Drive.

**Comment by dodepier** [comment]
It seems that hassio does not check capitals in password but if not correct gives this error during the restore process. I did check my password and did a full restore :)
