### ISSUE TITLE
Massive spike in backup size

### ISSUE THREAD

**Issue by nytram-md** [sabeechen/hassio-google-drive-backup#209]
Ive used this for a few months now and my backups are about 250MB 

Ive been on 0112.4 for a few days now and back ups all OK but this morning at 2am my backup jumped to 4GB in size and could not upload to Google Drive as it said I had run out of space.

Looking at this. My Hard drive size is 500GB but only using about 30GB of it but the backup today made my disk size spike at 80GB and when it finished it has now uploaded a 4GB backup to Google Drive and my disk size has gone back from 80GB back down to 30GB.

When I tried to open my 4GB file... there is no actual file that has got a large file size.

Thanks

Martyn

![image](https://user-images.githubusercontent.com/55548608/87324772-7fb2a800-c528-11ea-9a60-79eb79ea7444.png)

**Comment by nytram-md** [comment]
![image](https://user-images.githubusercontent.com/55548608/87324909-affa4680-c528-11ea-9f74-da301e12fea9.png)

**Comment by sabeechen** [comment]
First a little disclaimer: The addon uses the Home Assistant Supervisor to actually create the snapshots, which is almost certainly responsible for the weirdness you're seeing.  So while I doubt this is a problem with the addon per-se, I'll offer any advice I can give.

There is almost certainly some file in the archive taking up that extra space, I don't think there is a way of adding "empty" space to an archive and I'm not aware of anything in the Supervisor that would attempt to do so.  The file is probably burried deep within the folder heirarchy somewhere.  The supervisor isn't super efficient in how it creates snapshots, so it often leaves a lot of temp files behind that get cleaned up later on.  
Based on the pattern you've described, I'd guess that some file (probably a log file) got really big briefly, a snapshot got taken, and then sometime later the file got cleane dup or deleted.  For example the Home Assistant and and z-wave logs can get really spammy sometimes if a sensor goes down and it repeatedly runs into errors trying to reach it.

If you haven't already I'd recommend fully extracting the problematic snapshot and then searching for the largest files (eg with windows explorer).

**Comment by nytram-md** [comment]
Hi. I downloaded them yesterday not long after but didnt have time to look.

Just done so now and its the ADB Addon. I never used it. So just uninstalled it and run a test backup and its down to 174MB. So fully agree its not the backup.

Apologies but thanks for the reply and I will close the issue. 

Keep up the good work

Martyn

PS a feature update would be to see the info on a lovelace card if its possible ie how many backups, last backup and sizes etc and then we can do an automation ie if the backup size is above 500MB, then send me a notification
