### ISSUE TITLE
Error about binary sensor

### ISSUE THREAD

**Issue by damiano75** [sabeechen/hassio-google-drive-backup#21]
Hi,
I have a lot of erros in system log:

`Error on call https://172.30.32.1:8123/api/states/binary_sensor.snapshots_stale: Cannot connect to host 172.30.32.1:8123 ssl:None [Connection refused]`

It seems it tries to access to another ip.

Where can I configure this binary_sensor?

**Comment by sabeechen** [comment]
This most likely indicates that the add-on wasn't able to reach Home Assistant, that url is the one it uses to publish the state of the "binary_Sensor.snapshots_stale" sensor.  If you're seeing it consistently (eg right now every few seconds) then there is something wrong with your installation.  

If you're only seeing it when you restart or update Home Assistant, then its expected.  The add-on will be unable to connect to Home Assistant while its being restarted.

If you'd like the add-on to stop trying to publish this sensor, you can turn it off from the add-on's settings menu or by setting `"enable_snapshot_stale_sensor": false,` in your add-on configuration.

**Comment by damiano75** [comment]
Hi, it seems that after the last update I don't have the error any more.
Thank you

**Comment by lebaanbinh** [comment]
Hi, I have put the enable_snapshot_stale_sensor to false in the add-on configuration so the snapshot_stale_sensor error is gone. However, I still have this:
```
19-05-04 14:34:19 ERROR (MainThread) [hassio.homeassistant] Error on call http://172.30.32.1:8123/api/states/sensor.snapshot_backup: Cannot connect to host 172.30.32.1:8123 ssl:None [Connection refused]
19-05-04 14:34:19 ERROR (MainThread) [hassio.api.proxy] Error on API for request states/sensor.snapshot_backup
```
Could you shed some light on this please?
Btw, awesome add-on.

**Comment by sabeechen** [comment]
Its another sensor with details about the snapshots (count, last updated, next snapshot time, names, etc).  You can [turn it off](https://github.com/sabeechen/hassio-google-drive-backup#configuration-options) in the settings UI or with the config `"enable_snapshot_state_sensor": false`

**Comment by lebaanbinh** [comment]
> Its another sensor with details about the snapshots (count, last updated, next snapshot time, names, etc). You can [turn it off](https://github.com/sabeechen/hassio-google-drive-backup#configuration-options) in the settings UI or with the config `"enable_snapshot_state_sensor": false`

Thank you!
