### ISSUE TITLE
Documentation for contributing on the project (local development)?

### ISSUE THREAD

**Issue by ericmatte** [sabeechen/hassio-google-drive-backup#211]
Hi!

I would like to help out in some of my free time on your project.

I tried to run the project locally using the included VSCode tasks and the Dockerfiles.
However, building the image or installing the dependencies on a virtual python env fail for me, probably because I don't know the right way to set it up.

Do you have some documentation about how to properly run the project locally for development? That would be great!

Thank you!

**Comment by sabeechen** [comment]
Its taken me an embarrassing of time to get around to it, but I've made instructions for running the project locally and contributing [here](https://github.com/sabeechen/hassio-google-drive-backup/blob/master/CONTRIBUTING.md).  Let me know if you have any other questions.

**Comment by ericmatte** [comment]
This is great; thank you!
