### ISSUE TITLE
More useful timestamps

### ISSUE THREAD

**Issue by AlecRust** [sabeechen/hassio-google-drive-backup#212]
Just switched to this add-on, it's fantastic great work!

After configuring my schedule for backups the dashboard has some useful time outputs:

![screenshot](https://i.imgur.com/7Wudv8C.png)

I'd like a little more information here to avoid needing to do the math in my head to check this is scheduled for/happened at the times I expected.

One quick solution which would satisfy this would be to replace this:

```html
<h6 class="right" id="next_snapshot">14 hours</h6>
```

With something like this:

```html
<h6 class="right" id="next_snapshot">
  <time datetime="2020-08-02T03:00:00+01:00" title="2nd August, 2020 03:00">14 hours</time>
</h6>
```

This would provide tooltips for the friendly "hours ago" text which is somewhat of a convention.

**Comment by AlecRust** [comment]
In addition, these timestamps could be easier to read:

![screenshot](https://i.imgur.com/Fnsagwf.png)

**Comment by sabeechen** [comment]
Both good suggestions, I'lll add them in the next release.  Wasn't aware of the <time/> html tag before!

**Comment by sabeechen** [comment]
I've added this in the latest release, 0.101.0.  You can got to "Add-on Store" - > Click the 3 dots > "Reload" to make Home Assistant see the latest version.
