### ISSUE TITLE
Snapshot stale sensor 

### ISSUE THREAD

**Issue by groenmarsmannetje** [sabeechen/hassio-google-drive-backup#214]
Please assign the Problem device_class to this sensor, so that it better reflects its purpose and also takes translations into account.

**Comment by sabeechen** [comment]
Good idea, I'll add it in the next version.

**Comment by sabeechen** [comment]
I've added this in the latest release, 0.101.0.  You can got to "Add-on Store" - > Click the 3 dots > "Reload" to make Home Assistant see the latest version.
