### ISSUE TITLE
Settings pop-up should have save button always visible

### ISSUE THREAD

**Issue by mnaz** [sabeechen/hassio-google-drive-backup#22]
First off let me say you have done a great job and this add-in has helped me greatly.

The first time I got to the settings pop-up I did not realize it was more than what was showing. It was not clear that you could scroll and how to save content.

I was thinking that it might be nice to show the save button at the top. It would also be nice to have smarts to tell you you have changed settings and confirm you do not want to save when hitting ESC.

**Comment by sabeechen** [comment]
I'll change it to always be anchored to the bottom of the settings screen (eg it doesn't scroll away), since I think thats more common in such dialogs.  Agreed that it should confirm on unsaved changes, I'll add it to the next release.

**Comment by mnaz** [comment]
Sounds better, thanks for considering my comments.

**Comment by mnaz** [comment]
Verified with V0.91, Cancel and Save button always visible. When change made hitting Cancel or ESC show popup that indicates unsaved changes.
