### ISSUE TITLE
Device-class problem with the states

### ISSUE THREAD

**Issue by McGiverGim** [sabeechen/hassio-google-drive-backup#222]
The `binary_sensor.snapshots_stale` is not being shown as expected in the lovelace UI. 

The `device-class: problem` with states `on/off` is being showed in the UI of Home Assistant in a correct way (when it's `off` it appears as `OK` -no problem-). But your sensor uses `True/False` states and the UI is not able to interpret and shows them as `True/False`.

I don't know if this is a problem of Home Assistant that must accept `True/False` as states or is easier if you change the states of your sensorto the habitual `on/off`.

Regards and thanks for your plugin!!!

**Comment by sabeechen** [comment]
Yikes, you're right.  This has been wrong since the addon was first released.
Unfortunately, fixing this would likely break anyone who has created an automation based on the sensor.  Let me see if I can find a better way to fix this.

**Comment by sabeechen** [comment]
I've just released a new version, v0.101.1, that should resolve this by using the proper states.   If it doesn't work properly for you after updating, please let me know.
