### ISSUE TITLE
Sort backup listing newest at top.

### ISSUE THREAD

**Issue by mnaz** [sabeechen/hassio-google-drive-backup#23]
It would be easier when the list grows to show the current active backup along with newest first. This would avoid needing to scroll.

This is more a feature request :)

**Comment by sabeechen** [comment]
Good idea, I'll add this in the next release.  I recall intending to do this at some point, but I just kind of got used to the way it was :P

**Comment by mnaz** [comment]
Verified with V0.91, backup listing sort order is now current and most recent at top.
