### ISSUE TITLE
ERROR Worker Sync Worker got an unexpected error

### ISSUE THREAD

**Issue by uherting** [sabeechen/hassio-google-drive-backup#232]
**Just found the following entries in the log of the add-on:**

`
08-21 14:16:11 INFO Starting server on port 8099
08-21 14:16:11 INFO Server started
08-21 14:16:11 INFO Syncing Snapshots
08-21 14:29:32 INFO Requesting a new snapshot
08-21 14:29:52 INFO Deleting 'Full Snapshot 2020-08-21 06:49:30' From Google Drive
08-21 14:29:53 INFO Deleting 'Full Snapshot 2020-08-21 06:49:30' from Home Assistant
08-21 14:29:53 ERROR Worker Sync Worker got an unexpected error
08-21 14:29:53 ERROR 
  addon/backup/worker/worker.py:27 (work)
  addon/backup/model/syncer.py:31 (checkforSync)
  addon/backup/model/coordinator.py:63 (sync)
  addon/backup/model/coordinator.py:281 (_withSoftLock)
backup.exceptions.exceptions.PleaseWait

08-21 14:29:58 INFO Backup directory changed
08-21 14:29:58 INFO Syncing Snapshots
08-21 14:38:35 INFO Snapshot finished
08-21 14:38:36 INFO Syncing Snapshots
08-21 14:38:37 INFO Uploading 'Full Snapshot HA 0.114.3 - 20200821 142932' to Google Drive
08-21 14:43:10 INFO Backup directory changed
08-21 14:43:10 INFO Syncing Snapshots
`

**My configuration is as follows:**
`
max_snapshots_in_hassio: 4
max_snapshots_in_google_drive: 15
days_between_snapshots: 1
use_ssl: false
generational_day_of_week: sun
snapshot_time_of_day: '06:00'
send_error_reports: false
generational_days: 2
generational_weeks: 4
generational_months: 4
background_color: '#242424'
accent_color: '#7D0034'
enable_snapshot_state_sensor: true
enable_snapshot_stale_sensor: true
notify_for_stale_snapshots: true
snapshot_stale_minutes: 180
snapshot_name: '{type} Snapshot HA {version_ha} - {year}{month}{day} {hr24}{min}{sec}'

`

**Comment by uherting** [comment]
@sabeechen : Thank you!

**Comment by sabeechen** [comment]
Forgot to mention when I released it, but I suppressed this error in v0.101.2 a few days ago.
