### ISSUE TITLE
Unable to Set !secret Password

### ISSUE THREAD

**Issue by IIAIronWolf** [sabeechen/hassio-google-drive-backup#238]
I am setting up this add-on for the first time and tried to set my snapshot password using  `!secret`, but as soon as you add a `!` the add-on reports "Invalid YAML".
![image](https://user-images.githubusercontent.com/51146434/91317624-e827b280-e77f-11ea-96a8-5a3a36fd3414.png)

**Comment by sabeechen** [comment]
I believe YAML needs quotes around a value if it includes a "!", so I think you'd want
```yaml
snapshot_password: "!secret snapshot_pass"
````
Alternatively, you can set the password in the addon Web-UI by clicking "setting" up at the top.

**Comment by IIAIronWolf** [comment]
If you do that, it results in: 
![image](https://user-images.githubusercontent.com/51146434/91492820-e93e0a00-e87b-11ea-922b-a6f54120d403.png)

**Comment by IIAIronWolf** [comment]
However, if you can do it from the UI, it's not that big of a deal, I suppose.

**Comment by sabeechen** [comment]
I think the reason the supervisor is complaining is because of `snapshot_stale_minutes`.  It should be` snapshot_stale_seconds`, I'll update the docs.

**Comment by sabeechen** [comment]
I've updated the docs, let me know if you run into any other problems.
