### ISSUE TITLE
This is awesome.

### ISSUE THREAD

**Issue by Brianckramer** [sabeechen/hassio-google-drive-backup#24]
I don't have any issues, I just wanted to say that this is one of the best addons I've ever seen.  Thank you so much for your work, and for going the extra mile and making it so easy to use and reliable.  Other addons should use this as an example of how to make the UI easy to configure.

**Comment by sabeechen** [comment]
Thanks!  I tried pretty hard to keep things form being janky so I'm really pleased its coming across that way.

**Comment by gdreelin** [comment]
Out of all the backup ideas I have seen for HASSIO this one is the best! It was so easy to setup and it performs without having to have any automation code added or work arounds, so far it has been working flawlessly. Great job on this!

**Comment by sabeechen** [comment]
Thanks, that was part of my goal.  From the developer side I end up hearing a lot more about what *isn't* working than what is, so its really motivating when someone takes the time to let me know things worked well for them :)

**Comment by PrathikGopal** [comment]
Thank you for your hard work, the setup is just so clean and easy. 👍

**Comment by gdreelin** [comment]
> 
> 
> Thanks, that was part of my goal. From the developer side I end up hearing a lot more about what _isn't_ working than what is, so its really motivating when someone takes the time to let me know things worked well for them :)

No problem man I think you work has been great... best part DrZzs post your link yesterday on his live stream so it is getting out there more. I agree with @PrathikGopal thank you so much for the hard work on this. It is very clean and easy but best it works without any extra programming.  Cheers!

**Comment by DavidDeSloovere** [comment]
![were not worthy waynes world GIF](https://media1.giphy.com/media/iiS84hOJXh1Pq/giphy.gif)

**Comment by sabeechen** [comment]
Just closing this out to keep my issue list clean.  Thank you for the praise.  You ARE worthy!
