### ISSUE TITLE
binary_sensor.snapshots_stale Error

### ISSUE THREAD

**Issue by sotatech** [sabeechen/hassio-google-drive-backup#25]
I'm seeing a lot of these errors in the logs:
```
2019-04-25 10:39:49,394 ERROR 
Traceback (most recent call last):
  File "/app/backup/hassio.py", line 277, in _postHaData
    requests.post(self.config.haBaseUrl() + path, headers=self.config.getHaHeaders(), json=data).raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: http://hassio/homeassistant/api/states/binary_sensor.snapshots_stale
```
It's using the wrong URL (http://hassio/homeassistant/) for my HA as I use my own domain. Is there a way to change this?

**Comment by sabeechen** [comment]
The addon uses an internal proxy for HA that hassio provides, so that's the right URL.  It'll get http 502 when HA is down briefly (eg if you restart it for a config change or something else).  Seeing some amount of this message is normal.  Are you actually seeing a malfunction or is this just in the log?

**Comment by sotatech** [comment]
Add-on is working fine, so itmbay have been because I had updated HA yesterday and it neded a few restarts. Today I notice that it is spamming the logs a lot:
```
19-04-26 11:14:13 INFO (MainThread) [hassio.api.security] /homeassistant/info access from cebe7a76_hassio_google_drive_backup
19-04-26 11:14:13 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
19-04-26 11:14:14 INFO (MainThread) [hassio.api.security] /snapshots/f2a6eb94/info access from cebe7a76_hassio_google_drive_backup
19-04-26 11:14:14 INFO (MainThread) [hassio.api.security] /snapshots/c027aa08/info access from cebe7a76_hassio_google_drive_backup
19-04-26 11:14:14 INFO (MainThread) [hassio.api.security] /snapshots/d1b81308/info access from cebe7a76_hassio_google_drive_backup
19-04-26 11:14:14 INFO (MainThread) [hassio.api.security] /snapshots/b864950b/info access from cebe7a76_hassio_google_drive_backup
19-04-26 11:14:14 INFO (MainThread) [hassio.api.security] /snapshots/23aeef01/info access from cebe7a76_hassio_google_drive_backup
19-04-26 11:14:14 INFO (MainThread) [hassio.api.security] /snapshots/a40f3b38/info access from cebe7a76_hassio_google_drive_backup
19-04-26 11:14:14 INFO (MainThread) [hassio.api.security] /snapshots/bc6bbcbd/info access from cebe7a76_hassio_google_drive_backup
19-04-26 11:29:29 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
```
These messages are repeated every 15 minutes or so.

**Comment by sabeechen** [comment]
Hassio logs *almost* every time time an add-on accesses a Home Assistant or Hassio endpoint, I'm not sure why but this is how Hassio has decided to do their logging.

**Comment by sotatech** [comment]
OK, thanks for the explaination.

**Comment by tjorim** [comment]
It's actually pretty annoying to see this ammount of errors when you're doing an upgrade of  Home Assistant. This makes it almost impossible to see why an upgrade failed because the logs are just flooded. Would it be possible to set a time-out if it fails? On subsequent fails just time-out a bit longer each time...
`19-05-09 07:49:34 ERROR (MainThread) [hassio.homeassistant] Error on call http://172.30.32.1:8123/api/states/binary_sensor.snapshots_stale: Cannot connect to host 172.30.32.1:8123 ssl:None [Connection refused]
19-05-09 07:49:34 ERROR (MainThread) [hassio.api.proxy] Error on API for request states/binary_sensor.snapshots_stale`

**Comment by juampick** [comment]
Is there any solution for this?

**Comment by vMeph** [comment]
i see this problem alot also

**Comment by danielsjf** [comment]
I'm doing an upgrade to a newer version and this issue eventually seems to trigger a rollback.

`20-04-11 00:49:47 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository
20-04-11 00:49:47 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
20-04-11 00:49:47 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-04-11 00:49:49 INFO (MainThread) [supervisor.store] Load add-ons from store: 66 all - 0 new - 0 remove
20-04-11 00:51:25 ERROR (MainThread) [supervisor.homeassistant] Error on call https://172.30.32.1:8123/api/states/binary_sensor.snapshots_stale: Cannot connect to host 172.30.32.1:8123 ssl:None [Connection refused]
20-04-11 00:51:25 ERROR (MainThread) [supervisor.api.proxy] Error on API for request states/binary_sensor.snapshots_stale
20-04-11 00:54:18 WARNING (MainThread) [supervisor.homeassistant] Don't wait anymore of Home Assistant startup!
20-04-11 00:54:18 CRITICAL (MainThread) [supervisor.homeassistant] HomeAssistant update fails -> rollback!
20-04-11 00:54:18 INFO (MainThread) [supervisor.homeassistant] Update Home Assistant to version 0.107.0
20-04-11 00:54:18 INFO (SyncWorker_19) [supervisor.docker.interface] Update image homeassistant/raspberrypi4-64-homeassistant:0.108.2 to homeassistant/raspberrypi4-64-homeassistant:0.107.0 `
