### ISSUE TITLE
401: unauthorized after "Confirm your choices" auth permission screen

### ISSUE THREAD

**Issue by tylerlucas** [sabeechen/hassio-google-drive-backup#255]
Receiving a 401: unauthorized message when attempting to get the add-on set up for the first time.

- First, I've signed out of all of my Google accounts, then:
- From the web UI, I click "authenticate with Google Drive"
- Select the Google account I want to use
- "You already gave habackup.io access to:
   - View and manage Google Drive files and folders that you have opened or created with this app
   - Make sure you trust habackup.io
   - You may be sharing sensitive info with this site or app. Learn about how habackup.io will handle your data by reviewing its terms of service and privacy policies. You can always see or remove access in your Google Account."
- Click "Allow"
- 401: unauthorized

Any idea what's going on? The "You already gave access..." seems to indicate that I'm set up, but the web UI always takes me to the "Authenticate with Google Drive" screen, with no other options.

**Comment by sabeechen** [comment]
I'm looking into it, please see #257 for suggested workarounds.
Duplicate #257
