### ISSUE TITLE
401: Unauthorized when attempting to authorize with Google Drive

### ISSUE THREAD

**Issue by sabeechen** [sabeechen/hassio-google-drive-backup#257]
I'm still looking into the problem, but heres what I've found so far:

- It happens when I use firefox, and doesn't when I use chrome.
- A lot of users are running into it.
- It doesn't happen when I use a "fresh" installation of firefox (eg default settings).

I haven't made any releases recently and this doesn't appear to be tied to specific supervisor version.  I'm suspecting something changed in firefox.

**Potential Workarounds**
- Disable the "Delete cookies and site data when Firefox is closed" option while you authenticate the addon.
- Copy the URL form the address bar on the page when you get a "401" error and then open it in a new tab.  I know this sounds stupid but it worked every time for me.  No idea why.
- Authenticate in chrome or chromium instead of firefox.

**Comment by sabeechen** [comment]
If you're trying to install the addon to restore snapshots on a fresh install and the above doesn't work for you, you can still:
- download your snapshots from Google Drive
- put them in Home Assistant's /backup folder using something like the Samba addon
- Navigate to "Supervisor" -> "Snapshots" to restore them.

The snapshots this addon creates are the same as the ones the sueprvisor creates from that page.

**Comment by hscheele** [comment]
Stupid solution works also for me (here for Chrome). Therefore connection to Google drive can be established. But updates are not visible within add-on, althought the right folder is connected. 

> **Potential Workarounds**
> 
> * Copy the URL form the address bar on the page when you get a "401" error and then open it in a new tab.  I know this sounds stupid but it worked every time for me.  No idea why.
> * Authenticate in chrome or chromium instead of firefox.

**Comment by hscheele** [comment]
Workaround doesn't works for me as manually put backups are not visible in add-on, even after refreshing browser. Renaming to something simple makes no difference, although I started with naming as suggested by add-on during storage on Google Drive. Deleting achive bit (the only difference to a newly created snapshot by a new install) makes no difference also as expected. 

> If you're trying to install the addon to restore snapshots on a fresh install and the above doesn't work for you, you can still:
> 
> * download your snapshots from Google Drive
> * put them in Home Assistant's /backup folder using something like the Samba addon
> * Navigate to "Supervisor" -> "Snapshots" to restore them.
> 
> The snapshots this addon creates are the same as the ones the sueprvisor creates from that page.

**Comment by sabeechen** [comment]
Do you mean that your snapshots aren't in Google Drive?

**Comment by hscheele** [comment]
They are, although I now have 3 different folders there based on the various installations since NOV 2019 (named "Hass.io Snapshots") and the recent ones yesterday and a few days before (each named "Home Assistant Snapshots"). But directing the add-on manually to the right one of them seems to work. But after that no former backups visible within add-on

**Comment by sabeechen** [comment]
Were you previously using your own google api credentials?  You would have had to follow the instructions [here ](https://github.com/sabeechen/hassio-google-drive-backup/blob/master/LOCAL_AUTH.md)to do so.  If you did that, you'll need to use those credentials again to see the snapshots created using them

**Comment by hscheele** [comment]
No, nothing own created or special. Same basic config as worked as a charm since NOV 2019.

**Comment by sabeechen** [comment]
I've created #258 for your issue, since I'd like to keep the discussion in this thread about the mysterious 401 error.  We can continue the discussion there.

**Comment by sabeechen** [comment]
I’ve been testing around with different browser configurations, and I’m pretty sure this “401: Permission Denied” issue only affects users of Firefox who have it set to automatically delete cookies when the browser closes.
I don’t know why this would cause problems, but turning it on is the only thing I’ve found that reliably reproduces the problem. The error message is actually the Home Assistant Supervisor claiming that your browser isn’t presenting the cookie that verifies you’re logged in to Home Assistant.

I've tried using an older version of, v79.0.0 (80.0.1 is current latest) and I see the same problem, so I don't think this is a sudden regression in Firefox.  I'm at a loss for how this could just suddenly start happening.  I haven't released a new version of the addon, it doesn't look like it was an update in Firefox, and its not because of a new supervisor version.  Nothing has changed.

If anyone is seeing this error and they aren't using Firefox with the "Delete cookies and site data when Firefox is closed" option enabled, please chime in so I can broaden my search for other sources of the problem.

**Comment by danmed** [comment]
I am seeing the problem in both Firefox and Chrome and i do not delete cookes when either of them are closed down.

> 
> 
> I’ve been testing around with different browser configurations, and I’m pretty sure this “401: Permission Denied” issue only affects users of Firefox who have it set to automatically delete cookies when the browser closes.
> I don’t know why this would cause problems, but turning it on is the only thing I’ve found that reliably reproduces the problem. The error message is actually the Home Assistant Supervisor claiming that your browser isn’t presenting the cookie that verifies you’re logged in to Home Assistant.
> 
> I've tried using an older version of, v79.0.0 (80.0.1 is current latest) and I see the same problem, so I don't think this is a sudden regression in Firefox. I'm at a loss for how this could just suddenly start happening. I haven't released a new version of the addon, it doesn't look like it was an update in Firefox, and its not because of a new supervisor version. Nothing has changed.
> 
> If anyone is seeing this error and they aren't using Firefox with the "Delete cookies and site data when Firefox is closed" option enabled, please chime in so I can broaden my search for other sources of the problem.

I am seeing the problem in both Firefox and Chrome and i do not delete cookes when either of them are closed down.

**Comment by xTopher1049** [comment]
I was running into this same issue just now on a fresh install. I am using **Google Chrome**. Opening a new tab and copying pasting URL worked. Just FYI since I see lots of talk of it only being an issue in Firefox...

**Comment by sabeechen** [comment]
Well, that throws the firefox idea out.  This is problem exteremely weird.

**Comment by danmed** [comment]
Yep same copying the URL to a new tab works fine.

**Comment by NobleWolf** [comment]
Copy+paste the url at the 401 error window to a new tab works.
I tried "Duplicating" the tab but that did not work.
Using Chrome 85.0.4183.83

Before finding this bug I attempted to clear my cache and cookies, as well as sign out of all Google accounts. Neither of those actions worked. Thank you @sabeechen  for this amazing add-on. Let us know if there is anything we can do for testing a fix.

**Comment by sabeechen** [comment]
Thanks, I've had a lot of trouble figuring out why this stopped working.  

To recap:
As far as I can tell, when I redirect the browser from habackup.io to your local addon to pass along Google Drive credentials, for some users the session cookie that indicates to the supervisor your broswer has permission doesn't get included in the request.  This causes the supervisor to reject the request (HTTP 401), so the addon never gets the credentials it needs to work.

I've been able to reproduce this in:
- Edge (always) 
- Firefox if I configure it to "Delete cookies and site data when Firefox is closed"

Other users have indicated that it also fails for them in Chrome, but I haven't been able to make that happen.  I don't know why the Firefox setting changes this behavior, since that should only do something if the browser is restarted.

Whats most mysterious is why it started happening at all.  The addon has worked this way for over a year and this issue has never been reported, but now I can reliably make it happen.  I suspect Google (which hosts habackup.io) has changed something about how the redirect is served, but I lack the experience in these technologies to prove thats the case.  The appearance of the problem isn't correlated with a release of the addon, the supervisor, or the browsers affected. 

To fix this, I'm going to change the way credentials get passed back to the addon.  If it fails (it still doesn't for most users), Ill provide a string that you can copy/paste into the reauthorization page to work around the issue.

**Comment by mickdcsw** [comment]
So I was having the same 401 error on 2 separate machines using Chrome and Safari.  Tried copying the URL into a new tab as was suggested worked for me as well.

**Comment by Speil** [comment]
Same here - fresh installed hass.io yesterday with 401 error while authorization (Chrome, newest version)

Will try the "copy url to a new tab" workaround this evening

**Comment by Speil** [comment]
> Same here - fresh installed hass.io yesterday with 401 error while authorization (Chrome, newest version)
> 
> Will try the "copy url to a new tab" workaround this evening

Copy url to a new tab worked for me as well!

**Comment by ghayoz** [comment]
Same issue for me 
`401: Unauthorized`
User of Safari.
New tab don't resolve the issue. 

Any solution please?

**Comment by Jens-Wymeersch** [comment]
Initially, I didn't have any problems and could get the backup to work (previous HA version). Since today, I'm getting this 401 error message. I tried with Chrome, Firefox and Safari. Copy'ing the URL, etc...
I see in the google account that access was given but still it ends up at this error. Anything new ?

**Comment by sabeechen** [comment]
I just released a new version of the addon, 0.101.3, which provides a workaround for this.  Now when you authorize the addon with Google Drive, you'll be given the chance to copy an authorization string into the addon instead of having it redirect directly.

I'll probably never figure out why this problem suddenly started happening, as I've said before it doesn't seems to be associated with any release of the addon, the supervisor, or Home Assistant.  This workaround makes authentication a little more complicated (at least one extra click), but it does resolve this issue.

I'm closing this bug for now, but if anyone runs into more trouble or is able to provide any more information about why this is happening, please chime in here.
