### ISSUE TITLE
Google Drive Backup does not start

### ISSUE THREAD

**Issue by phit2000** [sabeechen/hassio-google-drive-backup#259]
Dear all,

I'm having the issue that the plugin does not start. I can press start but as soon as I try to open I get a "bad gateway" message and "Add-on is not running. Please start it first".

Before the plugin was working since months without an issue. I don't really know when the issue started. I observed it after an upgrade to supervisor version 238. Now I'm at version 242 but the issue persists.

To troubleshoot I uninstalled the plugin and re-installed (after reboot). The issue remains.

Any idea how I can fix it?
Thanks a lot!

In the google drive backup logs I have following information:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/backup/__main__.py", line 3, in <module>
    import ptvsd
  File "/usr/lib/python3.8/site-packages/ptvsd/__init__.py", line 13, in <module>
    from ._vendored import force_pydevd
  File "/usr/lib/python3.8/site-packages/ptvsd/_vendored/force_pydevd.py", line 18, in <module>
    pydevd_constants = import_module('_pydevd_bundle.pydevd_constants')
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.8/site-packages/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_constants.py", line 205, in <module>
    from _pydev_imps._pydev_saved_modules import thread
  File "/usr/lib/python3.8/site-packages/ptvsd/_vendored/pydevd/_pydev_imps/_pydev_saved_modules.py", line 22, in <module>
    import xmlrpc.server as _pydev_SimpleXMLRPCServer
ValueError: source code string cannot contain null bytes
```

**Comment by sabeechen** [comment]
Weird, never seen that before.  That error suggest that one of the libraries the addon depends on has the wrong encoding, which really shouldn't happen.  I would have suggested reinstalling it, but you already did that.

What platform/environment are you running this on, and do you know if you're running the 32 or 64 bit version of Home Assistant?  (eg a raspberry pi3, in a VM, on top of ubuntu, etc)

**Comment by phit2000** [comment]
Sure - it is Home Assistant running on a Raspberry pi3B. I'm running the 64bit Version.

`
arch | aarch64
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.13
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v8
python_version | 3.8.3
supervisor | 242
timezone | Europe/Berlin
version | 0.114.4
virtualenv | false

`

**Comment by michaelblight** [comment]
I'm getting this too for the last couple of days, and also for File Editor (old Configurator). There is nothing obvious in the docker logs, although they only show since I started them manually. It started happening for me after a Windows Update reboot (I'm running under an Ubuntu VM), so this is different to the OP. Not sure if this is useful info or a red herring.

**Comment by sabeechen** [comment]
I just released a new version of the addon, v0.101.3.  Could you see if updating to the latest version resolves this?

**Comment by phit2000** [comment]
Hey Sabeechen, I just installed the latest version - unfortunately this didn’t  fix the issue. Thanks a lot for your support 👍 :)

**Comment by sabeechen** [comment]
Did you install using the per-made image from [here](https://www.home-assistant.io/hassio/installation/)?  I'm going to try to reproduce this since I have a pi3B+ I can test with.

**Comment by phit2000** [comment]
Yes, I installed it via that link. Strange thing though is that the plugin worked for approximately half a year w/o an issue. I checked the latest snapshot which was taken by the plugin and it worked with version Home Assistant 0.112.4.

<img width="477" alt="Bildschirmfoto 2020-09-23 um 07 45 39" src="https://user-images.githubusercontent.com/59516548/93971690-0679d180-fd71-11ea-9efa-716f69fc8e78.png">

**Comment by phit2000** [comment]
So - it is solved.

1. reinstallation HASS.IO on a blank SD card and restoring from a backup did **NOT** work - Google Drive backup was still not there.
2. What worked was to install HASS.IO on a blank SD Card, installing the google drive backup addon and then doing a restore from the backup.

Now everything works as expected again!
