### ISSUE TITLE
Can't Change Settings from Within WebUI Due to Error

### ISSUE THREAD

**Issue by IIAIronWolf** [sabeechen/hassio-google-drive-backup#260]
I am getting the following, red error message when I try to change settings from within the WebUI.
Note: I also get this error message if I open the settings page, change nothing, and hit save.
![image](https://user-images.githubusercontent.com/51146434/92799854-c16d9c80-f379-11ea-89b2-8a2986fd56ae.png)

**Comment by IIAIronWolf** [comment]
Error: '0' isn't a valid value for max_sync_interval_seconds

**Comment by IIAIronWolf** [comment]
Another note: My settings for max_sync_interval_seconds from the Add-Ons configuration section is: 86400

**Comment by sabeechen** [comment]
What does the settings dialog say near the bottom for "Sync Interval"?  It should be something like "1 day' the config you have.

**Comment by IIAIronWolf** [comment]
Ah I see. It is 0, 0, 0
![image](https://user-images.githubusercontent.com/51146434/92804943-52df0d80-f37e-11ea-9246-1baca0532ad2.png)

However, I manually set this in the configuration section already:
![image](https://user-images.githubusercontent.com/51146434/92805145-799d4400-f37e-11ea-95b0-5a3e95822c96.png)

**Comment by sabeechen** [comment]
its probably a problem in my parser, I'll need to do some testing.
In the meantime, you should be able to save your settings if you set it to "1 day" when you save.

**Comment by sabeechen** [comment]
Yup its a bug in how I format times that land on 'day', 'hour', and 'minute' boundaries.  I'll fix it in the next release.  You can work around it for now by setting the value to 86401 seconds or '1 day, 1 second'

**Comment by IIAIronWolf** [comment]
Thanks!

**Comment by sabeechen** [comment]
I've fixed this in the latest release 0.101.3, let me know if you run into any other trouble.
