### ISSUE TITLE
Got unexpected HTTP error 504. Gateway timeout

### ISSUE THREAD

**Issue by fiorentino77** [sabeechen/hassio-google-drive-backup#266]
Hi,
i would restore a snapshot from my google drive but during upload i've the error in subject and the progress bar stopped (around 60%/70%).
I've tried two browsers and two different pc with different snapshot but the issue it the same.
I've also increased Google Drive timeout to 1000 seconds.
Hassio ver. 0.115.2
Snapshots dimensions: 960mb

Any ideas?
Thanks in advance for any help.
Regards,

Alessandro

**Comment by sabeechen** [comment]
There is a lot it could be.  Do you see anything in the addon logs?

To get the snapshot uploaded right away, you can upload it without using the addon.  You'll need to:
- Download the snapshot from Google Drive
- Put it in the /backup folder (you can use the [Samba addon](https://github.com/home-assistant/hassio-addons/tree/master/samba) from the official addon store or anything that lets you access HA's filesystem).
- Go to "Supervisor" > "Snapshots" in the Home Assistant web-ui
- Click the refresh icon in the top right

Then you should be able to select the addon and restore it, partially or completely.

**Comment by sabeechen** [comment]
Let me know if there is anything else I can help with.
