### ISSUE TITLE
Please add a title

### ISSUE THREAD

**Issue by JJ00-dk** [sabeechen/hassio-google-drive-backup#268]
Hello and thank you for making this addon for HA. 
I use it and it works greate, BUT evertime it runs (for me at night) it will fill up my swap file to almost 100% and this over time makes my raspberri pi 4 with ssd crash. What can bee done about this??
Thanks in advance

**Comment by sabeechen** [comment]
The supervisor is probably using the swap to create the snapshot, snapshots can get quite large and expensive to create.  You'll probably need to either increase the swap or make your snapshots smaller.  You can use partial snapshots to only include some addons/folders in a snapshot.

**Comment by sabeechen** [comment]
Please feel free to reopen this if there is anything else I can help with.

**Comment by Anto79-ops** [comment]
Hi just wanted to follow up on this. I too noticed that my swap use increases when this SUPER AWESOME addon runs (i tested this by running a backup while watching the swap numbers). I do full backup and they are aroun 400 megs right now. I suspect this is on the larger side? If so, I can partial backups. One of my addon is  MariaDB and the database is 1.2 GB right now. I don't think this back backup my entire database, does it? I mean I don't want it to, and if it does, how can I keep MariaDB in the backup, but without the actualy large database file? for information, I use a RPi 4, 4GB with a 500 GB SSD via USB. Memory usage is around 40% (not sure why its even using the swap). thanks

**Comment by sabeechen** [comment]
I can't really comment as to why its using swap except to say, well, memory management is super complicated in modern computers and it uses the swap when it thinks doing so is the most efficient way to handle its workload.  Both this addon and HA are written in Python, which doesn't give the programmer low level control over memory usage.  High swap doesn't typically indicate a problem unless its causing other things to fail.

400 Mb is a pretty normal.  If you're doing a "Full" backup (the default) then the database is getting included and compressed, a high compression ratio is normal for the database.  If you want to exclude MariaDB you can remove it from the backup in the add-ons settings under the "Partial Snapshots" section.

**Comment by Anto79-ops** [comment]
Thank you! your explanation and addon are fantastic. Cheers and thankyou!
