### ISSUE TITLE
How to fully remove this addon? It takes space

### ISSUE THREAD

**Issue by Vendo232** [sabeechen/hassio-google-drive-backup#270]
I run 32GB NUC and after installing and performing backup I ran out of space for HA, uninstallation did not help.

Where was the addon installed and how can I fully remove apppx 3.5gb?

**Comment by sabeechen** [comment]
The addon probably made a snapshot, and snapshtos are managed by the supervisor.  You'll need to go to "Supervisor" > Snapshots" and delete any snapshots you don't want there.  Let me know if that doesn't resolve it for you.

**Comment by sabeechen** [comment]
Please feel free to reopen this if there is anything else I can help with.
