### ISSUE TITLE
Cant upload to Hassio 

### ISSUE THREAD

**Issue by david78455** [sabeechen/hassio-google-drive-backup#272]
Hi 
I try stop & start,  Uninstall and install. nothing
Keep `receiving` the same error. please help
Thanks
David

10-07 10:23:21 ERROR    
Traceback (most recent call last):   
  File "/app/backup/hasource.py", line 207, in save   
    resp = self.harequests.upload(stream)   
  File "/app/backup/harequests.py", line 41, in upload   
    return self._postHassioData(url, data=stream)   
  File "/app/backup/harequests.py", line 136, in _postHassioData   
    return self._validateHassioReply(self._client.post(url, headers=self._getHassioHeaders(), json=json, data=data))   
  File "/app/backup/harequests.py", line 98, in _validateHassioReply   
    resp.raise_for_status()   
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status   
    raise HTTPError(http_error_msg, response=self)   
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://hassio/snapshots/new/upload

**Comment by david78455** [comment]
I try again after upgrading the add on

10-07 11:17:49 ERROR [backup.ha.hasource]    
  addon/backup/ha/hasource.py:265 (save)   
  addon/backup/ha/harequests.py:26 (wrap_and_call)   
  addon/backup/ha/harequests.py:67 (upload)   
  addon/backup/ha/harequests.py:26 (wrap_and_call)   
  addon/backup/ha/harequests.py:213 (_postHassioData)   
  addon/backup/ha/harequests.py:175 (_validateHassioReply)   
  /site-packages/aiohttp/client_reqrep.py:941 (raise_for_status)   
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('http://hassio/snapshots/new/upload')

**Comment by sabeechen** [comment]
There was a change in the supervisor's API that broke this addon, I'll be makign a fix for it soon.  In the meantime you can still upload snapshots by copying them into the "/backup" folder using something like the Samba or FTP Addon,

**Comment by david78455** [comment]
Hi Sabeechen ,
Thanks, I have done that but unfortunately I cant see the snapshot from HA
I downloaded the file from your app and uploaded with samba to folder backup. I can see also in that folder other Tar files, but my uploaded file docent show at HA any idea ?
Regards
David

**Comment by sabeechen** [comment]
Make sure you reloaded the snapshots, which you can do by going o to "Supervisor" > "Snapshots" in the Home Assistant interface, click the three dots in the upper right hand corner and then click "Reload".  If that still doesn't work, then check "Supervisor" > "System" > "Logs" to see if the supervisor printed out any error messages.

**Comment by sabeechen** [comment]
I just realized there is also a new feature in the Supervisor.  If you're running the latest version there is an option to upload a snapshot file directly from the "three dot" menu in "Supervisor" > "Snapshots"

**Comment by sabeechen** [comment]
I just released the addon version 0.102.0, which includes a fix for this.  Please let me know or reopen this issue if you run into any trouble with the new version.
Also just a reminder, to make Home Assistant see the new version right away go to "Supervisor" > "Add-on Store" > Three dots in the top right corner > "Reload"

**Comment by david78455** [comment]
Hi 
I cant upgrade to the last VERSION of HA since  one of my component docent work in the new ver.
But I will try your new version and let you know
Thank s a lot for for all your effort and contribution
Regards
David

**Comment by david78455** [comment]
Hi Sabeechen 
Thanks again It is working!! 🥇 
Regards
David
