### ISSUE TITLE
Can't authenticate Google Drive.

### ISSUE THREAD

**Issue by Kev7274** [sabeechen/hassio-google-drive-backup#273]
I can't authenticate using the Blue Button or by pasting the Authorization string. I read that copying and pasting the URL in a new tab will work,but when I do that,I get this error....

{"http_status": 500, "error_type": "generic_error", "message": "An unexpected error occurred: Invalid base64-encoded string: number of data characters (593) cannot be 1 more than a multiple of 4", "details": "\n  addon/backup/ui/uiserver.py:634 (error_middleware)\n  addon/backup/ui/uiserver.py:326 (token)\n  /usr/lib/python3.8/base64.py:87 (b64decode)\nbinascii.Error: Invalid base64-encoded string: number of data characters (593) cannot be 1 more than a multiple of 4\n"}

Any ideas? Thanks

**Comment by Primo83** [comment]
similar
{"http_status": 500, "error_type": "generic_error", "message": "An unexpected error occurred: Incorrect padding", "details": "\n  addon/backup/ui/uiserver.py:634 (error_middleware)\n  addon/backup/ui/uiserver.py:326 (token)\n  /usr/lib/python3.8/base64.py:87 (b64decode)\nbinascii.Error: Incorrect padding\n"}

**Comment by Kev7274** [comment]
> similar
> {"http_status": 500, "error_type": "generic_error", "message": "An unexpected error occurred: Incorrect padding", "details": "\n addon/backup/ui/uiserver.py:634 (error_middleware)\n addon/backup/ui/uiserver.py:326 (token)\n /usr/lib/python3.8/base64.py:87 (b64decode)\nbinascii.Error: Incorrect padding\n"}
> 
> yesterday everything was ok

I just tried to install yesterday,so It's never worked.

**Comment by Primo83** [comment]
supervisor 247 fixed it

**Comment by Primo83** [comment]
> I can't authenticate using the Blue Button or by pasting the Authorization string. I read that copying and pasting the URL in a new tab will work,but when I do that,I get this error....
> 
> {"http_status": 500, "error_type": "generic_error", "message": "An unexpected error occurred: Invalid base64-encoded string: number of data characters (593) cannot be 1 more than a multiple of 4", "details": "\n addon/backup/ui/uiserver.py:634 (error_middleware)\n addon/backup/ui/uiserver.py:326 (token)\n /usr/lib/python3.8/base64.py:87 (b64decode)\nbinascii.Error: Invalid base64-encoded string: number of data characters (593) cannot be 1 more than a multiple of 4\n"}
> 
> Any ideas? Thanks

you have to update supervisor to 247
![image](https://user-images.githubusercontent.com/7441243/95344154-9ebb9e80-08b9-11eb-9c19-5fd03971e2b4.png)
 copy key with blue button (with all spaces) and paste (ctr + v)
![image](https://user-images.githubusercontent.com/7441243/95344448-f528dd00-08b9-11eb-8c17-364f73dee882.png)

**Comment by Andrey1One** [comment]
I have this problem too. 
<img width="167" alt="Снимок экрана 2020-10-07 в 17 27 19" src="https://user-images.githubusercontent.com/58969179/95344889-ca8f5200-08c2-11eb-9019-928b66005130.png">
<img width="1192" alt="Снимок экрана 2020-10-07 в 17 27 30" src="https://user-images.githubusercontent.com/58969179/95344893-cb27e880-08c2-11eb-81c3-b925677dcec3.png">
<img width="832" alt="Снимок экрана 2020-10-07 в 17 27 44" src="https://user-images.githubusercontent.com/58969179/95344899-cc591580-08c2-11eb-938c-16a9d92abbb1.png">

**Comment by Kev7274** [comment]
> > I can't authenticate using the Blue Button or by pasting the Authorization string. I read that copying and pasting the URL in a new tab will work,but when I do that,I get this error....
> > {"http_status": 500, "error_type": "generic_error", "message": "An unexpected error occurred: Invalid base64-encoded string: number of data characters (593) cannot be 1 more than a multiple of 4", "details": "\n addon/backup/ui/uiserver.py:634 (error_middleware)\n addon/backup/ui/uiserver.py:326 (token)\n /usr/lib/python3.8/base64.py:87 (b64decode)\nbinascii.Error: Invalid base64-encoded string: number of data characters (593) cannot be 1 more than a multiple of 4\n"}
> > Any ideas? Thanks
> 
> you have to update supervisor to 247
> ![image](https://user-images.githubusercontent.com/7441243/95344154-9ebb9e80-08b9-11eb-9c19-5fd03971e2b4.png)
> copy key with blue button (with all spaces) and paste (ctr + v)
> ![image](https://user-images.githubusercontent.com/7441243/95344448-f528dd00-08b9-11eb-8c17-364f73dee882.png)

Yeah,I've tried that also. Gives me a 401 error.

**Comment by Andrey1One** [comment]
supervisor 247 is beta now

**Comment by Kev7274** [comment]
> supervisor 247 is beta now

Excellent. Thanks for the info. I did a restart and it's working.
