### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by NCC-1031** [sabeechen/hassio-google-drive-backup#28]
I found a funny spelling error in "Snapshot State". Here is a screenshot.

![Skärmklipp](https://user-images.githubusercontent.com/50058210/56854912-464f4600-693e-11e9-8f07-2444e6b5b538.jpg)

**Comment by sabeechen** [comment]
Thanks, fingers move too fast sometimes :)  I'll fix this in a release soon.

**Comment by NCC-1031** [comment]
No problems, your work is fantastic!

Den sön 28 apr. 2019 01:15Stephen Beechen <notifications@github.com> skrev:

**Comment by sabeechen** [comment]
Fixed this in the latest release, 0.93
