### ISSUE TITLE
Enhancement - do not include recorder database

### ISSUE THREAD

**Issue by borpin** [sabeechen/hassio-google-drive-backup#280]
The recorder databases get really large unless you configure them.

It would be a really good feature to be able to exclude the recorder database.

**Comment by KTibow** [comment]
Doesn't this need to be added to hassio first? I wouldn't want it to delete it, take a snapshot, and re-add it.

**Comment by sabeechen** [comment]
The adodn just asks the supervisor to take snapshots, so you're right that this would need to be implemented in the supervisor (formerly Hassio) first.   I'd support it the if they ever did, but I don't think they're going to.

What I'd recommend for you is use something like the [Maria DB](https://github.com/home-assistant/hassio-addons/blob/master/mariadb/DOCS.md) as you database, and then configure snapshots to exclude the Maria DB addon.  That will in effect backup everythign except the database.

Alternatively, you can configure your [purge_keeps_days](https://www.home-assistant.io/integrations/recorder/#purge_keep_days) lower to just make the DB smaller.
