### ISSUE TITLE
HACS Integration 

### ISSUE THREAD

**Issue by cdrom1028** [sabeechen/hassio-google-drive-backup#283]
Is there any chance you will be offering this through HACS for easier deployment??

**Comment by pizzakid25** [comment]
> Is there any chance you will be offering this through HACS for easier deployment??

Sorry @cdrom1028, HACS [does not handle add-ons](https://hacs.xyz/docs/faq/addons). However, it could be offered as a [community add-on](https://addons.community), but it is a [very lengthy process](https://addons.community/contributing) and not every add-on gets approved.

**Comment by sabeechen** [comment]
@pizzakid25 is right, this addon *requires* the supervisor.
