### ISSUE TITLE
MEDIA folder

### ISSUE THREAD

**Issue by hellymellywell** [sabeechen/hassio-google-drive-backup#284]
Hello,

Since the last versions of HA, there is a new folder \media included in the snapshots.

In the supervisor snapshot options you can now select/unselect the \media folder to be included in the partial snapshot or not.

Is it possible to add this folder in the partial snapshots options in the Add-On?

Thanks in advance!
Jaime.

**Comment by sabeechen** [comment]
Yup, I'll be adding it in soon.

**Comment by sabeechen** [comment]
I just released the addon version 0.102.0, now supports the media folder.  Please let me know or reopen this issue if you run into any trouble with the new version.
Also just a reminder, to make Home Assistant see the new version right away go to "Supervisor" > "Add-on Store" > Three dots in the top right corner > "Reload"
