### ISSUE TITLE
Generational Backup

### ISSUE THREAD

**Issue by bttfw** [sabeechen/hassio-google-drive-backup#292]
Can Backups that are Generational Month, Week, Year also be marked as such so they can be identified more easily?

For example 

Full-Snapshot-Oct-2020
Full-Snapshot-W1-Oct-2020 
Full-Snapshot-W2-Oct-2020
Full-Snapshot-W3-Oct-2020
Full-Snapshot-W4-Oct-2020
Full-Snapshot-2020

and keep daily as they are

**Comment by sabeechen** [comment]
The way generational snapshots works is that as that as new snapshots get taken, older ones get promoted to be the representative for day -> week -> month  -> year, so doing this would require changing the name.  Unfortunately thats a rather expensive thing to do, the name is baked into the snapshot's metadata so changing would require recreating its archive.

Something I think I could do is add some extra flare in the interface, maybe under the name, that indicates what generation each archive is being saved for.

I'm short on time for the immediate future (just working through bugs for now) but I'll add this to the list of features I'd like to implement in the future.

**Comment by bttfw** [comment]
> The way generational snapshots works is that as that as new snapshots get taken, older ones get promoted to be the representative for day -> week -> month -> year, so doing this would require changing the name. Unfortunately thats a rather expensive thing to do, the name is baked into the snapshot's metadata so changing would require recreating its archive.
> 
> Something I think I could do is add some extra flare in the interface, maybe under the name, that indicates what generation each archive is being saved for.
> 
> I'm short on time for the immediate future (just working through bugs for now) but I'll add this to the list of features I'd like to implement in the future.

Thank You it has no priority at all so take your time all the important stuff works flawlessly

**Comment by sabeechen** [comment]
It took me a longer than I hoped to release this feature, but v0.104.1 is available with it now.  Snapshots have a special icon when they're part of a generational backup scheme and you can see which day/week/month/year they're saved for by hovering over the snapshot (or clicking it to view its details).

To update the addon, go to:
`Supervisor` > `Add-on Store` > Click the `...` in the top right > `Refresh`
and you should see the new version.

Kindly reopen this bug and let me know if you run into problems with this after updating.
