### ISSUE TITLE
Snapshot template {type} displays "Full" even if partial snapshots are configured

### ISSUE THREAD

**Issue by crowbarz** [sabeechen/hassio-google-drive-backup#294]
In the New Snapshot screen (and also in Settings > Snapshot Name Template), the rendered template (shown after `Your snapshots name will look something like:`) always substitutes `{type}` as `Full`, even if partial snapshots are configured in settings.

If I proceed and create a snapshot, the add-on does seem to create a partial snapshot with the correct name, so it looks like it is just a display issue.

I'm running 0.101.3 of your addon on top of HA Supervised on a self-managed Debian install, with supervisor 2020.10.0 and HA Core 0.116.4.

**Comment by sabeechen** [comment]
Heh, I thought no one would ever notice that.  But you did!  So I'll fix it.

**Comment by sabeechen** [comment]
I just released the addon version 0.102.0, which includes a fix for this.  Please let me know or reopen this issue if you run into any trouble with the new version.
Also just a reminder, to make Home Assistant see the new version right away go to "Supervisor" > "Add-on Store" > Three dots in the top right corner > "Reload"
