### ISSUE TITLE
How to open password protected backup files?

### ISSUE THREAD

**Issue by RestOp** [sabeechen/hassio-google-drive-backup#308]
Hello,

i have  password protected backup. I can open Full Snapshot 2020-11-02 03_49_44.tar this file with winrar. But i canon open any file that it contents
![image](https://user-images.githubusercontent.com/46259141/99144908-4e7aed80-266a-11eb-965f-dd517a181f90.png)

winrar shows me that the file is corrupted.
Maybe it is because of password protection? So how can i open them in this case?

Thanks!

**Comment by sabeechen** [comment]
The supervisor uses an unusual method of encrypting the snapshot contents that isn't supported by any decompressing utility I'm aware of.  This question has come up before, and to be honest I'd like to be able to do this as well.  Unfortunately I'm I don't know  a way to get inside a password protected snapshot without restoring it to a running Home Assistant instance.

**Comment by RestOp** [comment]
Try this https://community.home-assistant.io/t/get-files-from-password-protected-snapshot/245066/16?u=thisio
