### ISSUE TITLE
Exclude MOTIONEYE videos from gdrive backup

### ISSUE THREAD

**Issue by iz3man** [sabeechen/hassio-google-drive-backup#309]
Lately I got warnings that gdrive snapshot upload didn't work, and the reason is obvious:
I moved motioneye addon to the "main" RPi4 and this is generating Gb of data. The regular snapshot is "just" a few hundred Mb, but now it's 25Gb with videos included. 
I don't need them to be backuped.

Any way to exclude them?

**Comment by demimii** [comment]
Yes you can. You can select Partial Snapshots in the add-on settings. You can then exclude certain folders or addons from the backup.
I hope this helps you. @iz3man

**Comment by sabeechen** [comment]
Like @demimii pointed out you can exclude some specific folders (media, share, ssl, local addons) using partial snapshots.  If your videos are in one of those folders, then just exclude that.  The supervisor doesn't let the addon have any more specific granularity than those specific folders (eg you can't exclude only a subfolder).
