### ISSUE TITLE
Addon reporting Google Drive is full when plenty of space available

### ISSUE THREAD

**Issue by guniv** [sabeechen/hassio-google-drive-backup#310]
I woke up this morning to the addon throwing an error at me about there not being enough space on the Drive it backs up to. The Drive I use is a separate account I use for Home Assistant and has nothing else stored on it. The account has 1.6GB of 15GB used.

I attempted restarting the addon, deleting a single snapshot to see if even freeing a little space would work, and reauthorizing Google Drive. I still get the error. The log shows the error "Google Drive is out of space" followed by "I'll try again in an hour."

Hoping this isn't somehow an issue on my end and that you can investigate. Thanks for making such a great addon!

**Comment by sabeechen** [comment]
This usually occurs when something happens that causes your snapshot size to blow up, so first verify that the snapshot its trying to upload is small enough to fit in the space you have left in Google Drive.  You should see the size of the latest snapshot at the top of the list of snapshots in the web-UI.

If that isn't the problem, could I have you go to "Actions" -> "Report a Bug" in the web-UI and paste the details it gives you here?

**Comment by guniv** [comment]
You're totally right, I glanced over the size of the file and I'm realizing it included some media I recently transferred to the Pi. My bad! Thanks for the quick reply.
