### ISSUE TITLE
After migrated from raspberry 2 to a raspberry 4b I can not install the plugin.

### ISSUE THREAD

**Issue by patximlg** [sabeechen/hassio-google-drive-backup#311]
I had an old raspberry 2 running home assistant perfectly and after I restored a backup into a rasp 4b everything else worked fine apart this plugin. When I press the install button in the add-on store I get this message:

> Failed to install addon
> 404 Client Error for http+docker://localhost/v1.40/images/sabeechen/hassio-google-drive-backup-armv7:0.102.0/json: Not Found ("no such image: sabeechen/hassio-google-drive-backup-armv7:0.102.0: No such image: sabeechen/hassio-google-drive-backup-armv7:0.102.0") 

So I don't know what could be the problem.

**Comment by sabeechen** [comment]
I've had this happen to me a few times with my addon and others.   And as far as I can tell its some problem with the supervisor, restarting the supervisor (or the host machine) has always fixed it for me.

**Comment by patximlg** [comment]
Thanks for your answer. I have tried it and nothing... what a shame It used to work really nice in my old pi :(

**Comment by sabeechen** [comment]
Sorry this took a while to get back on, but if you're still looking to work through this could you try:
-  Uninstalling the addon
-  Removing the addon's repository from your addon store.
-  Restarting the host machine
-  Adding the the repository back and reinstalling the addon

I had another user who was able to work around thissame error by following those steps.  I'm pretty sure this is a bug in the supervisor on 64bit hassos for the pi4, but I'm not entirely sure because I can't reproduce the error. Could you give that a shot?

**Comment by sabeechen** [comment]
I had a similar problem with another user, and after trying everything listed above the only thing that worked for them was taking a full snapshot and restoring from it.  I'm guessing that something is gets messed up in the supervisor at installation time and it has trouble recovering from it, but being unable to reproduce this on any of my test machines I'm not sure exactly what.

**Comment by patximlg** [comment]
Hello back! I finally got it working. I have been trying to install the plugin after every home assistant update... and a few weeks ago suddenly started working :S 

Not sure what happened here, to be honest, but at least I have my drive backups running again :D

Thanks for the time you took for making this nice addon!

**Comment by sabeechen** [comment]
Glad you were able to get it working.  A few people have reported this and I'm pretty convinced now that all the remedies I've offered aren't helping.  It seems like something random fixes it.  If anyone runs into further evidence for what makes the installation stop working or start working, please reopen this bug and post it here.  I'll take a look.
