### ISSUE TITLE
philosophyofpen.com 404 ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by 50l3r** [sabeechen/hassio-google-drive-backup#313]
Hi guys,

I recieve ERR_CONNECTION_REFUSED on my navigator when i try to reauthorize:

![](https://i.gyazo.com/094dcaa95a08341569a6068f978f06d1.png)

**Comment by sabeechen** [comment]
Please update the addon, you're using a pretty old version.  The new version uses a much more reliable domain to do authentication (https://habackup.io)

**Comment by 50l3r** [comment]
Much thanks. Problem solved 👍
