### ISSUE TITLE
problem to sync after upgraded to 2020.12.7

### ISSUE THREAD

**Issue by pilot1981** [sabeechen/hassio-google-drive-backup#319]
Hi,
I notice in log I'm not able to sync to google. I have these error:

12-18 23:58:34 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
12-18 23:58:34 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
12-18 23:58:34 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1dtNuccdTRd9JCOCz4IAayShAYhfMyWZ5/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
12-18 23:58:34 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271dtNuccdTRd9JCOCz4IAayShAYhfMyWZ5%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
12-19 00:58:35 DEBUG [backup.model.syncer] Sync requested by Coordinator
12-19 00:58:35 INFO [backup.model.coordinator] Syncing Snapshots
12-19 00:58:35 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
12-19 00:58:35 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
12-19 00:58:35 DEBUG [backup.creds.driverequester] Ran into trouble reaching Google Drive's servers.  We'll use alternate DNS servers on the next attempt.
12-19 00:58:35 ERROR [backup.model.coordinator] Unable to connect to www.googleapis.com
12-19 00:58:35 INFO [backup.model.coordinator] I'll try again right now
12-19 00:58:36 DEBUG [backup.model.syncer] Sync requested by Coordinator
12-19 00:58:36 INFO [backup.model.coordinator] Syncing Snapshots
12-19 00:58:36 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
12-19 00:58:36 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
12-19 00:58:36 DEBUG [backup.creds.driverequester] Ran into trouble reaching Google Drive's servers.  We'll use alternate DNS servers on the next attempt.
12-19 00:58:36 ERROR [backup.model.coordinator] Unable to connect to www.googleapis.com
12-19 00:58:36 INFO [backup.model.coordinator] I'll try again in 10 seconds
12-19 00:58:44 INFO [backup.debugworker] Sending error report (see settings to disable)
12-19 00:58:46 DEBUG [backup.model.syncer] Sync requested by Coordinator
12-19 00:58:46 INFO [backup.model.coordinator] Syncing Snapshots
12-19 00:58:46 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
12-19 00:58:46 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
12-19 00:58:46 DEBUG [backup.creds.driverequester] Ran into trouble reaching Google Drive's servers.  We'll use alternate DNS servers on the next attempt.
12-19 00:58:46 ERROR [backup.model.coordinator] Unable to connect to www.googleapis.com
12-19 00:58:46 INFO [backup.model.coordinator] I'll try again in 20 seconds
12-19 00:59:06 DEBUG [backup.model.syncer] Sync requested by Coordinator
12-19 00:59:06 INFO [backup.model.coordinator] Syncing Snapshots
12-19 00:59:06 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
12-19 00:59:06 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
12-19 00:59:06 DEBUG [backup.creds.driverequester] Ran into trouble reaching Google Drive's servers.  We'll use alternate DNS servers on the next attempt.
12-19 00:59:06 ERROR [backup.model.coordinator] Unable to connect to www.googleapis.com
12-19 00:59:06 INFO [backup.model.coordinator] I'll try again in 40 seconds

I have this error from different days...

**Comment by sabeechen** [comment]
Does it never get through and successfully sync or does it always fail?

If you haven't tried already, could you restarting the host machine?  Sometimes after an upgrade, the environment HA creates for its addons doesn't get properly recreated.

**Comment by pilot1981** [comment]
solved, it was a problem of connectivity in my network due to incompatibility between AH docker of HASSIO and DNS caching of EERO AP WIFI
