### ISSUE TITLE
Feature Request - Backup profiles

### ISSUE THREAD

**Issue by poudenes** [sabeechen/hassio-google-drive-backup#320]
Hi All,

I love the add-on, really great !!!!
Would be nice to able to create backup-profiles:

Profile 1: Every Monday, only backup configuration
Profile 2: Every Day, backup only add-on a, b, c, 
Profile 3: Every month full backup of whole system

So you can create your own backup plan.

Idea is same as Carbon Copy for OSX, or Sync Backup applications in windows

**Comment by sabeechen** [comment]
Duplicate #145
Just de-duplicating this bug in an attempt to keep my requested features organized.  I also posted a workaround in #145 if you'd like to give it a shot.
