### ISSUE TITLE
I can't finish configuring the google drive add-on

### ISSUE THREAD

**Issue by Henry1959** [sabeechen/hassio-google-drive-backup#321]
I am installing the add-on to make backups in newspapers in Home Assistan, however when following the steps in the guide it does not allow me to configure, it tells me that the supervisor has rejected the request from the addon. Please visit the web-UI for Guidance, However the details button does nothing. Thank you in advance for your kind attention

**Comment by sabeechen** [comment]
- What is newspapers?
- After you start the addon and see the error message, go to "Supervisor" -> "System" -> "Logs" in the addon web-ui.  If the supervisor is doing something strange, there should be an error message there that gives a little more detail.

**Comment by sabeechen** [comment]
Also, double check the supervisor/HA doesn't need to be updated.

**Comment by sabeechen** [comment]
I'm closing this issue for now, but feel free to reopen it or ping me if you there there is anything else I can do to help.
