### ISSUE TITLE
I click authenticate, allow my google account then nothing happens?

### ISSUE THREAD

**Issue by prestonsmartuk** [sabeechen/hassio-google-drive-backup#323]
So I installed this onto HA via RPI4.  
Clicked Authenticate 
Clicked Allow Grant habackup.io permission for my Google Account
Then nothing happens??? 
The logs don't show any errors.  

Help please

**Comment by sabeechen** [comment]
After you click "allow" you should get taken to a page that gives you a string you copy back into the addon that completes the authorization.  What does the addon's web-ui say?

**Comment by prestonsmartuk** [comment]
Hi
Yes I should of been taken to that page, but it didn't.  Logs or Web-ui didn't produce any errors.
I managed to fix it by opening the web-ui URL in Incognito Chrome and it then authorised.  However, it did flag up the same error that's already been highlighted by others.  So I copied the string and pasted that into the appropriate field.  All works now.  
Thank you!

**Comment by sabeechen** [comment]
I'd guess then that a chrome extension you have installed was blocking something in the page, and that extension was disabled in incognito mode.  If you're able to figure out what it was I'd be interested to know.  Glad you were able to get it to work!
