### ISSUE TITLE
Issue - 2020-01-05

### ISSUE THREAD

**Issue by vawaver** [sabeechen/hassio-google-drive-backup#324]
Description:
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
Addon version: 0.103.0 Home Assistant Version: 2020.12.2 Supervisor Version: 2020.12.7 Supervisor Channel: stable Hassos Version: 5.9 Docker Version: 19.03.13 Architecture: amd64 Machine: qemux86-64 Date: 2021-01-05T04:48:09.464730+00:00 Timezone: Europe/Bratislava Failure Time: 2021-01-05T04:47:31.250024+00:00 Last Good Sync: 2021-01-05T04:47:31.230775+00:00

Exception:

 addon/backup/model/coordinator.py:156 (_sync)
 addon/backup/model/model.py:152 (sync)
 addon/backup/model/model.py:239 (_syncSnapshots)
 addon/backup/drive/drivesource.py:92 (get)
 addon/backup/drive/drivesource.py:199 (getFolderId)
 addon/backup/drive/folderfinder.py:51 (get)
 addon/backup/drive/folderfinder.py:79 (save)
FileNotFoundError: [Errno 2] No such file or directory: '/data/folder.dat'

Snapshots:

{
   "HomeAssistant": {
       "snapshots": 4,
       "retained": 0,
       "deletable": 4,
       "name": "HomeAssistant",
       "title": "Home Assistant",
       "latest": "2021-01-04T16:45:52Z",
       "max": 4,
       "enabled": true,
       "size": "126.6 MB",
       "free_space": "23.7 GB"
   },
   "GoogleDrive": {
       "snapshots": 4,
       "retained": 0,
       "deletable": 4,
       "name": "GoogleDrive",
       "title": "Google Drive",
       "latest": "2021-01-04T16:45:52Z",
       "max": 4,
       "enabled": true,
       "size": "126.6 MB"
   }
}
Config:
{}
Addon Logs:
01-05 03:46:26 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
01-05 03:46:26 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
01-05 03:46:26 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
01-05 03:46:27 INFO [backup.drive.folderfinder] Found Hass.io Snapshots
01-05 03:46:27 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271Xzu4pk6uIOu-HU-ettTsmVWKtwIydg34%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
01-05 03:46:27 ERROR [backup.model.coordinator] A backup folder already exists.  Please visit the add-on Web UI to select where to backup.
01-05 03:46:27 INFO [backup.model.coordinator] I'll try again in an hour
01-05 04:46:27 DEBUG [backup.model.syncer] Sync requested by Coordinator
01-05 04:46:27 INFO [backup.model.coordinator] Syncing Snapshots
01-05 04:46:27 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
01-05 04:46:27 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
01-05 04:46:27 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
01-05 04:46:28 INFO [backup.drive.folderfinder] Found Hass.io Snapshots
01-05 04:46:28 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271Xzu4pk6uIOu-HU-ettTsmVWKtwIydg34%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
01-05 04:46:28 ERROR [backup.model.coordinator] A backup folder already exists.  Please visit the add-on Web UI to select where to backup.
01-05 04:46:28 INFO [backup.model.coordinator] I'll try again in an hour
01-05 05:46:28 DEBUG [backup.model.syncer] Sync requested by Coordinator
01-05 05:46:28 INFO [backup.model.coordinator] Syncing Snapshots
01-05 05:46:28 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
01-05 05:46:28 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
01-05 05:46:28 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
01-05 05:46:29 INFO [backup.drive.folderfinder] Found Hass.io Snapshots
01-05 05:46:29 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271Xzu4pk6uIOu-HU-ettTsmVWKtwIydg34%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
01-05 05:46:29 ERROR [backup.model.coordinator] A backup folder already exists.  Please visit the add-on Web UI to select where to backup.
01-05 05:46:29 INFO [backup.model.coordinator] I'll try again in an hour
01-05 05:47:31 INFO [backup.model.coordinator] Syncing Snapshots
01-05 05:47:31 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
01-05 05:47:31 INFO [backup.drive.folderfinder] Saving snapshot folder: 1Xzu4pk6uIOu-HU-ettTsmVWKtwIydg34
01-05 05:47:31 ERROR [backup.model.coordinator] 
 addon/backup/model/coordinator.py:156 (_sync)
 addon/backup/model/model.py:152 (sync)
 addon/backup/model/model.py:239 (_syncSnapshots)
 addon/backup/drive/drivesource.py:92 (get)
 addon/backup/drive/drivesource.py:199 (getFolderId)
 addon/backup/drive/folderfinder.py:51 (get)
 addon/backup/drive/folderfinder.py:79 (save)
FileNotFoundError: [Errno 2] No such file or directory: '/data/folder.dat'

01-05 05:47:31 INFO [backup.model.coordinator] I'll try again in an hour
Supervisor Logs:
[32m21-01-05 02:06:09 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING[0m
[32m21-01-05 02:06:09 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m21-01-05 02:06:52 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
[32m21-01-05 02:12:49 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m21-01-05 02:42:51 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m21-01-05 02:46:26 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m21-01-05 02:54:07 INFO (MainThread) [supervisor.host.info] Updating local host information[0m
[32m21-01-05 02:54:08 INFO (MainThread) [supervisor.host.services] Updating service information[0m
[32m21-01-05 02:54:08 INFO (MainThread) [supervisor.host.network] Updating local network information[0m
[32m21-01-05 02:54:08 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information[0m
[32m21-01-05 02:54:08 INFO (MainThread) [supervisor.host] Host information reload completed[0m
[32m21-01-05 03:06:09 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING[0m
[32m21-01-05 03:06:09 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m21-01-05 03:07:36 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository[0m
[32m21-01-05 03:07:36 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository[0m
[32m21-01-05 03:07:36 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository[0m
[32m21-01-05 03:07:37 INFO (MainThread) [supervisor.store] Loading add-ons from store: 67 all - 0 new - 0 remove[0m
[32m21-01-05 03:07:37 INFO (MainThread) [supervisor.store] Loading add-ons from store: 67 all - 0 new - 0 remove[0m
[32m21-01-05 03:12:52 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m21-01-05 03:42:54 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m21-01-05 03:46:27 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m21-01-05 04:06:09 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING[0m
[32m21-01-05 04:06:09 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m21-01-05 04:06:52 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
[32m21-01-05 04:12:55 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m21-01-05 04:42:57 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m21-01-05 04:46:28 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m21-01-05 04:47:31 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m21-01-05 04:48:09 INFO (MainThread) [supervisor.api.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

Home Assistant Core Logs:
[33m2021-01-05 05:34:09 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.led_spalna is taking over 10 seconds[0m
[33m2021-01-05 05:34:39 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.led_spalna is taking over 10 seconds[0m
[33m2021-01-05 05:35:09 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.led_spalna is taking over 10 seconds[0m
[33m2021-01-05 05:35:39 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.led_spalna is taking over 10 seconds[0m
[33m2021-01-05 05:36:09 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.led_spalna is taking over 10 seconds[0m
[33m2021-01-05 05:36:39 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.led_spalna is taking over 10 seconds[0m
[33m2021-01-05 05:37:09 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.led_spalna is taking over 10 seconds[0m
[33m2021-01-05 05:37:39 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.led_spalna is taking over 10 seconds[0m
[33m2021-01-05 05:38:09 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.led_spalna is taking over 10 seconds[0m
[33m2021-01-05 05:38:39 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.led_spalna is taking over 10 seconds[0m
[33m2021-01-05 05:39:09 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.led_spalna is taking over 10 seconds[0m
[33m2021-01-05 05:39:39 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.led_spalna is taking over 10 seconds[0m
[33m2021-01-05 05:40:09 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.led_spalna is taking over 10 seconds[0m
[33m2021-01-05 05:40:39 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.led_spalna is taking over 10 seconds[0m
[33m2021-01-05 05:41:09 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.led_spalna is taking over 10 seconds[0m
[33m2021-01-05 05:41:39 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.led_spalna is taking over 10 seconds[0m
[33m2021-01-05 05:42:09 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.led_spalna is taking over 10 seconds[0m
[33m2021-01-05 05:42:39 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.led_spalna is taking over 10 seconds[0m
[33m2021-01-05 05:43:09 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.led_spalna is taking over 10 seconds[0m
[33m2021-01-05 05:43:39 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.led_spalna is taking over 10 seconds[0m
[33m2021-01-05 05:44:09 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.led_spalna is taking over 10 seconds[0m
[33m2021-01-05 05:44:39 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.led_spalna is taking over 10 seconds[0m
[33m2021-01-05 05:45:09 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.led_spalna is taking over 10 seconds[0m
[33m2021-01-05 05:45:39 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.led_spalna is taking over 10 seconds[0m
[33m2021-01-05 05:46:09 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.led_spalna is taking over 10 seconds[0m
[33m2021-01-05 05:46:39 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.led_spalna is taking over 10 seconds[0m
[33m2021-01-05 05:47:09 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.led_spalna is taking over 10 seconds[0m
[33m2021-01-05 05:47:39 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.led_spalna is taking over 10 seconds[0m
[33m2021-01-05 05:48:09 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.led_spalna is taking over 10 seconds[0m

**Comment by sabeechen** [comment]
I've been seeing problems like this a lot lately, where the addon has trouble writing to a file or folder that the supervisor is supposed to make available to it, "/data" in this case.  I suspect it is a problem that only comes up after supervisor upgrades, but I'm not certain as it seems to happen only rarely and randomly.  I haven't been able to reproduce it myself.  Did you upgrade the supervisor or HA recently?

Others have been able to resolve it by restarting the host machine, so I'd give that a shot.

**Comment by vawaver** [comment]
A restart of HA server did not help but I restarted my host machine and now it looks like it is ok.

**Comment by sabeechen** [comment]
Glad you got it working again.  If you ever see anything that might shed light on why it happens, please don't hesitate to tell me about it.  I've been unable to reproduce this on any of my test machines to figure out whats causing it, so all the information I have about it is from reports like this.
