### ISSUE TITLE
Changed supervisor container now IP changed

### ISSUE THREAD

**Issue by scorpinus** [sabeechen/hassio-google-drive-backup#325]
Hi, I went to add the TZ value to the ENV of the docker (did this through Portainer) and redeployed the container. Now it suddenly has a new IP adress in the HASSIO network.

Now Home Assistant and all the add-ons can't find the supervisor anymore. I can tell Home Assistant that the IP has changed (also in the ENV) but the google add-on for example keeps wanting to connect to the old IP. No matter what I do.

Anybody know what's going on with the new IP supervisor is getting, or how I can set this back to the old IP? If this happens everytime I change something in the supervisor container then this won't be very usefull.

Also how do I tell the google-addon to connect to the new IP? I have tryed deleting the add-on and installing it again but then it still want's to connect to the old IP. Every other change (like the /etc/hosts file) I try does not survive a restart or recreate.

**Comment by scorpinus** [comment]
Removed the add-on, the container and even the stored image. As soon as I install the Google add-on again and start it it wants to connect to the old supervisor IP.

I have no clue where it is getting that old IP from...

**Comment by sabeechen** [comment]
Unfortunately I can only guess.  My relationship with how docker works is mysterious at best, and the way the supervisor sets up its environment is additionally quite complicated.  I knwo for certain it does a lot custom DNS stuff that I presume is quite fragile.   If I were in your shoes I would reinstall fresh from a backup.  I'd take a full snapshot no (while things are broken)w and try restoring that first, then try using an older one.  Some easier things you might consider trying:
- Restore a partial snapshot and only restore the addon.
- Uninstall the addon, restart the host machine, then try installing it again.

You could also consider asking in the [#addons](https://discord.gg/b4ESB3xq) discord HA support channel.  But be warned!  I haven't seen them take kindly to problems with people mucking about with portainer, it seems to be a bit of a sore point and the devs would rather the portainer addon not exist.

**Comment by scorpinus** [comment]
Thanks for the reply sabeechen. I might just have to go and try to restore and see how it goes. Worst case I just rebuild everything.

**Comment by sabeechen** [comment]
I'm closing this issue for now, but feel free to reopen it or ping me if you there there is anything else I can do to help.
