### ISSUE TITLE
Addon cannot install / restore from snapshot after reinstall (aarch64)

### ISSUE THREAD

**Issue by bancswissunique** [sabeechen/hassio-google-drive-backup#326]
Hi

I had this addon running for about a year with success and went through some restores during that time (hassio snapshot). This time I reinstalled my rpi4 mod b with the v5.10 64-bit version of hass (official hassio image) and the addon restore worked however it cannot start.

The error shown is:

`404 Client Error for http+docker://localhost/v1.40/containers/create?name=addon_cebe7a76_hassio_google_drive_backup: Not Found ("No such image: sabeechen/hassio-google-drive-backup-aarch64:0.103.0")`

The supervisor log shows:

`21-01-11 16:26:40 ERROR (SyncWorker_5) [supervisor.docker] Image sabeechen/hassio-google-drive-backup-aarch64 not exists for addon_cebe7a76_hassio_google_drive_backup`

If I remove the addon and add it again using the addon store it wouldn't even install and complains about the missing container image:

`404 Client Error for http+docker://localhost/v1.40/images/sabeechen/hassio-google-drive-backup-aarch64:0.103.0/json: Not Found ("no such image: sabeechen/hassio-google-drive-backup-aarch64:0.103.0: No such image: sabeechen/hassio-google-drive-backup-aarch64:0.103.0")`

And again the same as shown in the supervisor log:

`21-01-11 16:35:59 ERROR (SyncWorker_0) [supervisor.docker.interface] Can't install sabeechen/hassio-google-drive-backup-aarch64:0.103.0 -> 404 Client Error for http+docker://localhost/v1.40/images/sabeechen/hassio-google-drive-backup-aarch64:0.103.0/json: Not Found ("no such image: sabeechen/hassio-google-drive-backup-aarch64:0.103.0: No such image: sabeechen/hassio-google-drive-backup-aarch64:0.103.0").`

Is it not compatible with the 64-bit OS version? And if so could a 64-bit version be made available? I have no issues with all other addons I am using so would be great if this would work as well.

P.S.: Restarting the supervisor or even the whole OS (host) doesn't fix anything.

**Comment by sabeechen** [comment]
Its compatible, I have a 64bit pi 4 that I test on every once in a while and it still works.  Thank you for providing the supervisor logs, it helps a lot.  I've seen this error on different platforms before, and I'm pretty certain its a bug in the supervisor but I haven't been able to narrow it down where it happens because I can't reliably reproduce it on my machines.  I had another user who got around it by:

- Uninstalling the addon
- Removing the addon's repository from your addon store.
- Restarting the host machine
- Adding the the repository back and reinstalling the addon

Uninstalling the addon and removing the repository before restarting (I'm assuming) is critical.  Could you give that a shot?

**Comment by bancswissunique** [comment]
OK good to know it is compatible since I really like it! :)

I tested what you suggested but unfortuneatly the same error is shown. Is there anything else I can share like additional logs etc.?

**Comment by bancswissunique** [comment]
I actually just noticed another error coming up on the cli while connected through HDMI:

`overlayfs: overlapping upperdir path`

I am currently not logged on on the shell so this error is going to stdout or whatever that is and everytime I click "install" on the addon this message is generated here.

**Comment by sabeechen** [comment]
Strange, I see someone else running into that message [here](https://community.home-assistant.io/t/please-help-catastrophic-failure-virtualbox-vm-not-booting-how-to-restore-snapshot/206085), but their system seems to have failed much more catastrophically than yours and the discussion doesn't really seem to have a solution either.

Could you tell me exactly what hardware the snapshot was created and restored on?  I have an assortment of raspberry pi's and I might be able to reproduce this error if I can follow exactly the steps you took.

Also if you haven't already, make sure you're running the latest supervisor version (eg that you don't need to update).

**Comment by bancswissunique** [comment]
The snapshot was created on a rpi4 model B with 2GB memory and a 32GB sd card. There everything was working with the 32bit hass image. And now the same hardware is running with the 64bit variant (aarch64) of the same hassio version.

I am running ten other addons without any issues (at least I don't notice anything unusual). The mentioned error only appears when I try to install this addon. 

Everything is running the latest stable/peoduction versions.

**Comment by sabeechen** [comment]
I took a crack at reproducing this on a rpi4 8GB (its what I have on hand) but unfonrtunately I wasn't able to make this error come up.  I tried:

- Install 32-bit Home Assistant (v5.10)
- Install Home Assistant Google Drive Backup
- Install a bunch of other addons (choosen randomly, 5 total)
- Make sure all the addons install and start without errors.
- Take a snapshot, save it
- Re-image the pi4 with 64-bit Home Assistant (also v5.10)
- Restore the saved snapshot during the setup process with the "restore everything" option.

So I'm kind of stuck on debugging this issue further.  If you're somewhat familiar with docker and want to get your hands dirty, you could try installing the [portainer addon](https://github.com/hassio-addons/addon-portainer) and take a crack at debugging this yourself but be warned that it's _really easy_ to accidentally break your install by messing around with the docker environment in portainer.  Its definitely something in the supervisor's docker environment thats messed up.  The first thing you'd want to try is to "pull" the image sabeechen/hassio-google-drive-backup-aarch64:0.103.0 manually and see if you can install after that.

If you don't feel comfortable doing that I completely understand.  I'll either have to figure out a way to reproduce this or wait until more evidence comes along that points the way toward a solution.

**Comment by bancswissunique** [comment]
I did now create a new snapshot (without the addon installed). Reimaged the sd card with the same hassio image and after restoring the snapshot I was successfully able to install the addon without errors and can confirm it's working again. I guess this can be closed and no furhter investigation is needed. thanks for the great work!
