### ISSUE TITLE
cannot add not compliant

### ISSUE THREAD

**Issue by pongdevelop** [sabeechen/hassio-google-drive-backup#327]
Repostitory structure for v0.98.1 is not compliant

**Comment by sabeechen** [comment]
It sounds like you might be trying to install this through HACS, this is not a HACS plugin.  If so, please follow the [installation instructions](https://github.com/sabeechen/hassio-google-drive-backup#installation) and install it through the Home Assistant Addon store.

If I misunderstand, can you tell me where you're seeing this error?

**Comment by pongdevelop** [comment]
![image](https://user-images.githubusercontent.com/20515485/104402008-ecfece80-5587-11eb-9116-e6083efa3e47.png)

**Comment by sabeechen** [comment]
That is a screenshot of HACS (Home Assistant Community Store).  You can't install the addon through HACS.  It's a Home Assistant addon, not a HACS plugin.  You start by going to "Supervisor" > "Addon Store" in the home Assistant web UI, like I say in the [installation instruction](https://github.com/sabeechen/hassio-google-drive-backup#installation).
