### ISSUE TITLE
Cannot configure the folder in GDrive

### ISSUE THREAD

**Issue by pb1051** [sabeechen/hassio-google-drive-backup#334]
When I try to change the folder in which the backups are stored, the authorization fails after two pop-ups and gives a 400 error.

I tried the "verbose: true" config, but nothing about any errors showed in the log.

**Comment by sabeechen** [comment]
Do you use a popup blocker or other privacy plugins?  The folder chooser has to do some cross-domain stuff with Google that a lot of privacy-oriented plugins and browsers flag as nefarious.

Alternatively, you can just copy-paste the Drive folder ID into the addon's settings.  You can see the Id if you navigate to the folder in Google Drive, I have an example highlighted in red in the image below.

<img width="1045" alt="Fodler ID" src="https://user-images.githubusercontent.com/21026774/105394684-20220d00-5bdb-11eb-8e44-03494626678d.png">

**Comment by pb1051** [comment]
Taking the last part of the URL helped! thank you!
_________________________________

**Comment by sabeechen** [comment]
Glad I could help.
