### ISSUE TITLE
A snapshot is already in progress

### ISSUE THREAD

**Issue by mimuncito** [sabeechen/hassio-google-drive-backup#335]
I'm getting this:

Full Snapshot 2021-01-24 09:08:25 Pending   help    Size: pending

Error details

  addon/backup/ui/uiserver.py:637 (error_middleware)
  addon/backup/ui/uiserver.py:228 (snapshot)
  addon/backup/model/coordinator.py:216 (startSnapshot)
  addon/backup/model/coordinator.py:292 (_withSoftLock)
  addon/backup/model/coordinator.py:221 (_startSnapshot)
  addon/backup/ha/hasource.py:188 (create)
backup.exceptions.exceptions.SnapshotInProgress

Do you have any idea how to overcome this ?

**Comment by sabeechen** [comment]
Do you ...  have a snapshot in progress?  If your instance has a lot of data they can take hours to make.  That being said, you shouldn't be seeing the message as an error.

Can you get a debug report by going to "Actions" > "Report a Bug" in the addon web-ui?  You can just copy-paste what it spits out in a reply (its formatted markdown).

**Comment by mimuncito** [comment]
Description:
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
Addon version: 0.103.0 Home Assistant Version: 2021.1.4 Supervisor Version: 2021.01.5 Supervisor Channel: stable Hassos Version: 5.10 Docker Version: 19.03.13 Architecture: amd64 Machine: qemux86-64 Date: 2021-01-24T08:53:45.706922+00:00 Timezone: Europe/Bucharest Failure Time: Never Last Good Sync: 2021-01-24T08:23:20.187474+00:00

Exception:
No error could be identified automatically.
Snapshots:

{
   "HomeAssistant": {
       "snapshots": 1,
       "retained": 0,
       "deletable": 1,
       "name": "HomeAssistant",
       "title": "Home Assistant",
       "latest": "2021-01-24T07:08:25Z",
       "max": 10,
       "enabled": true,
       "size": "0.0 B",
       "free_space": "7.3 GB"
   },
   "GoogleDrive": {
       "snapshots": 0,
       "retained": 0,
       "deletable": 0,
       "name": "GoogleDrive",
       "title": "Google Drive",
       "latest": null,
       "max": 10,
       "enabled": true,
       "size": "0.0 B"
   }
}
Config:
{
   "Setting.MAX_SNAPSHOTS_IN_HASSIO": 10,
   "Setting.MAX_SNAPSHOTS_IN_GOOGLE_DRIVE": 10,
   "Setting.DAYS_BETWEEN_SNAPSHOTS": 0.0,
   "Setting.SPECIFY_SNAPSHOT_FOLDER": true,
   "Setting.WARN_FOR_LOW_SPACE": false,
   "Setting.GENERATIONAL_WEEKS": 1,
   "Setting.SEND_ERROR_REPORTS": true
}
Addon Logs:
01-24 09:19:33 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/info
01-24 09:19:33 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/core/info
01-24 09:19:33 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/supervisor/info
01-24 09:20:28 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/options
01-24 09:20:28 INFO [backup.drive.folderfinder] Saving snapshot folder: 1TiBlICfnZriY3auFV9Ah3WBBb9rdEq7Y
01-24 09:20:28 INFO [backup.model.coordinator] Syncing Snapshots
01-24 09:20:28 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
01-24 09:20:28 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271TiBlICfnZriY3auFV9Ah3WBBb9rdEq7Y%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
01-24 09:23:19 WARNING [backup.ha.hasource] A snapshot was already in progress
01-24 09:23:19 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/a0d7b954_plex/info
01-24 09:23:19 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
01-24 09:23:19 INFO [backup.model.coordinator] Syncing Snapshots
01-24 09:23:19 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
01-24 09:23:19 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1TiBlICfnZriY3auFV9Ah3WBBb9rdEq7Y/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
01-24 09:23:19 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271TiBlICfnZriY3auFV9Ah3WBBb9rdEq7Y%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
01-24 10:23:20 DEBUG [backup.model.syncer] Sync requested by Coordinator
01-24 10:23:20 INFO [backup.model.coordinator] Syncing Snapshots
01-24 10:23:20 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
01-24 10:23:20 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
01-24 10:23:20 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1TiBlICfnZriY3auFV9Ah3WBBb9rdEq7Y/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
01-24 10:23:20 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271TiBlICfnZriY3auFV9Ah3WBBb9rdEq7Y%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
01-24 10:49:30 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/info
01-24 10:49:30 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/info
01-24 10:49:30 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/core/info
01-24 10:49:30 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/supervisor/info
01-24 10:49:30 INFO [backup.ha.hasource] A snapshot was already in progress
01-24 10:49:36 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/info
01-24 10:49:36 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/info
01-24 10:49:36 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/core/info
01-24 10:49:36 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/supervisor/info
Supervisor Logs:
    next(self.gen)
 File "/usr/local/lib/python3.8/site-packages/atomicwrites/__init__.py", line 168, in _open
   self.sync(f)
OSError: [Errno 28] No space left on device
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
 File "/usr/src/supervisor/supervisor/snapshots/__init__.py", line 145, in do_snapshot_full
   await snapshot.store_folders()
 File "/usr/src/supervisor/supervisor/snapshots/snapshot.py", line 303, in __aexit__
   write_json_file(Path(self._tmp.name, "snapshot.json"), self._data)
 File "/usr/src/supervisor/supervisor/utils/json.py", line 45, in write_json_file
   raise JsonFileError() from err
supervisor.exceptions.JsonFileError[0m
[32m21-01-24 07:23:19 INFO (MainThread) [supervisor.api.security] /addons/a0d7b954_plex/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-01-24 07:23:19 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m21-01-24 07:38:28 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m21-01-24 08:02:42 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING[0m
[32m21-01-24 08:02:42 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m21-01-24 08:08:28 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m21-01-24 08:08:44 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
[32m21-01-24 08:23:20 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m21-01-24 08:38:38 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m21-01-24 08:49:30 INFO (MainThread) [supervisor.api.security] /core/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-01-24 08:49:30 INFO (MainThread) [supervisor.api.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-01-24 08:49:36 INFO (MainThread) [supervisor.api.security] /core/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-01-24 08:49:36 INFO (MainThread) [supervisor.api.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-01-24 08:51:04 INFO (MainThread) [supervisor.api.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m
[32m21-01-24 08:51:04 INFO (MainThread) [supervisor.api.security] /core/logs access from cebe7a76_hassio_google_drive_backup[0m
[32m21-01-24 08:53:45 INFO (MainThread) [supervisor.api.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

Home Assistant Core Logs:
[33m2021-01-24 10:52:54 WARNING (MainThread) [hass_nabucasa.cloud_api] Fetched https://remote-sni-api.nabucasa.com/snitun_token (409)[0m
[31m2021-01-24 10:52:54 ERROR (MainThread) [hass_nabucasa.remote] Can't refresh the snitun token[0m
[33m2021-01-24 10:53:02 WARNING (MainThread) [hass_nabucasa.cloud_api] Fetched https://remote-sni-api.nabucasa.com/snitun_token (409)[0m
[31m2021-01-24 10:53:02 ERROR (MainThread) [hass_nabucasa.remote] Can't refresh the snitun token[0m
[33m2021-01-24 10:53:12 WARNING (MainThread) [hass_nabucasa.cloud_api] Fetched https://remote-sni-api.nabucasa.com/snitun_token (409)[0m
[31m2021-01-24 10:53:12 ERROR (MainThread) [hass_nabucasa.remote] Can't refresh the snitun token[0m
[33m2021-01-24 10:53:19 WARNING (MainThread) [hass_nabucasa.cloud_api] Fetched https://remote-sni-api.nabucasa.com/snitun_token (409)[0m
[31m2021-01-24 10:53:19 ERROR (MainThread) [hass_nabucasa.remote] Can't refresh the snitun token[0m
[31m2021-01-24 10:53:21 ERROR (Thread-15) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-16, initial daemon)>>: on_message() missing 1 required positional argument: 'message'[0m
[31m2021-01-24 10:53:22 ERROR (MainThread) [custom_components.kodi_recently_added.entities] Error updating sensor, is kodi running?[0m
Traceback (most recent call last):
 File "/config/custom_components/kodi_recently_added/entities.py", line 44, in async_update
   result = await self.kodi.call_method(
 File "/usr/local/lib/python3.8/site-packages/pykodi/kodi.py", line 291, in call_method
   return await getattr(self._server, method)(**kwargs)
 File "/usr/local/lib/python3.8/site-packages/jsonrpc_websocket/jsonrpc.py", line 42, in send_message
   raise TransportError('Client is not connected.', message)
jsonrpc_base.jsonrpc.TransportError: Error calling method 'VideoLibrary.GetRecentlyAddedEpisodes': Client is not connected.[0m
[31m2021-01-24 10:53:22 ERROR (MainThread) [custom_components.kodi_recently_added.entities] Error updating sensor, is kodi running?[0m
Traceback (most recent call last):
 File "/config/custom_components/kodi_recently_added/entities.py", line 44, in async_update
   result = await self.kodi.call_method(
 File "/usr/local/lib/python3.8/site-packages/pykodi/kodi.py", line 291, in call_method
   return await getattr(self._server, method)(**kwargs)
 File "/usr/local/lib/python3.8/site-packages/jsonrpc_websocket/jsonrpc.py", line 42, in send_message
   raise TransportError('Client is not connected.', message)
jsonrpc_base.jsonrpc.TransportError: Error calling method 'VideoLibrary.GetRecentlyAddedMovies': Client is not connected.[0m
[33m2021-01-24 10:53:34 WARNING (MainThread) [hass_nabucasa.cloud_api] Fetched https://remote-sni-api.nabucasa.com/snitun_token (409)[0m
[31m2021-01-24 10:53:34 ERROR (MainThread) [hass_nabucasa.remote] Can't refresh the snitun token[0m

**Comment by mimuncito** [comment]
I've played a little bit with the settings and I was able to get the first Snapshot, so everything looks good for the time being.

**Comment by sabeechen** [comment]
Based on the logs from your supervisor, it looks like your VM might be out of disk space:
```
OSError: [Errno 28] No space left on device
````
That can cause tons of errors to start popping up everywhere in a lot of unpredictable unpredictable ways.

**Comment by sabeechen** [comment]
I'm closing this issue for now, but feel free to reopen it or ping me if you there there is anything else I can do to help.
