### ISSUE TITLE
Don't start backup

### ISSUE THREAD

**Issue by michele2308** [sabeechen/hassio-google-drive-backup#337]
hi,
 I install add-on, and I configured this way:

`fromPattern: /backup/*.tar
backupDirID: Some_Google_Drive_Unique_Opaque_Folder_ID
purge:
  enabled: false
  preserve: 3
purge_google:
  enabled: false
  preserve: 12
debug: false
`

I have done the authentication and authorization, but in Log there's this error:

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
GB_DEBUG = false
GB_VERSION = 1.7.7
[2021-01-27 09:34:58 +0100] [200] [INFO] Starting gunicorn 19.9.0
[2021-01-27 09:34:58 +0100] [200] [INFO] Listening at: http://0.0.0.0:8000 (200)
[2021-01-27 09:34:58 +0100] [200] [INFO] Using worker: gevent
[2021-01-27 09:34:58 +0100] [202] [INFO] Booting worker with pid: 202
INFO:root:No local_settings to import
INFO:oauth2client.client:Refreshing access_token
INFO:oauth2client.transport:Attempting refresh to obtain initial access_token
INFO:oauth2client.client:Refreshing access_token
WARNING:googleapiclient._helpers:build() takes at most 2 positional arguments (3 given)
ERROR:root:Traceback (most recent call last):
  File "/googlebackup/gb/views.py", line 77, in doBackup
    backupResult = backupFiles(fromPattern, backupDirID, request.build_absolute_uri('/'))
  File "/googlebackup/gbcommon.py", line 255, in backupFiles
    if alreadyBackedUp(file, backupDirID, drive_service):
  File "/googlebackup/gbcommon.py", line 106, in alreadyBackedUp
    fields="files(id, name)").execute()
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 907, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/drive/v3/files?q=name%3D%27f0c75122.tar%27+and+%27Hassio%27+in+parents+and+trashed+%3D+false&spaces=drive&fields=files%28id%2C+name%29&alt=json returned "File not found: .">
INFO:root:googlebackup result: {'errorMessage': '<HttpError 404 when requesting https://www.googleapis.com/drive/v3/files?q=name%3D%27f0c75122.tar%27+and+%27Hassio%27+in+parents+and+trashed+%3D+false&spaces=drive&fields=files%28id%2C+name%29&alt=json returned "File not found: .">'}
ERROR:django.request:Internal Server Error: /gbdoBackup`

why?

**Comment by sabeechen** [comment]
I think you may be using this [other google drive backup addon](https://github.com/samccauley/addon-hassiogooglebackup/), since this one isn't configured using those options.  You'll want to post your issue there.

That being said.  Consider switching to [the one you just stumbled into](https://github.com/sabeechen/hassio-google-drive-backup).  Its super!
