### ISSUE TITLE
Secret for password?

### ISSUE THREAD

**Issue by fredrikbaberg** [sabeechen/hassio-google-drive-backup#34]
Would it be possible to specify the password in secrets.yaml and use `!secret <name of secret>` instead of plain text in the config?

Perhaps nothing is gained by that, but I would like to keep credentials in one place if possible.

Also, would it be possible to exclude a file from backup, such as said `secrets.yaml`?

**Comment by sabeechen** [comment]
Hass.io is the one who actually does the work of creating the snapshot, the add-on only has the ability to tell it which folders and add-ons should be included.  You might be able to put your secrets.yaml in either /share or /ssl and then exclude that folder by using partial snapshots, though I've never tried importing yaml form outside the config folder.

AFAICT add-ons don't have a clean way to read configuration files (eg secrets.yaml), but I can see if there is a way to do it without having to write a parser engine.  I'm trying to keep the add-on as simple as possible.

**Comment by fredrikbaberg** [comment]
Thank you. Keeping the add-on simple is good.
There are some add-ons that seem to support the use of secrets in the config, but perhaps that is more of a workaround.

**Comment by sabeechen** [comment]
Can you point me toward one? I might be able to copy what they did.

**Comment by fredrikbaberg** [comment]
Some I found (but haven't tested):
- [FTP](https://github.com/hassio-addons/addon-ftp)
- [ZeroTier One](https://github.com/hassio-addons/addon-zerotier)
- [NodeRed](https://github.com/hassio-addons/addon-node-red)

**Comment by sabeechen** [comment]
Seems straightforward, I'll add it to the next release.

**Comment by sabeechen** [comment]
I've added this to the latest release, v0.96
