### ISSUE TITLE
Trouble updating Home assistant sensors

### ISSUE THREAD

**Issue by GoState** [sabeechen/hassio-google-drive-backup#349]
The Snapshots are stale sensor is not getting updated.  Everything is syncing as I've configured it so that isn't an issue but if there is an issue I can't rely on this sensor to tell me or send a notification.
From the logs: 

02-12 12:51:56 ERROR [backup.ha.haupdater] Trouble updating Home Assistant sensors.
02-12 12:51:56 ERROR [backup.ha.haupdater]    
  addon/backup/ha/haupdater.py:53 (update)   
  addon/backup/ha/harequests.py:256 (updateSnapshotStaleSensor)   
  addon/backup/ha/harequests.py:215 (_postHaData)   
  /site-packages/aiohttp/client.py:1117 (__aenter__)   
  addon/backup/tracing_session.py:20 (_request)   
  /site-packages/aiohttp/client.py:520 (_request)   
  [4 hidden frames]   
  /site-packages/aiohttp/connector.py:975 (_wrap_create_connection)   
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host hassio:80 ssl:default [Connect call failed ('172.30.32.2', 80)]   

02-12 13:33:55 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/info
02-12 13:33:55 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/info
02-12 13:33:55 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/core/info
02-12 13:33:55 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/supervisor/info

**Comment by sabeechen** [comment]
Sorry this took me so long to get back to you on, I had to step away from the project for a while for personal stuff.
Does this only happen when you restart the supervisor/HA, or is it getting printed out constantly?  This error usually indicates that HA isn't running, which you can expect to happen ever once in a while when the machine is booting up or HA is getting restarted.

If its constant, could you:

- Restart the addon
- Wait for the error to come up again in the logs
- In the addon web-ui go to "Actions" > "Report a bug" and copy the debug info here.

**Comment by sabeechen** [comment]
I'm closing this bug for now, but please feel free to reopen it if you think there is more I can help with.
