### ISSUE TITLE
User personal API key's

### ISSUE THREAD

**Issue by TychoWerner** [sabeechen/hassio-google-drive-backup#35]
Hi,

I saw in your docs:

> Google stores a history of information about the number of requests, number of errors, and latency of requests made by this Add-on and makes a graph of that visible to me. This is needed because Google only gives me a certain quota for requests shared between all users of the add-on, so I need to be aware if someone is abusing 

Maybe it's possible for you tell us how we can put in our own API key's or credentials so we run it on our own account. That way we release strain on your requests; plus people who like to not be depended on other people's cloud (or in this case your keys)

Hope you will consider!
Thanks for this awesome plugin.

**Comment by sabeechen** [comment]
Theres already a link to using your own client_secret/client_id (with instructions too) underneath the "Authenticate with Drive" button on the first page of the add-on.  You can get back to it by going to the top-right menu "ACTIONS" -> "Reauthenticate Google Drive" if you'd like to switch over to that method.

**Comment by sabeechen** [comment]
I should probably add a FAQ item for this specifically

**Comment by sabeechen** [comment]
Added the [FAQ item](https://github.com/sabeechen/hassio-google-drive-backup/blob/master/README.md#can-i-use-my-own-google-api-information-to-authenticate-instead-of-yours).  Feel free to re-open if this doesn't answer your question or things are still unclear.
