### ISSUE TITLE
Feature Request: Google Drive Retention policy (delete after x days or before next snapshot)

### ISSUE THREAD

**Issue by jjanderson** [sabeechen/hassio-google-drive-backup#356]
HI,

Firstly, I have to say I love this addon. It has saved my bacon on more than one occasion.

I was wondering if it were possible to have an option to "keep on google drive for x hours, days, etc. A retention policy of sorts 
 as it were.

My backups are big, and I like it that way. I have a sync option that pulls from google drive every time something is loaded up and dumps the backup locally on my Synology Nas.

The issue is that once a snapshot is complete, the next time it tries to run, it fails as there is not enough space on google drive. By this time, I already have the snapshot safe and sound on my infrastructure. I then need to go in and manually delete the snapshot on google drive before the snapshot can upload again.

Is this something that you think the addon can cater for?

Thanks again for the great addon!

**Comment by sabeechen** [comment]
I appreciate you taking the time to write a good issue report for this, but the reality is that this is a pretty niche feature and I'm forced to prioritize what I implement.  Lately I've struggled just keep parity with the changes they're making from the HA/Supervisor side of things and the user-base just keeps growing.  I hate saying no, but I have to say no sometimes :)

As an alternative workaround, you might be able to implement this using [a custom Google Apps Script](https://www.cirriustech.co.uk/blog/how-to-auto-tidy-files-in-google-drive).   wouldn't be as slick as having the addon do it for you, but I think it could get the job done if you're willign to write the script.
