### ISSUE TITLE
Repository compatibility problem in Home Assisstant 2021.03

### ISSUE THREAD

**Issue by micium** [sabeechen/hassio-google-drive-backup#357]
I installed a new instance of Home Assistant core-2021.3.2 and when I add hassio-google-drive-backup in hacs custom repository I got the msg "Repostitory structure for v0.98.1 is not compliant".

Can you please help me to resolve my problem?

Many thanks
Massimo

**Comment by sabeechen** [comment]
You're trying to install this through HACS.  This is a Home Assistant Addon, not a HACS plugin.  Please follow the [instructions](https://github.com/sabeechen/hassio-google-drive-backup#installation) and install it through the Add-on store.  You should start by going to "Supervisor" > "Add-on Store" in the home Assistant web-ui if you've never done it before.
