### ISSUE TITLE
Cannot add repository to HACS

### ISSUE THREAD

**Issue by paulearley** [sabeechen/hassio-google-drive-backup#359]
When I try to add the Google Drive Backup repository to HACS it returns the following error:

"Repostitory structure for v0.98.1 is not compliant."

Can you fix the repository structure if this is indeed the issue?

**Comment by sabeechen** [comment]
This is a Home Assistant addon, not a HACS plugin.  Yo install it you will need to go to "Supervisor" > "Add-on Store" I n the Home Assistant UI. More details in the installation instructions. https://github.com/sabeechen/hassio-google-drive-backup#installation

Could you help me understand how you came to think this is a HACS plugin and tried to install it that way?  I've been getting bugs exactly like this more often lately and I'd like to understand how the misunderstanding is starting.

**Comment by paulearley** [comment]
So sorry! I am not sure how I became confused. I pride myself on being a relatively sophisticated user and for some reason, I forgot where I loaded this from.I remembered adding the repository when installed and wound up thinking HACS vs. HA AddOn. The fact that both have a p[lace where you "add a repository" and the process for adding a repository is the same may be where the confusion comes in.
Hope this helps.Paul
    On Monday, March 8, 2021, 09:43:34 AM EST, Stephen Beechen <notifications@github.com> wrote:  
 
 


This is a Home Assistant addon, not a HACS plugin. Yo install it you will need to go to "Supervisor" > "Add-on Store" I n the Home Assistant UI. More details in the installation instructions. https://github.com/sabeechen/hassio-google-drive-backup#installation

Could you help me understand how you came to think this is a HACS plugin and tried to install it that way? I've been getting bugs exactly like this more often lately and I'd like to understand how the misunderstanding is starting.

**Comment by sabeechen** [comment]
I'll probably find some place in my instructions where I mention explicitly this isn't a HACS plugin if it keeps coming up.  Thanks for letting me know and I hope you enjoy the addon!
