### ISSUE TITLE
Snapshot creation stuck in loop

### ISSUE THREAD

**Issue by jc9677** [sabeechen/hassio-google-drive-backup#363]
I noticed that snapshots were created repeatedly for an hour, starting right when the DST clock change kicked in... when 2am became 1am.
In my case, I found about 20 snapshots were created during that 60 minute period. My scheduled snapshots happen to be set for 2am.

**Comment by sabeechen** [comment]
Yeah, that sounds like something my addon would do :)

Could I have you go to "Actions" > "Report a bug" and post the contents of what it gives you here?  that'll save a lot fo time going back and forth with me asking about how you have things set up.

Additionally, could you describe the time period over which the snapshots were taken?  Eg did they all have the same time, duplicates times, all spaced 5 minutes apart, etc?

**Comment by sabeechen** [comment]
I'll need more info to work on this bug.  I just released v0.104.1, if you continue to see this problem after updating to the new version please feel free to reopen this and I'll help where I can.
