### ISSUE TITLE
An unexpected error occurred: HTTPSConnectionPool(host='www.googleapis.com', port=443): Max retries exceeded with url: /upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ABg5-Uy-EfjH-9Iw7hR9JLacgYTAqp1CRNxRp_SCVkZ_orlFMtM4uxo-AbuGC1WzDvrY2w69ggUN2Y2INJ0pm191jjNp74Z_rw (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2607)')))

### ISSUE THREAD

**Issue by macnug** [sabeechen/hassio-google-drive-backup#368]
Please add some information about your configuration and the problem you ran into here. 
Hi, i am usind this fantastic addon since 2019 and warked flawlessly till some days ago. Now it can't sync with google drive and i don't know why. 
Can you help me throubleshoot this?
Thanks
 

Traceback (most recent call last):
  File "/app/backup/coordinator.py", line 109, in _sync
    self._buildModel().sync(self._time.now())
  File "/app/backup/model.py", line 155, in sync
    upload.addSource(self.dest.save(upload, self.source.read(upload)))
  File "/app/backup/drivesource.py", line 139, in save
    for progress in self.drivebackend.create(bytes, file_metadata, MIME_TYPE):
  File "/app/backup/driverequests.py", line 251, in create
    partial = self.retryRequest("PUT", location, headers=headers, data=data, patch_url=False)
  File "/app/backup/driverequests.py", line 325, in retryRequest
    raise e
  File "/app/backup/driverequests.py", line 312, in retryRequest
    response = self._request_client.request(method, url, headers=send_headers, json=json, timeout=self.config.get(Setting.GOOGLE_DRIVE_TIMEOUT_SECONDS), data=data, stream=stream)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.googleapis.com', port=443): Max retries exceeded with url: /upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ABg5-Uy-EfjH-9Iw7hR9JLacgYTAqp1CRNxRp_SCVkZ_orlFMtM4uxo-AbuGC1WzDvrY2w69ggUN2Y2INJ0pm191jjNp74Z_rw (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2607)')))

An unexpected error occurred: HTTPSConnectionPool(host='www.googleapis.com', port=443): Max retries exceeded with url: /upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ABg5-Uy-EfjH-9Iw7hR9JLacgYTAqp1CRNxRp_SCVkZ_orlFMtM4uxo-AbuGC1WzDvrY2w69ggUN2Y2INJ0pm191jjNp74Z_rw (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2607)')))

**Comment by sabeechen** [comment]
Sorry this took me so long to get back to you about, I've been slammed lately.

It looks like you're using a _very_ old version of the addon.  Could I have you install the latest version (v0.104.1) and then if you still see the error could you go to "Actions" > "Report a bug report" and paste what it says here?

**Comment by macnug** [comment]
Hi,
I updated the addon and I don’t have anymore the problem.
I deselected the media folder in order to backup just the config and the
important things.

Thank you!
Br
Marco

Il giorno gio 22 apr 2021 alle 04:03 Stephen Beechen <
***@***.***> ha scritto:

**Comment by sabeechen** [comment]
Great!
