### ISSUE TITLE
Updates to local authentication documentation needed

### ISSUE THREAD

**Issue by glyph-se** [sabeechen/hassio-google-drive-backup#369]
I went through the https://github.com/sabeechen/hassio-google-drive-backup/blob/master/LOCAL_AUTH.md documentation and I found some things that are outdated.

I made my way through it without any problem, but as advised above I will file an issue with the things that are outdated to help out.

1. The screenshots show only 3 menus to the left: Dashboard, Library and Credentials. I have 3 more: OAuth consent screen, Domain verification, Page usage agreement. See below.
2. When creating the OAuth consent screen you need to choose between internal and external app. Also, this page is now split up into multiple sub steps. Unfortunately I didn't take any screenshots of this.
3. When creating the client credentials. The application type "Other" is no longer available. I choose "Desktop app" instead which appears to work in a similar way.
![image](https://user-images.githubusercontent.com/1484881/112180323-bedae200-8bfb-11eb-8df9-88bfd4a9f340.png)
4. The e-mail address from the account used will need to be added to the list of test users on the Oauth Consent Screen. This is the case even though I am creating the project on the same account that I am later using in the addon:
![image](https://user-images.githubusercontent.com/1484881/112182157-54c33c80-8bfd-11eb-8bb3-bde37cbb7cdd.png)

**Comment by glyph-se** [comment]
8 days later and some sync problems I went to google and found issue #347

Seems like you already knew about this. Anyway, hope my above text can help out a bit :)

https://github.com/sabeechen/hassio-google-drive-backup/issues/347#issuecomment-782729185

**Comment by sabeechen** [comment]
I've published the updated documentation along with v0.104.1 of the addon, anybody let me know if they run into more trouble.
