### ISSUE TITLE
Differentiate between types of backup

### ISSUE THREAD

**Issue by tmjo** [sabeechen/hassio-google-drive-backup#372]
Hi! Thanks for your great work on this!

A feature request from my side. Now that HA has started to ask us if we want to do snapshots every time a add-on is updated, it may be a good idea to be able to differentiate between such single snapshots and the automated full snapshots. And then add an option not to push such single snapshots to Google Drive.

Background: I think taking an add-on snapshot before updating is a wise thing to do in case something breaks, but it may not be necessary to back them up to Google Drive. The main reason for not doing this would be, in my case, that I have a limit of XX snapshots stored in Drive. Updating several add-ons would then very quickly remove the full snapshots which I am interested in keeping.

For sure I could just increase the limit, so it's not a biggie. But just a thought. Thx.

**Comment by synth3tk** [comment]
I think that's going to be covered by #353.

**Comment by tmjo** [comment]
Ah, sorry, didn't see that one. Closing this issue. Thanks!
