### ISSUE TITLE
Guide is out of date

### ISSUE THREAD

**Issue by agusalex** [sabeechen/hassio-google-drive-backup#379]
Options combo box changed 
PR submitted
https://github.com/sabeechen/hassio-google-drive-backup/pull/378
![image](https://user-images.githubusercontent.com/15642727/113789513-a1d30280-9715-11eb-8c3e-e69c868b9c5b.png)

**Comment by sabeechen** [comment]
I just updated the guide to reflect Google's new requirements for authenticating.  Let me know if you see anything else wrong with it.
