### ISSUE TITLE
wrong {version_ha} indicated when snapshot is made after update

### ISSUE THREAD

**Issue by dhzl84** [sabeechen/hassio-google-drive-backup#38]
I updated HA from 92.1 to 92.2.
After the HA UI was available again I started a manual snapshot via the addons WebIF.
The snapshot was created with the {version_ha} variable and contains 92.1 instead of 92.2.

![image](https://user-images.githubusercontent.com/5675570/57143572-745ddb80-6dbf-11e9-845e-3abbc4acf7df.png)

Regards
Dominik

**Comment by sabeechen** [comment]
Looks like I'm updating the cached HA version when a scheduled snapshot is made, but not manual ones.  Should be a simple fix for the next release, thanks for identifying it.

**Comment by sabeechen** [comment]
I've fixed this in the latest release (v0.96)
