### ISSUE TITLE
Better /media exclusion handling (partial backups)

### ISSUE THREAD

**Issue by gwalker88** [sabeechen/hassio-google-drive-backup#382]
I exclude the /media folder from backups because I only use that for aarlo camera captures, and I manually ensure that it does not fill. 

This exclusion makes all my backups appear as "partial", which is a bit misleading, as it does include everything in HA, save for some video files. I would like to see a less binary "partial/full" description.

Perhaps this is a separate Issue, but if there were a way to only backup new files from the /media folders during a "full" backup, that would be even better. As it stands, full backups grow rapidly with the amount of video files captured, to the point where it's impractical to store full backups locally, (i.e., duplicating the contents of /media in every backup).

**Comment by sabeechen** [comment]
You can change the name of the snapshot to whatever you like in the settings, it doesn't need to say "full" or "partial".

As for excluding specific files in a folder, the supervisor is what actually creates the snapshot and it only allows including/excluding whole folders.  Only backing up certain files in a folder isn't possible unless the supervisor supports it first, which is out of my hands.

If there is anything else you think I can help with, feel free to reopen this bug and I'll do what I can.
