### ISSUE TITLE
Usar el addon para hacer snapshots en dos cuentas diferentes

### ISSUE THREAD

**Issue by maiflaii** [sabeechen/hassio-google-drive-backup#384]
Buenas tardes,es la primera vez que escribo por aqui,así que no se si lo estare realizado de la manera correcta,lo que planteo no es un error,sino mas bien una duda o solicitud.me gustaría saber si con este addon se puede realizar desde dos maquinas diferentes con dos instalaciones de ha diferentes desde la misma ubicacion(casa) en dos cuentas de google drive sus respectivos snapshots.gracias

**Comment by sabeechen** [comment]
Yes you can. When you start the addon just connect the different instances of the addon with different Google Drive accounts.  You can also use two instance of the addon with the same Google Drive account, when the addon starts up on the second machine it will notice that a folder already exists and ask if you want to use a different one.  Everything should work fine so long as you don't make both instances of the addon backup into the same folder in Google Drive.  Note that I used Google Translate to translate your response, so apologies if I misunderstood your question.

Transalation for convenience:
Traducción por conveniencia:
Sí tu puedes. Cuando inicie el addon, simplemente conecte las diferentes instancias del addon con diferentes cuentas de Google Drive. También puede usar dos instancias del addon con la misma cuenta de Google Drive, cuando el addon se inicie en la segunda máquina, notará que ya existe una carpeta y le preguntará si desea usar una diferente. Todo debería funcionar bien siempre que no haga ambas instancias de la copia de seguridad de addon en la misma carpeta en Google Drive. Tenga en cuenta que utilicé el Traductor de Google para traducir su respuesta, disculpe si entendí mal su pregunta.

**Comment by maiflaii** [comment]
Muchas graciass,hecho

**Comment by maiflaii** [comment]
Solucionado
