### ISSUE TITLE
Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of Google Assistant Webserver

### ISSUE THREAD

**Issue by g4m3r7ag** [sabeechen/hassio-google-drive-backup#386]
Getting the following in the log on startup, I believe it's from this addon

21-04-16 06:43:22 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of Google Assistant Webserver

**Comment by sabeechen** [comment]
That isn't my add-on.  I think you may have intended to let [this guy](https://github.com/AndBobsYourUncle/hassio-addons) know.
