### ISSUE TITLE
Feature Reques: Addon snapshots

### ISSUE THREAD

**Issue by DavyRoswinkel** [sabeechen/hassio-google-drive-backup#387]
It would come in handy if there was an apart system for keeping the addon snapshots.

I always keep the last addonsnapshot indefinitely, and when the addon updates and it takes a new snapshot, I manually delete the kept addonsnapshot and flag the new addonsnapshot to keep indefinitely. 

I think this would be a nice feature to add to this repository to happen automatically, if possible.

**Comment by sabeechen** [comment]
I'm not sure I understand what you're describing.  Do you manually indicate a snapshot should be kept forever every time its created?  If so why?

**Comment by DavyRoswinkel** [comment]
I am not sure how to explain what I mean. 
I mean:
If there is an update for an addon 
Then the supervisor lets you make a snapshot( from the current addon only) before installing the (addon)update.
I always do this ( to prevent problems if there is something wrong with the update)
But I keep this addonsnapshot, until there's a next addon update and a new addon snapshot is made.

This way I can always go back to a working addon.

But some addons are updating way more frequently then others, so keeping a snapshot only for a week or only keeping a certain number of snapshots doesn't always work.
I was wandering if there was a possibility to have the systems snapshots ( with it's rules of keeping and cleanup) And have  addon snapshots with other rules ( of keeping and cleanup, aka keeping until there is a new snapshot made from the addon)

(As I'm thinking now, I guess it starts with adding a flag or something to the addonsnapshot made by the supervisor, otherwise nothing can tell the difference...)

**Comment by DavyRoswinkel** [comment]
Just installed the newest update for this addon, and it looks like my issue is solved now! 

I can ignore the upgrade snapshots!
