### ISSUE TITLE
Ability to schedule a full backup in addition to partial backups

### ISSUE THREAD

**Issue by SmartM-ui** [sabeechen/hassio-google-drive-backup#388]
Hi,
I set up a partial backup every night and I would like to be able to schedule a full backup one day of the week, for example on Friday.
I didn't find this option, you can only choose between full backup and partial backup.
Is it possible to integrate a full backup between partial backups?
Thanks

**Comment by sabeechen** [comment]
Duplicate #145
Just de-duplicating this bug in an attempt to keep my requested features organized.  I also posted a workaround in #145 if you'd like to give it a shot.
