### ISSUE TITLE
Unable to display snapshots list

### ISSUE THREAD

**Issue by igogold** [sabeechen/hassio-google-drive-backup#389]
After upgrade of the addon to version 0.104.1 I'm unable to get list of snapshots in the addon's interface. It happens only on my home assistant install where I use for backup Drive from Google Workspaces business plan, I think it simply without limits on Drive space. There is no such error on another install with free end-user Google Drive account. I think error with _drive_info["storageQuota"]["limit"] in addon/backup/drive/drivesource.py:80 according to log:
```python
04-22 09:53:37 ERROR [backup.ui.uiserver] Error serving GET http://hass.mydomain.ru:8123/bootstrap?version=0.104.1
04-22 09:53:37 ERROR [backup.ui.uiserver]    
  addon/backup/ui/uiserver.py:684 (error_middleware)   
  addon/backup/ui/uiserver.py:173 (bootstrap)   
  addon/backup/ui/uiserver.py:143 (buildStatusInfo)   
  addon/backup/model/coordinator.py:158 (buildSnapshotMetrics)   
  addon/backup/drive/drivesource.py:80 (freeSpace)   
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'   
```

**Comment by sabeechen** [comment]
I should be able to release a fix for this tomorrow morning.  I 'm pretty sure I know what the error is.

**Comment by sabeechen** [comment]
Eh actually I'll just fix it right now.  I should have a new release out in about half an hour.

**Comment by sabeechen** [comment]
Okie dokey.  The newest version (v0.104.2) is live with the fix for this.  If HA doesn't see the new version right away, make sure you refresh the "add-on store" (```...``` in the top right) to force it to do so.  Feel free to reopen this issue if you continue to see any problems and thanks for letting me know so quickly.
