### ISSUE TITLE
Top level menu overlaps

### ISSUE THREAD

**Issue by sabeechen** [sabeechen/hassio-google-drive-backup#39]
The top level menu items overlaps with other UI elements when the screen is resized down.

**Comment by sabeechen** [comment]
Fixed this in the latest release v0.96.1

**Comment by NCC-1031** [comment]
Menu still overlaps om mobile phone.

**Comment by sabeechen** [comment]
Hrm you're right

**Comment by sabeechen** [comment]
Fixed this in 0.97.1, which I just released.
