### ISSUE TITLE
not FULL backup

### ISSUE THREAD

**Issue by snug-inglenook** [sabeechen/hassio-google-drive-backup#391]
Why does it produce only a partial snapshot? this is at least in the name of the snapshot file. I need specifically a full snapshot every other day. 
Thank you.

**Comment by snug-inglenook** [comment]
Double checked. No partial snapshot. Now, I haven't checked whether this is
indeed a partial snapshot or not but the name says so:

addon_cebe.....
10.5 kB - Backed up
PARTIAL SNAPSHOT
1 day ago

Full shapshots are 60MB or so large.

**Comment by sabeechen** [comment]
Ah, that snapshot is one that Home Assistant makes for you automatically when you update any addon or Home Assistant.  This is a recent feature added to Home Assistant, preventing them from being created is beyond the addon's control, and I'm not aware of a way to turn it off completely.
- If you'd prefer it didn't get made, make sure you de-select "Create a snapshot of...." in the dialog that pops up when you update an addon or home assistant manually.  I'm unsure if they're also automatically made for you when an addon is automatically updated.
- If you'd prefer that the addon ignore such snapshots, then check 'Ignore "Upgrade" Snapshots' in this addon's settings.  Note that I only added this feature very recently, so make sure this addon is updated to v0.104.2 (latest verison at the time of writing) before you look for it.  After you turn on this setting, any snapshot thats already been backed up to Google Drive won't be ignored until you delete it from Google Drive.

**Comment by snug-inglenook** [comment]
Thanks, will make changes and continue testing.
