### ISSUE TITLE
I can´t start after the last update

### ISSUE THREAD

**Issue by IsaTTeN** [sabeechen/hassio-google-drive-backup#40]
Hello

I updated today the add-on to 0.95, and now I´m unable to start it.

Nothing appears in log

![image](https://user-images.githubusercontent.com/20249994/57177683-8a6ea900-6e5e-11e9-87d4-62afe363eebc.png)

I have reinstalled the add-on without luck.

I don´t know what to do really...

**Comment by sabeechen** [comment]
After you start it or reinstall it, could you take a look at the supervisor logs (Hass.io > System > > System Logs > Refresh).  Usually problems starting/stopping/installing addons shows up there.

To help debug it'd be good for me to know your HA version and what kind of hardware you run it on.

**Comment by IsaTTeN** [comment]
I have this:

`19-05-04 16:43:07 ERROR (SyncWorker_4) [hassio.docker] Can't start addon_cebe7a76_hassio_google_drive_backup: 403 Client Error: Forbidden ("endpoint with name addon_cebe7a76_hassio_google_drive_backup already exists in network hassio")`


System  HassOS 2.8
HA 0.92.2
Raspberry Pi 3 B+

**Comment by sabeechen** [comment]
It looks like an error is not in the add-on or Hass.io, but Docker ([reference](https://www.reddit.com/r/Traefik/comments/9o1tsh/start_container_failedendpoint_with_name_already/)).  I suspect Hassio ran into an error trying to clean up the network during the upgrade, leaving it in a partially removed state.  Most likely the logs associated with that are long gone, but if you can still see them I'd bet the Hass.io folks would be interested in them.

I'd try:
* Uinstalling the add-on (copy your config somewhere if you haven't already)
* Restart HassOS (or just power cycle the host machine)
* Reinstall the add-on.

It might be worthwhile to check and see if any of your other addons are having trouble, If I'm right whatever happened could happen to any of them.  For each step double check the supervisor logs to ensure it completed without problems.

**Comment by IsaTTeN** [comment]
it works now, like before!

Unsinstall>Reboot>Install>Confg>Start>Give Permisissions again in Gdrive>OK

Thanks

**Comment by sabeechen** [comment]
Glad it works, if it ever comes up again check the supervisor log.  I suspect it isn't something I can prevent from the add-on side of things (eg a problem in Hassio), but I'd be curious to know what caused it.
