### ISSUE TITLE
Typo in Config Screen

### ISSUE THREAD

**Issue by cap60552** [sabeechen/hassio-google-drive-backup#404]
On the English language version, the description for 'Ignore "Upgrade" snapshots' contains a couple typos.  it says "The addon will ignore snapshots with only one addon or folder inside them. This is usefull if you'd like the addon to ignore snapshots that Homa Assistant automatically creates while updating. Ignored snapshots will not count toward "Snapshots in Home Assistant", get deleted, or get backed up unless you manually tell the addon to do so."

The word "useful" is misspelled, and "Home Assistant" is spelled "Homa Assistant"

**Comment by sabeechen** [comment]
Thanks for pointing this out.  Typos are a persistent problem for me.  I've got my IDE set up to do spell checking, and I re-read everything I write many, MANY times before I check it in.  Despite that, it still plagues me.  My mind just doesn't see the typos.  Fully 90% of the contributed PR's to this project are people correcting small typos.  I'll update this in the next release.

**Comment by juaigl** [comment]
One of the two reported ones was fixed in #395

**Comment by RubenKelevra** [comment]
Fixed in https://github.com/sabeechen/hassio-google-drive-backup/commit/7411504ebe84d95aa735c3e9adf4d39971d92101

**Comment by sabeechen** [comment]
It took a bit for me to get through everything in the latest release, but I've fixed this in the just released v0.105.1.
You can wait for HA to notice the new version, or go to "Supervisor" > "Addon Store" > "..." > "Reload"  to force a check.
Please feel free to re-open this issue if you think there is something else I can help with.
