### ISSUE TITLE
[FR]  Fix icon in the Supervisor Grid View

### ISSUE THREAD

**Issue by SirGoodenough** [sabeechen/hassio-google-drive-backup#407]
It makes me sad to look at your great add-on in the grid view and see the weird green puzzle piece instead of a representative icon for your App.  Perhaps you could put the cloud icon here that you have in the sidebar?

![Screenshot_2021-05-28_12-06-40](https://user-images.githubusercontent.com/47349533/120018789-3e46b200-bfad-11eb-82d6-bdac308b6a5e.png)

**Comment by juaigl** [comment]
for me it is ok
![imagen](https://user-images.githubusercontent.com/45799632/120119197-a4daf400-c196-11eb-8b1c-6e547de8668c.png)

**Comment by sabeechen** [comment]
You're using a pretty old verison of the addon, before the name change to "Home Assistant Google Drive Backup".  You should see the icon if you update.

**Comment by SirGoodenough** [comment]
I see that.
It has not asked me to update...
I have forced updates on other addons, this one is not asking and it is at 'Current version: 0.100.0'.  I will dump it and reload the repository to find '0.104.0'.

**Comment by sabeechen** [comment]
You might want to check your supervisor log if you continue to not see updates, the supervisor is responsible for checking new versions and if it has trouble it should show up there.

**Comment by SirGoodenough** [comment]
I blew it away and reset it.
Somehow the add-on was there but the repository was not, so the repository was not being checked as a result.  It's all working now, as is your last back-up sensor which is awesome, BTW....  Spotted that in the issues below.  You should put that in the WIKI or somewhere.
