### ISSUE TITLE
Repostitory structure for 0.104.1 is not compliant

### ISSUE THREAD

**Issue by BradleyGKV** [sabeechen/hassio-google-drive-backup#408]
When trying to add the repository to install Hassio Google Drive Backup, I receive an error stating "Repostitory structure for 0.104.1 is not compliant".

<img width="428" alt="Screen Shot 2021-05-28 at 8 03 21 PM 1" src="https://user-images.githubusercontent.com/34726304/120053501-23e1f800-bff0-11eb-82e5-92dca8dd2294.png">

**Comment by sabeechen** [comment]
You are trying to install the addon through HACS.  This is not a HACS plugin, it is a Home Assistant Supervisor Addon.  You can install it by closely following the [installation Instructions](https://github.com/sabeechen/hassio-google-drive-backup#detailed-install-instructions).
