### ISSUE TITLE
Port 1627 in use

### ISSUE THREAD

**Issue by six-shooter** [sabeechen/hassio-google-drive-backup#409]
I use version 0.104.3 of [Hassio google drive backup ](https://github.com/sabeechen/hassio-google-drive-backup/)

Since a short while, I get the message that Port 1627 is in use (I have no clue by what, I've even gone so far to disable most other add-ons and plugins, to no avail).

When changing the port to something else, the add-on does start, but I can't go to the web-ui. 
I get the error: "502: Bad Gateway".

I am a bit of a newbie with HA, and I am not sure where to go from here,.

**Comment by sabeechen** [comment]
I'd start by using the default port and restarting the host machine, HA might have locked the port for the addon and gotten confused when the addon restarted (or something like that).  Restarting the supervisor fixes a lot of problems.
If that doesn't work, a few questions to help figure this out:

- Has the addon ever worked before, or is this the first time you installed it?  If it worked before, what happened to make it stop (eg an upgrade)?
- When you run the addon with a different port, do you see anything in the addon logs ("Supervisor" > "Dashboard" > "HA Google Drive Backup" > "Logs") or the supervisor logs ("Supervisor" > "System" > "Logs")?

**Comment by six-shooter** [comment]
in short: It works again
in long:
- deleted addon and repository
- added and installed repository/addon (still didnt work)
- updated to newest HA (I always do this, and it hasnt worked since april). (didnt work)
- defaulted the settings/config of the addon (didnt work)

- rebooted supervisor

It now seems to work!

Still need to authorize, but no port error and no '502 bad gateway'. I also get the web ui now.

**Comment by six-shooter** [comment]
Bought you a coffee! Enjoy it!

**Comment by sabeechen** [comment]
Thanks for the coffee!  Thats a strange result but I'm glad things are working.  If you'd like to figure out why its still asking you to authorize, restart the addon, go into the web-UI, select ```Actions``` > ```Report a Bug``` and post the contents here, which would speed up debugging.  

If not, just leave this closed and enjoy the addon.
