### ISSUE TITLE
Error cannot access /data/credentials.dat

### ISSUE THREAD

**Issue by D3rax** [sabeechen/hassio-google-drive-backup#41]
Hello,

After starting the addon I get the following error in the log:

2019-05-05 13:30:32,146 INFO Loading config from /data/options.json
/usr/lib/python3.6/site-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access /data/credentials.dat: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))

Is there a way to solve this?

**Comment by sabeechen** [comment]
You won't see it again after you've connected the addon to Google Drive.  It just means you don't have stored credentials with Drive yet.

**Comment by sabeechen** [comment]
I've removed the warning from the latest version, v0.97
