### ISSUE TITLE
Cannot define a password

### ISSUE THREAD

**Issue by majes-github** [sabeechen/hassio-google-drive-backup#411]
When I try to set a password in the configuration (by "Show unused optional configuration options" and entering a password) I get this error upon trying to save:

```
Failed to save add-on configuration, not a valid value for dictionary value @ data['options']. Got {'max_snapshots_in_hassio': 4, 'max_snapshots_in_google_drive': 4, 'days_between_snapshots': 3, 'send_error_reports': False, 'use_ssl': False, 'accent_color': '', 'snapshot_password': 'notverysecret'}
```

Any idea how to solve this?

**Comment by sabeechen** [comment]
The addon config editor is effectively broken for addons like this one with lots of configuration options.  I have [strong feelings](https://github.com/home-assistant/frontend/issues/8364) about this, but there isn't much more I can do other than call it to the HA dev's attention.

Id recommend using the settings button inside the addon's Web-UI.  It has the ability to set all the configuration options you can set from Home Assistant, but also does error checking and provides explanations.  It saves the settings in exactly the same way as editing the yaml.

If you'd still like to use HA's editor, you have to go to ```... (top right)``` > ```Edit in YAML``` and remove the empty config options it adds, eg ```accent_color```.

**Comment by sabeechen** [comment]
If you think there is anything else I can help with, please feel free to reopen this bug.
