### ISSUE TITLE
Snapshot detail panel shows the incorrect size for addons.

### ISSUE THREAD

**Issue by sabeechen** [sabeechen/hassio-google-drive-backup#412]
The snapshot detail panel shows a size much smaller than they should be for addons.  I suspect HA is reporting the size of each item in a snapshot in MB and then the addon is interpreting it as bytes.

**Comment by Mincka** [comment]
Confirmed. It shows as "B" in the add-on but it's "MB" in reality.

**Comment by sabeechen** [comment]
It took a bit for me to get through everything in the latest release, but I've fixed this in the just released v0.105.1.
You can wait for HA to notice the new version, or go to "Supervisor" > "Addon Store" > "..." > "Reload"  to force a check.
Please feel free to re-open this issue if you think there is something else I can help with.
