### ISSUE TITLE
"Delete Snapshots After Upload" is ignored when "Snapshots in Home Assistant" is 0

### ISSUE THREAD

**Issue by CarlosGS** [sabeechen/hassio-google-drive-backup#415]
When "Snapshots in Home Assistant" is set to zero, backups remain stored locally in hassio even after the uploads are complete.

"Delete Snapshots After Upload" resumes its expected behavior when setting "Snapshots in Home Assistant" number to 1.

Addon version: `0.104.3`

PS: I really like that it warns before deleting backups. Nice work with this useful addon :)

**Comment by sabeechen** [comment]
You found a bug!  This is exciting for me, I haven't had a good bug in a while.  You're right that it should delete those snapshots.
Its the best kind of bug too, because it hasn't caused anyone to lose snapshots.  I'll fix this in the next release.

**Comment by sabeechen** [comment]
Also, good bug report.  You said all the things I needed to know to find the problem.

**Comment by CarlosGS** [comment]
You're making me blush! Glad to help, thanks for your feedback :)

Awesome plugin, awesome creator! :heart:

**Comment by sabeechen** [comment]
It took a bit for me to get through everything in the latest release, but I've fixed this in the just released v0.105.1.
You can wait for HA to notice the new version, or go to "Supervisor" > "Addon Store" > "..." > "Reload"  to force a check.
Please feel free to re-open this issue if you think there is something else I can help with.

**Comment by CarlosGS** [comment]
Thank you so much! :D
