### ISSUE TITLE
Server disconnected

### ISSUE THREAD

**Issue by andyp05** [sabeechen/hassio-google-drive-backup#416]
New install. HA is up to date. Running on Pi 4B.
Uploaded one snapshot to google drive out of 13. The one uploaded is good. 'Hone Assistant Snapshots' folder was created without error. 
Deleted all of the old snapshots in HA. Kept the 3 most recent. I thought it said it would keep 4.

The remaining snapshots will not upload. My internet is very reliable and I can log into google drive without error in my browser. Keep getting:

```
06-17 10:34:02 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/info
06-17 10:34:02 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/info
06-17 10:34:02 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/core/info
06-17 10:34:02 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/supervisor/info
06-17 10:34:44 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/options
06-17 10:34:44 INFO [backup.model.coordinator] Syncing Snapshots
06-17 10:34:44 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
06-17 10:34:44 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1vZDQBxogGMk0CGc9uMcnFpSaJuhpgMk1/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
06-17 10:34:44 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
06-17 10:34:44 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271vZDQBxogGMk0CGc9uMcnFpSaJuhpgMk1%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
06-17 10:34:45 ERROR [backup.model.coordinator]    
  addon/backup/model/coordinator.py:176 (_sync)   
  addon/backup/model/model.py:200 (sync)   
  addon/backup/drive/drivesource.py:172 (save)   
  addon/backup/util/asynchttpgetter.py:221 (__aenter__)   
  addon/backup/util/asynchttpgetter.py:61 (setup)   
  addon/backup/util/asynchttpgetter.py:161 (_startReadRemoteAt)   
  addon/backup/tracing_session.py:20 (_request)   
  /site-packages/aiohttp/client.py:544 (_request)   
  /site-packages/aiohttp/client_reqrep.py:890 (start)   
  /site-packages/aiohttp/streams.py:604 (read)   
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected   

06-17 10:34:45 INFO [backup.model.coordinator] I'll try again in an hour
```

Any suggestions would be appreciated.

Thanks

**Comment by andyp05** [comment]
Update.

The add-on deleted a local snapshot off of the HA drive but thought it still existed. When it went to upload, the file was not found. The 'Server Disconnected' error was not the real issue. 

If I went to delete the snapshot in the add-on it said it existed in HA. It did not and the delete failed with an error. I repopulated the backup file manually and all errors disappeared. To test, I manually created another snapshot and it uploaded to google instantly.

Thanks.

**Comment by sabeechen** [comment]
It'll be difficult to figure out whats going wrong, since it looks like more than one thing might be happening at once.  Could I have you:

- Restart the addon.
- Wait for the error to show up again.
- Go into the addon web-ui and click "Actions" -> "Report a bug"
- Copy the output form it here.

**Comment by sabeechen** [comment]
I'm going to close this issue for now, but please feel free to re-open it if you think there is something else I can help with.
