### ISSUE TITLE
Feature request. Upload media folder when camera.record is done.

### ISSUE THREAD

**Issue by andyp05** [sabeechen/hassio-google-drive-backup#417]
Great plugin. Appreciate the work.

I don't know what your plans are for future features, but I wanted to suggest one.

Using all of the same config options. Number of days to keep, auto cleanup, etc... It would be great if you extended the functionality to upload media files on creation from the camera.record service.

Thanks

**Comment by sabeechen** [comment]
I've thought about this, and its been suggested a few times, but for the time being I need to keep the focus of the project limited to keep it maintainable.  [Feature creep](https://en.wikipedia.org/wiki/Feature_creep) will destroy this project if I'm not careful.  Right now that means providing a good user experience around making and maintaining backups.  There are a couple of ways you could do what you want right now though:

- You can include the media folder as part of the snapshot which gets put into Google Drive by this addon.
- You can use [samccauley/addon-hassiogooglebackup](https://github.com/samccauley/addon-hassiogooglebackup/), a different addon that backs up files from home assistant to Google Drive.  Its a bit more difficult to configure and get running but it allows for more flexibility in what files and folders get backed up.  I believe you could configure it to sync as pecific HA media folder to a folder in Google Drive and have it automatically clean up old files, though I've never used it personally to do so.
