### ISSUE TITLE
Secrets password file

### ISSUE THREAD

**Issue by detxm80** [sabeechen/hassio-google-drive-backup#42]
Hi, there is an option for exclude folders, add-on, but i don't understand if i can exlude a file (like secret_password).
Thanks

**Comment by sabeechen** [comment]
The add-on uses the Hassio API to create snapshots, same as if you went through the Hass.io snapshots page, which unfortunately doesn't let you exclude specific files.  Just folders.  You *can* encrypt the snapshot with a password though.
