### ISSUE TITLE
Feature Request: Async Upload

### ISSUE THREAD

**Issue by rabin-io** [sabeechen/hassio-google-drive-backup#427]
Hi 

Can you implement that the upload will run as async background job, as the current state, for each update which create a snapshot, you need to wait until the backup is uploaded to Drive. This is a time consuming, and wasteful if for some reason one like to cancel an unneeded backup.

**Comment by sabeechen** [comment]
This is a limitation in Home Assistant's supervisor.  Home Assistant actually creates the snapshot, the addon only asks for it to be made at specific times and then copies it to Google Drive.  The only way to stop a snapshot in progress right now is to restart Home Assistant's Supervisor.  To support this in the addon, it would need to be implemented in Home Assistant.

**Comment by rabin-io** [comment]
Sorry, I'm a bit confused from the answer, I'm not sure if you replayed only on the last part of my question, or all of it.

About this part, 
> Home Assistant actually creates the snapshot, the addon only asks for it to be made at specific times and then copies it to Google Drive.

If the addon is asking for it, can it be uploaded asynchronously later on, as I see it, e.g when updating HA, the upgrade process will wait for the upload to be finished before proceeding with the upgrade.

**Comment by sabeechen** [comment]
Ah, I think I misunderstood what you're asking, I assumed you wanted to be able to stop a snapshot in progress after it starts.  I'm still confused, it is probably a language difference issue.  I'll need some more help to understand what you're asking.

Are you asking if the addon can upload its snapshots in parallel to Google Drive?

**Comment by rabin-io** [comment]
I will try to clarify it by example,
Let say you have a HA update, and you press the update link, the popup shows up and and you check the checkbox to do the snapshot. Now what will happen is that HA will take the snapshot then the addons will do it work to rotate the backups and sync/upload the file to google drive, and only then will start the update process. All the process is done in serial.

```
 ┌──────────┐        ┌──────────┐          ┌─────────────────────┐       ┌───────────────┐      ┌───────┐
 │  Update  │        │ Take     │          │  Upload/Sync        │       │ Pull new      │      │Reload │
 │  Event   ├────────► Snapshot ├──────────►   Snapshot to Drive ├───────► Image for HA  ├──────►       │
 └──────────┘        └──────────┘          └─────────────────────┘       └───────────────┘      └───────┘
```

what I'm asking/suggesting is to put the sync/upload process into a background job, and return early to the upgrade proces.

```
 ┌──────────┐        ┌──────────┐          ┌─────────────────────┐       ┌───────────────┐      ┌───────┐
 │  Update  │        │ Take     │          │Schedule Sync/Upload │       │ Pull new      │      │Reload │
 │  Event   ├────────► Snapshot ├──────────┤   Snapshot to Drive ├───────► Image for HA  ├───▲──►       │
 └──────────┘        └──────────┘          └───────────┬─────────┘       └───────────────┘   │  └───────┘
                                                       │                                     │
                                             ┌─────────▼──────────────────┐                  │
                                             │    Upload when ready       │                  │
                                             │    (or when device idle)   ├──────────────────┘
                                             │                            │
                                             └────────────────────────────┘
```

I hope I was able to clarify my intention

**Comment by sabeechen** [comment]
Thank you for the diagram, I think I understand what you're asking.

I believe the addon is already working asynchronously in the way you request, but I will need to do some testing to double check that is the case.  The addon *should* start uploading a snapshot immediately once its available, i.e. immediately after the supervisor writes the snapshot tar file to the /backup directory.  This should happen independently of what the supervisor is doing with Home Assistant (for example when updating its docker image).  One potential hiccup is that the addon needs the supervisor running to read the bytes of a snapshot file, so if an update of Home Assistant causes the supervisor to go offline for any reason (for example if the supervisor is also updated) then uploading in parallel to an update wouldn't be possible.  I haven't ever checked during a HA update to see if thats the case, I'll need to spin up a test instance to be sure.

**Comment by sabeechen** [comment]
I captured the logs from the most recent time I updated, and I think its already running the upload to Google Drive asynchronously as you request.  Here are the annotated logs from my last upgrade:

Supervisor logs:
```
# Asked to update Home Assistant, partial snapshot of Home Assistant folder starts
21-07-18 12:29:03 INFO (MainThread) [supervisor.snapshots] Creating new partial-snapshot with slug c838be71
21-07-18 12:29:03 INFO (MainThread) [supervisor.snapshots] Snapshotting c838be71 store folders
21-07-18 12:29:03 INFO (SyncWorker_4) [supervisor.snapshots.snapshot] Snapshot folder homeassistant
21-07-18 12:30:40 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup
21-07-18 12:32:30 INFO (SyncWorker_4) [supervisor.snapshots.snapshot] Snapshot folder homeassistant done
21-07-18 12:32:34 INFO (MainThread) [supervisor.snapshots] Creating partial-snapshot with slug c838be71 completed

# Snapshot finished here, supervisor starts updating Home Assistant by downloading the new image

21-07-18 12:32:34 INFO (MainThread) [supervisor.homeassistant.core] Updating Home Assistant to version 2021.7.3
21-07-18 12:32:34 INFO (SyncWorker_3) [supervisor.docker.interface] Updating image ghcr.io/home-assistant/qemux86-64-homeassistant:2021.7.1 to ghcr.io/home-assistant/qemux86-64-homeassistant:2021.7.3
21-07-18 12:32:34 INFO (SyncWorker_3) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/qemux86-64-homeassistant with tag 2021.7.3.

# Addon notices the new snapshot and starts downloading it 

21-07-18 12:32:39 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup
21-07-18 12:32:39 INFO (MainThread) [supervisor.api.middleware.security] /snapshots/c838be71/info access from cebe7a76_hassio_google_drive_backup
21-07-18 12:32:40 INFO (MainThread) [supervisor.api.middleware.security] /snapshots/c838be71/download access from cebe7a76_hassio_google_drive_backup
21-07-18 12:32:40 INFO (MainThread) [supervisor.api.snapshots] Downloading snapshot c838be71

# Supervisor finishes downloading the new HA image and recreates the container with it

21-07-18 12:33:38 INFO (SyncWorker_3) [supervisor.docker.interface] Stopping homeassistant application
21-07-18 12:33:58 INFO (SyncWorker_3) [supervisor.docker.interface] Cleaning homeassistant application\
21-07-18 12:33:58 INFO (SyncWorker_5) [supervisor.docker.homeassistant] Starting Home Assistant ghcr.io/home-assistant/qemux86-64-homeassistant with version 2021.7.3
21-07-18 12:33:58 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
21-07-18 12:34:19 INFO (SyncWorker_3) [supervisor.docker.interface] Cleanup images: ['ghcr.io/home-assistant/qemux86-64-homeassistant:2021.7.1']
21-07-18 12:34:20 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
```


Addon logs:
```
# Addon notices the new snapshot
07-18 12:32:34 DEBUG [backup.worker.watcher] Backup directory modified event
07-18 12:32:39 INFO [backup.worker.watcher] Backup directory changed
07-18 12:32:39 DEBUG [backup.model.syncer] Sync requested by Backup Directory Watcher
07-18 12:32:39 INFO [backup.model.coordinator] Syncing Snapshots
07-18 12:32:39 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
07-18 12:32:39 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/c838be71/info

# Addon starst uploading the snapshot
07-18 12:32:39 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/REDACTED/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
07-18 12:32:39 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
07-18 12:32:40 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%REDACTED%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
07-18 12:32:40 INFO [backup.drive.drivesource] Uploading 'core_2021.7.1' to Google Drive
07-18 12:32:40 DEBUG [backup.drive.driverequests] Starting a new upload session with Google Drive
07-18 12:32:40 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true
07-18 12:32:40 DEBUG [backup.drive.driverequests] Sending 262144 bytes to Google Drive
...
...
07-18 12:33:24 DEBUG [backup.drive.drivesource] Uploading core_2021.7.1 100.00%
07-18 12:33:24 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/REDACTED/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
07-18 13:33:24 DEBUG [backup.model.syncer] Sync requested by Coordinator
07-18 13:33:24 INFO [backup.model.coordinator] Syncing Snapshots
```

So the timeline of events was:
```
12:29:03 Supervisor starts a snapshot for the update
12:32:34 Supervisor finishes snapshot & starts updating HA
12:32:39 Addon notices the new snapshot & starts uploading to Google Drive
13:33:24 Addon finishes uploading the snapshot to Google Drive
12:33:58 Supervisor finishes updating HA
```


Because my snapshot was relatively small the snapshot was uploaded to Google Drive before the supervisor had finished updating HA, so its definitely happening in parallel.

There are some reasons why it might *appear* to happen in series:
- The UI goes offline while HA is being updated, so you can't see progress until the update is complete.
- Taking the snapshot of the HA folder can take much longer than it takes to update, and the upload can't start until the snapshot finishes, so it might appear that addon is waiting for the update to complete before uploading to Google Drive.


In any case if you think I misunderstood or got something wrong, please feel free to reopen this and we can talk about it.
