### ISSUE TITLE
Incorrect data of attribute 'last_snapshot' for 'sensor.snapshot_backup'

### ISSUE THREAD

**Issue by Enzokot** [sabeechen/hassio-google-drive-backup#431]
If the option "Ignore 'Upgrade' snapshots" is on, the attribute 'last_snapshot' for 'sensor.snapshot_backup' keeps fetching the last snapshot, even for addon's snaphots.
Version: 0.104.3
![image](https://user-images.githubusercontent.com/43236573/125805461-d6b24693-f396-4ac0-869b-36c138641224.png)
![image](https://user-images.githubusercontent.com/43236573/125805484-06257e09-0864-4766-aa14-ff0fbc4e0550.png)

**Comment by sabeechen** [comment]
You are correct, I'll fix this in the next update

**Comment by sabeechen** [comment]
It took a bit for me to get through everything in the latest release, but I've fixed this in the just released v0.105.1.
You can wait for HA to notice the new version, or go to "Supervisor" > "Addon Store" > "..." > "Reload"  to force a check.
Please feel free to re-open this issue if you think there is something else I can help with.

**Comment by Enzokot** [comment]
@sabeechen Thanks!
