### ISSUE TITLE
Exclude non-encrypted snapshots

### ISSUE THREAD

**Issue by marcgarciamarti** [sabeechen/hassio-google-drive-backup#432]
Can we somehow excluded not encrypted snapshots? These days home assistant will create a back up automatically when one upgrades the system. Is there anyway we could exclude those back ups? otherwise we are giving google our encryption key inadvertently when these snapshots in plain text are uploaded...

**Comment by sabeechen** [comment]
I could add another option, but wouldn't the "Ignore upgrade snapshots" or "ignore other snapshots" option in the settings handle this case for you?  I like supporting every use case but I've got to balance how complex I make the setting UI with how flexible it is.

**Comment by marcgarciamarti** [comment]
Hi and thanks for your prompt answer. Maybe I understood those options incorrectly. Let me elaborate a bit because maybe we are already covered and it is a matter of making sure I understand the options correctly.
HA will creat a partial snapshot of an add-on prior to upgrading it. And this snapshot will be ignored by your options. 
Will it also skip full snapshots that HA makes prior to doing a full system upgrade? If it does, then we are covered indeed.

**Comment by sabeechen** [comment]
When upgrading home assistant, it will automatically create a snapshot of just the home assistant folder.  When upgrading an addon, it will make a snapshot of just the addon.  I'm not aware of a case where it makes a "full" snapshot prior to any action.  Or what I should say is I haven't seen it do that, I might be wrong.

As for the options:
*"Ignore other snapshots"* will make the addon ignore any snapshots its confidant that it didn't ask for.  This includes the aforementioned upgrade snapshots, full and partial snapshots you request from the Supervisor's snapshot web-ui, and any other snapshots that weren't created by the addon.

*"Ignore upgrade snapshots"* works similarly but it will only ignore the snapshot if there is one "thing" in it (eg a single folder or a single addon)

So based on my understanding of how the upgrade snapshots are made, they'll always be ignored if you enabled *Ignore upgrade snapshots*, but if you wanted to be extra double certain you could enable *Ignore other snapshots* to exclude everything everything the addon didn't make no matter what.

Its also worth noting that even when a snapshot is ignored, you can still "un-ignore" it from the addon web-ui to get it backed up to drive and automatically cleaned up.  this is useful if you have *Ignore other snapshots* turned on but then made a snapshot through the Supervisor interface that you actually want uploaded to Google Drive.

**Comment by marcgarciamarti** [comment]
Thanks again for such a detailed explanation. I've already checked both options. We are covered! Awesome product with an awesome developer behind!
