### ISSUE TITLE
Request for integration with a third-party heartbeat monitoring service (e.g. Cronitor)

### ISSUE THREAD

**Issue by ndbroadbent** [sabeechen/hassio-google-drive-backup#434]
Thanks for the awesome work on this addon!

I just had a feature request related to the [How will I know this will be there when I need it?](https://github.com/sabeechen/hassio-google-drive-backup#how-will-i-know-this-will-be-there-when-i-need-it) section in the README. I'm a big fan of [Cronitor](https://cronitor.io/). This is a service that sends me an alert whenever one of my scheduled tasks fails to run on time (or takes too long.) It can be set up quite easily in any programming language (including a curl command from a bash script.) 

I think the built-in notifications are great, but once my home automation system is up and running, there might be some long periods of time where I don't log in to the dashboard, so I won't see the notifications. E.g. If I'm away on holiday, it would be great to get a proactive email alert saying that my backup failed to run, so something might be wrong with my Raspberry Pi.

I would love to be able to send an initial curl request to Cronitor when the scheduled snapshot task starts, and then send another curl request once the snapshot has been taken and uploaded to Google Drive. So it would be great if this addon could include support for some `before` and `after` scripts, and if I could edit these scripts in the UI (maybe under something like "advanced settings".)

Alternatively, is there a file that I could quickly edit (via SSH) to add a few curl commands to set up a simple Cronitor integration?

Thanks again for all the great work!

**Comment by sabeechen** [comment]
Anything you make in the container will get destroyed when home assistant restarts, but there are a few things you could do.  I'm not sure how cronitor works exactly, but you could set up some API's that can be queried:
- You can use the [Home Assistant API](https://developers.home-assistant.io/docs/api/rest/) to watch the ```binary_sensor.snapshots_stale``` sensor, eg:
  ```
   curl -X GET \
      -H "Authorization: Bearer <your token>" \
      -H "Content-Type: application/json" \
      http://homeassistant.local:8123/states/binary_sensor.snapshots_stale
  ```
  the state for this sensor will be "off" if a snapshot isn't created yet 6 hours past when it should be, which avoid triggering for transient problems
- To get more info, you can set up the addon to to expose its webserver in the Setting under "Expose this web interface on an additional port" (consider also enabling authentication).  You could then make a request to ```http://homeassistant.local:1627/status``` to get the same JSON data the addon web UI has.  There is a lot of info here, but for example status['last_snapshot_machine'] is the RFC339 date of the msot recent snapshot.  You can see [how the status object is constructed here](https://github.com/sabeechen/hassio-google-drive-backup/blob/master/hassio-google-drive-backup/backup/ui/uiserver.py#L89), but be warned I reserve the right to change it in future updates.
- With some clever scripting you can make HA fire an event when it sees the latest backed up snapshot change, which I've outlined [here](https://github.com/sabeechen/hassio-google-drive-backup/issues/385#issuecomment-824472746).  You could use that fire off an http request, update a sensor you've made, or do anything else Home assistant can do.

In the future, I'm planning to make the addon fire events in Home assistant when a snapshot starts/stops/gets uploaded, which would make triggering external events like this easier.  No ETA on that feature right now though.

**Comment by ndbroadbent** [comment]
Awesome, thanks a lot! I was able to get it working with an automation for `sensor.latest_snapshot`. Then I can send a curl command whenever the `sensor.latest_snapshot` state changes.

<img width="1093" alt="Screen Shot 2021-07-21 at 12 59 27 PM" src="https://user-images.githubusercontent.com/139536/126413904-b208b785-9638-4c63-aff5-1053af697f29.png">

<img width="1083" alt="Screen Shot 2021-07-21 at 12 59 48 PM" src="https://user-images.githubusercontent.com/139536/126413927-1719beb3-24d9-49a7-996f-69b07de99cee.png">

<img width="934" alt="Screen Shot 2021-07-21 at 1 00 17 PM" src="https://user-images.githubusercontent.com/139536/126413963-03c46c6f-86fa-478d-bab2-e40e3f084895.png">

<img width="1330" alt="Screen Shot 2021-07-21 at 12 57 56 PM" src="https://user-images.githubusercontent.com/139536/126413778-4aee1640-7dbf-4fda-9c17-2cc7a4f6e54d.png">


Works great! Thanks a lot for your help!

**Comment by ndbroadbent** [comment]
Oh the only thing that would be "nice to have" is another sensor that is only updated after the file is uploaded to Google Drive (and not just a local snapshot.) That way I can be 100% sure that the files are actually uploaded to an external backup in case the SD card breaks. But I'm pretty happy with this for now
