### ISSUE TITLE
double backup created

### ISSUE THREAD

**Issue by papperone** [sabeechen/hassio-google-drive-backup#44]
I've this addon setup to create snapshots every 3 days at 3:00am but it creates every time 2 snapshots, first one at 3:00 and second one at around 3:12; this is actually reducing by 50% the amount of real snapshots history as every time 2 snapshots are created and actually counted!

**Comment by sabeechen** [comment]
Thats really weird.  Does it take aroudn 12 minutes to create a snapshot?  There are definitely some [race conditions](https://en.wikipedia.org/wiki/Race_condition) where I could imagine this happening, but I'd be surprised to see it happen every time.  Does it happen if you take a snapshot manually too?

**Comment by papperone** [comment]
no it only happens with snapshot created by this addon;
as I like it and would like to provide you inputs to solve the problem for the moment I just doubled the amount of shanpshots as a workaround, please let me know how can I provide you more details in order to troubleshoot

**Comment by sabeechen** [comment]
Thanks, I appreciate the help.  This is the only report I've had of this problem but its likely more than just you running into.  Most either wouldn't notice or wouldn't report it.

It would be helpful if you get me a copy of your debug logs.  You can view them by clicking the "Logs" link at the top right of the Web UI, and on that page theres a link nera the top to download a text copy.  The logs can contain *sensitive* information (your snapshot names, list of addons, snapshot password if you have one configured, etc), so you might want to just copy the hour or so before and after when the double snapshots were created.  You can also email just me a copy at stephen@beechens.com

**Comment by sabeechen** [comment]
Sorry I hadn't got back to you sooner, but I've been putting together a new release that I think will help with the problem I could see in your logs.  Could you see if you still get double snapshots with the latest version (v0.97)?

**Comment by papperone** [comment]
Can’t see 0.97 yet released in hass.IO, latest seems to be 0.96.1, will test it as soon as it will be avail…

 

 

Da: Stephen Beechen <notifications@github.com> 
Inviato: sabato 18 maggio 2019 22:03
A: sabeechen/hassio-google-drive-backup <hassio-google-drive-backup@noreply.github.com>
Cc: papperone <giovanni.castania@gmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [sabeechen/hassio-google-drive-backup] double backup created (#44)

 

Sorry I hadn't got back to you sooner, but I've been putting together a new release that I think will help with the problem I could see in your logs. Could you see if you still get double snapshots with the latest version (v0.97)?

**Comment by sabeechen** [comment]
Hassio can be pretty slow to check for new version, you can force it to by click the refresh icon in the upper right of the addon store oage

**Comment by papperone** [comment]
done! just upgraded... will keep you updated if the problem will still occur or not in the next days :)

**Comment by sabeechen** [comment]
I'm closing this for now just to keep my bug list clean, but please reopen if you still see the problem and would like more help.
