### ISSUE TITLE
Spelling error.

### ISSUE THREAD

**Issue by Jontes-Tech** [sabeechen/hassio-google-drive-backup#443]
![image](https://user-images.githubusercontent.com/84264740/129558845-08c28ac2-099d-4c40-89f4-625d77f647bd.png)

Homa instead of Home. 
We all make mistakes, Have a great day!

Kind regards, **Jontes Tech**

PS: Right after taking the screenshot I realized you can make your own dark mode using background and accent colors! That's a lovely feature! Thanks for creating this wonderful addon!

**Comment by RubenKelevra** [comment]
This is already fixed in https://github.com/sabeechen/hassio-google-drive-backup/commit/7411504ebe84d95aa735c3e9adf4d39971d92101

**Comment by sabeechen** [comment]
It took a bit for me to get through everything in the latest release, but this is included in the just released v0.105.1.
You can wait for HA to notice the new version, or go to "Supervisor" > "Addon Store" > "..." > "Reload"  to force a check.
Please feel free to re-open this issue if you think there is something else I can help with.
