### ISSUE TITLE
Log files don’t open

### ISSUE THREAD

**Issue by erkr** [sabeechen/hassio-google-drive-backup#444]
##### Description:
```
Backup snapshots all seems to work fine! The issue;
When selecting the _log_ option the snapshots view, or selecting _debug logs_ in the help section, I get a _401: Unauthorized_ in the browser, on the IP address of my HA.
```

 Addon version: `0.104.3`
 Home Assistant Version: `2021.8.7`
 Supervisor Version: `2021.06.8`
 Supervisor Channel: `stable`
 Hassos Version: `6.2`
 Docker Version: `20.10.6`
 Architecture: `aarch64`
 Machine: `raspberrypi3-64`
 Date: `2021-08-17T12:48:03.757802+00:00`
 Timezone: `Europe/Amsterdam`
 Failure Time: `2021-08-16T14:21:35.057251+00:00`
 Last Good Sync: `2021-08-17T12:39:43.522041+00:00`
 ###### Exception:
 ```
 No error could be identified automatically.
 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 10,
        "retained": 0,
        "deletable": 10,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2021-08-16T14:30:09Z",
        "max": 10,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 0,
        "size": "100.8 MB",
        "ignored_size": "0.0 B",
        "free_space": "51.1 GB"
    },
    "GoogleDrive": {
        "snapshots": 10,
        "retained": 0,
        "deletable": 10,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2021-08-16T14:30:09Z",
        "max": 20,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "size": "100.7 MB",
        "ignored_size": "0.0 B",
        "free_space": "68.1 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_SNAPSHOTS_IN_HASSIO": 10,
    "Setting.MAX_SNAPSHOTS_IN_GOOGLE_DRIVE": 20,
    "Setting.SNAPSHOT_TIME_OF_DAY": "04:45"
}
 ```

**Comment by sabeechen** [comment]
- What is the address that the addon directs you to for the logs?
- Does anything show up in the supervisor logs when you get the 401 error?  That 401 response is coming from HA/supervisor.

**Comment by erkr** [comment]
Hi Stephen,
I noticed that it only fails on my iPhone, not on my PC (using chrome).
The links seem identical (IP=HA57) except for the dash on the end that is missing on the iPhone!:
On PC : http://ha57:8123/api/hassio_ingress/bH3wSSgKimJglgyoWog2dNbgH9fg-h6KNvfMLhYgpDc/log?format=view#
iPhone: http://192.168.178.47:8123/api/hassio_ingress/bH3wSSgKimJglgyoWog2dNbgH9fg-h6KNvfMLhYgpDc/log?format=view

On the iPhone I saw this corresponding warning in the supervisor log:
21-08-18 17:18:31 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None

regards
Eric

**Comment by sabeechen** [comment]
That error indicates that the cookie Home Assistant creates to give permission to view the addon's ingress iframe is not getting sent, so it denies you access to the page.  This is almost certainly a browser issue.

I tried viewing the logs page on an iphone using safari and didn't run into trouble.  If you are using a different browser (especially firefox) you may need to disable some of its security protections for your HA address for everything to work properly.  Home Assistant manages its cookies in a way that many security-focused browsers flag as suspicious.

In particular if you're using firefox, you may be hitting [this open issue](https://github.com/home-assistant/supervisor/issues/3021) with Home Assistant, which affects all addons and isn't something I can fix.

**Comment by erkr** [comment]
Hi 
I use safari with "stock" settings on iOS 14.7.1. 
Regards
Eric

**Comment by erkr** [comment]
`
In particular if you're using firefox, you may be hitting this open issue with Home Assistant, which affects all addons and isn't something I can fix.
`
Although I'm using safari, it seems indeed a HA issue. I will close this issue, thx for the support.
