### ISSUE TITLE
[0.96.1] Snapshot Name Template is reset when Addon is restartet

### ISSUE THREAD

**Issue by dhzl84** [sabeechen/hassio-google-drive-backup#45]
I use to have the current version of HA in my snapshot name, thus I added {version_ha} to the name template.
This work great until I restart/update the addon. After restart the name template is reset to the default one.

**Comment by vitinhosessa** [comment]
Same here, i tried to save inside de addon and in config. Snapshots name resets when i reboot or restart the addon.

**Comment by rbhr** [comment]
Same here. Ping me if you need any logs.

**Comment by sabeechen** [comment]
I think I found the problem, I forgot to add the "snapshot_name" to the add-on configuration, so on an update Hassio thinks the configuration is now invalid and resets it to default.  I'll release a fix soon.

**Comment by sabeechen** [comment]
Ive added the config necessary to correct this to v0.97, which I just released.
