### ISSUE TITLE
Snapshot -> Backup with Supervisor 2021.08

### ISSUE THREAD

**Issue by pschneider87** [sabeechen/hassio-google-drive-backup#451]
HA decided to use the term "Backup" instead of "Snapshot"
See https://www.home-assistant.io/blog/2021/08/24/supervisor-update/#renaming-snapshot-to-backup

Maybe a good time to rename the terms in the addon as well? 
@sabeechen if this change is fine for you, I could contribute

**Comment by sabeechen** [comment]
It took a bit for me to get through everything in the latest release, but I've completed this in the just released v0.105.1.
Only difference is that the config option for using the "old" sensor names/values is ```call_backup_snapshot```.
You can wait for HA to notice the new version, or go to "Supervisor" > "Addon Store" > "..." > "Reload"  to force a check.
Please feel free to re-open this issue if you think there is something else I can help with.
