### ISSUE TITLE
An unexpected error occurred: list index out of range

### ISSUE THREAD

**Issue by creeve4** [sabeechen/hassio-google-drive-backup#453]
Description:
New install of google drive backup.

Addon version: 0.104.3 Home Assistant Version: 2021.8.8 Supervisor Version: 2021.06.8 Supervisor Channel: stable Hassos Version: 6.2 Docker Version: 20.10.6 Architecture: aarch64 Machine: raspberrypi4-64 Date: 2021-08-27T19:56:18.307462+00:00 Timezone: America/Denver Failure Time: 2021-08-27T19:56:12.023522+00:00 Last Good Sync: 2021-08-27T19:56:11.627049+00:00

Exception:

 addon/backup/model/coordinator.py:176 (_sync)
 addon/backup/model/model.py:178 (sync)
 addon/backup/model/model.py:294 (_handleSnapshotDetails)
 addon/backup/model/backupscheme.py:194 (handleNaming)
 addon/backup/model/backupscheme.py:117 (_buildPartitions)
IndexError: list index out of range

Snapshots:

{
   "HomeAssistant": {
       "snapshots": 0,
       "retained": 0,
       "deletable": 0,
       "name": "HomeAssistant",
       "title": "Home Assistant",
       "latest": null,
       "max": 4,
       "enabled": true,
       "icon": "home-assistant",
       "ignored": 0,
       "size": "0.0 B",
       "ignored_size": "0.0 B",
       "free_space": "25.1 GB"
   },
   "GoogleDrive": {
       "snapshots": 0,
       "retained": 0,
       "deletable": 0,
       "name": "GoogleDrive",
       "title": "Google Drive",
       "latest": null,
       "max": 10,
       "enabled": true,
       "icon": "google-drive",
       "ignored": 0,
       "size": "0.0 B",
       "ignored_size": "0.0 B",
       "free_space": "12.4 GB"
   }
}
Config:
{
   "Setting.MAX_SNAPSHOTS_IN_GOOGLE_DRIVE": 10,
   "Setting.DAYS_BETWEEN_SNAPSHOTS": 1.0,
   "Setting.GENERATIONAL_DAYS": 6,
   "Setting.GENERATIONAL_WEEKS": 2,
   "Setting.GENERATIONAL_MONTHS": 1,
   "Setting.SEND_ERROR_REPORTS": true,
   "Setting.BACKGROUND_COLOR": "#000000",
   "Setting.MAX_SYNC_INTERVAL_SECONDS": 21600
}
Addon Logs:
08-27 13:55:24 INFO [backup.model.coordinator] I'll try again right now
08-27 13:55:24 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-27 13:55:24 INFO [backup.model.coordinator] Syncing Snapshots
08-27 13:55:24 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
08-27 13:55:24 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
08-27 13:55:25 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271o4ZTA7xt-8QCXTkTU8vGehWlh03ykIWM%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
08-27 13:55:25 ERROR [backup.model.coordinator] 
 addon/backup/model/coordinator.py:176 (_sync)
 addon/backup/model/model.py:178 (sync)
 addon/backup/model/model.py:294 (_handleSnapshotDetails)
 addon/backup/model/backupscheme.py:194 (handleNaming)
 addon/backup/model/backupscheme.py:117 (_buildPartitions)
IndexError: list index out of range

08-27 13:55:25 INFO [backup.model.coordinator] I'll try again in 10 seconds
08-27 13:55:33 INFO [backup.debugworker] Sending error report (see settings to disable)
08-27 13:55:35 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-27 13:55:35 INFO [backup.model.coordinator] Syncing Snapshots
08-27 13:55:35 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
08-27 13:55:35 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
08-27 13:55:35 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271o4ZTA7xt-8QCXTkTU8vGehWlh03ykIWM%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
08-27 13:55:35 ERROR [backup.model.coordinator] 
 addon/backup/model/coordinator.py:176 (_sync)
 addon/backup/model/model.py:178 (sync)
 addon/backup/model/model.py:294 (_handleSnapshotDetails)
 addon/backup/model/backupscheme.py:194 (handleNaming)
 addon/backup/model/backupscheme.py:117 (_buildPartitions)
IndexError: list index out of range

08-27 13:55:35 INFO [backup.model.coordinator] I'll try again in 20 seconds
08-27 13:55:55 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-27 13:55:55 INFO [backup.model.coordinator] Syncing Snapshots
08-27 13:55:55 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
08-27 13:55:55 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1o4ZTA7xt-8QCXTkTU8vGehWlh03ykIWM/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
08-27 13:55:55 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
08-27 13:55:56 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271o4ZTA7xt-8QCXTkTU8vGehWlh03ykIWM%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
08-27 13:55:56 ERROR [backup.model.coordinator] 
 addon/backup/model/coordinator.py:176 (_sync)
 addon/backup/model/model.py:178 (sync)
 addon/backup/model/model.py:294 (_handleSnapshotDetails)
 addon/backup/model/backupscheme.py:194 (handleNaming)
 addon/backup/model/backupscheme.py:117 (_buildPartitions)
IndexError: list index out of range

08-27 13:55:56 INFO [backup.model.coordinator] I'll try again in 40 seconds
08-27 13:56:11 INFO [backup.model.coordinator] Syncing Snapshots
08-27 13:56:11 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
08-27 13:56:11 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
08-27 13:56:11 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271o4ZTA7xt-8QCXTkTU8vGehWlh03ykIWM%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
08-27 13:56:12 ERROR [backup.model.coordinator] 
 addon/backup/model/coordinator.py:176 (_sync)
 addon/backup/model/model.py:178 (sync)
 addon/backup/model/model.py:294 (_handleSnapshotDetails)
 addon/backup/model/backupscheme.py:194 (handleNaming)
 addon/backup/model/backupscheme.py:117 (_buildPartitions)
IndexError: list index out of range

08-27 13:56:12 INFO [backup.model.coordinator] I'll try again in 1(ish) minutes
Supervisor Logs:
[32m21-08-27 13:50:47 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-27 13:50:57 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-27 13:51:17 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-27 13:52:34 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING[0m
[32m21-08-27 13:52:34 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON[0m
[32m21-08-27 13:52:34 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM[0m
[32m21-08-27 13:52:34 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE[0m
[32m21-08-27 13:52:34 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m21-08-27 13:52:34 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING[0m
[32m21-08-27 13:52:34 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
[32m21-08-27 13:52:34 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m21-08-27 13:52:34 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING[0m
[32m21-08-27 13:52:34 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m
[32m21-08-27 13:52:38 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-27 13:52:38 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-27 13:52:38 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-27 13:55:03 INFO (MainThread) [supervisor.snapshots] Found 0 snapshot files[0m
[32m21-08-27 13:55:03 INFO (MainThread) [supervisor.snapshots] Found 0 snapshot files[0m
[32m21-08-27 13:55:19 INFO (SyncWorker_1) [supervisor.docker.interface] Stopping addon_cebe7a76_hassio_google_drive_backup application[0m
[32m21-08-27 13:55:19 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning addon_cebe7a76_hassio_google_drive_backup application[0m
[32m21-08-27 13:55:22 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on sabeechen/hassio-google-drive-backup-aarch64 with version 0.104.3[0m
[32m21-08-27 13:55:23 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-27 13:55:23 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-27 13:55:23 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-27 13:55:24 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-27 13:55:35 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-27 13:55:55 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-27 13:56:11 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-27 13:56:18 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

Home Assistant Core Logs:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[31m2021-08-27 12:47:30 ERROR (MainThread) [homeassistant.components.hassio.handler] Client error on /homeassistant/restart request Server disconnected[0m
Unable to find configuration. Creating default one in /config
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by sabeechen** [comment]
You've run into this bug #447.  You can follow [these instructions ](https://github.com/sabeechen/hassio-google-drive-backup/issues/447#issuecomment-903156040) to work around it for the time being.  I'm going to release a fix for it soon, but I've run into some hold-ups getting out the new release.
Duplicate #447
