### ISSUE TITLE
Feature request: encrypt backups (non-HA password)

### ISSUE THREAD

**Issue by andriej** [sabeechen/hassio-google-drive-backup#459]
I always have issue when restoring password protected backups. I do that only because they're uploaded to cloud.
What would be nice, is to have HA's backups without password and let add-on encrypt and password protect it's archive stored in cloud (so it would be another task to be done).

**Comment by sabeechen** [comment]
My hands are tied on implementing this.  The add-on doesn't actually create the snapshot, it just asks Home Assistant to do so and either does or doesn't provide a password so I never have access to an unencrypted version of an encrypted snapshot.

I admit it would be possible to have the add-on itself encrypt the snapshot on-the-fly as its uploaded to Google Drive but then I'd have to provide a separate tool that decrypts the snapshot before you could install it during Home Assistant's restore process.  It would be difficult to communicate this to my users.

**Comment by andriej** [comment]
@sabeechen how about approach
1. Setup HA for non-encrypted snapshot/backup (plain)
2. Add-on itself uses some more common (than HA's supervisor) way of encryption

This tool can be any kind of that can pack&encrypt whole package, like ie. 7zip does (or any linux equivalent)
