### ISSUE TITLE
requests.exceptions.ConnectionError: ('Connection aborted.', timeout('The write operation timed out',))

### ISSUE THREAD

**Issue by jj-x** [sabeechen/hassio-google-drive-backup#46]
When trying to upload backup it stops on 21% and I get the following error

My configuration
{
  "max_snapshots_in_hassio": 3,
  "max_snapshots_in_google_drive": 8,
  "days_between_snapshots": 7,
  "use_ssl": false,
  "drive_experimental": true,
  "ignore_ipv6_addresses": true,
  "drive_ipv4": "172.217.1.202",
  "send_error_reports": true,
  "snapshot_time_of_day": "22:30"
}

Traceback (most recent call last):
  File "/app/backup/engine.py", line 162, in doBackupWorkflow
    self._checkForBackup()
  File "/app/backup/engine.py", line 443, in _checkForBackup
    self.drive.saveSnapshot(to_backup, self.hassio.downloadUrl(to_backup), self.folder_id)
  File "/app/backup/drive.py", line 92, in saveSnapshot
    for progress in self.drivebackend.create(stream, file_metadata, MIME_TYPE):
  File "/app/backup/driverequests.py", line 181, in create
    partial = self.retryRequest("PUT", location, headers=headers, data=data)
  File "/app/backup/driverequests.py", line 216, in retryRequest
    response = request(method, url, headers=send_headers, json=json, timeout=(30, 30), data=data, stream=stream)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', timeout('The write operation timed out',))

**Comment by sabeechen** [comment]
Just to verify, does it stop at 21% every time and does it resolve on a retry?
Occasional timeouts are to be expected.  In a version I'm releasing soon you'll be able to configure a higher timeout.  The add-on uploads snapshots in 2.5Mb chunks and I suspect that if one of those junks takes longer than the 30 seconds timeout it will fail.  How big is that snapshot and how long does sit take to get to 21%?

**Comment by jj-x** [comment]
It's 102mb it takes about 4 minutes

**Comment by sabeechen** [comment]
I've added a longer timeout (3 minutes) to the latest version v0.97.  You can also increase the timeout in the settings menu, please reopen the issue and let me know if you still run into trouble with this change.
