### ISSUE TITLE
Google backup snapshot.... Needs a little attention?

### ISSUE THREAD

**Issue by Sandman-wr** [sabeechen/hassio-google-drive-backup#462]
With snapshots being deprecated, and changed to backup, anything need to be done?  Thanks!

**Comment by sabeechen** [comment]
It took a bit for me to get through everything for the latest release, but I've included this in the just released v0.105.1.
You can wait for HA to notice the new version, or go to "Supervisor" > "Addon Store" > "..." > "Reload"  to force a check.

Let me know if anything looks out of place.
