### ISSUE TITLE
Feature Request: Expose next_backup as a timestamp like last_backup

### ISSUE THREAD

**Issue by rpitera** [sabeechen/hassio-google-drive-backup#470]
Title lays it out, basically.  I'd like to have the next scheduled backup/snapshot be exposed as an attribute of `sensor.snapshot_backup` so I can extract it as a sensor like the other attributes you've provided.  I could then use it on my dashboard and in automations.  

I found the current attributes quite useful (thank you!) and I'd like to have this one added.  (Seems to make sense to have both the last and the next.)

Thank You!

**Comment by sabeechen** [comment]
I meant to implement this ages ago, but then ... I forgot!

I just released v 0.106.2 which includes it in the ```sensor.backup_state``` sensor.

**Comment by rpitera** [comment]
Thanks!
