### ISSUE TITLE
401: Unauthorized

### ISSUE THREAD

**Issue by mpoffo1231** [sabeechen/hassio-google-drive-backup#471]
I tried to go into the web UI and received the following error:

401: Unauthorized

I have update HA and the plug-in and restarted but I still cannot open the WebUI.  It had been working great.

Is this a new issue with HA updates?  Any suggestions on how I can correct this?  I did not set-up duck DNS and was not using SSL.

I see this in the error log:

> 09-09 22:32:35 ERROR Trouble updating Home Assistant sensors.
09-09 22:32:35 ERROR 
  addon/backup/ha/haupdater.py:54 (update)
  addon/backup/ha/harequests.py:296 (updateBackupStaleSensor)
  addon/backup/ha/harequests.py:254 (_postHaData)
  /site-packages/aiohttp/client.py:1117 (__aenter__)
  addon/backup/tracing_session.py:35 (_request)
  /site-packages/aiohttp/client.py:520 (_request)
  [4 hidden frames]
  /site-packages/aiohttp/connector.py:975 (_wrap_create_connection)
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host supervisor:80 ssl:default [Connect call failed ('172.30.32.2', 80)]

**Comment by mpoffo1231** [comment]
Seems to be an issue with FireFox.  I can use Google and access it.  Weird.  Any thoughts on what do for for Firefox?  I cleared

**Comment by sabeechen** [comment]
If its [this](https://github.com/home-assistant/supervisor/issues/3021) firefox issue, you should also see the 401 with any other addon too.
I use Firefox mainly too, and what I've found is that If I add my HA server's address to the cookie exception list in Firefox's settings, the problem goes away for me.  If that doesn't work, I think all we can do is wait for the [fix from mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1725996).  If I'm reading that right they're planning to fix it in firefox 94.

Let me know if you think there is anything else I can do to help.

**Comment by sabeechen** [comment]
Oh, I should have read the stack exception you put there a little more closely.  That is a more serious problem unrelated to the Firefox 401, as it means the addon can't talk to the supervisor and will  not be able to do anything.  If you're still seeing that, can you go the the addon web-ui and copy the contents of what "Actions" -> "Report a bug" says?

**Comment by mpoffo1231** [comment]
To follow-up I was seeing the issue with a few other add-ons.  I did not realize this until after I posted this.  SSH was not working with the same error.  I was able to access it with chrome.  After some additional googling I saw several reporting issues with Firefox and this issue.  It had been working great for me but an update must have changed something in Firefox/HA.  I cleared the cookies/data and also made an exception in Firefox to allow my HA install to allow cookies and data.  It then started working in Firefox again.

**Comment by sabeechen** [comment]
Feel free to reopen this issue if there is anything else I can help with.

**Comment by LordNex** [comment]
I just started getting this after reinstalling your addon after not using it for a while. I can get to the page to grant authorization from google but after that I get a 401:Unauthorized error. I am running SSL with the DuckDNS addon for domain resolution but I usually access my server remotely through Nabu Casa due to my Starlink connection using CGNAT. Anything you can suggest? I'm using Chrome on iOS 16.0.2

**Comment by LordNex** [comment]
Also, it doesn't seem to matter what browser I use I still get the same error. I also get the error if I try and click on the "logs" area.

**Comment by LordNex** [comment]
Here is part of the error that is in debug

```

###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.108.4`
 Home Assistant Version: `Uninitialized`
 Supervisor Version: `Uninitialized`
 Supervisor Channel: `{supervisor_channel}`
 Hassos Version: `{hassos_version}`
 Docker Version: `{docker_version}`
 Architecture: `Uninitialized`
 Machine: `{machine}`
 Date: `2022-10-03T06:14:27.920682+00:00`
 Timezone: `Uninitialized`
 Failure Time: `2022-10-03T06:09:03.381704+00:00`
 Last Good Sync: `2022-10-03T06:09:03.376161+00:00`
 ###### Exception:
 ```
 
  addon/backup/ha/harequests.py:33 (wrap_and_call)
  addon/backup/ha/harequests.py:250 (_getHassioData)
  addon/backup/ha/harequests.py:208 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1004 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('http://supervisor/addons/self/info')
Whose handling caused:
  addon/backup/model/coordinator.py:177 (_sync)
  addon/backup/model/model.py:177 (sync)
  addon/backup/model/model.py:285 (_syncBackups)
  addon/backup/ha/hasource.py:247 (get)
  addon/backup/ha/hasource.py:385 (init)
  addon/backup/ha/hasource.py:428 (_refreshInfo)
  addon/backup/ha/hasource.py:393 (_refreshInfo)
  addon/backup/ha/harequests.py:33 (wrap_and_call)
  addon/backup/ha/harequests.py:138 (selfInfo)
  addon/backup/ha/harequests.py:33 (wrap_and_call)
  addon/backup/ha/harequests.py:142 (getAddonInfo)
  addon/backup/ha/harequests.py:40 (wrap_and_call)
backup.exceptions.exceptions.SupervisorPermissionError

 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 0,
        "retained": 0,
        "deletable": 0,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": null,
        "max": 4,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 0,
        "detail": "",
        "size": "0.0 B",
        "ignored_size": "0.0 B",
        "free_space": "223.5 GB"
    },
    "GoogleDrive": {
        "backups": 0,
        "retained": 0,
        "deletable": 0,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": null,
        "max": 4,
        "enabled": false,
        "icon": "google-drive",
        "ignored": 0,
        "detail": "",
        "size": "0.0 B",
        "ignored_size": "0.0 B"
    }
}
 ```
 ###### Config:
 ```
 {}
 ```
 ###### Addon Logs:
 ```
 10-03 00:53:03 ERROR [backup.model.coordinator] The supervisor is rejecting requests from the addon.  Please visit the web-UI for guidance
10-03 00:53:03 INFO [backup.model.coordinator] I'll try again in 5(ish) minutes
10-03 00:55:21 ERROR [backup.ha.haupdater] Trouble updating Home Assistant sensors.
10-03 00:58:23 DEBUG [backup.model.syncer] Sync requested by Coordinator
10-03 00:58:23 INFO [backup.model.coordinator] Syncing Backups
10-03 00:58:23 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/self/info
10-03 00:58:23 DEBUG [backup.ha.hasource] Failed to connect to supervisor
10-03 00:58:23 DEBUG [backup.ha.hasource] 
  addon/backup/ha/harequests.py:33 (wrap_and_call)
  addon/backup/ha/harequests.py:250 (_getHassioData)
  addon/backup/ha/harequests.py:208 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1004 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('http://supervisor/addons/self/info')
Whose handling caused:
  addon/backup/ha/hasource.py:393 (_refreshInfo)
  addon/backup/ha/harequests.py:33 (wrap_and_call)
  addon/backup/ha/harequests.py:138 (selfInfo)
  addon/backup/ha/harequests.py:33 (wrap_and_call)
  addon/backup/ha/harequests.py:142 (getAddonInfo)
  addon/backup/ha/harequests.py:40 (wrap_and_call)
backup.exceptions.exceptions.SupervisorPermissionError

10-03 00:58:23 ERROR [backup.model.coordinator] The supervisor is rejecting requests from the addon.  Please visit the web-UI for guidance
10-03 00:58:23 INFO [backup.model.coordinator] I'll try again in 10(ish) minutes
10-03 00:58:36 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/self/info
10-03 00:58:36 DEBUG [backup.ha.hasource] Failed to connect to supervisor
10-03 00:58:36 DEBUG [backup.ha.hasource] 
  addon/backup/ha/harequests.py:33 (wrap_and_call)
  addon/backup/ha/harequests.py:250 (_getHassioData)
  addon/backup/ha/harequests.py:208 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1004 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('http://supervisor/addons/self/info')
Whose handling caused:
  addon/backup/ha/hasource.py:393 (_refreshInfo)
  addon/backup/ha/harequests.py:33 (wrap_and_call)
  addon/backup/ha/harequests.py:138 (selfInfo)
  addon/backup/ha/harequests.py:33 (wrap_and_call)
  addon/backup/ha/harequests.py:142 (getAddonInfo)
  addon/backup/ha/harequests.py:40 (wrap_and_call)
backup.exceptions.exceptions.SupervisorPermissionError

10-03 00:58:36 ERROR [backup.ui.uiserver] Error serving POST http://powersofwar.duckdns.org:8123/getconfig
10-03 00:58:36 ERROR [backup.ui.uiserver] 
  addon/backup/ha/harequests.py:33 (wrap_and_call)
  addon/backup/ha/harequests.py:250 (_getHassioData)
  addon/backup/ha/harequests.py:208 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1004 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('http://supervisor/addons/self/info')
Whose handling caused:
  addon/backup/ui/uiserver.py:762 (error_middleware)
  addon/backup/ui/uiserver.py:433 (getconfig)
  addon/backup/ha/hasource.py:389 (refresh)
  addon/backup/ha/hasource.py:428 (_refreshInfo)
  addon/backup/ha/hasource.py:393 (_refreshInfo)
  addon/backup/ha/harequests.py:33 (wrap_and_call)
  addon/backup/ha/harequests.py:138 (selfInfo)
  addon/backup/ha/harequests.py:33 (wrap_and_call)
  addon/backup/ha/harequests.py:142 (getAddonInfo)
  addon/backup/ha/harequests.py:40 (wrap_and_call)
backup.exceptions.exceptions.SupervisorPermissionError

10-03 00:58:36 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/self/info
10-03 00:58:36 DEBUG [backup.ha.hasource] Failed to connect to supervisor
10-03 00:58:36 DEBUG [backup.ha.hasource] 
  addon/backup/ha/harequests.py:33 (wrap_and_call)
  addon/backup/ha/harequests.py:250 (_getHassioData)
  addon/backup/ha/harequests.py:208 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1004 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('http://supervisor/addons/self/info')
Whose handling caused:
  addon/backup/ha/hasource.py:393 (_refreshInfo)
  addon/backup/ha/harequests.py:33 (wrap_and_call)
  addon/backup/ha/harequests.py:138 (selfInfo)
  addon/backup/ha/harequests.py:33 (wrap_and_call)
  addon/backup/ha/harequests.py:142 (getAddonInfo)
  addon/backup/ha/harequests.py:40 (wrap_and_call)
backup.exceptions.exceptions.SupervisorPermissionError

10-03 00:58:36 ERROR [backup.ui.uiserver] Error serving POST http://powersofwar.duckdns.org:8123/getconfig
10-03 00:58:36 ERROR [backup.ui.uiserver] 
  addon/backup/ha/harequests.py:33 (wrap_and_call)
  addon/backup/ha/harequests.py:250 (_getHassioData)
  addon/backup/ha/harequests.py:208 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1004 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('http://supervisor/addons/self/info')
Whose handling caused:
  addon/backup/ui/uiserver.py:762 (error_middleware)
  addon/backup/ui/uiserver.py:433 (getconfig)
  addon/backup/ha/hasource.py:389 (refresh)
  addon/backup/ha/hasource.py:428 (_refreshInfo)
  addon/backup/ha/hasource.py:393 (_refreshInfo)
  addon/backup/ha/harequests.py:33 (wrap_and_call)
  addon/backup/ha/harequests.py:138 (selfInfo)
  addon/backup/ha/harequests.py:33 (wrap_and_call)
  addon/backup/ha/harequests.py:142 (getAddonInfo)
  addon/backup/ha/harequests.py:40 (wrap_and_call)
backup.exceptions.exceptions.SupervisorPermissionError

10-03 01:00:31 ERROR [backup.ha.haupdater] Trouble updating Home Assistant sensors.
10-03 01:05:41 ERROR [backup.ha.haupdater] Trouble updating Home Assistant sensors.
10-03 01:09:03 DEBUG [backup.model.syncer] Sync requested by Coordinator
10-03 01:09:03 INFO [backup.model.coordinator] Syncing Backups
10-03 01:09:03 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/self/info
10-03 01:09:03 DEBUG [backup.ha.hasource] Failed to connect to supervisor
10-03 01:09:03 DEBUG [backup.ha.hasource] 
  addon/backup/ha/harequests.py:33 (wrap_and_call)
  addon/backup/ha/harequests.py:250 (_getHassioData)
  addon/backup/ha/harequests.py:208 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1004 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('http://supervisor/addons/self/info')
Whose handling caused:
  addon/backup/ha/hasource.py:393 (_refreshInfo)
  addon/backup/ha/harequests.py:33 (wrap_and_call)
  addon/backup/ha/harequests.py:138 (selfInfo)
  addon/backup/ha/harequests.py:33 (wrap_and_call)
  addon/backup/ha/harequests.py:142 (getAddonInfo)
  addon/backup/ha/harequests.py:40 (wrap_and_call)
backup.exceptions.exceptions.SupervisorPermissionError

10-03 01:09:03 ERROR [backup.model.coordinator] The supervisor is rejecting requests from the addon.  Please visit the web-UI for guidance
10-03 01:09:03 INFO [backup.model.coordinator] I'll try again in 21(ish) minutes
10-03 01:10:51 ERROR [backup.ha.haupdater] Trouble updating Home Assistant sensors.
 ```
 ###### Supervisor Logs:
 ```
 
  addon/backup/ha/harequests.py:33 (wrap_and_call)
  addon/backup/ha/harequests.py:196 (getSuperLogs)
  /site-packages/aiohttp/client_reqrep.py:1004 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('http://supervisor/supervisor/logs')
Whose handling caused:
  addon/backup/debugworker.py:162 (buildBugReportData)
  addon/backup/ha/harequests.py:40 (wrap_and_call)
backup.exceptions.exceptions.SupervisorPermissionError

 ```
 ###### Home Assistant Core Logs:
 ```
 
  addon/backup/ha/harequests.py:33 (wrap_and_call)
  addon/backup/ha/harequests.py:203 (getCoreLogs)
  /site-packages/aiohttp/client_reqrep.py:1004 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('http://supervisor/core/logs')
Whose handling caused:
  addon/backup/debugworker.py:166 (buildBugReportData)
  addon/backup/ha/harequests.py:40 (wrap_and_call)
backup.exceptions.exceptions.SupervisorPermissionError

 ```
