### ISSUE TITLE
Feature Request - Compression

### ISSUE THREAD

**Issue by willvincent** [sabeechen/hassio-google-drive-backup#479]
Looking at google drive, I see that my backups are stored as a tar file. It'd be nice if they were compressed with gzip, bzip, etc so that the used space on google drive was less. Presently my backups are coming in around 5gb, and without paying for increased google drive storage I'm pretty much limited to a single backup.

**Comment by willvincent** [comment]
Edit: I realize most of the size of my backups is from frigate - so excluding the media directory resolves that issue, but still compression would be good. 👍

**Comment by sabeechen** [comment]
Backups are actually compressed.  If you look inside the tar file, you'll see that each folder and addon is inside its own ```.tag.gz```, a gzip compressed tar.  It might seem kind of silly to put compressed tar files inside an uncompressed tar, but the supervisor has its reasons and you are still getting the space saving benefits of the compression.  Only the backup's metdata file (usually backup.json or snapshot.json) is truly uncompressed, and it is rarely more than a few kB in size.

Regardless this addon doesn't actually create the backup files, it just asks Home Assistants supervisor to create them at the right time and then handles uploading them to Google Drive, deleting on a schedule, etc.  Any changes to the backups format would need to be made in the [supervisor](https://github.com/home-assistant/supervisor).
