### ISSUE TITLE
Backblaze?

### ISSUE THREAD

**Issue by reesericci** [sabeechen/hassio-google-drive-backup#484]
It would be really cool if this addon supported the much cheaper Backblaze B2 Cloud storage. It has a REST api and is also s3 compatible. The main selling point is that it is wayyy cheaper than Google Drive so I like to store my backups there.

--reese

**Comment by sabeechen** [comment]
https://github.com/sabeechen/hassio-google-drive-backup#will-this-ever-upload-to-dropboxondriveftpsmbmyfavoriteprotocol
I'd like to support a bunch of different storage options, but I simply don't have the free time to make it *good*.  Maybe someday, _maybe_.

**Comment by reesericci** [comment]
S3 would be huge though as it is supported by many providers, not just amazon/backblaze.

**Comment by reesericci** [comment]
I understand the limitations though.

**Comment by sabeechen** [comment]
Its at the top of my list if I'm able to support any of them :)

**Comment by reesericci** [comment]
no worries, great app *irr*egardless
