### ISSUE TITLE
Possible error in the latest version, when changing from "snapshot" to "backups"?

### ISSUE THREAD

**Issue by Gferretta** [sabeechen/hassio-google-drive-backup#485]
Hi
I have upgraded to the latest version, where he suggested to use "backup" instead of "snapshot", which I did.
But I keep getting this error in the Supervisor log.
Any ideas?
Should I make any other configuration changes to avoid this message?

![backup error](https://user-images.githubusercontent.com/65413059/134357694-998c91a4-aef8-4670-9966-b143ffd34e67.jpg)

**Comment by sabeechen** [comment]
These are warning HA is giving you about other addons using deprecated names in their configuration.  For example [here ](https://github.com/hassio-addons/addon-adguard-home/blob/main/adguard/config.json#L41 ) is the key in the AdGuard Addon's configuration that causes the warning.  They already have an [open issue for it](https://github.com/hassio-addons/addon-adguard-home/issues/249) in fact.  Fixing it will require the addon's maintainer to change it.

The warning is harmless for right now, and literally every HA user is seeing it.  There is a months long grace period where all addons' are supposed to change over their configs, but honestly it seems like kind of an oversight that this feature spits out warnings this soon when many addons in the community repo (installed by default) still haven't been updated.

**Comment by Gferretta** [comment]
I understand.
thanks for the clarification.
regards
