### ISSUE TITLE
Repository not added to HA

### ISSUE THREAD

**Issue by leszekzb** [sabeechen/hassio-google-drive-backup#486]
When adding repository i get an error:
expected a URL @ data['addons_repositories'][2]. Got ' https://github.com/sabeechen/hassio-google-drive-backup'

Same outcome on two different systems with the latest two core versions:
Version | core-2021.9.6 - Installation Type | Home Assistant OS
Version | core-2021.9.6 - Installation Type | Home Assistant Supervised
Version | core-2021.9.7 - Installation Type | Home Assistant OS
Version | core-2021.9.7 - Installation Type | Home Assistant Supervised

**Comment by dacapla** [comment]
Same issue

**Comment by sabeechen** [comment]
- Is this showing up in the supervisor logs, Home Assistant logs, or a pop up dialog?
- Is there a file name or line number given in front of the error?
- What version of the supervisor are you running?

I've had issues from other users in the past where the Supervisor seems to cache some information it got from GitHub and refuses to refresh it.  Could I have you restart the host machine and see if adding the repository works?

**Comment by leszekzb** [comment]
With core 2021.9.7  The supervisor is 2021.09.6
Its in the popup when you try to add new repository.
There is no number or line given.

Today i just got a new error stating:  Invalid Add-on repository! 

Here is the entry from log;
21-09-29 17:57:05 ERROR (MainThread) [supervisor.store.git] Can't clone https://github.com/sabeechen/hassio-google-drive-backup' repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v --recursive --depth=1 --shallow-submodules https://github.com/sabeechen/hassio-google-drive-backup' /data/addons/git/40c5852e
  stderr: 'Cloning into '/data/addons/git/40c5852e'...
fatal: unable to access 'https://github.com/sabeechen/hassio-google-drive-backup'/': The requested URL returned error: 400

**Comment by sabeechen** [comment]
I think you might be adding an extra ```'``` (single quotation mark) at the end of the repository url

**Comment by leszekzb** [comment]
correct, that entry to the log might have had extra quote in the url. 

I'm still unable to get the repository loaded with the url copied from the instructions.

**Comment by neldonado** [comment]
I am having a similar issue. I added the repository URL from the instructions, it spins for a few seconds and then nothing shows up. I don't see anything in my logs about it either.

**Comment by michaudjp** [comment]
Similar issue with different flavor. Running Version core-2021.10.4 Version supervisor-2021.10.0 , added repo, I see it has been added but no icon of Google Drive add-on.

Tried core reboot, deleting/install repo again.

21-10-15 21:26:45 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/sabeechen/hassio-google-drive-backup repository
21-10-15 21:26:46 INFO (MainThread) [supervisor.store] Loading add-ons from store: 66 all - 1 new - 0 remove
21-10-15 21:26:46 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
21-10-15 21:26:47 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-10-15 21:26:57 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
21-10-15 21:26:57 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt repository
21-10-15 21:26:57 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
21-10-15 21:26:57 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository


Is there a command line I could use to install add-on?

**Comment by ivoryman50** [comment]
even thought the repository is added, i'm not seeing the add-on to install.  i have restarted the whole system as well as the supervisor service.  the supervisor system logs seem to recognize it:

21-11-18 23:46:31 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/sabeechen/hassio-google-drive-backup repository
21-11-18 23:46:37 INFO (MainThread) [supervisor.store] Loading add-ons from store: 63 all - 1 new - 0 remove

i'm running:
core-2021.11.4
supervisor-2021.10.8
Home Assistant OS 6.6

i saw that michaudjp looks to be running on a beta version for supervisor-2021.10.0, but i'd prefer to stay on stable releases.

any thoughts?

**Comment by ivoryman50** [comment]
> 
> 
> even thought the repository is added, i'm not seeing the add-on to install. i have restarted the whole system as well as the supervisor service. the supervisor system logs seem to recognize it:
> 
> 21-11-18 23:46:31 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/sabeechen/hassio-google-drive-backup repository 21-11-18 23:46:37 INFO (MainThread) [supervisor.store] Loading add-ons from store: 63 all - 1 new - 0 remove
> 
> i'm running: core-2021.11.4 supervisor-2021.10.8 Home Assistant OS 6.6
> 
> i saw that michaudjp looks to be running on a beta version for supervisor-2021.10.0, but i'd prefer to stay on stable releases.
> 
> any thoughts?

for anyone that may be having the same issue, it appears that my https setup wasn't completely set up right.  i was seeing some connection refused logs.  so, make sure your traffic is configured properly.

**Comment by hellad** [comment]
Same problem on fresh installation of supervisor-2022.01.1 and core-2022.2.9. 
It's on Raspberry Pi3 with 64-bit Linux raspberrypi 5.10.92-v8+ #1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022 aarch64 GNU/Linux.

despite the successful addition of repository the add-on does not appear at the bottom of list and can't be found in search.

There are no any error messages in log.

**Comment by richard-scott** [comment]
I've had similar issues and created a /root/.git-credentials file on the Docker host running HA. I put a Personal Access Token in there and now things are better. I had other devices on my network that was hammering Github and this rate-limited my setup.
