### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BrunoCunha1983** [sabeechen/hassio-google-drive-backup#488]
An unexpected error occurred: [Errno 32] Broken pipe

arrow_drop_down View Error Details

  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:204 (sync)
  addon/backup/drive/drivesource.py:179 (save)
  addon/backup/drive/driverequests.py:280 (create)
  addon/backup/drive/driverequests.py:349 (retryRequest)
  addon/backup/creds/driverequester.py:30 (request)
  addon/backup/tracing_session.py:35 (_request)
  /site-packages/aiohttp/client.py:544 (_request)
  /site-packages/aiohttp/client_reqrep.py:890 (start)
  /site-packages/aiohttp/streams.py:604 (read)
aiohttp.client_exceptions.ClientOSError: [Errno 32] Broken pipe

**Comment by sabeechen** [comment]
I'm closing this for now, but please let me know or reopen the issue if you think there is something else you think I can help with.
