### ISSUE TITLE
Non-unique sensors left behind when moving from snapshots to backups

### ISSUE THREAD

**Issue by creeve4** [sabeechen/hassio-google-drive-backup#491]
In the move from the "snapshot" naming to "backup" several sensors were left behind and cannot be removed because they do not have a unique ID and are read-only:

binary_sensor.snapshots_stale
sensor.snapshot_backup

**Comment by creeve4** [comment]
Please ignore this. I had not updated HASS.

**Comment by sabeechen** [comment]
To anyone else reading this, the old sensors go away the next time you restart Home Assistant.
