### ISSUE TITLE
onedrive backup

### ISSUE THREAD

**Issue by TobiasKoller** [sabeechen/hassio-google-drive-backup#494]
my complete environment is based on microsoft and office365. 
Could you implement a function to backup the files in onedrive, too?

**Comment by jamesmyatt** [comment]
If you replace the interface with google drive with an [fsspec](https://filesystem-spec.readthedocs.io/en/latest/?badge=latest)-based one (e.g. https://github.com/fsspec/gdrivefs), then it should be much easier to add support for other file-store backends.
