### ISSUE TITLE
[Enhancement] Secondary backup upload routine (i.e. for database only)

### ISSUE THREAD

**Issue by Ndrinta** [sabeechen/hassio-google-drive-backup#496]
Hi all,

Today I decided I want to extend my `purge_keep_days` to something like 1/2 months (or even more).
I then thought about the consequential increase of the database size and immediately after at the implications of that choice with this add-on.

In the past year or so I always backed up everything (database included) and having a `purge_keep_days` of 21 days, the total backup size was ~2GB, not allowing me to keep more than 8/9 backups. I always thought I wanted to keep more backups but I was pretty happy with more than 5, especially considering I have the Generational Backups option set to go back a few weeks.

![image](https://user-images.githubusercontent.com/4704172/135596135-6c4e6db4-6cc0-4710-ac4b-771e5747a1a2.png)

Now, with an inevitable increase in the size of the database I won't be able to keep all these backups in 15GB anymore but I realized (in ideal conditions) I don't need to have multiple copies of the "same" database, but only the most recent one (or at least not more then 2/3 just in case one gets corrupted).

I then found out I could move my database in a separate folder (i.e. /share) and exclude it from the backup (using the "Partial Backups" options), this, of course, reduced the size of the backup to a mere 5MB (and it's great!) but I will now have to _manually_ (🤮) backup my database somewhere else every day if I want to keep a safe copy of it.

**But wait a minute: I can store hundreds of partial backups - with everything but the database - and maybe 2/3 copies of the database only, in a 15GB only Google Drive.**

15GB - ( 5MB * 100 partial backups ) = 14.5GB left for the "database only backups".

This would be amazing I think, **having a secondary routine to upload another partial backup on a different schedule**.
Don't you agree?

PS:
If there is a better solution, please do let me know. Even an additional automated local backup solution (of that folder/db) would be great for the time being.

Thanks all for listening, I hope I didn't make anyone upset 😄

**Comment by catalinbordan** [comment]
I have the same idea. Did you found a solution? Could we use a fork for the second back-up?

**Comment by rikmueller** [comment]
I would also appreciate this feature for a similar purpose

**Comment by jack5mikemotown** [comment]
A workaround I found for this is to add the repository to add-ons twice, once with and once without a backslash at the end
`https://github.com/sabeechen/hassio-google-drive-backup`
`https://github.com/sabeechen/hassio-google-drive-backup/`

**Comment by sabeechen** [comment]
Heh, I didn't knwo you could do that trick with the slash.  I won't do anything to prevent it but its likely in the future changes in Home Assistant works could cause those repos to get de-duplicated, just an FYI if you run into problems later.

I've answered my stance on the "multiple backup routines" question a few times, so I'll just link [this response here ](https://github.com/sabeechen/hassio-google-drive-backup/issues/405#issuecomment-850919079) and add it to the FAQ.
