### ISSUE TITLE
max_backups_in_google_drive affects all backups thus deleting important core backups

### ISSUE THREAD

**Issue by webdados** [sabeechen/hassio-google-drive-backup#498]
Let's say you configure max_backups_in_google_drive to "2". If you have a core (important) backup on Google Drive and you then update 2 or 3 small addons, those addons backups will also be sent to Google Drive and the core one will be deleted.

I suggest that this setting is per type of backup and not global.

**Comment by thomas-svrts** [comment]
yes, I had the same. 
After updating several addons I have now 5 partials backups and no full backup or backup of my core anymore :-O

**Comment by sabeechen** [comment]
I'm always trying to balance functionality of the addon with how difficult it is to configure and how time consuming it is to maintain.  Generally with this addon I try to provide easier configuration, and therefore less customization.  The downside of that is that often very specific use cases, perhaps like yours, are either difficult or impossible.

The addon has a few features you might not be aware of:
- "Ignore upgrade backups" causes the addon to "ignore" (ie not copy to Google Drive) any backups with only one thing in it, which is what the "upgrade" backups are.
- "Ignore other backups" causes it to ignore any backup the addon didn't itself create.
- "Delete ignored backups" (just added today in v0.106.1) causes it to automatically delete any of the "ignored" backups after a configurable age.

This won't accomplish what you're asking for, but it does give a path to doing something "reasonable" with with the backups that get created automatically after upgrades.  In particular you can keep them locally for a while, then delete them without interrupting the normal backup schedule.  For the time being, this is the only workflow I'm willing to support.

**Comment by webdados** [comment]
> The downside of that is that often very specific use cases, perhaps like yours, are either difficult or impossible.

This is NOT a very specific use case.
I bet 99% of Home Assistant users have add-ons installed.

**Comment by sabeechen** [comment]
The specificity of your use case is that you want to have a different schedule for each type of backup.  I would like to have this feature for myself and find a way to make it easy to use for new users, but there is only so much I'm able to support for free in my spare time.
