### ISSUE TITLE
[Feature Request] Set a time for Backup

### ISSUE THREAD

**Issue by Obicom** [sabeechen/hassio-google-drive-backup#5]
Would be great if I could set a specific time (e.g. every night at 4 o'clock) for the backup.

**Comment by sabeechen** [comment]
I'll intend to add this soon, though I've got some bugs to work through first.

**Comment by Obicom** [comment]
Sounds good but when is the normal "backup" time? Sometimes I have a new backup after 24h next time after 6h ... can't find the "rythem" ...

**Comment by sabeechen** [comment]
It should be 24 hrs after the most recent backup, or 1hr after the add-on starts if there are no backups.

**Comment by Obicom** [comment]
as you can see in my case your toll did it two times per day ....

![image](https://user-images.githubusercontent.com/25134482/55285872-3d497400-5394-11e9-88b8-642e38d3c1d3.png)

**Comment by sabeechen** [comment]
I've added the time-of-day config option to a release I just made (v0.52), which also fixes a ton of issues that I strongly suspect are causing the more-than-daily backups you're seeing.
You can see instructions for it in the [FAQ](https://github.com/sabeechen/hassio-google-drive-backup#configuration-options).
If you still see problems with the latest release, please re-open the this issue and I'll take another crack at it.
