### ISSUE TITLE
Ask for password twice?

### ISSUE THREAD

**Issue by PieBru** [sabeechen/hassio-google-drive-backup#50]
Hi, I like very much your addon, it's simply great.
How about asking twice for the password in the UI settings?
As you say "an erroneous comma makes you unable to turn on any of the lights in your house".
Cheers,
Piero

**Comment by sabeechen** [comment]
Seems reasonable, I won't have it ready for the next release but I'll put in in after that.

**Comment by sabeechen** [comment]
Forgot to mention when I released it, but this is in the latest version (v0.97.3)
