### ISSUE TITLE
Cannot restore from backups

### ISSUE THREAD

**Issue by michaelblight** [sabeechen/hassio-google-drive-backup#504]
I selected the "download to Home Assistant" option, and after some time the progress message showed "NaN% (Beyond mortal comprehension) - (determining speed) - Started undefined" and progressed no further. I have 3 backups on Google Drive (but not locally), and all are doing the same thing. They are all about 1.9GB, and all got to at least 95% before showing the message.

I downloaded one to my PC and copied it to "/backup" using the samba addon, but Home Assistant couldn't see it for some reason. I did the same for another, but this worked, and am restoring from it as I type.

**Comment by sabeechen** [comment]
I'm closing this issue for now, but please feel free to re-open it if you think there is more I can help with.
