### ISSUE TITLE
Use Device Auth instead of MITM user access tokens

### ISSUE THREAD

**Issue by colemickens** [sabeechen/hassio-google-drive-backup#506]
Hi. I sort of understand why the OAuth flow goes through your server, but it's not necessary, even to achieve UX for users without public-facing servers.

https://developers.google.com/identity/protocols/oauth2/limited-input-device#allowedscopes

This grant-type flow is meant for this scenario, and specifically supports the Drive API scope that you need.

**Comment by colemickens** [comment]
more info: https://datatracker.ietf.org/doc/html/draft-ietf-oauth-device-flow

**Comment by colemickens** [comment]
Oh wow, this answer is far more than I expected, though I should've known better given the detail and polish everywhere else in this addon.

I'm more than convinced, and I'm sad I hadn't found the LOCAL_AUTH document, that again is more than I'd hoped for.

Thanks for the awesome detailed answer and the great extension - I'm about to go get my family adopting it :)

**Comment by colemickens** [comment]
It just feels like a gap in OAuth that there isn't a better way to handle this sort of scenario. I guess it is "well-supported" with self-provisioned applications, but it does feel like there's could be a better middle-ground for open-source self-hosted apps.

Anyway, thanks again, you've clearly put a lot of love and thought into this extension!

**Comment by sabeechen** [comment]
I agree.  To make things weirder, in some of their documentation Google doesn't really treat the client_secret as a secret and implies you should include it in client-side javascript.  I'm not totally sure if I'm just spinning my wheels with all these authorization servers for no real security gain.

I should probably make the local_auth document more visible in the instructions, right now you just have to notice the link at the bottom of the authentication screen.  I just worry about bombarding new users with too many choices and options when they're getting started.
