### ISSUE TITLE
Can I run this via docker instead of the addon store?

### ISSUE THREAD

**Issue by Talor-A** [sabeechen/hassio-google-drive-backup#516]
Hi, I'm using home assistant container with docker. since I don't have access to the supervisor / addon store, is there a way I can use this repo via docker? I see a dockerfile but don't see any documentation or other issues covering this. Just want to see if it's possible

**Comment by sabeechen** [comment]
The addon requires the supervisor to run.  The supervisor is what actually creates/restores backups and also manages the docker environment the addon requires to run.  The addon only asks for backups to be made and manages the files between Google Drive/Supervisor.  

IMHO Home Assistant is (regrettably) pretty limited without the supervisor, and the way the supervisor demands control over the operating system is frustrating.  Regardless I'd recommend jumping through the hoops to get a supervised install going if you depend on HA for anything serious.

**Comment by Talor-A** [comment]
I was not aware the supervisor was so integrated to the whole process, that makes sense. Thanks for the explanation @sabeechen !
