### ISSUE TITLE
Web UI not loading on SSL

### ISSUE THREAD

**Issue by andreaconfa** [sabeechen/hassio-google-drive-backup#52]
Hi all,

Problem 1: when i start the plugin i get this error and then the plugin continue the start-up
`05-15 22:51:53 INFO Loading config from /data/options.json
/usr/lib/python3.6/site-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access /data/credentials.dat: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))`

Problem 2: If i enable SSL on hassio and i try to access the WebUi i get an ERR_CONNECTION_TIMED_OUT from the browser, even if the ssl is enabled or disabled also in the plugin

Please help me :)

**Comment by sabeechen** [comment]
The warning is just from an underlying library, you shouldn't see it after you've connected it with Google Drive.  If you're still seeing after you connect it with Drive and restart the add-on, that could indicate a problem.
When you're unable to connect to the WebUI, do you see anything in the add-on or Hassio logs?

**Comment by sabeechen** [comment]
If your connecting over ssl, make sure you're hitting the web ui over HTTPS:\\, some browsers can timeout out if they're trying to interpret HTTPS as HTTP or vice versa.

**Comment by andreaconfa** [comment]
thanks, my mistake... ssl solved. error also. thanks

**Comment by sabeechen** [comment]
glad I could help
