### ISSUE TITLE
Cannot add repo

### ISSUE THREAD

**Issue by The-IKIQ** [sabeechen/hassio-google-drive-backup#523]
21-11-20 20:11:36 ERROR (MainThread) [supervisor.store.git] Can't clone https://github.com/sabeechen/hassio-google-drive-backup repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v --recursive --depth=1 --shallow-submodules https://github.com/sabeechen/hassio-google-drive-backup /data/addons/git/cebe7a76
  stderr: 'Cloning into '/data/addons/git/cebe7a76'...
POST git-upload-pack (175 bytes)
POST git-upload-pack (244 bytes)
fatal: unable to open /data/addons/git/cebe7a76/.git/objects/pack/tmp_pack_Suhxuw: No such file or directory
fatal: fetch-pack: invalid index-pack output
'.

**Comment by sabeechen** [comment]
Sorry this took me so long to get back to you on, I've had to balance priorities lately.
First some context:  Home Assistant uses git to download this addon's repository when you add it to the addon store.  The error you're seeing is from the git command line tools.  I've had [users report this in the past](https://github.com/sabeechen/hassio-google-drive-backup/issues?q=is%3Aissue+%22Can%27t+clone%22+), and we've never been able to get to the bottom of why it happens.  It looks like its either a bug in Git or a problem in how Home Assistant uses Git.  There isn't currently anything I can do about it as an addon developer. 

Others have had success trying the following:
- Restarting the machine running Home Assistant (I suspect this clears out some temporary files that are jamming thing up)
- Attempting to add the repo over and over.
