### ISSUE TITLE
Repostitory structure for v0.105.1 is not compliant

### ISSUE THREAD

**Issue by rainman369** [sabeechen/hassio-google-drive-backup#524]
Error received when trying to add custom repo through HACS.

Home Assistant docker with HACS installed.

**Comment by sabeechen** [comment]
This isn't a HACS repo, its a Home Assistant Supervisor Addon.  You'll need the supervisor to install it, please see the [installation instructions](https://github.com/sabeechen/hassio-google-drive-backup#detailed-install-instructions).

**Comment by rainman369** [comment]
Thanks!
