### ISSUE TITLE
bad 404 on upload

### ISSUE THREAD

**Issue by waynerigley** [sabeechen/hassio-google-drive-backup#525]
Google drive has my backup and i had a home assistant issue so created a new VM on proxmox and now trying to upload the back back in but keep getting a 404 error.. i removed the influx .tar out of the folder and re tar'ed it and tried to upl;oad it again without any luck.. is there a workaround for this ? I'm STUCK and my heating is going crazy here ! l
![bad404](https://user-images.githubusercontent.com/44474035/143481813-80a20880-77db-43fe-b002-1db61e691bac.png)
ol

**Comment by sabeechen** [comment]
That uploader can be pretty difficult sometimes.  What I'd do is:

- Continue with the installation, fill in whatever it wants to make a barebones HA install.
- Install this addon again and connect it with Google Drive so you can see your backups
- On one of your backups click it and then click "Load into Home Assistant", wait for it to finish

At this point you either have a backup or ready to be restored or you should be able to see in the Supervisor logs ("Supervisor" > "System" > "Logs") an error message giving some clue about what might be wrong.

If that still  doesn't work, you can also use the Samba Addon to upload backup tar files directly into the backup folder.

**Comment by waynerigley** [comment]
so the issue was... when i download it from google the file is corrupt so that was the reason.. i tried to load it via google on a basic platform and also from the samba and ended up getting a backup from 4 months ago and that worked.. but now the work starts as i have to update from the last 4 months ! lol

**Comment by sabeechen** [comment]
I'm glad you were able to get it to work.  I wish getting backups onto a fresh install was easier.
