### ISSUE TITLE
deletion of all backups

### ISSUE THREAD

**Issue by s0ftice** [sabeechen/hassio-google-drive-backup#526]
Hi there, I'm using the add-on for local backups to my file system (mainly due to the awesome fine-tuneable retention settings).
As I ran out of disk space, I changed the retention policy, however this was not applied (in terms of deleting older backups which were no longer part of the retention plan) after the last automated backup over night.

As clicking hundreds of backups manually in the UI to delete them (3-4 clicks per backup required), I decided to manually remove the .tar files in the backup directory to make space. However, the add-on still shows all the older backups.

I found metadata in data_cache.json, however removing this file doesn't help, it's re-created after restarting the add-on.
It seems more backup metadata is in home-assistant_v2.db, but before tinkering with that, I wanted to quickly ask if there's an easy way to remove all/certain backup metadata?

Thanks

**Comment by sabeechen** [comment]
After deleting manually from the /backup directory you might need to click the refresh icon in the top right of the "Supervisor" > "Backups" page in Home Assistant, sometimes Home Assistant doesn't notice.

If you're still seeing "ghost" backups after that could you go to the Add web-ui and
- Click "Actions" -> "Sync Now" 
- Click "Actions" -> "report a bug"
- Paste the output here

**Comment by s0ftice** [comment]
Thanks for your answer. It actually went away by itself. Maybe it was a browser cache issue...

Great add-on!!
Cheers
