### ISSUE TITLE
Critical bug: when trying to restore backups on new install old backups get deleted without prompt

### ISSUE THREAD

**Issue by capstan1** [sabeechen/hassio-google-drive-backup#53]
### So, what happened:
I had your Add-On setup with generational backup and up to 30 backups. Now my Hass.io died on me and (as for the last time this happened) I went the new and easy route using your addon to restore.
So I installed your addon and connected it to my drive. Thing is: because the standard settings are `4 backups in Google Drive` it just deleted all my backups except for the last 4.

This happened without any prompt. Just out of nowhere, while waiting for my most recent backup to download it deleted the snapshots. They aren't present in Google Drives recycle bin.

(I even thought a second that this could lead to misbehaviour but I didn't expect it to just delete files without asking.)

### Possible solutions
So, after a new setup there should be some kind of prompt "I found various Backups in your Drive. The amount exceeds your current settings. Should I delete them?" If "no" is pressed it could ask again when accessing the frontend for the next time.
**Or another nice approach:** write the current settings in a file within the same Google Drive folder. After authenticating the Add-On it could look for this file first and prompt "I have found older settings with `this `content. Your current settings are `these`. Do you want to restore your old Add-On settings before going on?

-> I guess the two things eventually should be combined.

I think I didn't really loose any important data, but I did loose older snapshots which I wanted save in case of. Thats a thing that just shouldn't happen with an addon like this. 
Hope this doesn't sound too bitchy, english isn't my mothers tongue, I just want to express this bug is critical.

**Comment by sabeechen** [comment]
Yup I agree, this is an oversight.  I'm sorry you lost your older backups but glad you didn't lose the ones you needed now.   Someone would have to really pay attention to what the default setting mean at installation time (on the new instance) to avoid this and at that point they're probably more focused on just getting things running.

Saving the settings elsewhere might be a good feature, but that has a lot of corner cases I'd need to figure out.  What I'm thinking on the shorter term is:
Under "normal" circumstances, the add-on should only ever delete one snapshot at a time, right after when a new one is created.  If it ever looks like its going to delete 2 or more, it should stop and require confirmation.   This would also act as a safeguard against:
* Someone syncing on a fresh install (what happened to you)
* *Accidentally* changing the settings to something that unknowingly deletes your snapshot history
* Hassio reverting your add-on settings to default (it really does that sometimes)
* Restoring a snapshot that overwrites the add-on settings with ones that would delete more snapshots.

I'm hesitant to create something that intentionally "blocks" backups, but I think this should only ever happen after changing settings, installing, or restoring, which are times when the user is already interacting working with the add-on so hopefully it won't cause much disruption.  I'll also make it trigger a persistent notification in the HA UI indicating that the add-on needs attention.

**Comment by sabeechen** [comment]
I've added this functionality as described to the just released v0.97
