### ISSUE TITLE
Option to exclude database from backups

### ISSUE THREAD

**Issue by Heisenberg2980** [sabeechen/hassio-google-drive-backup#532]
Hi, I am not sure if this happens to everyone, but every time I need to restart a backup, the database is corrupted and I have to delete it (which is fine, not a big deal for me). 

My question is considering the database is the biggest file which contributes to the size of the HA backup file, could you add an option to the partial backup settings to exclude the database files (i.e. home-assistant_v2.db, home-assistant_v2.db-shm and home-assistant_v2.db-wal) from the backup? At the moment the partial backup just allows you to remove the whole config folder, but obviously this folder is important and shouldn´t be excluded from the backups

**Comment by sabeechen** [comment]
The addon [can only exclude the main folders](https://github.com/sabeechen/hassio-google-drive-backup#can-i-exclude-specific-sub-folders-from-my-backup) (config, ssl, share, media, etc), which is a restriction imposed by the HA supervisor that I can't work around.  I'd support it if I could.

What you can do to get the same effect is install something like the Maria DB addon (its the in the "official Addons" section of the add-on store), and then exclude that addon from backups.  Note that you'd then need to reinstall the MariaDB addon when you restore a snapshot.   This is how I handle it on my personal HA installation.

**Comment by Heisenberg2980** [comment]
Thank you, that workaround is brilliant!! (you might want to include it in the FAQ section as I am sure many people will have the same question)

**Comment by Heisenberg2980** [comment]
@sabeechen just a quick question about the workaround, when you restore a snapshot and MariaDB is not present in HA yet, is HA starting fine to let you install MariaDB?

**Comment by Heisenberg2980** [comment]
> The addon [can only exclude the main folders](https://github.com/sabeechen/hassio-google-drive-backup#can-i-exclude-specific-sub-folders-from-my-backup) (config, ssl, share, media, etc), which is a restriction imposed by the HA supervisor that I can't work around. I'd support it if I could.
> 
> What you can do to get the same effect is install something like the Maria DB addon (its the in the "official Addons" section of the add-on store), and then exclude that addon from backups. Note that you'd then need to reinstall the MariaDB addon when you restore a snapshot. This is how I handle it on my personal HA installation.

@sabeechen unfortunately I can answer my own question: I have tried to restore a partial backup that contained everything except the MariaDB add-on but Home Assistant have not been able to start in order for me to install MariaDB, so if you are doing this please be aware in case of an issue you might not be able to restore HA from a partial backup

**Comment by sabeechen** [comment]
Apologies, this slipped under my email's radar.

Not recently, but I've restored a partial backup that excludes MariaDB a few times in the past.  In my experience what happens is (1) The logs get spammed with database error messages and (2) Home Assistant buffers up writes to the database in memory and slowly runs out of memory until it crashes.  To get around this I've either:
(1) Installed the Maria DB addon right before restoring the partial backup
(2) Installed it right after restoring before it runs out of memory (risky).

Obviously this isn't a perfect solution, but it does work.  Lately instead I've been just keeping my database smaller with an aggressive 24 hour sensor history so I can include everything in a backup.
