### ISSUE TITLE
Download to HA loops..

### ISSUE THREAD

**Issue by korsmann** [sabeechen/hassio-google-drive-backup#539]
Trying to upload a snapshot from Google Drive to HA it never get finished.
It upload for 1 minute exactly, the restarts, never getting past 26%...

![image](https://user-images.githubusercontent.com/24713270/150118117-6fddf768-5680-43d5-bd46-5123ce779586.png)

**Comment by korsmann** [comment]
And stops...

![image](https://user-images.githubusercontent.com/24713270/150121565-b61d1967-109e-4281-842f-5308eb44869a.png)

**Comment by korsmann** [comment]
Never mind, works as expected when I got to my local PC and network.
Whilst trying remotely via Nabucasa it did not work.

**Comment by sabeechen** [comment]
I've never tried to load a backup like this through the Nabucasa remote endpoint and I see the exact same thing as you.  It works fine if I do it locally but seems to loops indefinitely through Nabucasa.  I'm going to leave this open to remind me to investigate, I haven't had a legitimate bug in a while!

**Comment by sabeechen** [comment]
It looks like Nabucasa's remote-ui proxy has timeouts all over the place.  I think [this one](https://github.com/NabuCasa/snitun/blob/d67eacf349c602bdc857f0ef5ec6052fcd48bab7/snitun/client/client_peer.py#L20) is what causes the upload to fail.

I've just made a new release, v0.106.1, which works around this.  Please let me know if you still run into trouble with the new version.
