### ISSUE TITLE
How addon communicate with google drive?

### ISSUE THREAD

**Issue by fik236** [sabeechen/hassio-google-drive-backup#541]
Hello at first point I would like to thanks for this addon!
Everything works well.

But I have ask: how addon communicate with google drive? Does google disk mount its space to some folder with e.g. some fuse (at my linux desktop I use google-drive-ocamlfuse  for that)?
I have looked for mount point in my homeassistant filesystem, but I did not succeed.

I am asking for that, because I am thinking about copying e.g. some photos from my cameras into my google drive.
Is there any posibility to use your addon to do that?

Thank you a lot
Fik236

**Comment by sabeechen** [comment]
This addon is very tightly coupled around the idea of packaging the entire HA install into a single archive and uploading it to Google Drive, it doesn't have any functionality around syncing individual files from HA.

You might consider looking at [samccauley/addon-hassiogooglebackup ](https://github.com/samccauley/addon-hassiogooglebackup/), its no longer officially supported but from what I understand it still works and is a lot more flexible in terms of syncing individual files/folder into Google Drive.
