### ISSUE TITLE
Automation with Google drive backup

### ISSUE THREAD

**Issue by sharonoren1** [sabeechen/hassio-google-drive-backup#543]
Hi,

Can I do some automations with Google drive backup?
I thinking about sending telegram bot message when backup was not completed or canceled.

Best regards,
Oren

**Comment by sabeechen** [comment]
I typically recommend triggering off of the ```binary_sensor.backups_stale``` sensor that the addon publishes ([see here](https://github.com/sabeechen/hassio-google-drive-backup#mobile-notifications)).  It will turn on when backups are a few hours late to avoid publishing on temporary errors.

More complicated automation could be done using the data from ```sensor.backup_state```, ([see details](https://github.com/sabeechen/hassio-google-drive-backup/blob/master/hassio-google-drive-backup/BACKUP_AND_SNAPSHOT.md#backup-state-sensor-1)).

Is that what you're looking for?

**Comment by sharonoren1** [comment]
> I typically recommend triggering off of the `binary_sensor.backups_stale` sensor that the addon publishes ([see here](https://github.com/sabeechen/hassio-google-drive-backup#mobile-notifications)). It will turn on when backups are a few hours late to avoid publishing on temporary errors.
> 
> More complicated automation could be done using the data from `sensor.backup_state`, ([see details](https://github.com/sabeechen/hassio-google-drive-backup/blob/master/hassio-google-drive-backup/BACKUP_AND_SNAPSHOT.md#backup-state-sensor-1)).
> 
> Is that what you're looking for?

Hi Stephen,

Thanks for your answer.
I can't find "sensor.backup_state" at my HA. I have other called "sensor.snapshot_backup". It's the same?

Regards,
Oren

**Comment by sabeechen** [comment]
If you update the addon to the latest version (and click the dialog that comes up in the new WebUI about it) it'll get the new name, or you can just keep the old one.

**Comment by sharonoren1** [comment]
Thanks!
