### ISSUE TITLE
Google drive backup not in supervisor store?

### ISSUE THREAD

**Issue by Zetto12** [sabeechen/hassio-google-drive-backup#546]
I did a backup of my system because I've installed an SSD. Home Assistant Google Drive Backup wasn't working after restoring the instance so I thought I just remove it and install again. After uninstalling the app it still shows in my existing apps but I get this when I click on it. 
![image](https://user-images.githubusercontent.com/95339767/152960874-2bf8b33e-161b-4a4a-9fcd-acfa84815ec1.png)
I've tried to install it again from the supervisor store but it seems to be gone. Any idea what happened?
I'm running core-2022.2.2 & supervisor-2022.01.1
Cheers, Martin

**Comment by sabeechen** [comment]
Can you check what it says in the supervisor logs right after you get that message?  They're at <kbd>Configuration</kbd> > <kbd>Addon's Backups, & Supervisor</kbd> > <kbd>System</kbd>  in the Home Assistant UI.   Whatever is going wrong should show up in those logs.

**Comment by Zetto12** [comment]
The Add-on has disappeared now. Not sure what the issue was. It stayed in my add-ons for hours after uninstalling.

**Comment by sabeechen** [comment]
Its hard to say, it sounds like the install failed "part way" during your restore but didn't get cleaned up correctly.  In the past when people have had issues installing either restarting the supervisor or the machine its running on does the trick, but I was hoping the logs could give some insight into what went wrong.  Regardless I'm glad its working for you now.
