### ISSUE TITLE
"Pending" snapshot mouseover: I'm not able to click on the link.

### ISSUE THREAD

**Issue by PieBru** [sabeechen/hassio-google-drive-backup#55]
Hi,

The current snapshot started 2 hours ago and is still in progress, stuck at "Size: 0 B ". I tried with Firefox and Chromium (Arch Linux), with magnification ranging from 50% to 300%, but my elderly fingers aren't able to take advantage of the link :)

In these cases it would be nice to have an "Action" button choice "Cancel snapshot".
If the snapshot is too huge and it takes too long, it would be nice to have an "Action" button choice "Cancel upload" and/or "Don't upload / Keep local only" (see #54).

Thanks,
Piero

**Comment by sabeechen** [comment]
Heh, that link has been there almost since the first verison and I never noticed you can't click it!  Looks like the UI library I'm using doesn't make tooltips clickable.  I'll replace it with some more useful text text.

**Comment by sabeechen** [comment]
WRT canceling a pending snapshot, I'm limited by what Hassio will let me do.  Once a snapshot it started it doesn't expose a way to cancel it or see progress.  I'd be happy to implement support for that if Hassio every exposes that though.

**Comment by sabeechen** [comment]
I've updated the text in the latest version, 0.97
