### ISSUE TITLE
Delete Upgrade Backups after a given time

### ISSUE THREAD

**Issue by ElVit** [sabeechen/hassio-google-drive-backup#550]
The Supervisor may crate backups before an addon or the core will be updated. This is very useful in my opinion for a fast restore if something goes wrong. But I found out that these backups are not deleted by this addon if I enable the option "Ignore Upgrade Backups". I had around 100 of these backups and had to delete them manually 😩.

Is it possible add an option to delete all Upgrade Backups after a given time e.g. one week?

**Comment by sabeechen** [comment]
This seem like a good idea to me.  Let me think a little bit about the best way to implement it.
