### ISSUE TITLE
question mark in black circle on every backup tile

### ISSUE THREAD

**Issue by danb5** [sabeechen/hassio-google-drive-backup#551]
What does the small question mark in the black circle on every backup tile in the dashboard mean?

**Comment by sabeechen** [comment]
If you hover over it, it will describe what the text undeneath the title means.  For example if the backup's state is "Backed Up" then putting your mouse over the "?" will show the text "This backup has been uploaded to Google Drive".  Every state for the backup has its own description.

**Comment by danb5** [comment]
Thanks!
