### ISSUE TITLE
No me deja instalar Google Drive backup

### ISSUE THREAD

**Issue by Pablito1402** [sabeechen/hassio-google-drive-backup#554]
Hola buenas soy nuevo por aquí y llevo varios días que no soy capaz solucionar el error que me sale, cuando añado la URL para que me salga en la tienda de complementos me da error pero no sé cómo he conseguido que me aparezca en la tienda complemento lo que pasa que cuando le doy a instalar me da un error y no sé qué hacer 
![Uploading IMG_20220220_204213.jpg…]()

**Comment by sabeechen** [comment]
I'll help where I can, please be aware I'm using Google Translate to read your message so I apologize if I don't understand you clearly.  Sometimes Home Assistant has problems downloading the addon's information from Github and gets into a bad state.  Most people are able to solve the problem by restarting the host machine, so please try that first.  If it doesn't resolve your problem, please check the logs in the following place after attempting to add the addon:

<kbd>Configuration</kbd> > <kbd>Add-ons, Backups & Supervisor</kbd> > <kbd>System</kbd>

Please also note the image you attempted to include did not load, so I'm not sure what error message you're seeing.


Translation:
Te ayudaré en lo que pueda, ten en cuenta que estoy usando Google Translate para leer tu mensaje, así que te pido disculpas si no te entiendo claramente. A veces, Home Assistant tiene problemas para descargar la información del complemento de Github y entra en un mal estado. La mayoría de las personas pueden resolver el problema reiniciando la máquina host, así que pruébelo primero. Si no resuelve su problema, verifique los registros en el siguiente lugar después de intentar agregar el complemento: 

<kbd>Configuration</kbd> > <kbd>Add-ons, Backups & Supervisor</kbd> > <kbd>System</kbd>

Tenga en cuenta también que la imagen que intentó incluir no se cargó, por lo que no estoy seguro de qué mensaje de error está viendo.

**Comment by sabeechen** [comment]
I'm closing this issue for now, but please feel free to re-open it if you think there is some way I can help more.
