### ISSUE TITLE
error en addon en home assistant

### ISSUE THREAD

**Issue by brotwi** [sabeechen/hassio-google-drive-backup#555]
cuando inicia el addon el log da este error
[supervisor.docker.interface] Container addon_cebe7a76_hassio_google_drive_backup is not running

**Comment by brotwi** [comment]
solo el log de supervisor tiene informacion
al iniciar el addon inmediatamente se cae.

Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:120
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 17:57:20 (2 occurrences)
Last logged: 17:57:30

Failed to to call /addons/cebe7a76_hassio_google_drive_backup/stats - Container addon_cebe7a76_hassio_google_drive_backup is not running

22-02-22 17:57:05 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_cebe7a76_hassio_google_drive_backup application
22-02-22 17:57:10 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on sabeechen/hassio-google-drive-backup-aarch64 with version 0.105.2
22-02-22 17:57:20 ERROR (SyncWorker_1) [supervisor.docker.interface] Container addon_cebe7a76_hassio_google_drive_backup is not running
22-02-22 17:57:30 ERROR (SyncWorker_1) [supervisor.docker.interface] Container addon_cebe7a76_hassio_google_drive_backup is not running

**Comment by sabeechen** [comment]
Can you try completely uninstalling and reinstalling the addon?  Unfortunately there is nothing in that error message that suggest what might be causing the problem and I've never seen this issue before.  Something must be wrong with the environment that Home Assistant is setting up for the addon to run in.

¿Puede intentar desinstalar y reinstalar completamente el complemento? Desafortunadamente, no hay nada en ese mensaje de error que sugiera lo que podría estar causando el problema y nunca antes había visto este problema. Algo debe estar mal con el entorno que Home Assistant está configurando para que se ejecute el complemento.

**Comment by brotwi** [comment]
Esta funcionando!  lo reinstale, no habia mucha informacion del error, y tampoco habia nada que hubiese actualizado recientemente, solo dejo de funcionar. extraño no?

**Comment by sabeechen** [comment]
I'm glad re-installation worked.  Its unusual everything stopped working suddenly, but honestly not very surprising.  Home Assistant's Supervisor creates a docker environment that runs Home Assistant Core and the addons inside of docker containers, there are just a bunch of layers of automated virtualization.  A lot of things can go wrong in a lot of places.  Its usually works pretty well, but when something like this goes wrong it is often impractical to fully diagnose the problem.  I'm glad you were able to get it running again!

Me alegro de que la reinstalación haya funcionado. Es inusual que todo dejara de funcionar de repente, pero honestamente no es muy sorprendente. El Supervisor de Home Assistant crea un entorno docker que ejecuta Home Assistant Core y los complementos dentro de los contenedores docker, solo hay un montón de capas de virtualización automatizada. Muchas cosas pueden salir mal en muchos lugares. Por lo general, funciona bastante bien, pero cuando algo como esto sale mal, a menudo no es práctico diagnosticar completamente el problema. ¡Me alegro de que hayas podido ponerlo en marcha de nuevo!

**Comment by brotwi** [comment]
Muchas gracias a ti por el interes y la ayuda.
