### ISSUE TITLE
Unable to restore backups

### ISSUE THREAD

**Issue by CMDR-Sloma** [sabeechen/hassio-google-drive-backup#557]
Hi, 
For the reasons that are not very important, I had to flash my HA Blue with new image in order to restore  one of my backups.

Unfortunately, all of my daily backups are causing this:

`22-02-24 13:27:26 WARNING (MainThread) [supervisor.homeassistant.module] Can't restore Home Assistant Core config folder: not a gzip file
22-02-24 13:27:26 INFO (MainThread) [supervisor.backups.manager] Restoring e014452a folders
22-02-24 13:27:26 INFO (SyncWorker_2) [supervisor.backups.backup] Restore folder addons/local
22-02-24 13:27:26 WARNING (SyncWorker_2) [supervisor.backups.backup] Can't restore folder addons/local: not a gzip file
22-02-24 13:27:26 INFO (SyncWorker_6) [supervisor.backups.backup] Restore folder ssl
22-02-24 13:27:26 WARNING (SyncWorker_6) [supervisor.backups.backup] Can't restore folder ssl: not a gzip file
22-02-24 13:27:26 INFO (SyncWorker_0) [supervisor.backups.backup] Restore folder share
22-02-24 13:27:26 WARNING (SyncWorker_0) [supervisor.backups.backup] Can't restore folder share: not a gzip file
22-02-24 13:27:26 INFO (MainThread) [supervisor.backups.manager] Restoring e014452a Home Assistant Core
22-02-24 13:27:26 ERROR (MainThread) [supervisor.backups.manager] Restore e014452a error`

`Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/backups/manager.py", line 251, in _do_restore
    backup.restore_homeassistant()
  File "/usr/src/supervisor/supervisor/backups/backup.py", line 467, in restore_homeassistant
    self.sys_homeassistant.refresh_token = self._decrypt_data(
  File "/usr/src/supervisor/supervisor/backups/backup.py", line 212, in _decrypt_data
    data = padder.update(decrypt.update(b64decode(data))) + padder.finalize()
  File "/usr/local/lib/python3.9/site-packages/cryptography/hazmat/primitives/padding.py", line 159, in finalize
    result = _byte_unpadding_check(
  File "/usr/local/lib/python3.9/site-packages/cryptography/hazmat/primitives/padding.py", line 101, in _byte_unpadding_check
    raise ValueError("Invalid padding bytes.")
ValueError: Invalid padding bytes.`

Is there anything I can do to restore my HA?

**Comment by sabeechen** [comment]
Is it possible you used a password to create the snapshots but aren't providing one to the restore?  Or if you did use a password, but provided the wrong one when it was restored?  Home Assistant isn't always perfect about recognizing the difference between data corruption and using the wrong password.  Ive [seen this error before](https://github.com/sabeechen/hassio-google-drive-backup/issues/208) and that was the reason.

If you did not create the backup with a password the backup can be opened with normal archiving tools (7zip is known to work well), its just a tar file with other compressed tar files inside it.  The tar file contains one compressed tar file inside it for each folder or addon inside the backup.  Its possible to almost completely restore a snapshot just by copying files over.

If the backup is password protected, to the best of my knowledge it can only be read by Home Assistant.

**Comment by CMDR-Sloma** [comment]
I don't think so, because when I leave the password blank I get an error telling the password is incorrect, same as when I use an incorrect password. When provided correct password, I loose connection to HA for a min or two, and then I get this error.

**Comment by sabeechen** [comment]
Its a little more tricky, unfortunately.  Because of a quirk in how HA hashes passwords, ~10% of the time it will assume that an incorrect password is actually the correct one and attempt to restore the snapshot using it, producing one of a handful of opaque error messages when it unsuccessfully decrypts.

You can verify this yourself it you attempt to restore a snapshot using a variety of incorrect passwords (eg "wrongpassword1", "wrongpassword2",....).  9 out of 10 times it will tell you the password is incorrect, but 1/10 times it will attempt to restore the snapshot and fail with a cryptic error message.  It is bad math in the logic HA uses to hash password.

This puts a person in your situation in a difficult position, because you can't know for certain if the password you're using is incorrect or if the backup is corrupted for some other reason.  It's possible your backups were corrupted on your HD before they were uploaded to Google Drive.  HD corruption is rare and would be even more unlikely to happen to _all_ of your bakcups, but it is possible.

**Comment by CMDR-Sloma** [comment]
Shouldn't this be reported as an issue in HA then?

In the past I had issues with backups but that was on RPI and SD card.
Later I moved to proxmox on a nuc, again problems with unreliable backup
restoration. For the past year I have been using HA on Odroid N2+ (blue)
and here I am with the same problem.  If this is not Google Backup add-on
issue then maybe this should be closed. I see this is serious problem as it
affect crucial feature of HA.

**Comment by sabeechen** [comment]
It looks like some [recent changes](https://github.com/home-assistant/supervisor/commit/9104b287e5663f463735e55a255b2fce105bf7d8) to the backup format in the supervisor will make this issue irrelevant, so I think backups moving forward won't have this problem once it rolls out.
