### ISSUE TITLE
[0.97] minor GUI flaw

### ISSUE THREAD

**Issue by dhzl84** [sabeechen/hassio-google-drive-backup#56]
When not specifying an override IP for Google Drive, the heading overlaps the value field (4k screen, 150% scaling, Win 10):

![image](https://user-images.githubusercontent.com/5675570/57974972-47b1e280-79c1-11e9-9090-e69edf5c2d2b.png)

**Comment by sabeechen** [comment]
Fixed this in 0.97.1 (just released it)
