### ISSUE TITLE
Too Manu requests

### ISSUE THREAD

**Issue by aladin2000** [sabeechen/hassio-google-drive-backup#562]
Hi 
I  got that error 
How to fix it ?
03-01 03:04:59 ERROR [backup.drive.driverequests] The addon has made too many requests to Google Drive, and will back off: we'll retry in 16 seconds
03-01 04:05:16 INFO [backup.model.coordinator] Syncing Snapshots
03-01 05:05:17 INFO [backup.model.coordinator] Syncing Snapshots

**Comment by sabeechen** [comment]
Sorry it took me so long to get back to you on this, I've been out of touch for a while.

Google only allows so many requests to be made against a Google Drive account at a time.  Its unlikely that the add-on by itself could reach that limit, so most likely something else is writing data using your Google Drive account (eg something else you previously connected to it or using it through https://drive.google.com)

Usually this goes away by itself, but if it doesn't your options are to:
* Remove or stop the other apps writing to your account.  You can see what else you have connected by going to https://myaccount.google.com/permissions
* Reauthorize your the add-on with Google drive ("Actions" > "Reauthorize" in the web-ui).  This doesn't alwasy work
* Use a different Google Drive account.


If none of this works or you think there is some other way I can help, feel free to reply or re-open this issue.
