### ISSUE TITLE
Flaw on Custom File Names

### ISSUE THREAD

**Issue by gdreelin** [sabeechen/hassio-google-drive-backup#57]
I have noticed that when you change the custom file names to say this "{month_short} {day}, {year} ({version_ha}) {type}" it will save but once you stop and restart it goes back to the original setting. It does the same every time it updates too. It does not want to hold the settings permanently. Just giving heads up, still best backup out there!!! It is awesome!

**Comment by sabeechen** [comment]
A misconfiguration caused caused hassio to think the snapshot name entry was invalid until a release I made today.  Are you still seeing this with version v0.97?  You might need to click the refresh icon on the add-store page to make it see the new version is available.

**Comment by sabeechen** [comment]
I'm closing this for now just to keep my bug list clean, but please reopen if you still see the problem with the latest version.

**Comment by gdreelin** [comment]
> 
> 
> I'm closing this for now just to keep my bug list clean, but please reopen if you still see the problem with the latest version.

I am cool with that just wanted to let you know..
