### ISSUE TITLE
400 Error Using Personal Client ID and Secret

### ISSUE THREAD

**Issue by riedlem** [sabeechen/hassio-google-drive-backup#570]
Followed the instructions in https://github.com/sabeechen/hassio-google-drive-backup/blob/master/LOCAL_AUTH.md to generate a client id and secret. Once they're entered into the addon and click on Connect, presented with the following error, with no token generated:

Authorization Error
Error 400: invalid_request

You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy for keeping apps secure.

You can let the app developer know that this app doesn't comply with one or more Google validation rules.

If you’re the app developer, make sure that these request details comply with Google policies.
redirect_uri: urn:ietf:wg:oauth:2.0:oob

Looking up similar issues online led me to https://github.com/home-assistant/core/issues/67662 where they describe the issue as being related to Google decommissioning the oob redirect_url

**Comment by sabeechen** [comment]
Yikes, it looks like they're really locking things down.  I'm going to need to have the addon use [this mechanism](https://developers.google.com/identity/protocols/oauth2/limited-input-device) with polling to authenticate using personal credentials.  This will make the workflow slightly more complicated, but then again its already pretty complicated so ¯\_(ツ)_/¯ can't fight Google.  Hopefully this will keep working for at least a few years.  this is the third time I've had to rewrite this damn thing to meet  the shifting sands of Google's security requirements.

In the mean time I can't think of a workaround.  Authenticating using the web service I set up (the "Easy Way" in the instructions) still works but personal/custom credentials will require substantial code changes in the addon to make it work again.  Bummer.

**Comment by riedlem** [comment]
Following the instructions in , I was able to get the Nest integration setup with the Web OAuthID, so maybe that can be used in this integration as well? I'm not sure what restrictions there are for the Drive API.

Of note, when using the same Web OAuthID from the Nest setup, the following error is seen:

Error 400: redirect_uri_mismatch
The redirect URI in the request, urn:ietf:wg:oauth:2.0:oob, can only be used by a Client ID for native application. It is not allowed for the WEB client type. You can create a Client ID for native application at https://console.developers.google.com/apis/credentials/oauthclient

**Comment by sabeechen** [comment]
The issue is having a public address for the Google Authentication workflow to redirect back to.  The nest integration runs directly in Home Assistant and so it can create an endpoint you can redirect to from the browser.  Addons like this run in a restricted environment and can only be accessed through a proxy that doesn't work properly with redirects (its an issue with HA's authorization cookies).

I've implemented the "TV's and Limited Input Devices" workflow in testing and I think it will work well.  I should have it out once I chew through a couple other bugs.
