### ISSUE TITLE
iCloud option

### ISSUE THREAD

**Issue by Patrick1610** [sabeechen/hassio-google-drive-backup#573]
Hi, 

I have no idea it what I am about to ask is possible at all and how much work it would require, so forgive me if it is undoable. 
Because I have a limited Google storage, but a very big iCloud storage, and I really love all the options and custom options you have for controlling the backup routine I was wondering if it is possible to make an iCloud option to store the backups on?

Regards, 
Patrick

**Comment by sabeechen** [comment]
I'd like to but its not possible for me right now, I simply don't have the time to support it.
https://github.com/sabeechen/hassio-google-drive-backup#will-this-ever-upload-to-dropboxondriveftpsmbmyfavoriteprotocol

In the future, _maybe_.
