### ISSUE TITLE
sensor.snapshot_backup_snapshots_in_google_drive unavailable ?

### ISSUE THREAD

**Issue by stefanuytterhoeven** [sabeechen/hassio-google-drive-backup#577]
this is a "template" sensor. Can it be removed? (since it's unavailable), or is this 'normal' behaviour ?
it states it's "unavailable" in "developers menu" and in "entities" the status is"repaired"

**Comment by sabeechen** [comment]
This isn't a sensor the addon publishes, its likely one that you've added as a template sensor in your configuration.yaml.  By default the sensors the addon publishes are:
- ```binary_sensor.backups_stale```
- ```sensor.backup_state```

Both of which can be turned off in the settings.

If you're using an older version of the addon or have some uncommon configuration options selected, the addon may be publishing to different sensor names.  See [this document](https://github.com/sabeechen/hassio-google-drive-backup/blob/master/hassio-google-drive-backup/BACKUP_AND_SNAPSHOT.md) for details about that.

**Comment by sabeechen** [comment]
I'm closing this for now, but please let me know if you think there is something else I can help with.
