### ISSUE TITLE
ERROR Unable to reach Home Assistant.  Is it restarting?

### ISSUE THREAD

**Issue by ACJ132** [sabeechen/hassio-google-drive-backup#58]
Hi sabeechen. Awesome Add-on. However, I am having some issues related to the stale snaphshot sensor. In the Google Drive Backup log I get the following error: 

_ERROR Unable to reach Home Assistant.  Is it restarting?_

On the Hass.io System tab I am getting the following error messages related Google Drive Backup:2

ERROR (MainThread) [hassio.homeassistant] Error on call https://172.30.32.1:8123/api/states/binary_sensor.snapshots_stale: Cannot connect to host 172.30.32.1:8123 ssl:None [Connection refused]
ERROR (MainThread) [hassio.api.proxy] Error on API for request states/binary_sensor.snapshots_stale
ERROR (MainThread) [hassio.homeassistant] Can't update Home Assistant access token!
ERROR (MainThread) [hassio.api.proxy] Authenticate error on API for request states/sensor.snapshot_backup
ERROR (MainThread) [hassio.homeassistant] Can't update Home Assistant access token!
ERROR (MainThread) [hassio.api.proxy] Authenticate error on API for request states/binary_sensor.snapshots_stale

This is my Config:
{
  "max_snapshots_in_hassio": 3,
  "max_snapshots_in_google_drive": 20,
  "days_between_snapshots": 1,
  "use_ssl": true,
  "certfile": "/ssl/fullchain.pem",
  "keyfile": "/ssl/privkey.pem",
  "snapshot_time_of_day": "03:30",
  "snapshot_password": "mypwd",
  "snapshot_name": "{type} Snapshot v{version_ha} {year}-{month}-{day} {hr24}:{min}:{sec}",
  "enable_snapshot_stale_sensor": false,
  "send_error_reports": true,
  "generational_days": 3,
  "generational_weeks": 4,
  "generational_months": 6
}

The add-on is creating my backups just fine and storing them to my Google Drive. Any idea why I am getting these errors?

Note, I do use a DNS and LetsEncrypt with my hassio installation. To access my ha instance I use https://my.dns.com. On my router I have the following ports forwarded to my hass.io ip: 1627 and 8099 along with the ports I use for other addons.

**Comment by klaasnicolaas** [comment]
I have exactly the same error

**Comment by wneessen** [comment]
Same here since the last update:

"CRITICAL Unable to reach Hassio supervisor.  Please ensure the supervisor is running."

**Comment by sabeechen** [comment]
@ACJ132 The error means the addon can't reach Home Assistant through a proxy that Hassio provides.  This is normal if you're restarting or updating HA, but it should go away after its back up.  It won't interrupt your backups but it will prevent the "Snapshot Backup" and "Snapshot State" sensors from updating.

The warning you're seeing in the supervisor logs makes it look like Hassio is also having trouble reaching Home Assistant, that error is just getting propagated to the add-on.  I think you're going to need to restart your supervisor or possible the add-on.

@wneessen The error message you're seeing is different and much worse, it means the add-on can't even reach Hassio (the supervisor) on the internal network.  The add-on can't even start up without reaching Hassio, as it depends on it to do pretty much anything.  This should basically never happen, Hassio should always be reachable on the internal network.  Id recommend either restarting the add-on, the supervisor, or the host machine.  Is there anything significant you changed in your configuration recently?

**Comment by froz** [comment]
On my system, something is leaking memory, which is severe enough to cause the Hassio watchdog to restart about every eight hours.  The "unable to reach" errors happen just before and during the restarts.  I thought this add-on was the culprit, but there is still a pretty severe leak without it installed.  The leaking does get worse with it installed, but that does not prove that this add-on itself is leaking.

**Comment by wneessen** [comment]
@sabeechen I tried restarting the add-on, the supervisor as well as did a complete power cycle of my HASS.io RaspberryPi with no success. I just de-installed the add-on and then re-installed it. Same result/error. I didn't change anything in my configuration recently, the only change was the installation of the latest version of the add-on. Before that it worked fine.

**Comment by sabeechen** [comment]
@wneessen Is there anything that shows up in your supervisor logs in Hassio?  You can get to it from Hass.io -> System -> System Logs in the Home Assistant UI

@froz Seeing the error while HA is rebooting is normal.  If you see any evidence that the add-on itself is leaking memory, I'd be curious to know more.

**Comment by wneessen** [comment]
@sabeechen Hundreds of these:
9-05-22 18:39:40 INFO (MainThread) [hassio.api.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
19-05-22 18:39:51 INFO (MainThread) [hassio.api.security] /homeassistant/info access from cebe7a76_hassio_google_drive_backup

**Comment by sabeechen** [comment]
That getting somewhere, you've definitely run into a bug but I'm going to need to make another release in order to get it to print out why to the logs.   I'll make that release today.

**Comment by wneessen** [comment]
Highly appreciated!

**Comment by sabeechen** [comment]
@wneessen I just released v 0.97.1, which prints out some better logging when it can't reach the supervisor on startup.  That should tell us whats going wrong on your install.

**Comment by wneessen** [comment]
Here you go:
05-23 08:49:03 CRITICAL Unable to reach Hassio supervisor.
05-23 08:49:03 CRITICAL 
Traceback (most recent call last):
  File "/app/backup/__main__.py", line 56, in main
    ha_source.init()
  File "/app/backup/hasource.py", line 222, in init
    self._refreshInfo()
  File "/app/backup/hasource.py", line 235, in _refreshInfo
    self._info.url = ensureKey("webui", self.self_info, "addon metdata").replace("[HOST]", ensureKey("hostname", self.host_info, "host metadata") + ".local")
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by sabeechen** [comment]
That explains it, I didn't know hassio could return a null hostname.  I've made a fix and release version 0.97.2, let me know if still run into problems with it.

**Comment by wneessen** [comment]
@sabeechen Works again like a charm! Thanks for the great support!

**Comment by ACJ132** [comment]
sabeechen.

Sorry for the delay in getting back to you. Too much going on as always.

I see that the issue appears to have been resolved. I have updated to the latest version and I am no longer getting the error messages.

Thanks for your support. 

Andrew J
