### ISSUE TITLE
Hardware Restart of HA on RPi causes error

### ISSUE THREAD

**Issue by techman25** [sabeechen/hassio-google-drive-backup#582]
After a hardware restart of the RPi running HA, the following error appeared. However all seems OK, backups to Google Drive are fine and deletion functionality works.  Probably a one off but notifying you as requested.

The server encountered an error while processing this request: invalid_grant<br/>Please <a href='https://github.com/sabeechen/hassio-google-drive-backup/issues'>file an issue</a> on Home Assistant Google Backup's GitHub page so I'm aware of this problem or attempt authorizing with Google Drive again.

**Comment by sabeechen** [comment]
Sorry this took me a while to get back to you on, I've been occupied with other demands.

That error indicates that Google Drive rejected the credentials the addon had cached for your user.  Did the error go away by itself or did you ahve to reauthenticate with addon with Google Drive?  I've had a few users report this happening, and it can usually be traced back to something happening with your google account (eg a password change or changing the account's security controls at https://myaccount.google.com).

**Comment by techman25** [comment]
Hi, all works fine and I'm very happy with the add on.  I haven't recently changed anything on my Google account and it authenticates fine now when rebooting the RPi.  So probably a one off, maybe due to some timing or sequencing issues on first use?
