### ISSUE TITLE
[Feature Request] Last backup and number of backups sensor

### ISSUE THREAD

**Issue by 07lodgeT** [sabeechen/hassio-google-drive-backup#583]
Is it possible to get some sensors to get some more details on the dashboard.
It would be nice to get some details to quickly look at on the dashboard.

I was thinking:
- sensor.last_backup  -  Last time the backup was ran
- sensor.ha_backups  -  Number of backups stored on Home Assistant
- sensor.google_backups  -  Number of backups stored on Google Drive
- sensor.backup_time  -  Time of day that the backups are ran
- sensor.backup_between  -  Number of days between backups

**Comment by sabeechen** [comment]
I think most of what you want is already exposed in the attributes of ```sensor.backups_state```, (docs [here](https://github.com/sabeechen/hassio-google-drive-backup/blob/master/hassio-google-drive-backup/BACKUP_AND_SNAPSHOT.md#backup-state-sensor-1))

Though it doesn't include ```backup_time``` or ```backup_between```, but it does include ```last_backup```, ```last_upload```, and ```next_backup``` as dates.  I suspect that will be more useful for dashboarding.
