### ISSUE TITLE
[Feature Request] please show up which acount is used to sync

### ISSUE THREAD

**Issue by let-alone** [sabeechen/hassio-google-drive-backup#587]
First thanks for great add-on

I use several google account.

So I cannot  remember which google acount is used for back up add-on.

Please add the display feature that which account is used for backup.

Thanks for reading.
Have a nice day

**Comment by sabeechen** [comment]
I'll see if there is a way to do this without expanding the permissions the addon gets from Google.

**Comment by let-alone** [comment]
> I'll see if there is a way to do this without expanding the permissions the addon gets from Google.

Thank you!!

**Comment by sabeechen** [comment]
Looks doable.  The email address will appear under the "Google drive" section on the left of the Web-UI in the next version.

**Comment by Opontios** [comment]
A very useful feature, please implement it.

**Comment by sabeechen** [comment]
I've just released v 0.107.1 which shows the email in use in the account sidebar.  Please let me know you run into trouble with it after updating.
