### ISSUE TITLE
Question: snapshots size containment

### ISSUE THREAD

**Issue by PieBru** [sabeechen/hassio-google-drive-backup#59]
Hi Stephen,

I've a question only marginally pertaining to your add-on, but it originated from your automatic-snapshots usage in my experiments with HA. I didn't notice it before with manual/casual snapshot.

I wasn't able to find info digging the net, do you think it's possible to exclude some files/folders from snapshots? Such a feature could help limiting snapshots size.

If not possible, it may be useful in your addon to link a page of hints on how to avoid snapshots became ginormous, such as don't use default folders for MotionEye recordings, unless your root dir is on a chubby hard disk ;)

Thanks,
Piero

**Comment by sabeechen** [comment]
The add-on never actually manages the contents of a snapshot, it just asks Hassio to create one and depends on the info the Hassio api returns.   Hassio ony lets you 
* Exclude some of the 4 "main" folders.
* Exclude add-on configuration
* Encrypt with a password
* Give it a different name
I think you could accomplish something similar to what you want by putting your large files in /share and then excluding that folder (IIUC thats kind of what the folder is for), but to have more control over the snapshot contents it would need to be implemented in Hassio first.

**Comment by PieBru** [comment]
Thank you Stephen, your thorough explanation pointed me in the right direction of a better usage and thus exclusion of the /share/motioneye directory, which is a nonsense and a problem if included in automatic backups.
Piero

**Comment by radinsky** [comment]
@PieBru , can you tell how did you exclude only the  /share/motioneye ? I see there's only option to exclude the entire /share directory..

**Comment by radinsky** [comment]
Nevermind, found:
` "exclude_folders": "homeassistant,ssl,share,addons/local" `
