### ISSUE TITLE
Can't add respository to HA

### ISSUE THREAD

**Issue by DirkStorck** [sabeechen/hassio-google-drive-backup#593]
Hi,

I try to add you repository to my HA and get the following errror

![grafik](https://user-images.githubusercontent.com/2306190/163358857-3589c24e-f08a-40f0-8ed0-08ce8c18ca4c.png)

Here is a screenshot of the system I use and a part of the log

![grafik](https://user-images.githubusercontent.com/2306190/163359140-178f2d05-e150-4bf2-955d-832ad5d8991e.png)

Any ideas why this happens? 

Thank you!

**Comment by DirkStorck** [comment]
Found out, that after that the repo is added 

![grafik](https://user-images.githubusercontent.com/2306190/163364846-5485e9a3-5818-4070-8c27-8782f73a91b4.png)


but I can't find the add-on 

![grafik](https://user-images.githubusercontent.com/2306190/163364760-63716934-1545-498d-a084-be5b9d82cdfd.png)

**Comment by sabeechen** [comment]
The supervisor logs seem to think it loaded the addon metadata fine which is ... weird.  It even says it added "1 new" to the store, which _must_ be my addon.  This might be a stupid suggestion, but could you try CTRL+F5 on the store page (a forced refresh)?  Its possible the UI is just caching old info.

**Comment by DirkStorck** [comment]
Hi,

thanks for the advice with clearing cache browser! That worked. Now I can see you add-on :) 

![grafik](https://user-images.githubusercontent.com/2306190/163542306-8a3f0e86-7780-48b7-a2cd-8249ab68cef0.png)

Works perfectly! 

![grafik](https://user-images.githubusercontent.com/2306190/163550000-0819fe41-af98-4fcd-8515-d006b8ef434e.png)

Here a little support for your work! ;) :)
7HF37171MW713613Y

Thanks!

**Comment by sabeechen** [comment]
Thanks!  I'll put it to good use
