### ISSUE TITLE
Lost password save location

### ISSUE THREAD

**Issue by DhillanKara** [sabeechen/hassio-google-drive-backup#594]
I have unfortunately lost my backup password. 
Attempting to restore I incorrectly entered the password and the restore occurred without decryption, the instance will no longer start fully and I can not access the frontend site.

Now I have a set of backups which I cannot use without the password.

I still have samba share access to my HASS instance and can see config files, is there any way to view the password set in the backups UI with this so I can use and restore these backups?

**Comment by sabeechen** [comment]
If you stored the password as a using the "!sercret my_Secret_name" then the password should be in your secrets.yaml file which is in the config directory accessible through Samba.  If not (eg you just configured a password without using !secret) then the password is in a configuration file that Home Assistant makes it notoriously difficult to get to, and getting it will depend on how you have Home Assistant installed (eg HA Supervised, HA OS, or from the raspberry pi image).  If you're abel to get OS shell access to the machine HA runs on, it should be in /usr/share/hassio/addons/hassio_google_drive_backup_XXXXXX/config.json

If you used the wrong password while restoring, Home Assistant will fail to decrypt the backup right at the start and won't continue so its likely something else happened.  If you're able to plug a monitor and keyboard into the machine you're running HA on you can get access to the [Home Assistant CLI](https://www.home-assistant.io/common-tasks/os#home-assistant-via-the-command-line), from which you can do many things including restore a backup.  Its a little difficult to to use but it might tell you whats wrong if you poke around in it.

**Comment by sabeechen** [comment]
I'm closing this for now, but please let me know if there is anything else I can help with.
