### ISSUE TITLE
Error in Logs: Option 'delete_ignored_after_days' does not exist in the schema for Home Assistant Google Drive Backup

### ISSUE THREAD

**Issue by Jeppedy** [sabeechen/hassio-google-drive-backup#599]
22-04-27 18:02:25 WARNING (MainThread) [supervisor.addons.options] Option 'delete_ignored_after_days' does not exist in the schema for Home Assistant Google Drive Backup

Many of these messages are found in my log.
What's up?  Any ideas?

**Comment by sabeechen** [comment]
Thanks for bringing this to my attention, looks like I just forgot to include the schema change in the last version.  I just released v0.107.1 that includes a fix for this.  Apologies for the log spam!
