### ISSUE TITLE
Exception: A snapshot is already in progress

### ISSUE THREAD

**Issue by Obicom** [sabeechen/hassio-google-drive-backup#6]
Hassio 0.90.2 .... after the issue the CPU usage stays with a high value of 34% 

Traceback (most recent call last):
  File "/app/backup/engine.py", line 90, in doBackupWorkflow
    self._checkForBackup()
  File "/app/backup/engine.py", line 244, in _checkForBackup
    self.snapshots.append(self.hassio.newSnapshot())
  File "/app/backup/hassio.py", line 74, in newSnapshot
    raise Exception("A snapshot is already in progress")
Exception: A snapshot is already in progress

**Comment by sabeechen** [comment]
Does this error stick around for more than an hour?

**Comment by Obicom** [comment]
NO,  it's solved.

**Comment by sabeechen** [comment]
The high CPU usage while a snapshot is in progress is because Hass.io is creating the snapshot, its a compressed archive that can take a while to create.  In this case the add-on shouldn't surface the error, since it should just let the snapshot complete and move on.  I'll make a fix.

**Comment by sabeechen** [comment]
I just published a new release that should take care of this error (v0.52),
