### ISSUE TITLE
[object Object], [object Object] in Snapshot State sensor

### ISSUE THREAD

**Issue by jarzebskim** [sabeechen/hassio-google-drive-backup#60]
Hi, In Snapshot State sensor I've [object Object], [object Object] items. It shouldn't be snapshot names?

![Zrzut ekranu z 2019-05-21 20-45-49](https://user-images.githubusercontent.com/48404550/58122550-2abc2000-7c0a-11e9-9b52-281eeca32113.png)

**Comment by sabeechen** [comment]
It just how home assistant chooses to render them, they're json objects with a format like:
```json
{
  "name": "Full Snapshot 2019-05-21 00:00:00",
  "date": "2019-05-21T00:00:00:00+00:00Z",
  "state": "Backed Up"
}
```
