### ISSUE TITLE
The tags used by generational backups are wrong manager wirh the ignore backups

### ISSUE THREAD

**Issue by horttorrell32** [sabeechen/hassio-google-drive-backup#611]
The tags for generational backups (e.g. generation day 1 of 4, generation week 2 of 2...) are wrong managed when ignore backups are used (ignore_upgrade_backups, ignore_other_backups equal true).

The tags are not showed in the generactional backup, they are show in te ignored backups intead of.
And sometimes wrong tags are generated:
E.g. generation day 5 of 4...

BR

**Comment by sabeechen** [comment]
Thanks for noticing this, I think this was introduced in a recent change I made to how ignored backups work.  Just to confirm, you're not seeing any incorrect behavior (eg deleting or keeping backups it shouldn't), you're just seeing that the labels are incorrect?

**Comment by horttorrell32** [comment]
Yes, I don't detect any incorrect behavior. It seems format issue.

**Comment by sabeechen** [comment]
I've released v0.108.0 of the addon, which includes a fix for this.  Feel free to reopen this issue if you notice any other problems with it or think I can otherwise help.
