### ISSUE TITLE
README.md does not show updated installation instructions.

### ISSUE THREAD

**Issue by appuchias** [sabeechen/hassio-google-drive-backup#613]
I recently reinstalled HA and saw that the instructions on the repo differ from what the menus are named as of Home Assistant 2022.5.

I created PR #612, but it was closed.

**Comment by sabeechen** [comment]
Thanks, I'm not sure why it got closed.  I didn't do it and github doesn't list a reason.  Anyway I reopened and merged it.  Thanks!

**Comment by appuchias** [comment]
No problem! Happy to help.
