### ISSUE TITLE
Config files not showing after restore?

### ISSUE THREAD

**Issue by Geniusness** [sabeechen/hassio-google-drive-backup#614]
Not 100% sure if this is related to a restore or not. Trying to track it down without much luck. 

I have not seen any files in the config directory since before restoring a backup. My HA setup is running fine, except for not seeing files in the File Editor add-on. Files show in my backup after downloading and decompressing. Currently running 2022.5.3, just restored from 2022.5.4 trying to fix the. Original restore was 2022.5.2 to 2022.5.1. 

Any insight would be greatly appreciated!

**Comment by sabeechen** [comment]
During a restore if some part of it fails Home Assistant will just continue on and restore what it can.  The supervisor logs will show any errors in encountered doing that, but they're most likely long gone by now.  

If I were you I'd do a partial restore of just Home Assistant again to see if you can get your config folder back, it'll overwrite the existing contents without touching anything else.  If here are any problems you should see it in the supervisor logs right after.

Another note: The addon doesn't actually create the backups or restore them, it just tells Home Assistant to create them and copies the data HA creates to Google Drive.  If there is a problem restoring then its almost definitely a problem in Home Assistant's supervisor.

**Comment by Geniusness** [comment]
Thanks for the suggestions!

Your additional note...I now remember reading that when I originally installed the add-on. Thanks for refreshing that!
