### ISSUE TITLE
Shows Google Drive FUll

### ISSUE THREAD

**Issue by jerryaycock** [sabeechen/hassio-google-drive-backup#618]
Google drive is empty.
332mb of 19Gb used.
I tried resyncing.

**Comment by sabeechen** [comment]
I should make something clear, the addon never checks Google drive to see if free space is available.  It always asks Google Drive to allocate X GB for a backup and the "Google Drive Full" error only gets displayed if Google tells the addon there isn't enough space.  So Google is the one who thinks you don't have enough space for the latest backup.  Here is some guidance:

- Ensure that the latest backup you're trying to upload is less than 19 GB
- Check Drive's trash folder.  Items in the trash still take up your quota and I'm not sure if they're listed in the number you're seeing.
- you can go to [https://drive.google.com/drive/quota](https://drive.google.com/drive/quota) to see what your largest files in Drive are.
- Verify that other google services aren't using up the rest of your storage space (see [https://one.google.com/storage](https://one.google.com/storage))

Side note:  How did you get exactly 19GB of storage space in on your Google account?  I'm not aware of a plan they have that offers that.

**Comment by sabeechen** [comment]
I'm closing this issue for now but if there is any other way you think I can help please feel free to reopen it and let me know.
