### ISSUE TITLE
Re : Backup won't run

### ISSUE THREAD

**Issue by fitments** [sabeechen/hassio-google-drive-backup#619]
Hi, i have been trying to run a backup the whole morning but it just shows

Full Backup 2022-05-23
pending - Pending
Full backup
4 hours ago

What could be causing this ?

![Capture](https://user-images.githubusercontent.com/32286296/169809813-1685729a-d80e-4460-a74b-244c52332431.PNG)

**Comment by sabeechen** [comment]
If you have a really big backup, a slow computer, or a slow hard drive, the backup can take a really long time.  This is especially true on rasbperry PI's, which can take hours to write a few GB of compressed data to their SD card.

You should be able to check your supervisor logs (Settings > System > Logs > (top right) Supervisor) to see if something is going wrong with a backup.

If everything is working correctly and its just taking a long time you can:
* Use partial snapshots (check the addons' settings) to only backup some parts of Home Assistant.
* If your sensor database is really big you can use something like the [Maria DB addon ](https://www.home-assistant.io/integrations/recorder#mariadb-and-mysql) to move the database into an addon and then create partial backups without that addon.

**Comment by sabeechen** [comment]
I'm closing this issue for now but if there is any other way you think I can help please feel free to reopen it and let me know.
