### ISSUE TITLE
[Feature Request] Possibility to add a note to a backup

### ISSUE THREAD

**Issue by JoostAB** [sabeechen/hassio-google-drive-backup#623]
Every once in a while I like to keep an automatic created backup for a while. Could be because HA-OS was upgraded, core upgrade or whatever. I would like to be able to make a note why I checked 'Never delete' because I'm sure I won't remember that after a month...
I've seen issue #271, but that was only a question. I's like to upgrade that into a feature request.

**Comment by sabeechen** [comment]
Why not!

I just released v 0.108.1 of the addon, which adds this ability.  You can specify a comment when creating a one-off backup and you can change it later in the backup details page (the one where you click on a backup).
