### ISSUE TITLE
Question: excluding directories in partial backups

### ISSUE THREAD

**Issue by erkr** [sabeechen/hassio-google-drive-backup#634]
Thanks for this life-saving add-on that assures me of having cloud backups :-)

I have a question about excluding folders:
The settings UI offers a limited set of standard folders that can be excluded (Very useful) in partial backups
The YAML version looks more versatile 'exclude_folders: media'.
Is it possible to exclude other directories when specified via the YAML? 
Specifically, can I exclude (a file or) a sub-folder inside the config folder?

The background is that I use Music Assistant, which creates a large database inside the config folder, that easily can be regenerated.

Sincerely
Eric

**Comment by sabeechen** [comment]
Unfortunately, it isn't possible to exclude folders at any granularity outside of the main ones (/config, /ssl, /media, etc).  This is a Home Assistant limitation.  This add-on doesn't actually create the snapshot, it still just asks Home Assistant to create one with a specific configuration, and right now Home Assistant only allows including/excluding those specific folders.

**Comment by erkr** [comment]
Thanks for the fast answer, that is clear 👍
