### ISSUE TITLE
exclude recorder data? MariaDB data on disk is 200mb but uploads are 2GB?

### ISSUE THREAD

**Issue by zeltak** [sabeechen/hassio-google-drive-backup#638]
Hi all

I have been using this amazing add on for months now and its super rock solid.

I have had 2 recent issue which are closely related 

1) is that it seems mariaDB is growing to be very large (on disk df -h says 200mb) but when I see my google uploads it seems like mariaDB is taking 2GB in the upload! im trying to figure out why?

2) if this is the case is there a setting to exclude recorder data?

thx a bunch for your awesome work

Z

**Comment by sabeechen** [comment]
You should be able to open up a backup (its just a tar.gz file) to see whats inside with 7-zip or a similar utility, that will show you definitively what is taking up space.   If you use a password consider making a non-password-protected backup just to check this.

If you're using the MariaDB addon you can just create a partial backup that excludes the Maria DB addon (check the addon's settings) but if you're using the default sqlite database there isnt any way to exclude just the database file.

**Comment by zeltak** [comment]
thx so much @sabeechen !

im very new to the whole Home assistant scene so appreciate  your answer

I am using mariaDB and indeed extracted as suggested the back file

drilling down it seems the a HUGE file is the states.ibd..

![CleanShot 2022-06-21 at 21 13 19](https://user-images.githubusercontent.com/498410/174869648-ba7acb86-69e3-4e36-85c1-22dbca6771f6.png)

![CleanShot 2022-06-21 at 21 13 27](https://user-images.githubusercontent.com/498410/174869673-50b6c492-2f26-4c91-8395-7f8c4b2ec3fb.png)


I assume something very wrong is going on there.. 

I will look into partial backups 

thx alot

Z
