### ISSUE TITLE
Reading /snapshots folder twice per second

### ISSUE THREAD

**Issue by jakubka** [sabeechen/hassio-google-drive-backup#661]
I noticed that the add-on is reading the /snapshots folder very often.

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/4806497/177954967-3522a426-84eb-48c5-90d5-31ccfca6d077.png">

It's a minor issue. It can shorten the life of the SD card and pollutes logs.

Any way how to make it read the folder less often?

**Comment by sabeechen** [comment]
Is this happening right after installing the addon?  This is expected before connecting the addon with Google Drive.  Please also ensure you are using the most recent version of the addon (0.108.2).

The '/snapshot' in this error message is referencing the '/snapshot' endpoint of the supervisor HTTP API, not the folder backups are stored in.  The supervisor, for some reason, insists that it logs every usage of the internal supervisor API from addons.  The message isn't referencing access to the SD card.

**Comment by jakubka** [comment]
Ah good to know that it's an endpoint call. Also I don't have the latest version, so I will update and check again. I will close the issue and reopen if needed. Thanks!
