### ISSUE TITLE
Failed to start add-on 

### ISSUE THREAD

**Issue by skyinlife** [sabeechen/hassio-google-drive-backup#666]
Failed to start add-on
Image sabeechen/hassio-google-drive-backup-armv7:0.108.2 does not exist for addon_cebe7a76_hassio_google_drive_backup

**Comment by biltoc** [comment]
Same for me - Failed to start add-on

**Comment by KalleHoppe** [comment]
Same issue here, and no errors in the log just this:
```
07-30 11:15:24 INFO Starting server on port 8099
07-30 11:15:24 INFO Server started
07-30 11:15:24 INFO Syncing Backups
```
The page just blinks and nothing happens. There aren´t even any configuration settings

**Comment by sabeechen** [comment]
The Home Assistant can get into a bad state sometimes, where the installation has failed or is partially cached, etc.   Please try the following:
- Uninstall this addon
- Restart the Home Assistant machine (this clears its caches)
- Reinstall this addon

**Comment by KalleHoppe** [comment]
ok, thanks, I restarted the whole host machine and it appeared as normal. Its up and running now. Great work by the way! Appreciate it 👍

**Comment by sabeechen** [comment]
If [that](https://github.com/sabeechen/hassio-google-drive-backup/issues/666#issuecomment-1203205567) doesn't work for anyone, please feel free to re-open this issue and let me know.  I'll do what I can to help.

**Comment by skyinlife** [comment]
Tnx, now is work fine!!!!


чт, 14 июля 2022 г. в 22:49, Stephen Beechen ***@***.***>:
