### ISSUE TITLE
Able to use without being an add-on?

### ISSUE THREAD

**Issue by abishur** [sabeechen/hassio-google-drive-backup#667]
I'm using home assistant in a docker container using Truenas Scale as a host.  Is there a way to still make use of this add-on through something like HACS?

**Comment by sabeechen** [comment]
Right now the add-on can only run on a supervised install of Home Assistant, it is a hard dependency.  Making it work with HA Core is [something I'd like to do](https://github.com/sabeechen/hassio-google-drive-backup/issues/586), but I have no timeline for when it will happen.
