### ISSUE TITLE
An unexpected error occurred: 404, message='Not Found', url=URL('http://hassio/snapshots')

### ISSUE THREAD

**Issue by milandzuris** [sabeechen/hassio-google-drive-backup#668]
addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:167 (sync)
  addon/backup/model/model.py:261 (_syncSnapshots)
  addon/backup/ha/hasource.py:246 (get)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:108 (snapshots)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:221 (_getHassioData)
  addon/backup/ha/harequests.py:181 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

**Comment by jartill** [comment]
Found this. Fixed the issue! https://github.com/sabeechen/hassio-google-drive-backup/issues/658#issuecomment-1177307797

**Comment by sabeechen** [comment]
[Check my response here](https://github.com/sabeechen/hassio-google-drive-backup/issues/652#issuecomment-1177943877) if you're still having trouble.
Duplicate #652
