### ISSUE TITLE
Are encrypted backups really encrypted?

### ISSUE THREAD

**Issue by StayPirate** [sabeechen/hassio-google-drive-backup#669]
Disclaimer: I'm new to HA, maybe I did sth stupid within my configuration (?).

I configured your add-on with a passphrase to encrypt newly created backups, and according to the add-on page it should be working correctly:

![image](https://user-images.githubusercontent.com/37073343/179003160-c93ea69c-2195-4707-b7e8-a133af24bc19.png)

Anyway, if I download the archive either from HA or GDrive, the archive itself is not encrypted. I can access any file into it without input any password. I'm wondering if this is only happening to me. Plus, do you have any CD/CI pipeline or unit-test suite which check the encryption feature for every new release?

**Comment by sabeechen** [comment]
The backup file is always a unencrypted tar file, this is so the metadata file (backup.json) inside of it is always readable.  Each of the individual archives inside the backup (eg homeassistant.tar.gz) are what gets encrypted, using an encryption scheme specific to Home Assistant.  Try decompressing them and you will see it fails to even be recognized as a compressed files.
