### ISSUE TITLE
How to Reinstall from Scratch

### ISSUE THREAD

**Issue by vlsech** [sabeechen/hassio-google-drive-backup#672]
I had to roll back to an earlier backup of HA before installing your backup.  Now I have lost my original key and cannot reinstall.  How can I do a clean install from scratch?

Vince

**Comment by sabeechen** [comment]
Apologies it took me a while to get back to you, I've been out of touch.  I'm not confident I understand what you're asking.

To reinstall the addon you just install it again using [the instructions](https://github.com/sabeechen/hassio-google-drive-backup#detailed-install-instructions).  If you used it previously it will find the old folder automatically and ask if you want to use it after you connect with Google Drive.

You shouldn't have to worry about a key unless you previously chose to use custom credentials (eg using [these instructions](https://github.com/sabeechen/hassio-google-drive-backup/blob/master/LOCAL_AUTH.md)).  If thats the case you can get the client id and client secret from the [Credentials Page of Google Cloud Console](https://console.cloud.google.com/apis/credentials).

**Comment by sabeechen** [comment]
Please feel free to reopen this if you think there is more I can help with.
