### ISSUE TITLE
An unexpected error occurred: 404, message='Not Found',

### ISSUE THREAD

**Issue by cherepanov-pavel79** [sabeechen/hassio-google-drive-backup#673]
Copy the info from the previous page here

**Comment by gafain** [comment]
Same problem

**Comment by MuadDev** [comment]
me too

**Comment by sabeechen** [comment]
Please see my comment [here](https://github.com/sabeechen/hassio-google-drive-backup/issues/652#issuecomment-1177943877).

Duplicate #652
