### ISSUE TITLE
Issue with Google Drive Backup

### ISSUE THREAD

**Issue by ralunagithub** [sabeechen/hassio-google-drive-backup#677]
[home-assistant-google-drive-backup.log](https://github.com/sabeechen/hassio-google-drive-backup/files/9184646/home-assistant-google-drive-backup.log)

**Comment by matthewcooper** [comment]
Also, have the same problem after upgrading Home Assistant 2022.7.7 and Operating System 8.4 I am not sure which one caused the problem

**Comment by His-Holy-Noodliness** [comment]
I think I have the same, looks like the HA guys felt the need (once again) to reorganise and rename things to make it harder to find stuff and break addons, what a joy.

**Comment by sabeechen** [comment]
Pleas see my response [here ](https://github.com/sabeechen/hassio-google-drive-backup/issues/652#issuecomment-1177943877) for guidance.  It is caused by a combination of:

- Home Assistant renamed its internal API's
- Auto-update is broken for some people

Duplicate #652
