### ISSUE TITLE
Google Drive incorrectly shown as full & backup failing

### ISSUE THREAD

**Issue by PanMat** [sabeechen/hassio-google-drive-backup#679]
I recently updated to v0.108.2 and started seeing "Google Drive is full" error while there is lot of free space left on the drive ([see screenshot](https://imgur.com/a/BOZqw6D)). Also included below are the logs for reference.

`
07-27 20:58:51 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/self/info
07-27 20:58:51 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/info
07-27 20:58:51 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/core/info
07-27 20:58:51 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
07-27 20:58:51 INFO [backup.ui.uiserver] Starting server on port 8099
07-27 20:58:51 INFO [backup.ui.uiserver] Server started
07-27 20:58:51 DEBUG [backup.model.syncer] Sync requested by Coordinator
07-27 20:58:51 INFO [backup.model.coordinator] Syncing Backups
07-27 20:58:51 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
07-27 20:58:51 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups
07-27 20:58:51 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups/6b242561/info
07-27 20:58:51 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups/a8cbe17b/info
07-27 20:58:51 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups/634fdf8b/info
07-27 20:58:51 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups/55c7cadf/info
07-27 20:58:51 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups/72c50e96/info
07-27 20:58:51 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups/edc2f073/info
07-27 20:58:51 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups/7e4991b8/info
07-27 20:58:51 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups/72b42469/info
07-27 20:58:51 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups/5427a552/info
07-27 20:58:51 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups/e1e48c60/info
07-27 20:58:51 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups/bb2d017b/info
07-27 20:58:51 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups/0553a743/info
07-27 20:58:51 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups/a78be02a/info
07-27 20:58:51 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups/18e250fa/info
07-27 20:58:51 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups/1a716069/info
07-27 20:58:51 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups/369bcdec/info
07-27 20:58:51 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups/fdf35aa1/info
07-27 20:58:51 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/<redacted>/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
07-27 20:58:51 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota%2Cuser
07-27 20:58:51 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%27<redacted>%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
07-27 20:58:51 INFO [backup.drive.drivesource] Uploading 'Full Backup 2022-07-25 20:58:58' to Google Drive
07-27 20:58:51 DEBUG [backup.drive.driverequests] Starting a new upload session with Google Drive
07-27 20:58:51 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true
07-27 20:58:52 ERROR [backup.model.coordinator] Google Drive is out of space
07-27 20:58:52 INFO [backup.model.coordinator] I'll try again in an hour
07-27 20:59:01 INFO [backup.debugworker] Sending error report (see settings to disable)
`

**Comment by sabeechen** [comment]
Answered [here](https://community.home-assistant.io/t/add-on-home-assistant-google-drive-backup/107928/653), the most recent backup was too large to fit in Drive.
