### ISSUE TITLE
log error

### ISSUE THREAD

**Issue by mclaudiopt** [sabeechen/hassio-google-drive-backup#68]
hello
i am having this on the LOG
what does it mean and how to solve?
thanks
```
19-06-24 02:27:37 ERROR (MainThread) [hassio.addons.addon] Can't write tarfile <hassio.utils.tar.SecureTarFile object at 0x71deec30>: [Errno 2] No such file or directory: '/data/addons/data/a0d7b954_ssh'
19-06-24 02:27:37 ERROR (MainThread) [hassio.snapshots.snapshot] Can't make snapshot from a0d7b954_ssh
```

**Comment by sabeechen** [comment]
It looks like Hass.io is having trouble backing up your SSH add-on.  My add-on just asks Hass.io to create the snapshot, so it isn't something I can necessarily fix but I'll try to help.

As a first step I'd trying reinstalling the ssh add-on.   Seems like something in it is busted.  You could also see if creating a partial snapshot without the ssh add-on completes.  If none of that works you'd have to file an issue with the hass.io folks.

**Comment by mclaudiopt** [comment]
hello
i just updated ssh and now dont have more errors !
thanks a lot !

**Comment by sabeechen** [comment]
Glad I could help
