### ISSUE TITLE
Addons not restarting after backup

### ISSUE THREAD

**Issue by URBANsUNITED** [sabeechen/hassio-google-drive-backup#682]
Hi Stephen!

As explained earlier already.
Some addons don't restart and the watchdog is disabled after a succesful backup.
My addons in question are:
Mariadb
Zigbee2MQtt
esphome

These didn't start after the backup in the past. Today it was only Zigbee2MQTT which didn't restart.

For your information, mariadb is running and working, even there is an error below... Strange!!!!

Log:

Addon version: 0.108.2 Home Assistant Version: 2022.7.7 Supervisor Version: 2022.07.1 Supervisor Channel: stable Hassos Version: None Docker Version: 20.10.12 Architecture: amd64 Machine: qemux86-64 Date: 2022-08-02T07:27:53.512729+00:00 Timezone: Europe/Berlin Failure Time: Never Last Good Sync: 2022-08-02T07:16:57.808961+00:00

Exception:
No error could be identified automatically.
Backups:

{
   "HomeAssistant": {
       "backups": 2,
       "retained": 0,
       "deletable": 2,
       "name": "HomeAssistant",
       "title": "Home Assistant",
       "latest": "2022-08-02T07:10:40Z",
       "max": 2,
       "enabled": true,
       "icon": "home-assistant",
       "ignored": 76,
       "detail": "",
       "size": "573.4 MB",
       "ignored_size": "3.7 GB",
       "free_space": "14.4 GB"
   },
   "GoogleDrive": {
       "backups": 5,
       "retained": 1,
       "deletable": 4,
       "name": "GoogleDrive",
       "title": "Google Drive",
       "latest": "2022-08-02T07:10:40Z",
       "max": 4,
       "enabled": true,
       "icon": "google-drive",
       "ignored": 0,
       "detail": "urbansunited@gmail.com",
       "size": "1.4 GB",
       "ignored_size": "0.0 B",
       "free_space": "879.2 GB"
   }
}
Config:
{
   "Setting.MAX_BACKUPS_IN_HA": 2,
   "Setting.DAYS_BETWEEN_BACKUPS": 1.0,
   "Setting.IGNORE_OTHER_BACKUPS": true,
   "Setting.BACKUP_TIME_OF_DAY": "02:00",
   "Setting.SPECIFY_BACKUP_FOLDER": true,
   "Setting.GENERATIONAL_DAYS": 3,
   "Setting.GENERATIONAL_WEEKS": 1,
   "Setting.GENERATIONAL_MONTHS": 1,
   "Setting.GENERATIONAL_YEARS": 1,
   "Setting.STOP_ADDONS": "03d23610_dasshio,core_duckdns,core_configurator,core_samba,a0d7b954_sonweb,core_ssh,core_zwave_js,45df7312_zigbee2mqtt,a0d7b954_phpmyadmin,a0d7b954_grafana,core_mariadb,a0d7b954_bitwarden,a0d7b954_nodered,7094bb28_docker-wyze-bridge,5c53de3b_esphome",
   "Setting.USE_SSL": true
}
Addon Logs:
08-02 09:25:23 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/45df7312_zigbee2mqtt/info
08-02 09:25:23 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/5c53de3b_esphome/info
08-02 09:25:33 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/45df7312_zigbee2mqtt/info
08-02 09:25:33 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/5c53de3b_esphome/info
08-02 09:25:43 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/45df7312_zigbee2mqtt/info
08-02 09:25:43 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/5c53de3b_esphome/info
08-02 09:25:53 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/45df7312_zigbee2mqtt/info
08-02 09:25:53 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/5c53de3b_esphome/info
08-02 09:26:03 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/45df7312_zigbee2mqtt/info
08-02 09:26:03 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/5c53de3b_esphome/info
08-02 09:26:13 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/45df7312_zigbee2mqtt/info
08-02 09:26:13 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/5c53de3b_esphome/info
08-02 09:26:23 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/45df7312_zigbee2mqtt/info
08-02 09:26:23 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/5c53de3b_esphome/info
08-02 09:26:33 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/45df7312_zigbee2mqtt/info
08-02 09:26:33 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/5c53de3b_esphome/info
08-02 09:26:43 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/45df7312_zigbee2mqtt/info
08-02 09:26:43 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/5c53de3b_esphome/info
08-02 09:26:54 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/45df7312_zigbee2mqtt/info
08-02 09:26:54 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/5c53de3b_esphome/info
08-02 09:27:04 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/45df7312_zigbee2mqtt/info
08-02 09:27:04 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/5c53de3b_esphome/info
08-02 09:27:14 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/45df7312_zigbee2mqtt/info
08-02 09:27:14 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/5c53de3b_esphome/info
08-02 09:27:24 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/45df7312_zigbee2mqtt/info
08-02 09:27:24 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/5c53de3b_esphome/info
08-02 09:27:34 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/45df7312_zigbee2mqtt/info
08-02 09:27:34 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/5c53de3b_esphome/info
08-02 09:27:44 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/45df7312_zigbee2mqtt/info
08-02 09:27:44 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/5c53de3b_esphome/info
Supervisor Logs:
[33m22-08-02 09:27:34 WARNING (MainThread) [supervisor.addons.options] Option 'devices' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)[0m
[33m22-08-02 09:27:34 WARNING (MainThread) [supervisor.addons.options] Option 'groups' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)[0m
[33m22-08-02 09:27:34 WARNING (MainThread) [supervisor.addons.options] Option 'homeassistant' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)[0m
[33m22-08-02 09:27:34 WARNING (MainThread) [supervisor.addons.options] Option 'permit_join' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)[0m
[33m22-08-02 09:27:34 WARNING (MainThread) [supervisor.addons.options] Option 'advanced' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)[0m
[33m22-08-02 09:27:34 WARNING (MainThread) [supervisor.addons.options] Option 'device_options' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)[0m
[33m22-08-02 09:27:34 WARNING (MainThread) [supervisor.addons.options] Option 'blocklist' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)[0m
[33m22-08-02 09:27:34 WARNING (MainThread) [supervisor.addons.options] Option 'passlist' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)[0m
[33m22-08-02 09:27:34 WARNING (MainThread) [supervisor.addons.options] Option 'queue' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)[0m
[33m22-08-02 09:27:34 WARNING (MainThread) [supervisor.addons.options] Option 'frontend' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)[0m
[33m22-08-02 09:27:34 WARNING (MainThread) [supervisor.addons.options] Option 'experimental' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)[0m
[33m22-08-02 09:27:34 WARNING (MainThread) [supervisor.addons.options] Option 'availability' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)[0m
[33m22-08-02 09:27:34 WARNING (MainThread) [supervisor.addons.options] Option 'ota' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)[0m
[33m22-08-02 09:27:44 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2mqtt (45df7312_zigbee2mqtt)[0m
[33m22-08-02 09:27:44 WARNING (MainThread) [supervisor.addons.options] Unknown option 'disable_led' for Zigbee2mqtt (45df7312_zigbee2mqtt)[0m
[33m22-08-02 09:27:44 WARNING (MainThread) [supervisor.addons.options] Option 'external_converters' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)[0m
[33m22-08-02 09:27:44 WARNING (MainThread) [supervisor.addons.options] Option 'devices' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)[0m
[33m22-08-02 09:27:44 WARNING (MainThread) [supervisor.addons.options] Option 'groups' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)[0m
[33m22-08-02 09:27:44 WARNING (MainThread) [supervisor.addons.options] Option 'homeassistant' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)[0m
[33m22-08-02 09:27:44 WARNING (MainThread) [supervisor.addons.options] Option 'permit_join' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)[0m
[33m22-08-02 09:27:44 WARNING (MainThread) [supervisor.addons.options] Option 'advanced' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)[0m
[33m22-08-02 09:27:44 WARNING (MainThread) [supervisor.addons.options] Option 'device_options' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)[0m
[33m22-08-02 09:27:44 WARNING (MainThread) [supervisor.addons.options] Option 'blocklist' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)[0m
[33m22-08-02 09:27:44 WARNING (MainThread) [supervisor.addons.options] Option 'passlist' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)[0m
[33m22-08-02 09:27:44 WARNING (MainThread) [supervisor.addons.options] Option 'queue' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)[0m
[33m22-08-02 09:27:44 WARNING (MainThread) [supervisor.addons.options] Option 'frontend' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)[0m
[33m22-08-02 09:27:44 WARNING (MainThread) [supervisor.addons.options] Option 'experimental' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)[0m
[33m22-08-02 09:27:44 WARNING (MainThread) [supervisor.addons.options] Option 'availability' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)[0m
[33m22-08-02 09:27:44 WARNING (MainThread) [supervisor.addons.options] Option 'ota' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)[0m

Home Assistant Core Logs:
    with util.safe_reraise():
 File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
   compat.raise_(
 File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
   raise exception
 File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
   return self._create_connection()
 File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
   return _ConnectionRecord(self)
 File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
   self.__connect()
 File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 665, in __connect
   with util.safe_reraise():
 File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
   compat.raise_(
 File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
   raise exception
 File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
   self.dbapi_connection = connection = pool._invoke_creator(self)
 File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 590, in connect
   return dialect.connect(*cargs, **cparams)
 File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 597, in connect
   return self.dbapi.connect(*cargs, **cparams)
 File "/usr/local/lib/python3.10/site-packages/MySQLdb/__init__.py", line 123, in Connect
   return Connection(*args, **kwargs)
 File "/usr/local/lib/python3.10/site-packages/MySQLdb/connections.py", line 185, in __init__
   super().__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (MySQLdb.OperationalError) (2005, "Unknown MySQL server host 'core-mariadb' (-2)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)[0m

**Comment by sabeechen** [comment]
Whatever is causing the problem will probably only show up in the supervisor logs, right after a snapshot is made and the addon's fail to start back up.  To catch it you'd need to:

- Manually start all of the add-ons that are stopped
- Manually start a backup, wait for it to finish.
- Do the bug report, or just copy any errors that show up out of the supervisor logs manually.


Separately, do you actually need to stop these addons during backup?  For a while now Home Assistant has had logic built in to pause/resume addons that need it during backup.  I've only left the option in this add-on for compatibility reasons.

**Comment by Alfamonk** [comment]
Same happens for me, but only for MariaDB. For example it starts InfluxDB, it's re-enabling the watchdog for InfluxDB, it then re-enables the watchdog for MariaDB, but misses to start MariaDB... 

08-11 14:10:16 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-11 14:10:16 INFO [backup.model.coordinator] Syncing Backups
08-11 14:10:16 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
08-11 14:10:16 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups
08-11 14:10:16 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
08-11 14:10:17 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1Hxe55ngpdTCE_7ZOC44HY_71hzRgxg7n/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
08-11 14:10:17 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota%2Cuser
08-11 14:10:17 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271Hxe55ngpdTCE_7ZOC44HY_71hzRgxg7n%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
08-11 14:10:24 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/a0d7b954_influxdb/info
08-11 14:10:24 INFO [backup.ha.addon_stopper] Starting addon 'InfluxDB'
08-11 14:10:24 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/a0d7b954_influxdb/start
08-11 14:10:25 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/a0d7b954_influxdb/info
08-11 14:10:25 INFO [backup.ha.addon_stopper] Re-enabling watchdog for addon 'InfluxDB'
08-11 14:10:25 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/a0d7b954_influxdb/options
08-11 14:10:25 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/core_mariadb/info
08-11 14:10:25 INFO [backup.ha.addon_stopper] Re-enabling watchdog for addon 'MariaDB'
08-11 14:10:25 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/core_mariadb/options
08-11 15:10:18 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-11 15:10:18 INFO [backup.model.coordinator] Syncing Backups
08-11 15:10:18 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
08-11 15:10:18 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups
08-11 15:10:18 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials

**Comment by URBANsUNITED** [comment]
I stopped worring about after i read this from stephen:

Separately, do you actually need to stop these addons during backup? For a while now Home Assistant has had logic built in to pause/resume addons that need it during backup. I've only left the option in this add-on for compatibility reasons.

I‘ved unticked all addons and I see no issues with choosing so. 
Maybe I‘ll check again after coming back from holiday.

cheers

URBANsUNITED

**Comment by Alfamonk** [comment]
My MariaDB databases are huge... I'm afraid it will not do a full database backup with it running...

**Comment by sabeechen** [comment]
Home Assistant will now "freeze" the database automatically during a snapshot.  This is like stopping it, but more efficient and IIUC it only freezes the database while that addon is being backup up (rather than during the entire backup).

Its true that almost no-one needs to make this addon stop other addons during backup, Home Assistant is supposed to take care of that automatically now.  that being said, I'd like the feature to work well.  Looking at the logs again, I suspect it might have failed because the current addon configuration is invalid for some addons.  You'll see lines like this in the supervisor logs:
```
33m22-08-02 09:27:44 WARNING (MainThread) [supervisor.addons.options] Option 'experimental' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
```
For anyone else still seeing addons fail to start back up after a backup, could you see if it still fails after resolving these errors?  Usually these happen when the configuration for an addon has changed (for example removing a configuration option) but your configuration still references the old value.

**Comment by sabeechen** [comment]
This turned out to be a bug.  Newer versions of the supervisor sometimes report the status of an addon as "error" rather than "stopped" after being stopped, I'm not sure why.  When restarting addons, _this_ addon wasn't sure what to do with the "error" state and so it would never start back up.

The latest version of the addon, v0.108.3, should fix this however I still would recommend that you just don't stop other addons while taking a backup.  Home Assistant has logic built into most addons now that prepare them appropriately for backup and handle it automatically.  MariaDB, for example, freezes the database during backup automatically which is much less disruptive than shutting it down.

If you continue to see problems with the new version, feel free to re-open this issue.
