### ISSUE TITLE
Change google account associated with hassio-google-drive-backup

### ISSUE THREAD

**Issue by rushabh55** [sabeechen/hassio-google-drive-backup#684]
I have setup the drive backup, and its working as expected. Due to size limitations on my google account, I want to start using another google account for storing backups. What is the process to signOut and reauthroize this add-on to work with another account? 

I tried finding signout/logout in settings. Didn't find anything
"Reauthorize" works on the current account, not another account
Reinstalling addon did not solve the problem

**Comment by sabeechen** [comment]
When you "reauthorize" the addon, just sign in to google using the new account instead.  If Google doesn't give you the option to choose a different account, try logging out of your old google account before doing the reauthorization.  Whatever account you authorize it with is the one it will upload to.

**Comment by sabeechen** [comment]
Please feel free to reopen this if you think there is more I can help with.
