### ISSUE TITLE
How to apply partial backups?

### ISSUE THREAD

**Issue by jangoergens** [sabeechen/hassio-google-drive-backup#689]
I am using a Raspberry Pi 3b and my sd-card just died while making an update.

I have used this addon for a while and even have a backup just before this crash. The issue is, that apparently all my latest backups are marked as partial backups and when I try to restore them to a new homeassistant instance, the web ui does not load (I can access the pi through ssh though). Only when I apply a backup that is marked as Full backup 5 months ago the the web ui works again.

![image](https://user-images.githubusercontent.com/22739836/183643473-7b37d075-2d51-4a8f-bcc1-746891f4530d.png)

I would appreciate any help with this problem! if this is a duplicate, please refer me to the relevant thread.

**Comment by sabeechen** [comment]
The partial backups you have are what Home Assistant creates automatically when you upgrade an add-on or Home Assistant.  You can avoid them by either:
1. Making sure none of the partial backusp are "saved indefinitely" and then checking "Ignore upgrade backups" in the add-on settings.
2. De-selecting the "Create a Backup" checkbox when you update an add-on or Home Assistant.

Its possible that the partial backup is just taking a long time to restore, that would look the same as a failure from the outside.
I think you'll want to get a look at the supervisor's logs to see what is failing. The most reliable way to do that is to hook up a monitor to your raspberry pi and run the command:
```bash
supervisor logs
```

You should also be able to check the logs if you have ssh access, though the command might be different depending on which SSH plugin you're using.  Looking at the logs after or during a restore should tell you whats taking so long or failed.

**Comment by jangoergens** [comment]
Thanks, that is very good to know! How are these partial backups different than full backups?

I have now choosen the Full Back Up from 5 months ago and am now applying the 8.1 backup.

![image](https://user-images.githubusercontent.com/22739836/183719753-2277d467-3bcf-4237-8397-427bf973a0d2.png)
![image](https://user-images.githubusercontent.com/22739836/183719774-11f058e2-a53a-4773-9e75-043e5a63c5d6.png)

Now these are the logs I am seeing through ssh:

![image](https://user-images.githubusercontent.com/22739836/183726737-87d7a1bd-542b-4a5b-8cb5-a33a9157b6d4.png)

```22-08-09 19:26:53 INFO (MainThread) [supervisor.backups.manager] Found 5 backup files
22-08-09 19:27:16 INFO (MainThread) [supervisor.backups.manager] Partial-Restore 250d10c2 start
22-08-09 19:27:16 INFO (MainThread) [supervisor.backups.manager] Restoring 250d10c2 Docker config
22-08-09 19:27:16 INFO (MainThread) [supervisor.backups.manager] Restoring 250d10c2 Home Assistant Core
22-08-09 19:27:16 INFO (SyncWorker_0) [supervisor.docker.interface] Stopping homeassistant application
22-08-09 19:27:41 INFO (MainThread) [supervisor.homeassistant.module] Restore Home Assistant Core config folder
22-08-09 19:27:42 INFO (MainThread) [supervisor.homeassistant.module] Restore Home Assistant Core config folder done
22-08-09 19:27:42 INFO (MainThread) [supervisor.homeassistant.module] Restore Home Assistant Core metadata
22-08-09 19:27:43 INFO (MainThread) [supervisor.backups.manager] Restore 250d10c2 wait for Home-Assistant
22-08-09 19:27:43 INFO (MainThread) [supervisor.homeassistant.core] Updating Home Assistant to version 2022.8.1
22-08-09 19:27:43 INFO (SyncWorker_3) [supervisor.docker.interface] Updating image ghcr.io/home-assistant/raspberrypi3-64-homeassistant:2022.3.6 to ghcr.io/home-assistant/raspberrypi3-64-homeassistant:2022.8.1
22-08-09 19:27:43 INFO (SyncWorker_3) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/raspberrypi3-64-homeassistant with tag 2022.8.1.
22-08-09 19:29:55 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from a0d7b954_ssh
22-08-09 19:29:55 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from a0d7b954_ssh
22-08-09 19:29:55 INFO (MainThread) [supervisor.api.middleware.security] /host/info access from a0d7b954_ssh
22-08-09 19:29:55 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from a0d7b954_ssh
22-08-09 19:30:08 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from a0d7b954_ssh
22-08-09 19:31:11 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from a0d7b954_ssh
22-08-09 19:34:50 INFO (SyncWorker_3) [supervisor.docker.interface] Cleaning homeassistant application
22-08-09 19:34:50 INFO (MainThread) [supervisor.homeassistant.core] Successfully started Home Assistant 2022.8.1
22-08-09 19:34:50 INFO (SyncWorker_1) [supervisor.docker.interface] Cleanup images: ['ghcr.io/home-assistant/raspberrypi3-64-homeassistant:2022.3.6']
22-08-09 19:35:29 ERROR (MainThread) [supervisor.homeassistant.api] Error on call https://172.30.32.1:8123/api/config: Cannot connect to host 172.30.32.1:8123 ssl:False [Connect call failed ('172.30.32.1', 8123)]
22-08-09 19:35:29 INFO (MainThread) [supervisor.homeassistant.module] Update pulse/client.config: /data/tmp/homeassistant_pulse
22-08-09 19:35:33 INFO (SyncWorker_3) [supervisor.docker.homeassistant] Starting Home Assistant ghcr.io/home-assistant/raspberrypi3-64-homeassistant with version 2022.8.1
22-08-09 19:35:33 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
22-08-09 19:42:00 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from a0d7b954_ssh
22-08-09 20:01:24 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from a0d7b954_ssh
```

**Comment by sabeechen** [comment]
The automatic backups home assistant makes have either one addon or just the Home Assistant config folder in them, whatever is being upgraded.  You can click on one to look inside.  They are kind of annoying if you use this addon, a lot of users don't know they're there and they just sit around until they fill up the SD card.  You can configure the addon to ignore and then automatically delete them after some time in the settings if you want.

I think you'd see complaints about protection mode in the logs if that were the problem.  Maybe Home Assistant isn't starting up correctly?  You can see its logs with the command:
```bash
core log
````

**Comment by jangoergens** [comment]
I see, that means that since this plugin only uploads the 4 most recent backups to Google Drive, the homeassistant backups have overwritten all backups created by this plugin? If that is the case, all changes I have made since my last full backup 5 months ago are gone (that have not directly changed the homeassistant files)?

I have not found any older backups from this plugin in my Google Drive trash, is there any way to restore them or are they permanently gone? 

Thank you for your help, I guess I have to retrace my steps and add the things I changed manually. Do you think it would be a good idea to put a PSA somewhere at the top of this repo to not use homeassistant built in backups?

**Comment by sabeechen** [comment]
For this reason, recent versions of the addon default to ignoring these "upgrade" backups and anyone upgrading from an older version sees a one-time banner in the addon web-ui recommending they change their settings.  Someone else who ran into this exact same problem a few months ago is what caused me to change the default.

Unfortunately the old backups are gone, the addon can't trash backups because the trash still eats quota in Google Drive.  
In case you didn't know, the "core_xxx.xx.xx" backups are backups of your config folder, which is where most people store most of their changes.  If one of those is recent then you'll only need to worry about manually recreating changes made to your add-ons in the last 5 months.  Id suppose that the "core_2022.8.0" is your most recent backup from a complete version since its over 80 MB.

I'm sorry it didn't backup properly for you.  This happens every once in a while, I get a bug filed where someone depended on this add-on and still had some data loss.  It makes me sad, but I don't have a way to force updates or verify their settings.

Personally I set a scheduled reminder for myself to manually double check all my backups every 3 months, since you can never be 100% certain that complex interactions don't break things silently in the background as they auto update.

**Comment by jangoergens** [comment]
That is a good point, I should start doing that in the future! 

I will migrate from SD-Card to SSD for my raspberry pi today, to avoid future data loses due to SD-Card failure. When I install a new homeassistant version and am asked to provide a backup, should I choose the core  "core_2022.8.0" or my full backup and try applying the core later on?

**Comment by sabeechen** [comment]
I'd do the full backup and then apply the core backup after, that would be the easiest to restore.

**Comment by jangoergens** [comment]
I was able to apply the full backup to the SSD, but applying the partial backups did result in the same issue. At this point I do not think pursuing this further is cost-effective step forward.

Thank you so much for your help, I will definitely apply your suggestions moving forward!
