### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by mrfixers** [sabeechen/hassio-google-drive-backup#69]
just done clean instass hassio this first program installed to try recover an image when i try to authenticate i get The server encountered an internal error or misconfiguration and was unable to complete your request.

**Comment by skynet01** [comment]
same here

**Comment by sabeechen** [comment]
I'll need to know more about your setup to help.

1. Can you share your add-on configuration?
2. Does the add-on log have any errors, or the supervisor logs? (Go to Hassio -> System > System Log)
3. Does the web-UI load if you set `"require_login": false`?

Also double check sure you're using the correct URL.  EG if you have SSL enabeld for the add-on make sure the url starts with https:// vs http://.   Also if you're doing a fresh install and have SSL enabled ensure you've actually valid certs present in your /ssl directory.

**Comment by skynet01** [comment]
I have nginx and duckdns setup. With router forwarding the port if i want to access my instance remotely. I can access https://domain.duckdns.org:1627 with no issues. When i hit authenticate it goes to
**https://philosophyofpen.com/login/backup.py?redirectbacktoken=https%3A%2F%2FDOMAIN.duckdns.org%3A1627%2Ftoken**
(i redacted my actual domain with the word DOMAIN),

Addon config
`{
  "max_snapshots_in_hassio": 4,
  "max_snapshots_in_google_drive": 4,
  "days_between_snapshots": 3,
  "use_ssl": true
}`

2) no errors just a flood of "19-06-25 23:59:49 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup"
3) it does not ask me for login

**Comment by sabeechen** [comment]
Ah thank you, its a problem with authenticating the addon with Drive (not login authentication).  I can reproduce this, so it looks like auth is broken for everyone for the time being.  I'll need to figure out whats going on with my domain.

In the meantime, you can still restore a backup by copying the snapshot from Google Drive into Hassio's /backup folder.

**Comment by sabeechen** [comment]
Looks like my server got impacted by [a big bug in Python](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=931044).  Yikes, what a mess.  

I've patched it up so you should be able to authenticate now.  I also made the error message on that page a bit more useful if anyone runs into a similar problem in the future.  Feel free to reopen if you still have problems.
