### ISSUE TITLE
Not starting?

### ISSUE THREAD

**Issue by hahchu** [sabeechen/hassio-google-drive-backup#691]
After installing, I can't seem to start the add-on or show the "open web ui"
Did I miss something?
![Screen Recording 2022-08-15 at 6 58 23 AM](https://user-images.githubusercontent.com/110723042/184558187-a51af49e-f8c1-4151-8893-11a2da5d62e2.gif)

**Comment by sabeechen** [comment]
If it isn't starting, an error is probably showing up in the supervisor  logs or the addon logs.  After trying to start the addon, see if you can find an error in these log locations:

- <kbd>Settings</kbd> > <kbd>System</kbd> > <kbd>Logs</kbd> > <kbd>"..." menu (top right)</kbd> > <kbd>Supervisor</kbd>
- <kbd>Settings</kbd> > <kbd>Add-ons</kbd> > <kbd>Home Assistant Google Drive Backup</kbd> > <kbd>Log</kbd>


Sometimes Home Assistant also just doesn't update the page automatically,  try ctrl+f5 to refresh the page to be sure.

**Comment by hahchu** [comment]
No logs unfortunately, nothing is showing

**Comment by sabeechen** [comment]
You might need to enable "advanced mode" to see the supervisor logs, its a toggle in you're Home Assistant user profile settings (<kbd>Profile (Username on the sidebar)</kbd> > <kbd>Advanced Mode</kbd>).  Its dumb that Home Assistant makes you turn that on, the logs are the only way to diagnose problems.

The supervisor logs will _definitely have something in it_, either a message saying the addon started successfully or an error message that will point us toward whats wrong.

**Comment by fribse** [comment]
I've seen this as well in my testings, the problem is starting in the later versions of HA (2022.08+). Looking in Supervisor logs it says it's already started, but looking in the GUI for google backup, it says it's not running.
If I do a 'Host Restart' on my HA Core it works after reboot.

**Comment by sabeechen** [comment]
I just want to do a sanity check on this.  A lot of times the web-ui in Home Assistant will not update right away to reflect what has happened under the hood, especially for addons.  The next time you see this, could you manually refresh the webpage just to make sure that isn't whats happening?  I've actually had quite a few "issues" filed in the past, described exactly like this, that turned out to be just a stale UI in Home Assistant.

**Comment by hahchu** [comment]
With the latest update of HA, this is now working!
