### ISSUE TITLE
Database consistent backup

### ISSUE THREAD

**Issue by boehser-enkel** [sabeechen/hassio-google-drive-backup#692]
Hi there,

is the backup of the integrated database (or MariaDB Addon) consistent? Or does it just copies away the files?

greetz

**Comment by sabeechen** [comment]
This add-on just asks Home Assistant to create a backup, it doesn't actually handle the individual files or addons.  

Each addon is allowed to respond to requests to backup in its own way, I'm not familiar with how MariaDB handles things internally.  You might consider asking on [their GitHub](https://github.com/home-assistant/addons/tree/master/mariadb).
