### ISSUE TITLE
Slow Down

### ISSUE THREAD

**Issue by cataseven** [sabeechen/hassio-google-drive-backup#699]
Hi,

After the last updated, boh backing up and sync operation slowed down. Anyone with same problem?

**Comment by sabeechen** [comment]
The most likely thing that would cause both is an increase in the size of backups, for example if your database or soem addon suddenly got larger.

Backing up is handled by Home Assistant (the addon just asks it to make one).  You might be able to check the supervisor logs to see which part of the backup is taking so long.

**Comment by cataseven** [comment]
You are absolutely right. I was upload some jpeg to media folder. That is the reason. Sorry for this stupid inconvenience

**Comment by sabeechen** [comment]
No worries, its easy to miss.
