### ISSUE TITLE
How to (temporary) backup only locally?

### ISSUE THREAD

**Issue by PieBru** [sabeechen/hassio-google-drive-backup#70]
Hi Stephen,
while trying to figure out my backup strategy, my Google Drive space is way too small.
So I tried to "disable" GD uploads by configuring "max_snapshots_in_google_drive": 0, but the addon complains about GD insufficient space at startup.
The max_snapshots_in_google_drive setting is confusing me, as the inline help defines it "The maximum number of snapshots to keep remotely in Google Drive, or 0 to disable **cleanup** of old snapshots entirely."
Zero disables cleanup? IMO if it's zero, the addon should ignore Google Drive space check and backup uploads, and do only local backups.
Thanks,
Piero

**Comment by sabeechen** [comment]
The max_snapshots_in_[google_drive|hassio] options both work the same way, setting them to zero stops the cleanup in that place.  I agree that it could be less confusing, but at this point changing it would break those already depending on it.

I think what you're trying to accomplish is to still create snapshots on a schedule, clean them up in Home Assistant, but never attempt to upload or delete them in Google Drive.   There isn't a way to configure the add-on to do that right now.

I could add an option to basically disable integration with Drive though I'd worry that doesn't make things less confusing for someone looking at the settings.  Uploading to Drive is the core feature this add-on provides.  Couldn't you stop the add-on while you're trying to sort out for storage in Google Drive?

**Comment by sabeechen** [comment]
On second thought, I'll just add the option to disable upload in the settings.

**Comment by PieBru** [comment]
You centered the point, Stephen.

Over the time I felt so comfortable with your "configure-and-forget" addon, that I would happily use it  to do frequent partial backups on an external USB drive, as well as less-frequent cloud backups on Google Drive.

Maybe this idea can be useful in your addon: as I hate maintenance workload, I built a cron script which deletes the oldest files and empty directories, repeating the loop while on the USB storage the free space is less than 10% of its whole capacity. This way I squeeze the max from the storage I bought.

Also, this frees me from calculating MotionEye media and hassio backups "time-based" cleanup: the files will be kept until there is free space.

Thanks,
Piero

**Comment by sabeechen** [comment]
I added

**Comment by sabeechen** [comment]
I've added the option to suspend uploads in the latest release, 0.98.1.  It show sup in the settings now as "Enable Google Drive Upload"
