### ISSUE TITLE
Constantly Polling Addons That have Been Uninstalled

### ISSUE THREAD

**Issue by brandon8782** [sabeechen/hassio-google-drive-backup#703]
Had an issue where after running a backup at midnight, most of my addons wouldn't start up again. Found the below in the logs. These addons have long since been removed, and are not selected in the backup settings:

08-25 12:53:53 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/core_rpc_shutdown/info
08-25 12:53:53 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/core_ssh/info
08-25 12:54:03 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/core_rpc_shutdown/info
08-25 12:54:03 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/core_ssh/info
08-25 12:54:13 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/core_rpc_shutdown/info
08-25 12:54:13 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/core_ssh/info
08-25 12:54:23 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/core_rpc_shutdown/info
08-25 12:54:23 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/core_ssh/info
08-25 12:54:33 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/core_rpc_shutdown/info
08-25 12:54:33 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/core_ssh/info
08-25 12:54:43 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/core_rpc_shutdown/info
08-25 12:54:43 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/core_ssh/info
08-25 12:54:53 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/core_rpc_shutdown/info
08-25 12:54:53 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/core_ssh/info
08-25 12:55:03 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/core_rpc_shutdown/info
08-25 12:55:03 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/core_ssh/info
08-25 12:55:13 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/core_rpc_shutdown/info
08-25 12:55:13 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/core_ssh/info
08-25 12:55:23 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/core_rpc_shutdown/info
08-25 12:55:23 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/core_ssh/info
08-25 12:55:33 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/core_rpc_shutdown/info
08-25 12:55:33 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/core_ssh/info
08-25 12:55:43 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/core_rpc_shutdown/info
08-25 12:55:43 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/core_ssh/info
08-25 12:55:53 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/core_rpc_shutdown/info
08-25 12:55:53 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/core_ssh/info
08-25 12:56:03 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/core_rpc_shutdown/info
08-25 12:56:03 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/core_ssh/info

**Comment by sabeechen** [comment]
You most likely aren't using the latest version of the add-on, a recently resolved issue would cause the add-on to poll forever like this sometimes when attempting to restart a stopped addon after a backup.  If you're still having the same problem with the latest verison, v0.108.4, can you go to "Actions" > "Report a bug" inside the addon and copy the bug report here?

**Comment by brandon8782** [comment]
Yep. You were right. After updating Home assistant, I lost the addon repository, so I never received the update. Seems to have resolved for now :)  Thanks!

**Comment by sabeechen** [comment]
I wish I knew what causes the repo to get removed sometimes.  Most of the bugs I get now are from people who were are a new version is available for this reason.
