### ISSUE TITLE
Add on has stopped working?

### ISSUE THREAD

**Issue by ritehaus** [sabeechen/hassio-google-drive-backup#707]
I've been using your add-on for a while (thank you :)) but it stopped working this morning. I tried uninstalling and reinstalling but now the add-on will not start. If I click start, I get a whirling arrow for a second then it reverts back to showing the 'Start' link.

The logs show:
09-03 09:24:33 INFO Starting server on port 8099
09-03 09:24:33 INFO Server started
09-03 09:24:33 INFO Syncing Backups

If I click the sidebar link, a message pops up saying the add-on is not running and needs to be started.

Any ideas?

**Comment by sabeechen** [comment]
The logs indicate the addon is running, it couldn't produce log output without running.  So why does home assistant say it isn't?

I haven't changed anything significant in the addon recently, so I suspect this is a problem in Home Assistant or the supervisor.  A number of other users have reported this problem and then said it goes away after a day or so by itself, which is weird.  Could I have you check the supervisor's logs to see if any errors show up there after you click "start"?  You should be able to get to them at:
<kbd>Settings</kbd > > <kbd>System</kbd> > <kbd>Logs</kbd > > <kbd>Supervisor (top right drop down)</kbd>

If the <kbd>Supervisor</kbd> options isn't in the drop-down list, please make sure you also have "Advanced Mode" enable in your user's settings in Home Assistant, eg:
<kbd>Profile Page (Picture in the bottom left)</kbd> > <kbd>Advanced Mode</kbd >

**Comment by ritehaus** [comment]
Hi Stephen

Thanks for getting back to me.

I think it has just been one of those days!

I seem to have had a load of HA issues today and the backup problem was just the first I noticed . It’s been weird with various add-ons not playing ball (ESPHome was the other big one) but now, after several restarts and just going to the pub for a while, things seem to be settling.

Backup is now up and running again.

No idea what has been going on.

Regards

David
David Wright LLB FCIM Chartered Marketer
***@***.******@***.***>
uk.linkedin.com/in/b2bgrowth<https://uk.linkedin.com/in/b2bgrowth>

T: 01457 851111
W: www.bsamarketing.com
BSA Marketing - Glossop Gasworks - Arundel Street - GLOSSOP SK13 7AB
Co Reg No:3169628

NOTE: I shall be on vacation 29th July to 8th August and then working away until 31st August.  I will be available during this time although my connection may be intermittent. I will be contactable via email. However please bear with me as it may take a little longer than usual to get back to you.

**Comment by sabeechen** [comment]
I'm glad things are working again.  If you're able to figure out what made the addon fail and you think I might be able to do something about it, please feel free to reopen this issue and let me know.  I suspect something is going wrong in Home Assistant/Supervisor.

**Comment by ritehaus** [comment]
Hi Stephen,
Yes, I agree. I’m pretty sure it was an HA issue. Not sure what it was though.

Regards, David

David Wright
BSA Marketing

From my mobile
________________________________
