### ISSUE TITLE
Add On Causes Home Assistant to Hang?

### ISSUE THREAD

**Issue by CeasarPrime** [sabeechen/hassio-google-drive-backup#708]
Yesterday I had an issue where my router went down and my Raspberry Pi 4 running HA could no long reach Google Drive.  When Home Assistant tried to connect to Google Drive at it's usual back up time that operation failed and I got a notification to that effect from the Google Drive Add On.  For some reason the whole Home Assistant application seemed to "hang" at that point.  All automations failed to execute until I cleared the Google Drive Add On notification.  
This Add On has been very useful and reliable for many months.  I am hoping there is a easy fix, or perhaps I just don't understand something!

**Comment by sabeechen** [comment]
Its unlikely this add-on caused your automations to fail to execute, the add-on only interacts with Home Assistant in only a very limited way through its API and doesn't touch automations.  I don't meant to says its impossible, just _very_ unlikely based on what I know about how Home Assistant works.

Some theories:
- Taking a backup is very CPU and disk intensive, a large backup can make Home Asisstant so slow that it appears unresponsize.
- When Home Assistant is restarted it can take a long time to start back up, during which automations might not execute.
- Whatever caused backup to continue (maybe the internet coming back online?) may have also cleared whatever prevented your automations from executing.

Regardless, if it happens again there is likely to be something in the logs that tells you what is going wrong.  You should be able to see them in <kbd>Settings</kbd> > <kbd>System</kbd> > <kbd>Logs</kbd>, it would be difficult for me to help further without a better indication of what went wrong.

**Comment by CeasarPrime** [comment]
Thank you for your response and suggestions.  I checked the logs last time but could see nothing pertinent.  I will just stay alert to whatever might be the cause of this, should it happen again.  (I hope it doesn't!)  Kind regards.

**Comment by sabeechen** [comment]
I'll close this for now, but if you think there is something else I can help with feel free to reopen it.
