### ISSUE TITLE
Backup to Team Drive?

### ISSUE THREAD

**Issue by ArnoutVerbeken** [sabeechen/hassio-google-drive-backup#71]
Hello,

Just tested this addon and it is indeed awesome.
I have moved the backup-folder from the default location to a shared drive, but when I make a new backup, the backup-folder is recreated in the default location.
I thought I had read it you could move the folder around....  Is Team Drives not supported?  Will you add it?

Thanks in advance.

**Comment by sabeechen** [comment]
It doesn't support team drive right now (or any shared Drive).  Right now if you add the folder to a Shared Drive I think the add-on will just act as though the folder were deleted, which would create a new one as you're seeing.

The reasons are that I'd have to set up a GSuite account to do any real testing and nobody has asked for it yet.  But .... I guess its time, I'll get started on it.

**Comment by ArnoutVerbeken** [comment]
I can give you an account on my google domain if you want it to test.  Once it's working I will have to delete your account, I hope you understand that.
Let me know if you are interested and we can sync private.

**Comment by sabeechen** [comment]
No worries, I just used the free trial GSuite provides.  I appreciate the offer though!
I'll have Team Drive support in the next release.

**Comment by sabeechen** [comment]
Support for Shared Drives and Team Drives is Included in the latest release, 0.98.1.  Make sure you refresh the add-on store page to make sure Hass.io sees the update.  Let me know if you run into trouble with it.

**Comment by ArnoutVerbeken** [comment]
Works like a charm.  Thank you.

**Comment by sabeechen** [comment]
Glad to hear it!

**Comment by LuigiMigliardi** [comment]
Hi, there are some news about this issue?
