### ISSUE TITLE
'generational_delete_early' is not an option in Configuration

### ISSUE THREAD

**Issue by tango2590** [sabeechen/hassio-google-drive-backup#716]
In the addon Configuration tab, `generational_delete_early` is not an option. You have to check "Purge Old Backups Early" in the UI settings. Since the rest of the configuration options are available in the addon Configuration tab and the current readme references those settings, I'd recommend just adding the `generational_delete_early` to the config tab rather than re-write the readme.

**Comment by sabeechen** [comment]
A few the mgs to try first:

- Make sure you're running the latest versions n of the addon.  Latest is 0.108.4
- In the configuration UI, make sure you check "Show unused optional configuration options" at the bottom
