### ISSUE TITLE
ENGINE Error in 'start' listener when adding to config

### ISSUE THREAD

**Issue by danner26** [sabeechen/hassio-google-drive-backup#72]
Hello, please see my config below. I added one line to it, and I got an error. I tried adding differnt options and it seems anytime I add to the config it breaks. 

**The config:**
```
{
  "max_snapshots_in_hassio": 5,
  "max_snapshots_in_google_drive": 10,
  "days_between_snapshots": 2,
  "use_ssl": true,
  "snapshot_password": "!secret snapshot_password"
}
```
**The error:**
```
07-03 11:47:44 INFO Starting server on port 8099
07-03 11:47:44 INFO Starting server on port 1627
07-03 11:47:44 ERROR [03/Jul/2019:11:47:44] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x7f08f4ab86d8>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cherrypy/process/wspbus.py", line 230, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/lib/python3.6/site-packages/cherrypy/_cpserver.py", line 179, in start
    self.httpserver, self.bind_addr = self.httpserver_from_self()
  File "/usr/lib/python3.6/site-packages/cherrypy/_cpserver.py", line 170, in httpserver_from_self
    httpserver = _cpwsgi_server.CPWSGIServer(self)
  File "/usr/lib/python3.6/site-packages/cherrypy/_cpwsgi_server.py", line 103, in __init__
    self.server_adapter.ssl_ciphers)
  File "/usr/lib/python3.6/site-packages/cheroot/ssl/builtin.py", line 101, in __init__
    self.context.load_cert_chain(certificate, private_key)
FileNotFoundError: [Errno 2] No such file or directory

07-03 11:47:44 ERROR [03/Jul/2019:11:47:44] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cherrypy/process/wspbus.py", line 268, in start
    self.publish('start')
  File "/usr/lib/python3.6/site-packages/cherrypy/process/wspbus.py", line 248, in publish
    raise exc
cherrypy.process.wspbus.ChannelFailures: FileNotFoundError(2, 'No such file or directory')
```

**Comment by sabeechen** [comment]
`FileNotFoundError: [Errno 2] No such file or directory`
This means it can't find the public and private key files the server needs to enable SSL.  Presumably, the line you added to your config is `use_ssl: true`.  Unfortunately, the web server framework the add-on uses doesn't make it easy to determine if server startup failed and just spits out this error instead.  I should do something about that.

You can specify your cert files using the config keys `keyfile` and `certfile` (more details in the [readme](https://github.com/sabeechen/hassio-google-drive-backup#configuration-options))

If you don't have cert files, you'll need to generate them.  Lots of people for example use [DuckDns](https://www.home-assistant.io/addons/duckdns/) but you can also make them with the [Let's Encrypt](https://www.home-assistant.io/addons/lets_encrypt/) add-on.

**Comment by danner26** [comment]
Ah I see! That makes sense, does the Use SSL only apply for the web page?

For instance, if I only use this locally, is there any reason to have SSL besides encrypting the traffic on the local network?

**Comment by sabeechen** [comment]
Yup its just for the web UI you see.  Communication with Google Drive is always encrypted and communication with Hass.io/Home Assistant doesn't happen over the local network.

Most use SSL if they're accessing the web UI remotely, but if it isn't exposed on the internet then you don't get much out of it.

**Comment by danner26** [comment]
Awesome, thank you. Yeah I am only exposing this internally to one computer. 
WebUI is proxied but this doesnt need to be accessed externally.

**Comment by sabeechen** [comment]
Also once I've ironed out all the kinks the next release will support ingress, which will proxy the web UI through the Home Assistant webserver.  This will make exposing the add-on's web UI through another port, using SSL, or using user/pass authentication optional and largely redundant.

I'll make separate issue to make the error message the logs print out for bad/missing SSL certs more descriptive in case anyone runs into this in the future.
