### ISSUE TITLE
Please add a title

### ISSUE THREAD

**Issue by WinterVincent** [sabeechen/hassio-google-drive-backup#723]
The add-on got the error below while trying to sync your snapshots. Some transient errors are expected (eg an upload could fail if the internet is down) but if this persist for more than a few minutes your snapshots won't get backed up and the information you see on this page may be stale. If you file an issue on GitHub with the link below, it could be helpful to provide the logs downloaded from the "Download Logs" link below

An unexpected error occurred: 404, message='Not Found', url=URL('http://hassio/snapshots')

[arrow_drop_down View Exception Details](http://192.168.5.237:8123/api/hassio_ingress/LN_3YzM4JWOebnkENNNzQavBF_yJTsfmQkzcBhXU3jI/#!)

  addon/backup/model/coordinator.py:156 (_sync)
  addon/backup/model/model.py:149 (sync)
  addon/backup/model/model.py:236 (_syncSnapshots)
  addon/backup/ha/hasource.py:224 (get)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:102 (snapshots)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:207 (_getHassioData)
  addon/backup/ha/harequests.py:174 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

**Comment by sabeechen** [comment]
Please see my comment [here](https://github.com/sabeechen/hassio-google-drive-backup/issues/652#issuecomment-1177943877)

Duplicate #652
