### ISSUE TITLE
unable to unzip backups

### ISSUE THREAD

**Issue by joselao** [sabeechen/hassio-google-drive-backup#725]
I'm unable to unzip backups, I can decompress the main backup file "Full Backup 2022-09-27 03/00/00.tar", but I got an error trying to decompress any of the tar.gz files inside, i.e.: "homeassistant.tar.gz" or any other file. I tried different (4) unrar/unzip software for decompression but unsuccessful for any of them. I put a password in the settings but the unzip process never asked me for it.

**Comment by sabeechen** [comment]
Assuming you're creating backups with a password: Home Assistant creates the backups, and it uses a custom encryption format that isn't supported by any compression/decompression utility I'm aware of.  I don't know why they use an uncommon format.

I've created a command-line utility you can use from the command line decrypt a password encrypted backup here:
https://github.com/sabeechen/decrypt-ha-backup

To the best of my knowledge this is the only way to get inside an encrypted backup without restoring it on a home assistant instance.
