### ISSUE TITLE
Failed to install addon.

### ISSUE THREAD

**Issue by DarthAnhur** [sabeechen/hassio-google-drive-backup#729]
When I clicked <INSTALL> after adding the repository I received this error. 

![image](https://user-images.githubusercontent.com/115293559/194619113-58824012-74a2-427f-8478-726f3c2335a7.png)

**Comment by sabeechen** [comment]
[Please see my comment here](https://github.com/sabeechen/hassio-google-drive-backup/issues/311#issuecomment-758159811) for a recommended resolution.

I've had a few users run into this problem, and I suspect it has to do with something going wrong in Home assistant.  Usually it goes away by itself or after following the instructions linked above.  Prior attempts to figure out whats wrong have failed, it seems like something gets messed up internally in Home assistant.  I'm going to clsoe this for now but if you think there is some way I can help further, please feel free ro reopen in.
