### ISSUE TITLE
new feature request - free space attribute

### ISSUE THREAD

**Issue by Gugulator** [sabeechen/hassio-google-drive-backup#730]
Please add a sensor attribute - remaining free space on google drive

**Comment by sabeechen** [comment]
Thats a good idea, surprised I didn't think to add it when I started keeping track of the usage in Google Drive.  I'll add it in the next version.

**Comment by sabeechen** [comment]
I've added this in v0.109.1, which I just released.  It has a new attribute called 'free_space_in_google_drive'.  Note that the attribute will be empty if:
 - you have an unlimited storage plan (Eg shared drives)
 - the addon has just started up and hasn't queried Google Drive yet.
