### ISSUE TITLE
Time between backups not working ?

### ISSUE THREAD

**Issue by Spifthespa** [sabeechen/hassio-google-drive-backup#734]
Hi guys,
I set 3 days between backups but it seems that HA does one every day. Strange
Regards

**Comment by sabeechen** [comment]
Do you have an automation in Home assistant creating them?
You should be able to tell if the addon is making the backups or home assistant is based on the name.  The addon's backups have the format "Full Backup YYY-MM-DD HH:M:SS" unless you changed it.  The addon should also tell you in its web-ui when it expects to create a new backup, is it more than a day from now?

If not, could you post what the addon gives you in Actions > Report a Bug after it creates one of the early backups?

**Comment by Spifthespa** [comment]
Hi Stephen,

Here are details following your request


###### Description:
```
If you have anything else that could help explain what happened, click 
"Markdown" above and write it here.
```

  Addon version: `0.108.4`
  Home Assistant Version: `2022.10.5`
  Supervisor Version: `2022.10.0`
  Supervisor Channel: `stable`
  Hassos Version: `9.2`
  Docker Version: `20.10.17`
  Architecture: `armv7`
  Machine: `raspberrypi3`
  Date: `2022-10-24T07:18:07.299061+00:00`
  Timezone: `Europe/Paris`
  Failure Time: `Never`
  Last Good Sync: `2022-10-24T06:56:34.800632+00:00`
  ###### Exception:
  ```
  No error could be identified automatically.
  ```
  Backups:
  ```
  {
     "HomeAssistant": {
         "backups": 6,
         "retained": 2,
         "deletable": 4,
         "name": "HomeAssistant",
         "title": "Home Assistant",
         "latest": "2022-10-24T01:00:00Z",
         "max": 4,
         "enabled": true,
         "icon": "home-assistant",
         "ignored": 0,
         "detail": "",
         "size": "3.9 GB",
         "ignored_size": "0.0 B",
         "free_space": "81.6 GB"
     },
     "GoogleDrive": {
         "backups": 4,
         "retained": 0,
         "deletable": 4,
         "name": "GoogleDrive",
         "title": "Google Drive",
         "latest": "2022-10-24T01:00:00Z",
         "max": 4,
         "enabled": true,
         "icon": "google-drive",
         "ignored": 0,
         "detail": ***@***.***",
         "size": "2.2 GB",
         "ignored_size": "0.0 B",
         "free_space": "10.7 GB"
     }
}
  ```
  ###### Config:
  ```
  {
     "Setting.BACKUP_TIME_OF_DAY": "02:00",
     "Setting.SEND_ERROR_REPORTS": true
}
  ```
  ###### Addon Logs:
  ```
  10-24 06:56:30 INFO [backup.worker.watcher] Backup directory changed
10-24 06:56:30 DEBUG [backup.model.syncer] Sync requested by Backup 
Directory Watcher
10-24 06:56:30 INFO [backup.model.coordinator] Syncing Backups
10-24 06:56:30 DEBUG [backup.ha.harequests] Making Hassio request: 
http://supervisor/supervisor/info
10-24 06:56:30 DEBUG [backup.ha.harequests] Making Hassio request: 
http://supervisor/backups
10-24 06:56:30 DEBUG [backup.drive.driverequests] Making Google Drive 
request: 
https://www.googleapis.com/drive/v3/files/1FkYn_3J-UXJM3HGoDUnZrORfxcY6mmDz/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
10-24 06:56:30 DEBUG [backup.drive.driverequests] Making Google Drive 
request: 
https://www.googleapis.com/drive/v3/about?fields=storageQuota%2Cuser
10-24 06:56:31 DEBUG [backup.drive.driverequests] Making Google Drive 
request: 
https://www.googleapis.com/drive/v3/files/?q=%271FkYn_3J-UXJM3HGoDUnZrORfxcY6mmDz%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
10-24 06:56:32 DEBUG [backup.model.syncer] Sync requested by Backup 
Directory Watcher
10-24 06:56:32 INFO [backup.model.coordinator] Syncing Backups
10-24 06:56:32 DEBUG [backup.ha.harequests] Making Hassio request: 
http://supervisor/supervisor/info
10-24 06:56:32 DEBUG [backup.ha.harequests] Making Hassio request: 
http://supervisor/backups
10-24 06:56:32 DEBUG [backup.drive.driverequests] Making Google Drive 
request: 
https://www.googleapis.com/drive/v3/about?fields=storageQuota%2Cuser
10-24 06:56:32 DEBUG [backup.drive.driverequests] Making Google Drive 
request: 
https://www.googleapis.com/drive/v3/files/?q=%271FkYn_3J-UXJM3HGoDUnZrORfxcY6mmDz%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
10-24 07:56:33 DEBUG [backup.model.syncer] Sync requested by Coordinator
10-24 07:56:33 INFO [backup.model.coordinator] Syncing Backups
10-24 07:56:33 DEBUG [backup.ha.harequests] Making Hassio request: 
http://supervisor/supervisor/info
10-24 07:56:33 DEBUG [backup.ha.harequests] Making Hassio request: 
http://supervisor/backups
10-24 07:56:33 DEBUG [backup.drive.driverequests] Requesting refreshed 
Google Drive credentials
10-24 07:56:33 DEBUG [backup.drive.driverequests] Making Google Drive 
request: 
https://www.googleapis.com/drive/v3/files/1FkYn_3J-UXJM3HGoDUnZrORfxcY6mmDz/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
10-24 07:56:33 DEBUG [backup.drive.driverequests] Making Google Drive 
request: 
https://www.googleapis.com/drive/v3/about?fields=storageQuota%2Cuser
10-24 07:56:34 DEBUG [backup.drive.driverequests] Making Google Drive 
request: 
https://www.googleapis.com/drive/v3/files/?q=%271FkYn_3J-UXJM3HGoDUnZrORfxcY6mmDz%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
10-24 08:56:34 DEBUG [backup.model.syncer] Sync requested by Coordinator
10-24 08:56:34 INFO [backup.model.coordinator] Syncing Backups
10-24 08:56:34 DEBUG [backup.ha.harequests] Making Hassio request: 
http://supervisor/supervisor/info
10-24 08:56:34 DEBUG [backup.ha.harequests] Making Hassio request: 
http://supervisor/backups
10-24 08:56:34 DEBUG [backup.drive.driverequests] Requesting refreshed 
Google Drive credentials
10-24 08:56:35 DEBUG [backup.drive.driverequests] Making Google Drive 
request: 
https://www.googleapis.com/drive/v3/files/1FkYn_3J-UXJM3HGoDUnZrORfxcY6mmDz/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
10-24 08:56:35 DEBUG [backup.drive.driverequests] Making Google Drive 
request: 
https://www.googleapis.com/drive/v3/about?fields=storageQuota%2Cuser
10-24 08:56:35 DEBUG [backup.drive.driverequests] Making Google Drive 
request: 
https://www.googleapis.com/drive/v3/files/?q=%271FkYn_3J-UXJM3HGoDUnZrORfxcY6mmDz%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
  ```
  ###### Supervisor Logs:
  ```
  [32m22-10-24 08:53:47 INFO (MainThread) 
[supervisor.resolution.evaluate] Starting system evaluation with state 
CoreState.RUNNING[0m
[32m22-10-24 08:53:47 INFO (MainThread) 
[supervisor.resolution.evaluate] System evaluation complete[0m
[32m22-10-24 08:53:47 INFO (MainThread) [supervisor.resolution.fixup] 
Starting system autofix at state CoreState.RUNNING[0m
[32m22-10-24 08:53:47 INFO (MainThread) [supervisor.resolution.fixup] 
System autofix complete[0m
[32m22-10-24 08:54:02 INFO (MainThread) [supervisor.updater] Fetching 
update data from https://version.home-assistant.io/stable.json[0m
[33m22-10-24 08:54:22 WARNING (MainThread) [supervisor.addons.options] 
Option 'interface' does not exist in the schema for Samba share 
(core_samba)[0m
[33m22-10-24 08:54:22 WARNING (MainThread) [supervisor.addons.options] 
Option 'anonymous' does not exist in the schema for Mosquitto broker 
(core_mosquitto)[0m
[33m22-10-24 08:54:22 WARNING (MainThread) [supervisor.addons.options] 
Unknown option 'init_commands' for SSH & Web Terminal (a0d7b954_ssh)[0m
[32m22-10-24 08:54:38 INFO (MainThread) [supervisor.host.info] Updating 
local host information[0m
[32m22-10-24 08:54:40 INFO (MainThread) [supervisor.host.services] 
Updating service information[0m
[32m22-10-24 08:54:40 INFO (MainThread) [supervisor.host.network] 
Updating local network information[0m
[32m22-10-24 08:54:40 INFO (MainThread) [supervisor.host.sound] 
Updating PulseAudio information[0m
[32m22-10-24 08:54:40 INFO (MainThread) [supervisor.host.manager] Host 
information reload completed[0m
[32m22-10-24 08:56:34 INFO (MainThread) 
[supervisor.api.middleware.security] /supervisor/info access from 
cebe7a76_hassio_google_drive_backup[0m
[32m22-10-24 08:56:34 INFO (MainThread) 
[supervisor.api.middleware.security] /backups access from 
cebe7a76_hassio_google_drive_backup[0m
[32m22-10-24 08:57:29 INFO (MainThread) [supervisor.homeassistant.api] 
Updated Home Assistant API token[0m
[33m22-10-24 08:59:24 WARNING (MainThread) [supervisor.addons.options] 
Option 'interface' does not exist in the schema for Samba share 
(core_samba)[0m
[33m22-10-24 08:59:24 WARNING (MainThread) [supervisor.addons.options] 
Option 'anonymous' does not exist in the schema for Mosquitto broker 
(core_mosquitto)[0m
[33m22-10-24 08:59:24 WARNING (MainThread) [supervisor.addons.options] 
Unknown option 'init_commands' for SSH & Web Terminal (a0d7b954_ssh)[0m
[33m22-10-24 09:04:26 WARNING (MainThread) [supervisor.addons.options] 
Option 'interface' does not exist in the schema for Samba share 
(core_samba)[0m
[33m22-10-24 09:04:26 WARNING (MainThread) [supervisor.addons.options] 
Option 'anonymous' does not exist in the schema for Mosquitto broker 
(core_mosquitto)[0m
[33m22-10-24 09:04:26 WARNING (MainThread) [supervisor.addons.options] 
Unknown option 'init_commands' for SSH & Web Terminal (a0d7b954_ssh)[0m
[33m22-10-24 09:09:28 WARNING (MainThread) [supervisor.addons.options] 
Option 'interface' does not exist in the schema for Samba share 
(core_samba)[0m
[33m22-10-24 09:09:28 WARNING (MainThread) [supervisor.addons.options] 
Option 'anonymous' does not exist in the schema for Mosquitto broker 
(core_mosquitto)[0m
[33m22-10-24 09:09:28 WARNING (MainThread) [supervisor.addons.options] 
Unknown option 'init_commands' for SSH & Web Terminal (a0d7b954_ssh)[0m
[33m22-10-24 09:14:30 WARNING (MainThread) [supervisor.addons.options] 
Option 'interface' does not exist in the schema for Samba share 
(core_samba)[0m
[33m22-10-24 09:14:30 WARNING (MainThread) [supervisor.addons.options] 
Option 'anonymous' does not exist in the schema for Mosquitto broker 
(core_mosquitto)[0m
[33m22-10-24 09:14:30 WARNING (MainThread) [supervisor.addons.options] 
Unknown option 'init_commands' for SSH & Web Terminal (a0d7b954_ssh)[0m
[32m22-10-24 09:18:07 INFO (MainThread) 
[supervisor.api.middleware.security] /supervisor/logs access from 
cebe7a76_hassio_google_drive_backup[0m

  ```
  ###### Home Assistant Core Logs:
  ```
  [31m2022-10-24 08:48:36.120 ERROR (SyncWorker_5) 
[homeassistant.components.influxdb] Cannot connect to InfluxDB due to 
'HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries 
exceeded with url: /write?db=Homeassistant (Caused by 
NewConnectionError('<urllib3.connection.HTTPConnection object at 
0x5a5847f0>: Failed to establish a new connection: [Errno -2] Name does 
not resolve'))'. Please check that the provided connection details 
(host, port, etc.) are correct and that your InfluxDB server is running 
and accessible. Retrying in 60 seconds.[0m
[31m2022-10-24 08:49:39.873 ERROR (SyncWorker_3) 
[homeassistant.components.influxdb] Cannot connect to InfluxDB due to 
'HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries 
exceeded with url: /write?db=Homeassistant (Caused by 
NewConnectionError('<urllib3.connection.HTTPConnection object at 
0x570f12c8>: Failed to establish a new connection: [Errno -2] Name does 
not resolve'))'. Please check that the provided connection details 
(host, port, etc.) are correct and that your InfluxDB server is running 
and accessible. Retrying in 60 seconds.[0m
[31m2022-10-24 08:50:43.625 ERROR (SyncWorker_0) 
[homeassistant.components.influxdb] Cannot connect to InfluxDB due to 
'HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries 
exceeded with url: /write?db=Homeassistant (Caused by 
NewConnectionError('<urllib3.connection.HTTPConnection object at 
0x676161d8>: Failed to establish a new connection: [Errno -2] Name does 
not resolve'))'. Please check that the provided connection details 
(host, port, etc.) are correct and that your InfluxDB server is running 
and accessible. Retrying in 60 seconds.[0m
[31m2022-10-24 08:51:47.384 ERROR (SyncWorker_2) 
[homeassistant.components.influxdb] Cannot connect to InfluxDB due to 
'HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries 
exceeded with url: /write?db=Homeassistant (Caused by 
NewConnectionError('<urllib3.connection.HTTPConnection object at 
0x5a7167d8>: Failed to establish a new connection: [Errno -2] Name does 
not resolve'))'. Please check that the provided connection details 
(host, port, etc.) are correct and that your InfluxDB server is running 
and accessible. Retrying in 60 seconds.[0m
[31m2022-10-24 08:52:51.109 ERROR (SyncWorker_1) 
[homeassistant.components.influxdb] Cannot connect to InfluxDB due to 
'HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries 
exceeded with url: /write?db=Homeassistant (Caused by 
NewConnectionError('<urllib3.connection.HTTPConnection object at 
0x57de1940>: Failed to establish a new connection: [Errno -2] Name does 
not resolve'))'. Please check that the provided connection details 
(host, port, etc.) are correct and that your InfluxDB server is running 
and accessible. Retrying in 60 seconds.[0m
[31m2022-10-24 08:53:54.615 ERROR (SyncWorker_4) 
[homeassistant.components.influxdb] Cannot connect to InfluxDB due to 
'HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries 
exceeded with url: /write?db=Homeassistant (Caused by 
NewConnectionError('<urllib3.connection.HTTPConnection object at 
0x570f1340>: Failed to establish a new connection: [Errno -2] Name does 
not resolve'))'. Please check that the provided connection details 
(host, port, etc.) are correct and that your InfluxDB server is running 
and accessible. Retrying in 60 seconds.[0m
[31m2022-10-24 08:54:58.373 ERROR (SyncWorker_4) 
[homeassistant.components.influxdb] Cannot connect to InfluxDB due to 
'HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries 
exceeded with url: /write?db=Homeassistant (Caused by 
NewConnectionError('<urllib3.connection.HTTPConnection object at 
0x59ffb988>: Failed to establish a new connection: [Errno -2] Name does 
not resolve'))'. Please check that the provided connection details 
(host, port, etc.) are correct and that your InfluxDB server is running 
and accessible. Retrying in 60 seconds.[0m
[31m2022-10-24 08:56:02.111 ERROR (SyncWorker_2) 
[homeassistant.components.influxdb] Cannot connect to InfluxDB due to 
'HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries 
exceeded with url: /write?db=Homeassistant (Caused by 
NewConnectionError('<urllib3.connection.HTTPConnection object at 
0x579a8190>: Failed to establish a new connection: [Errno -2] Name does 
not resolve'))'. Please check that the provided connection details 
(host, port, etc.) are correct and that your InfluxDB server is running 
and accessible. Retrying in 60 seconds.[0m
[31m2022-10-24 08:57:05.883 ERROR (SyncWorker_5) 
[homeassistant.components.influxdb] Cannot connect to InfluxDB due to 
'HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries 
exceeded with url: /write?db=Homeassistant (Caused by 
NewConnectionError('<urllib3.connection.HTTPConnection object at 
0x579a8a78>: Failed to establish a new connection: [Errno -2] Name does 
not resolve'))'. Please check that the provided connection details 
(host, port, etc.) are correct and that your InfluxDB server is running 
and accessible. Retrying in 60 seconds.[0m
[31m2022-10-24 08:58:09.624 ERROR (SyncWorker_5) 
[homeassistant.components.influxdb] Cannot connect to InfluxDB due to 
'HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries 
exceeded with url: /write?db=Homeassistant (Caused by 
NewConnectionError('<urllib3.connection.HTTPConnection object at 
0x58a50850>: Failed to establish a new connection: [Errno -2] Name does 
not resolve'))'. Please check that the provided connection details 
(host, port, etc.) are correct and that your InfluxDB server is running 
and accessible. Retrying in 60 seconds.[0m
[31m2022-10-24 08:59:13.361 ERROR (SyncWorker_3) 
[homeassistant.components.influxdb] Cannot connect to InfluxDB due to 
'HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries 
exceeded with url: /write?db=Homeassistant (Caused by 
NewConnectionError('<urllib3.connection.HTTPConnection object at 
0x5a7d7340>: Failed to establish a new connection: [Errno -2] Name does 
not resolve'))'. Please check that the provided connection details 
(host, port, etc.) are correct and that your InfluxDB server is running 
and accessible. Retrying in 60 seconds.[0m
[31m2022-10-24 09:00:17.143 ERROR (SyncWorker_4) 
[homeassistant.components.influxdb] Cannot connect to InfluxDB due to 
'HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries 
exceeded with url: /write?db=Homeassistant (Caused by 
NewConnectionError('<urllib3.connection.HTTPConnection object at 
0x592d8c88>: Failed to establish a new connection: [Errno -2] Name does 
not resolve'))'. Please check that the provided connection details 
(host, port, etc.) are correct and that your InfluxDB server is running 
and accessible. Retrying in 60 seconds.[0m
[31m2022-10-24 09:01:20.873 ERROR (SyncWorker_3) 
[homeassistant.components.influxdb] Cannot connect to InfluxDB due to 
'HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries 
exceeded with url: /write?db=Homeassistant (Caused by 
NewConnectionError('<urllib3.connection.HTTPConnection object at 
0x5a59a508>: Failed to establish a new connection: [Errno -2] Name does 
not resolve'))'. Please check that the provided connection details 
(host, port, etc.) are correct and that your InfluxDB server is running 
and accessible. Retrying in 60 seconds.[0m
[31m2022-10-24 09:02:24.635 ERROR (SyncWorker_5) 
[homeassistant.components.influxdb] Cannot connect to InfluxDB due to 
'HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries 
exceeded with url: /write?db=Homeassistant (Caused by 
NewConnectionError('<urllib3.connection.HTTPConnection object at 
0x579f5b50>: Failed to establish a new connection: [Errno -2] Name does 
not resolve'))'. Please check that the provided connection details 
(host, port, etc.) are correct and that your InfluxDB server is running 
and accessible. Retrying in 60 seconds.[0m
[31m2022-10-24 09:03:28.402 ERROR (SyncWorker_4) 
[homeassistant.components.influxdb] Cannot connect to InfluxDB due to 
'HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries 
exceeded with url: /write?db=Homeassistant (Caused by 
NewConnectionError('<urllib3.connection.HTTPConnection object at 
0x58a50220>: Failed to establish a new connection: [Errno -2] Name does 
not resolve'))'. Please check that the provided connection details 
(host, port, etc.) are correct and that your InfluxDB server is running 
and accessible. Retrying in 60 seconds.[0m
[31m2022-10-24 09:04:32.112 ERROR (SyncWorker_5) 
[homeassistant.components.influxdb] Cannot connect to InfluxDB due to 
'HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries 
exceeded with url: /write?db=Homeassistant (Caused by 
NewConnectionError('<urllib3.connection.HTTPConnection object at 
0x58eec388>: Failed to establish a new connection: [Errno -2] Name does 
not resolve'))'. Please check that the provided connection details 
(host, port, etc.) are correct and that your InfluxDB server is running 
and accessible. Retrying in 60 seconds.[0m
[31m2022-10-24 09:05:35.897 ERROR (SyncWorker_0) 
[homeassistant.components.influxdb] Cannot connect to InfluxDB due to 
'HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries 
exceeded with url: /write?db=Homeassistant (Caused by 
NewConnectionError('<urllib3.connection.HTTPConnection object at 
0x5a7d7568>: Failed to establish a new connection: [Errno -2] Name does 
not resolve'))'. Please check that the provided connection details 
(host, port, etc.) are correct and that your InfluxDB server is running 
and accessible. Retrying in 60 seconds.[0m
[31m2022-10-24 09:06:39.623 ERROR (SyncWorker_3) 
[homeassistant.components.influxdb] Cannot connect to InfluxDB due to 
'HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries 
exceeded with url: /write?db=Homeassistant (Caused by 
NewConnectionError('<urllib3.connection.HTTPConnection object at 
0x570e6160>: Failed to establish a new connection: [Errno -2] Name does 
not resolve'))'. Please check that the provided connection details 
(host, port, etc.) are correct and that your InfluxDB server is running 
and accessible. Retrying in 60 seconds.[0m
[31m2022-10-24 09:07:43.401 ERROR (SyncWorker_2) 
[homeassistant.components.influxdb] Cannot connect to InfluxDB due to 
'HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries 
exceeded with url: /write?db=Homeassistant (Caused by 
NewConnectionError('<urllib3.connection.HTTPConnection object at 
0x58ff18f8>: Failed to establish a new connection: [Errno -2] Name does 
not resolve'))'. Please check that the provided connection details 
(host, port, etc.) are correct and that your InfluxDB server is running 
and accessible. Retrying in 60 seconds.[0m
[31m2022-10-24 09:08:47.141 ERROR (SyncWorker_4) 
[homeassistant.components.influxdb] Cannot connect to InfluxDB due to 
'HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries 
exceeded with url: /write?db=Homeassistant (Caused by 
NewConnectionError('<urllib3.connection.HTTPConnection object at 
0x59287478>: Failed to establish a new connection: [Errno -2] Name does 
not resolve'))'. Please check that the provided connection details 
(host, port, etc.) are correct and that your InfluxDB server is running 
and accessible. Retrying in 60 seconds.[0m
[31m2022-10-24 09:09:50.888 ERROR (SyncWorker_5) 
[homeassistant.components.influxdb] Cannot connect to InfluxDB due to 
'HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries 
exceeded with url: /write?db=Homeassistant (Caused by 
NewConnectionError('<urllib3.connection.HTTPConnection object at 
0x592d8160>: Failed to establish a new connection: [Errno -2] Name does 
not resolve'))'. Please check that the provided connection details 
(host, port, etc.) are correct and that your InfluxDB server is running 
and accessible. Retrying in 60 seconds.[0m
[31m2022-10-24 09:10:54.625 ERROR (SyncWorker_5) 
[homeassistant.components.influxdb] Cannot connect to InfluxDB due to 
'HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries 
exceeded with url: /write?db=Homeassistant (Caused by 
NewConnectionError('<urllib3.connection.HTTPConnection object at 
0x5b5a01a8>: Failed to establish a new connection: [Errno -2] Name does 
not resolve'))'. Please check that the provided connection details 
(host, port, etc.) are correct and that your InfluxDB server is running 
and accessible. Retrying in 60 seconds.[0m
[31m2022-10-24 09:11:58.247 ERROR (SyncWorker_4) 
[homeassistant.components.influxdb] Cannot connect to InfluxDB due to 
'HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries 
exceeded with url: /write?db=Homeassistant (Caused by 
NewConnectionError('<urllib3.connection.HTTPConnection object at 
0x58ff16e8>: Failed to establish a new connection: [Errno -2] Name does 
not resolve'))'. Please check that the provided connection details 
(host, port, etc.) are correct and that your InfluxDB server is running 
and accessible. Retrying in 60 seconds.[0m
[31m2022-10-24 09:13:01.869 ERROR (SyncWorker_2) 
[homeassistant.components.influxdb] Cannot connect to InfluxDB due to 
'HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries 
exceeded with url: /write?db=Homeassistant (Caused by 
NewConnectionError('<urllib3.connection.HTTPConnection object at 
0x5607aa48>: Failed to establish a new connection: [Errno -2] Name does 
not resolve'))'. Please check that the provided connection details 
(host, port, etc.) are correct and that your InfluxDB server is running 
and accessible. Retrying in 60 seconds.[0m
[31m2022-10-24 09:14:05.632 ERROR (SyncWorker_1) 
[homeassistant.components.influxdb] Cannot connect to InfluxDB due to 
'HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries 
exceeded with url: /write?db=Homeassistant (Caused by 
NewConnectionError('<urllib3.connection.HTTPConnection object at 
0x579df340>: Failed to establish a new connection: [Errno -2] Name does 
not resolve'))'. Please check that the provided connection details 
(host, port, etc.) are correct and that your InfluxDB server is running 
and accessible. Retrying in 60 seconds.[0m
[31m2022-10-24 09:15:09.371 ERROR (SyncWorker_5) 
[homeassistant.components.influxdb] Cannot connect to InfluxDB due to 
'HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries 
exceeded with url: /write?db=Homeassistant (Caused by 
NewConnectionError('<urllib3.connection.HTTPConnection object at 
0x57ad5298>: Failed to establish a new connection: [Errno -2] Name does 
not resolve'))'. Please check that the provided connection details 
(host, port, etc.) are correct and that your InfluxDB server is running 
and accessible. Retrying in 60 seconds.[0m
[31m2022-10-24 09:16:13.121 ERROR (SyncWorker_3) 
[homeassistant.components.influxdb] Cannot connect to InfluxDB due to 
'HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries 
exceeded with url: /write?db=Homeassistant (Caused by 
NewConnectionError('<urllib3.connection.HTTPConnection object at 
0x579f5898>: Failed to establish a new connection: [Errno -2] Name does 
not resolve'))'. Please check that the provided connection details 
(host, port, etc.) are correct and that your InfluxDB server is running 
and accessible. Retrying in 60 seconds.[0m
[31m2022-10-24 09:17:16.894 ERROR (SyncWorker_5) 
[homeassistant.components.influxdb] Cannot connect to InfluxDB due to 
'HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries 
exceeded with url: /write?db=Homeassistant (Caused by 
NewConnectionError('<urllib3.connection.HTTPConnection object at 
0x5b731ec8>: Failed to establish a new connection: [Errno -2] Name does 
not resolve'))'. Please check that the provided connection details 
(host, port, etc.) are correct and that your InfluxDB server is running 
and accessible. Retrying in 60 seconds.[0m
[31m2022-10-24 09:17:49.289 ERROR (MainThread) 
[frontend.js.latest.202210100] http://192.168.1.30:8123/lovelace/0:0:0 
Uncaught [0m

  ```

Le 24/10/2022 à 00:57, Stephen Beechen a écrit :

**Comment by sabeechen** [comment]
Apologies for taking so long to get back to you, home life has been taking more time for me recently.

Nothing in your configuration or logs stands out to me as a problem, you are using almost default settings (except for setting the time of day for the backup) which should only make backups once every 3 days as you expect.

Are you sure the addon is making these daily backups?  Its possible for Home Assistant to make backups by itself if you have an automation set up to do so, you should be able to tell by the name if they're from the addon vs the automation.  Backups from the addon will have a name like "Full Backup 2022-11-03 01:00:00".

If not, what does the addon say in the web-ui about the next backup?  It should have an estimate on the left side about when the next backup will be made, does look like it think the next backup is 3 days from the last one?

**Comment by Spifthespa** [comment]
Stephen,

Thanks for answer. No problem for delay as this problem is definitely 
not critical

Actually I use Google Drive Backup

Here is a snapshot of HA Backup panel. What is confusing me is the 
mention Next Backup in 3 days but on right one automatic backup actually 
done every day

It seams there is an addition of backups done by complementary module 
and, may be, those made by standard HA system...


In addition I receive an error about a rest command - Perhaps another 
problem without link with first one

I certainly miss something...

Regards

Patrice


Le 04/11/2022 à 11:39, Stephen Beechen a écrit :

**Comment by sabeechen** [comment]
I've let this fall off my radar again, so I apologize.  I think you're saying that there might be something else creating backups.  You also mention a screenshot, but there isn't one attached to your post.  If you're replying to github through email then image attachments don't get transferred over so its better to use https://github.com

**Comment by sabeechen** [comment]
I'm going to close this issue for now, but if you think there is something else I can help with please reopen and let me know.
