### ISSUE TITLE
unable to finish a backup to Google Drive

### ISSUE THREAD

**Issue by vpoma777** [sabeechen/hassio-google-drive-backup#736]
I'm unable to finish a backup... I haven't internet problems

If you have anything else that could help explain what happened, click "Markdown" above and write it here.
Addon version: 0.108.4 Home Assistant Version: 2022.10.4 Supervisor Version: 2022.10.0 Supervisor Channel: stable Hassos Version: 8.4 Docker Version: 20.10.14 Architecture: amd64 Machine: qemux86-64 Date: 2022-10-29T19:12:50.537761+00:00 Timezone: Europe/Rome Failure Time: 2022-10-29T19:03:53.514698+00:00 Last Good Sync: 2022-10-29T18:52:27.324147+00:00

Exception:

 addon/backup/model/coordinator.py:177 (_sync)
 addon/backup/model/model.py:224 (sync)
 addon/backup/drive/drivesource.py:202 (save)
 addon/backup/drive/driverequests.py:295 (create)
 addon/backup/drive/driverequests.py:367 (retryRequest)
 addon/backup/creds/driverequester.py:30 (request)
 addon/backup/tracing_session.py:35 (_request)
 /site-packages/aiohttp/client.py:559 (_request)
 /site-packages/aiohttp/client_reqrep.py:898 (start)
 /site-packages/aiohttp/streams.py:616 (read)
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer

Backups:

{
   "HomeAssistant": {
       "backups": 5,
       "retained": 0,
       "deletable": 5,
       "name": "HomeAssistant",
       "title": "Home Assistant",
       "latest": "2022-10-29T12:43:38Z",
       "max": 7,
       "enabled": true,
       "icon": "home-assistant",
       "ignored": 0,
       "detail": "",
       "size": "19.6 GB",
       "ignored_size": "0.0 B",
       "free_space": "14.8 GB"
   },
   "GoogleDrive": {
       "backups": 18,
       "retained": 0,
       "deletable": 18,
       "name": "GoogleDrive",
       "title": "Google Drive",
       "latest": "2022-10-26T22:31:22Z",
       "max": 30,
       "enabled": true,
       "icon": "google-drive",
       "ignored": 0,
       "detail": "vincenzopoma@gmail.com",
       "size": "68.7 GB",
       "ignored_size": "0.0 B",
       "free_space": "29.9 GB"
   }
}
Config:
{
   "Setting.MAX_BACKUPS_IN_HA": 7,
   "Setting.MAX_BACKUPS_IN_GOOGLE_DRIVE": 30,
   "Setting.DAYS_BETWEEN_BACKUPS": 1.0,
   "Setting.BACKUP_TIME_OF_DAY": "02:00",
   "Setting.SPECIFY_BACKUP_FOLDER": true
}
Addon Logs:
10-29 21:01:53 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdvRw1R98Z7NDsSdAjMcBKKGVNFHbkbfk2oGPxu4-0xXT5TDlH_zZwhotw-8tzXUYPzLNnmwRhRQq5t_5kGUuDlE
10-29 21:02:02 DEBUG [backup.drive.drivesource] Uploading Backup Manuale 29-10-2022 dopo FritzBox 64.56%
10-29 21:02:03 DEBUG [backup.drive.driverequests] Sending 8650752 bytes to Google Drive
10-29 21:02:03 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdvRw1R98Z7NDsSdAjMcBKKGVNFHbkbfk2oGPxu4-0xXT5TDlH_zZwhotw-8tzXUYPzLNnmwRhRQq5t_5kGUuDlE
10-29 21:02:12 DEBUG [backup.drive.drivesource] Uploading Backup Manuale 29-10-2022 dopo FritzBox 64.76%
10-29 21:02:13 DEBUG [backup.drive.driverequests] Sending 8650752 bytes to Google Drive
10-29 21:02:13 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdvRw1R98Z7NDsSdAjMcBKKGVNFHbkbfk2oGPxu4-0xXT5TDlH_zZwhotw-8tzXUYPzLNnmwRhRQq5t_5kGUuDlE
10-29 21:02:22 DEBUG [backup.drive.drivesource] Uploading Backup Manuale 29-10-2022 dopo FritzBox 64.97%
10-29 21:02:23 DEBUG [backup.drive.driverequests] Sending 8650752 bytes to Google Drive
10-29 21:02:23 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdvRw1R98Z7NDsSdAjMcBKKGVNFHbkbfk2oGPxu4-0xXT5TDlH_zZwhotw-8tzXUYPzLNnmwRhRQq5t_5kGUuDlE
10-29 21:02:32 DEBUG [backup.drive.drivesource] Uploading Backup Manuale 29-10-2022 dopo FritzBox 65.17%
10-29 21:02:32 DEBUG [backup.drive.driverequests] Sending 8650752 bytes to Google Drive
10-29 21:02:32 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdvRw1R98Z7NDsSdAjMcBKKGVNFHbkbfk2oGPxu4-0xXT5TDlH_zZwhotw-8tzXUYPzLNnmwRhRQq5t_5kGUuDlE
10-29 21:02:42 DEBUG [backup.drive.drivesource] Uploading Backup Manuale 29-10-2022 dopo FritzBox 65.37%
10-29 21:02:42 DEBUG [backup.drive.driverequests] Sending 8650752 bytes to Google Drive
10-29 21:02:42 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdvRw1R98Z7NDsSdAjMcBKKGVNFHbkbfk2oGPxu4-0xXT5TDlH_zZwhotw-8tzXUYPzLNnmwRhRQq5t_5kGUuDlE
10-29 21:02:52 DEBUG [backup.drive.drivesource] Uploading Backup Manuale 29-10-2022 dopo FritzBox 65.57%
10-29 21:02:52 DEBUG [backup.drive.driverequests] Sending 8650752 bytes to Google Drive
10-29 21:02:52 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdvRw1R98Z7NDsSdAjMcBKKGVNFHbkbfk2oGPxu4-0xXT5TDlH_zZwhotw-8tzXUYPzLNnmwRhRQq5t_5kGUuDlE
10-29 21:03:02 DEBUG [backup.drive.drivesource] Uploading Backup Manuale 29-10-2022 dopo FritzBox 65.77%
10-29 21:03:02 DEBUG [backup.drive.driverequests] Sending 8650752 bytes to Google Drive
10-29 21:03:02 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdvRw1R98Z7NDsSdAjMcBKKGVNFHbkbfk2oGPxu4-0xXT5TDlH_zZwhotw-8tzXUYPzLNnmwRhRQq5t_5kGUuDlE
10-29 21:03:12 DEBUG [backup.drive.drivesource] Uploading Backup Manuale 29-10-2022 dopo FritzBox 65.97%
10-29 21:03:12 DEBUG [backup.drive.driverequests] Sending 8650752 bytes to Google Drive
10-29 21:03:12 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdvRw1R98Z7NDsSdAjMcBKKGVNFHbkbfk2oGPxu4-0xXT5TDlH_zZwhotw-8tzXUYPzLNnmwRhRQq5t_5kGUuDlE
10-29 21:03:22 DEBUG [backup.drive.drivesource] Uploading Backup Manuale 29-10-2022 dopo FritzBox 66.17%
10-29 21:03:22 DEBUG [backup.drive.driverequests] Sending 8650752 bytes to Google Drive
10-29 21:03:22 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdvRw1R98Z7NDsSdAjMcBKKGVNFHbkbfk2oGPxu4-0xXT5TDlH_zZwhotw-8tzXUYPzLNnmwRhRQq5t_5kGUuDlE
10-29 21:03:53 ERROR [backup.model.coordinator] 
 addon/backup/model/coordinator.py:177 (_sync)
 addon/backup/model/model.py:224 (sync)
 addon/backup/drive/drivesource.py:202 (save)
 addon/backup/drive/driverequests.py:295 (create)
 addon/backup/drive/driverequests.py:367 (retryRequest)
 addon/backup/creds/driverequester.py:30 (request)
 addon/backup/tracing_session.py:35 (_request)
 /site-packages/aiohttp/client.py:559 (_request)
 /site-packages/aiohttp/client_reqrep.py:898 (start)
 /site-packages/aiohttp/streams.py:616 (read)
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer

10-29 21:03:53 INFO [backup.model.coordinator] I'll try again in an hour

**Comment by vpoma777** [comment]
restarting HA it has completed the backup fine

**Comment by sabeechen** [comment]
I had a recent issue where someone had a very similar problem and solved it by [changing the virtualized network card from VirtIO to Intel E1000 in proxmox](https://github.com/sabeechen/hassio-google-drive-backup/issues/733#issuecomment-1279849071).

If you're also using proxmox, could that be the problem here too?

**Comment by sabeechen** [comment]
I'm going to close this issue for now, but if you think there is something else I can help with please reopen and let me know.
