### ISSUE TITLE
Error opening archive: Unrecognised archive format

### ISSUE THREAD

**Issue by asellitt** [sabeechen/hassio-google-drive-backup#737]
Hello,

I recently installed this add on and was testing it out to see if things were working, but it seems that i'm unable to open the archive.

I can open up the top level archive, but when i try to open up the actual backup files, it fails:

```
 $> tar -xvf homeassistant.tar.gz
tar: Error opening archive: Unrecognized archive format
```

The backups are created with a password, but i'm pretty sure the tar format doesnt support passwords. So, i'm guessing its compressed, then encrypted, but I couldnt find any info in the readme about how to unencrypt the backups.

**Comment by sabeechen** [comment]
You're right!  The encryption format that HA uses is non-standard and to to my knowledge not supported by any common decompression utility.  Side note: HA actually creates the backup, this addon just copies it to Drive.

I get this question, how to open encrypted backups, a lot.  So much in fact that I [wrote a little utility](https://github.com/sabeechen/decrypt-ha-backup) that will decrypt backups. I wish HA just used zip or 7zip so it would be less confusing.
