### ISSUE TITLE
Ignore a specific folder, is it possible?

### ISSUE THREAD

**Issue by obaldius** [sabeechen/hassio-google-drive-backup#743]
Not sure this goes here so sorry in advanced. 

Is it possible to ignore a specific folder from whithin the config folder? 

I'd like to ignore config/www/this_folder

thanks in advanded

**Comment by sabeechen** [comment]
[Unfortunately, no.](https://github.com/sabeechen/hassio-google-drive-backup#can-i-exclude-specific-sub-folders-from-my-backup)  This is a restriction in Home Assistant so there isn't a way for the this addon to work around it.
