### ISSUE TITLE
Google Backup Translation

### ISSUE THREAD

**Issue by Betacart** [sabeechen/hassio-google-drive-backup#746]
Hi, I would like to translate Google Backup to Czech. Can you let me know, what to do?
Thanks, Jirka

**Comment by sabeechen** [comment]
Duplicate #598

I'd like to do translations, but I didn't have it on the roadmap when I started the addon and there is a TON of work I'd have to do to extract all of the language out of the addon and make it translatable.

I appreciate your offer and I'll keep you in mind for when I get to the point where I can make use of translators.

**Comment by Betacart** [comment]
Hi,

understand you well. So, once you will be ready, definitely let me know!

Jirka
