### ISSUE TITLE
Allow selecting the backup folder (eg support multiple instances on the same Google Drive account)

### ISSUE THREAD

**Issue by 01kbpatel** [sabeechen/hassio-google-drive-backup#75]
Is it possible to backup from two separate instances of HA (production and dev) to single google account, keeping both sets of backups as per individual configurations.

**Comment by sabeechen** [comment]
Right now you can't.  The logic the add-on uses right now when you connect an account is to look for the most recently created snapshot folder that isn't in the trash and upload snapshots there, creating it if none are found.  As a result if you connect two instances of the add-on to the same Drive account, they'll use the same folder and constantly try to overwrite eachother.

Uploading into a user-selected folder is something I'd like to add, it would just take some time to implement as there is a good amount of logic and UI in the add-on I'd have to change around.

I've had less time to implement new features recently (mostly focused on fixing bugs) but I'll aim to make this a priority for the release after the next one.

**Comment by elliottmarter** [comment]
Just commenting so you know my use case also.

I Have two HA instances and both addons set to allow 10 snapshots in the cloud (but this ends up being 5 each). I have two "homes" and so both instances are totally separate.

Not sure if this is at all useful but another google drive addon I used (may have been this one???) made me specify the google drive folder ID (which is at the end of the URL).

So you could allow for an optional parameter in the config that would attempt to backup to the specified folder ID and then the user could simply create whatever folders he wanted for as many addons as he liked.

**Comment by sabeechen** [comment]
I've added this in the latest release v0.100.0.  Theres a checkbox in the settings dialog now for selecting a new snapshot folder.
