### ISSUE TITLE
Plex addon backing up 'new' drivers?

### ISSUE THREAD

**Issue by Preference22** [sabeechen/hassio-google-drive-backup#750]
Hello,

I noticed yesterday that my backup size for the plex addon went to 10 times the size it was (24 mb to 242 mb). This is just the addon data and not the media (movies etc.). I opened a post on reddit and via that I concluded that in the larger backup file a map is added in the plex backup folder called 'drivers' with a subfolder called 'icr-9-linux-x86_64'. This map allocates for the size gain in the backup.

Someone on reddit concluded that these drivers are not supposed to be in the backup and thus should be excluded and suggested to open an issue for it on github.

![image](https://user-images.githubusercontent.com/62695220/202895925-b3ec9c3e-585e-48b3-adb1-79ed8ab0ad74.png)

If you need any more information, please let me know. Love the work! Thanks in advance @sabeechen.

Edit: Figured I had a few small updates on core/supervisor open so did a full update but the problem still persists. More info below:

- Running Hassio OS
- Home Assistant 2022.11.3
- Supervisor 2022.10.2
- Operating System 9.3
- Google drive back up: 0.109.2
- Plex: 3.1.2

**Comment by sabeechen** [comment]
The addon actually just asks Home Assistant to create the backup, and Home Assistant only lets you [include or exclude the main top-level folders](https://github.com/sabeechen/hassio-google-drive-backup#can-i-exclude-specific-sub-folders-from-my-backup).  More specific inclusion/exclusion would need to be added in the supervisor, which I'd be happy to support if it were made available.

I don't mean to bump you around between projects, but you might have some success if you notified the devs in the [Plex Add-on](https://github.com/hassio-addons/addon-plex) repo.  I don't know anything about Plex how works, and I'm not aware of a way for add-ons to tell Home Assistant to ignore one of their folders, but maybe they could do something?
