### ISSUE TITLE
Unable to back up shows pending

### ISSUE THREAD

**Issue by copetogo** [sabeechen/hassio-google-drive-backup#751]
Not sure this is only a problem with me . I am  HA core version 2022.11.2  HA supervisor 2022.11.0. My google drive just goes in pending mode. i was not able to find anything is HA logs. I am attaching the debug logs of the addon
[home-assistant-google-drive-backup.log](https://github.com/sabeechen/hassio-google-drive-backup/files/10053958/home-assistant-google-drive-backup.log)

**Comment by tybo611** [comment]
I too see this issue.

**Comment by Bascht74** [comment]
Wait 30 minutes and restart host. Sometime it goes away… 

Open HA shell and enter „ha supervisor repair“ watch the supervisor logs (no output in shell)

**Comment by emilinsweden** [comment]
I reinstalled HA from backup and it is working.

**Comment by Mariusthvdb** [comment]
my backups seem to be fine, but the 2 entities are either not created at startup, and, after reloading the add-on, eternally like this

<img width="494" alt="Scherm­afbeelding 2022-11-23 om 10 48 43" src="https://user-images.githubusercontent.com/33354141/203531975-56d44755-797c-4db3-86d8-a915941e3c83.png">

posted in the community: https://community.home-assistant.io/t/add-on-home-assistant-google-drive-backup/107928/699?u=mariusthvdb

logs in the add-on:

[home-assistant-google-drive-backup.log](https://github.com/sabeechen/hassio-google-drive-backup/files/10074861/home-assistant-google-drive-backup.log)

no issues at Google, drive is fully available an as posted, the left side menu add-on page shows all is in order?

**Comment by sabeechen** [comment]
@Mariusthvdb The addon uses home assistant in a non-standard way which makes the sensors take a while (a few minutes) to come back after restarting Home Assistant.  Its an [open issue](https://github.com/sabeechen/hassio-google-drive-backup/issues/586) that I'll resolve when I have the time available.  I'm guess that the sensors are available now that that addon has sat around for a while.

@others
I wasn't around for the supervisor issues is 2022.11.0 (has some IRL problems to deal with) and its hard for me to tell in this thread if anyone is still having a problem with the addon.  Is there still something I need to address or provide help with?

**Comment by Bascht74** [comment]
@sabeechen not for me :-) After updating to 2022.11.2, wait 1/2 hour, ha supervisor repair + restart after finish -> everything is working fine.

**Comment by sabeechen** [comment]
Thanks.  I'll close this for now, but anyone feel free to re-open it if I missed something.

**Comment by Mariusthvdb** [comment]
yes, it returned finally.

>  The addon uses home assistant in a non-standard way which makes the sensors take a while (a few minutes) to come back after restarting Home Assistant

Aware that is t be expected, and used to that. his however was something entirely different, and not seen before.
If it comes back, I'll be back ;-)
