### ISSUE TITLE
Addon for Dockerized Hassio

### ISSUE THREAD

**Issue by Blacksimo** [sabeechen/hassio-google-drive-backup#757]
Hi everyone, i was wondering if there exist a version of the addon that can work with the dockerized version of Home Assistant (i.e. when Add-on Store does not show up in Home Assistant side panel)

**Comment by sabeechen** [comment]
Duplicate #586

Unfortunately, no.  The addon is very tightly coupled with the supervisor (aka hassio).  Id like for it to work within Home Assistant by itself, but its surprisingly complicated effort that I won't have complete for a long time.
