### ISSUE TITLE
Out of storage error 

### ISSUE THREAD

**Issue by AalianKhan** [sabeechen/hassio-google-drive-backup#76]
Hello, I just started to use this addon and I really like it. after a few uploads to google drive, I got an error saying I am out of storage. The problem is that I am not out of storage. I have about 6 gigs available and my snapshots are 5 MBs big. Any ideas?

**Comment by sabeechen** [comment]
Could be there's a bunch of big files in your trash, I'm not sure how stuff in the trash gets counted toward the storage limit.  Do the addon logs say anything else and do you have trouble uploading files to drive.google.com?

**Comment by AalianKhan** [comment]
Yes trash does not get deleted automatically and does get counted in the total storage. But even after deleting it, the logs still say out of storage

**Comment by AalianKhan** [comment]
I also have motion eye that saves my camera feeds and it was getting pretty big so it was saving all the feeds in the snapshot too. so that's why it couldn't make a snapshot because it was doubling the storage. so now I'm only doing partial snapshots and its working
