### ISSUE TITLE
Backup location - It looks like you're low on disk space.

### ISSUE THREAD

**Issue by Gordan74** [sabeechen/hassio-google-drive-backup#768]
I see following error:
 0 (0.0 B) in Home Assistant

    0.0 B remaining info 

Where are backups located so I can manually delete them.
Please help me.
Thanks.
Gordan

**Comment by sabeechen** [comment]
- If you have any backups, you can delete them from the addon-on's web-ui.  Click on the backup and click delete.
- If that doesn't work, you can delete them from the home assistant web-ui in Settings > System > Backups
- If that doesn't work you can install a few addons that give you more direct access to the file system:
  - The "Files" addon works, but remember to disable the "Enforce Basepath" option when you install it.  Bakcups are in the "/backup" directory.  Backups will have random-looking names like "xxxxxx.tar"
  - The "Samba" addon gets you fiel access too, though setting up samba uthentication and access can be a pain.

If you don't see any backups already in the web UI its likely that something else (eg in your config directory) is taking up all the space.
