### ISSUE TITLE
Provide instructions for Home assistant running in container

### ISSUE THREAD

**Issue by carefulcomputer** [sabeechen/hassio-google-drive-backup#773]
Currently all instructions for this are provided as an 'add-on' which requires Home Assistant Supervised/OS. Since this add-on uses docker, I am hoping it is easy to install as a container and use it in home assistants running in containers. Please provide instruction on how to install it as docker container and it's docker compose file (ports/mounts etc).

**Comment by sabeechen** [comment]
Please [see here](https://github.com/sabeechen/hassio-google-drive-backup/issues/586) for some context.  This is something I'd like to support but a lot of work needs to be done to make it happen.
