### ISSUE TITLE
If you specify a stopped app to stop before backup, its started afterwards when it should remain stopped

### ISSUE THREAD

**Issue by magiva** [sabeechen/hassio-google-drive-backup#775]
I have motioneye stopped with all options to start when boot, watchdog, etc all turned off.
It is still listed in my backup to backup but stop beforehand.

it seems that backup is then starting the app without knowing if it was started before it was stopped.

**Comment by sabeechen** [comment]
Let me make sure I understand.  You have the MotionEye addon stopped, you take a backup, and then it starts the addon after the backup completes?

Can you copy the contents of of "Actions" > "Report a Bug" in the web-ui right after a backup completes?  It should be noticing that the addon isn't running and ignore it after a backup.

**Comment by magiva** [comment]
thats what i see happening yes.  i concluded it was this addon doing this
because i only see this on the morning after the backup occurs on the
previous night.  consistently

ill take logs tonight when im home

**Comment by magiva** [comment]
i no longer think its backup thats causing this, more a reboot but not all
the time, strange that motioneye for example starts when its not ticked.
