### ISSUE TITLE
Select "+ don't ignore" add-on backup

### ISSUE THREAD

**Issue by sky7176** [sabeechen/hassio-google-drive-backup#776]
I selected the "+ don't ignore" button in a backup of an add-on, its backup disappeared from the list of ignored backups, but I don't understand where it went.

I don't see it on google drive and it's gone in the Hassio Backup folder.

How does this option work?

Many thanks
Giuseppe

**Comment by sabeechen** [comment]
When you click "+ Don't Ignore" it gets included in the list of backups that should be synced to Google Drive, the big list in the web-ui that isn't collapsed by default.  Depending on what your settings are the addon may have deleted it if, for example, it was the oldest backup and adding it put you over your backup count limit.
