### ISSUE TITLE
Can't restore from Google Drive backup

### ISSUE THREAD

**Issue by Jonosaurus** [sabeechen/hassio-google-drive-backup#779]
Having issues restoring from my Google Drive backups, using the add-on gives me a timeout error (NaN% (Beyond mortal comprehension) - (determining speed) - Started undefined) and shows this in the log

01-10 18:44:32 ERROR 
  addon/backup/ha/hasource.py:369 (save)
  addon/backup/ha/harequests.py:33 (wrap_and_call)
  addon/backup/ha/harequests.py:91 (upload)
  addon/backup/ha/harequests.py:255 (_postHassioData)
  addon/backup/ha/harequests.py:33 (wrap_and_call)
  addon/backup/ha/harequests.py:263 (_sendHassioData)
  addon/backup/ha/harequests.py:208 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1005 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('http://supervisor/backups/new/upload')

Tried copying the file from Drive with Samba and it's not visible in the back up option in the GUI and it's not visible, guessing it might be because it's compressed?

**Comment by sabeechen** [comment]
That error means that Home Assistant, the supervisor specifically, isn't recognizing the backup file as a valid backup.  Thats not good and usually indicates the file is corrupt.  To help figure out whats wrong:
- Make sure the backup is in the /backup folder, which it sound like you already did with the Samba Add-on
- Make sure "Advanced Mode" is enabled in your Home Assistant user profile (eg http://homeassistant.local:8123/profile)
- In Home Assistant go to Settings > System > Backups > ... (top right) > Reload
- Next check the supervisor logs at Settings > System > Logs > Supervisor (top right drop down)

Something should be printed in the logs there about failing to import the backup file, hopefully with an easy-to-fix reason why.  If you had Hard Drive corruption, its possible that corrupted data was copied to Google Drive and the data inside is unrecoverable.  Its also possible that _some_ but not all of the data is recoverable.  If you have earlier backups, you might need to restore one of those instead.

Backups are just compressed tar files, which can be opened with a utility like [7-zip](https://www.7-zip.org/), so thats another way to inspect the contents of the backup.  

If you encrypt your backups with a password, then you'll need to use a utility I wrote [here ](https://github.com/sabeechen/decrypt-ha-backup) to decrypt its contents, the supervisor uses an esoteric encryption format that isn't recognized by any other utilities I'm aware of.   Decrypting may just error out if the backup is corrupted.

Depending on what the supervisor says is wrong with the backup I _may_ be able to provide further guidance, as I have some knowledge of how the supervisor expects backups to be formatted.

**Comment by Jonosaurus** [comment]
I've tried using all the backups that are in my Drive.

This is the log from the Supervisor

23-01-11 06:35:06 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-01-11 06:46:19 INFO (MainThread) [supervisor.api.middleware.security] /backups/new/upload access from cebe7a76_hassio_google_drive_backup
23-01-11 06:48:16 ERROR (MainThread) [supervisor.backups.backup] Can't read backup tarfile /data/tmp/tmp3evra0pf/backup.tar: unexpected end of data

I've tried using 7-zip to uncompress the file but that gives me an error, on a Chromebook I can open the folder but just see gibberish in the files I can open. Weirdly, I can't do anything the main file it just gives me an error. 

Because it's letting me access some of the config via my Chromebook I can see the config file for the add-on


  "version": 2,
  "slug": "**",
  "name": "Full Backup 2023-01-04 15:28:38",
  "date": "2023-01-04T15:28:40.000930+00:00",
  "type": "full",
  "2022.12.1": "2022.12.1",
  "folders": [
    "share",
    "addons/local",
    "ssl",
    "media"
  ],
  "docker": {
    "registries": {}
  },
  "crypto": null,
  "addons": [
    {
      "slug": "a0d7b954_vscode",
      "name": "Studio Code Server",
      "version": "5.5.1",
      "size": 2.94
    },
    {
      "slug": "core_configurator",
      "name": "File editor",
      "version": "5.4.2",
      "size": 0.0
    },
    {
      "slug": "5c53de3b_esphome",
      "name": "ESPHome",
      "version": "2022.12.3",
      "size": 0.0
    },
    {
      "slug": "a0d7b954_ssh",
      "name": "SSH & Web Terminal",
      "version": "13.0.0",
      "size": 0.0
    },
    {
      "slug": "cebe7a76_hassio_google_drive_backup",
      "name": "Home Assistant Google Drive Backup",
      "version": "0.109.2",
      "size": 0.01
    },
    {
      "slug": "a0d7b954_adguard",
      "name": "AdGuard Home",
      "version": "4.7.6",
      "size": 0.39
    },
    {
      "slug": "7c966942_emulated_hue_dev",
      "name": "Emulated HUE (dev)",
      "version": "0.2.3",
      "size": 89.05
    },
    {
      "slug": "core_mosquitto",
      "name": "Mosquitto broker",
      "version": "6.1.3",
      "size": 0.0
    },
    {
      "slug": "ccab4aaf_frigate",
      "name": "Frigate",
      "version": "0.11.1",
      "size": 0.0
    }
  ],
  "repositories": [
    "https://github.com/hass-emulated-hue/hassio-repo",
    "https://github.com/hassio-addons/repository",
    "https://github.com/diyhue/hassio-addon",
    "core",
    "local",
    "https://github.com/blakeblackshear/frigate-hass-addons",
    "https://github.com/sabeechen/hassio-google-drive-backup",
    "https://github.com/esphome/home-assistant-addon"
  ],
  "protected": false,
  "homeassistant": {
    "version": "2022.12.6",
    "size": 1848.61
  },
  "compressed": true
}

Which doesn't look to me like it's encryted?

**Comment by Jonosaurus** [comment]
I've just downloaded the available backups from Drive and I can open them all in 7-Zip but every time I try to open the homeassistant.tar.gz I get Data error :.\homeassistant.tar.gz which I think (according to Google) means it's corrupted, not sure why they're all corrupted though

**Comment by sabeechen** [comment]
The line in the config file:
```json
{"protected": false}
```

Means it isn't encrypted, so you _should_ be able to open all the *.tar.gz fiels inside the archive.

The supervisor error:
```
unexpected end of data
```
Is the error I've seen in the past associated with corruption, its an error coming from the underlying gzip libraries.  It doesn't really indicate anything specific, just that the file wasn't formatted as expected part of the way through.

Its unusual that more than one backup would have this problem.  Was the hard drive these came off of in really bad shape?  My frist thought is that the addon might have done something wrong while uploading it to Google Drive, but this is the first report of corruption I've had in a very long time.  Having the same part of more than one file be corrupted is very, _very_ unlikely unless the disk used was having extensive issues over a long period of time.

So, that pretty clearly indicates the file has been corrupted and can't be opened with the normal tools.  I haven't ever needed to try this, but there are tools available that attempt to partially recover corrupted gzip files, [this one comes to mind](https://github.com/arenn/gzrt).  [Commercial tools also exist](https://www.sysinfotools.com/recovery/archive-recovery.php) with demos that offer some functionality, that I haven't used those personally either.

**Comment by Jonosaurus** [comment]
Thanks for taking the time to reply, I've managed to get back mostly to where I was before. The disk had been filling up which may have something to do with it. I've created a couple of manual backups and checked to make sure the files aren't corrupted and so far all seems ok

**Comment by Jonosaurus** [comment]
Will close out now
