### ISSUE TITLE
philosophyofpen.com

### ISSUE THREAD

**Issue by xgwhk** [sabeechen/hassio-google-drive-backup#78]
I would suggest that the domain name is mentioned in clear on the setup window when we are going to do the authentication.

It took me quite some time to figure out that this domain is yours and can be trusted. 
I even posted on DrZZs discord channel to get help on the matter.

Thanks,
Nico

**Comment by sabeechen** [comment]
Seems reasonable to me, I'll add a little blurb about it on the page and maybe a link to learn more about how google auth works with external domains.  Not in the next release but the one after.

**Comment by sabeechen** [comment]
I've added some more detail to the page where you authenticate in v0.98.2, and written a whole doc detailign the details how authentication works [here](https://github.com/sabeechen/hassio-google-drive-backup/blob/master/hassio-google-drive-backup/AUTHENTICATION.md).
