### ISSUE TITLE
problem attempt authorizing with Google Drive

### ISSUE THREAD

**Issue by basdezeeuw2110** [sabeechen/hassio-google-drive-backup#781]
The server encountered an error while processing this request: invalid_grant<br/>Please <a href='https://github.com/sabeechen/hassio-google-drive-backup/issues'>file an issue</a> on Home Assistant Google Backup's GitHub page so I'm aware of this problem or attempt authorizing with Google Drive again.

**Comment by sabeechen** [comment]
Could you try going to Actions > Reauthorize Google Drive?
It sound slike something's Ng got messed up with your Google Drive credentials.

**Comment by basdezeeuw2110** [comment]
That worked out fine. Thanks.


Op za 14 jan. 2023 17:15 schreef Stephen Beechen ***@***.***>:
