### ISSUE TITLE
Full backup backs up the whole drive, not only HA catalogues

### ISSUE THREAD

**Issue by SuperMaximus1984** [sabeechen/hassio-google-drive-backup#782]
When I select the Full backup option, I have an archive sized about 25GB, which is enormous...
How to configure it to backup only the necessary Home Assistant data?

**Comment by sabeechen** [comment]
You can exclude some of your folders or add-ons from the backup, check out "partial backups" in the add-ons settings.

You can only include/exclude an entire folder or addon as a whole, which is limitation imposed by home assistant.
