### ISSUE TITLE
502:  Bad Gateway

### ISSUE THREAD

**Issue by sheyman1** [sabeechen/hassio-google-drive-backup#783]
Not sure if this is just me but when I click on the sidebar cloud icon or Open web UI link in the addon, I get an error 502:  Bad Gateway.  Anyone else having this issue?

Thank you
Scott

**Comment by sheyman1** [comment]
PS  I have been using this addon for a long time without any issues, this just started about a week ago...

**Comment by sheyman1** [comment]
Disregard.  Seems there were some corrupt files.  Uninstall and reinstall resolved the issue.

**Comment by rootd** [comment]
@sheyman1 then you should close this issue.
