### ISSUE TITLE
AddOns' WebUI not available after restore

### ISSUE THREAD

**Issue by verboEse** [sabeechen/hassio-google-drive-backup#784]
I had to restore my HA installation (on a raspi) from Backup. After that, I wasn't able to open the WebUI for any installed AddOn.
Searching for this issue I found this: https://community.home-assistant.io/t/i-just-installed-the-addon-and-the-webui-doesnt-load/187882
It suggests that maybe a configuration for some older version of a daemon (e. g AppDaemon) was installed, but a more recent version is installed. I was one patch release behind at most, so I don't know if this could be the reason?

In logs I can see that the AddOns *are* running, just the WebUI isn't available to HA. How can I resolve it?

**Comment by sabeechen** [comment]
I'm assuming this is the behavior you're seeing:
- Going to the logs tab of an addon shows logs (proving it is running)
- Going to the "main" tab of an installed addon shows the start button and no "Web-UI" button, indicating it is stopped.

If thats the case I've had users report it before, as far as I can tell it isn't a problem with any addon and instead is that something gets messed up in how Home assistant is caching the state of the addon.  IE, its running but the UI thinks it isn't and when you attempt to go to the web-ui home assistant complains that it isn't running.  Thats my current theory, anyway.

In all the cases I've seen, the problem goes away with a restart of the Home Assistant.

If you're willing to try and help me figure out whats going wrong then before restarting:
 - Make sure "Advanced Mode" is enabled in your Home Assistant user profile page  (eg http://homeassistant.local:8123/profile)
 - Click the "start" button for an addon thats bugged out.
 - Go to "Settings" > "System" > "Logs" > (top right) "Supervisor"

Do the logs there show any errors or suspicious log messages?

**Comment by verboEse** [comment]
First I want to thank you for your fast answer and great support!

You were right: It goes away, but not just by restarting, at least not at once. I tried restarting several times and even uninstalled und re-installed some addons. After I created this issue, I got something to eat and dismantled the Christmas tree. After that, indeed magically all addons were fully functional again. 
So, in my opinion a simple hint for users in the manual for showing some patience (and maybe a reboot) should be enough.

Sorry I can't do the proposed steps for helping you analyse the problem, as everything works now and the supervisor log doesn't go far enough for showing the last 'start' try. :-(

If I feel brave enough, maybe I will try and do it all again (fresh installation of HA and restore the backup I still have available on my local drive), but I'm not sure currently. For now I'm closing this issue.

**Comment by sabeechen** [comment]
Interesting, maybe its actually a browser cache problem?  That could explain why it stops after an indeterminate time.  I wouldn't ask you you to endanger your installation to test the bug for me, but if you see it again please don't hesitate to get me any relevant supervisor logs.  I've had users reporting this to me for over a year now and I've never been able to reproduce it on any of my test machines.
