### ISSUE TITLE
After restoring from backup, hassio-google-drive-backup won't start

### ISSUE THREAD

**Issue by wptracy** [sabeechen/hassio-google-drive-backup#789]
After restoring from backup, hassio-google-drive-backup won't start.

I uninstalled it and re-installed it and it still won't start.

The log says it started but it's really not.

01-21 11:56:58 INFO Starting server on port 8099
01-21 11:56:58 INFO Server started
01-21 11:56:58 INFO Syncing Backups

This might be related. But it might be from uninstalling and re-installing.

Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:124
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 11:52:57 AM (2 occurrences)
Last logged: 11:53:54 AM

Failed to to call /store/repositories - expected a URL for dictionary value @ data['repository']. Got ' https://github.com/sabeechen/hassio-google-drive-backup'
Failed to to call /store/repositories - Can't add https://github.com/sabeechen/hassio-google-drive-backup, already in the store

Restarts didn't help.  

I powered the system down and powered back up.

Now it works, but I had to re-authenticate with Google Drive.

I did another backup.

**Comment by sabeechen** [comment]
Sorry it took me a while to get back to you.  This sounds like the same issue as [here](https://github.com/sabeechen/hassio-google-drive-backup/issues/710), which is looking like some kind of bug in Home Assistant (the supervisor specifically) which affects all addons.  It looks like rebooting the Home Assistant machine after installing resolves it.

duplicate #710
