### ISSUE TITLE
Sensor is not visible in Home Assistant

### ISSUE THREAD

**Issue by mokshmridul** [sabeechen/hassio-google-drive-backup#79]
Hi,

I have enabled the state sensors, but the same are not visible in HA, through the states page. I have tried removing the addon, disabling it, enabling it, restarting HA, and all combinations of these, but it still wont show up.

My config is below:

```
{
  "max_snapshots_in_hassio": 7,
  "max_snapshots_in_google_drive": 100,
  "days_between_snapshots": 1,
  "use_ssl": false,
  "snapshot_time_of_day": "00:30",
  "snapshot_name": "{type} Snapshot of {version_ha} on {day}-{month_short}-{year} at {hr12}:{min}{ampm}",
  "send_error_reports": true,
  "enable_snapshot_stale_sensor": true,
  "enable_snapshot_state_sensor": true,
  "notify_for_stale_snapshots": true  
}

**Comment by mokshmridul** [comment]
Im sorry to ask, but is this project still being maintained, or has it been abandoned?

**Comment by sabeechen** [comment]
Its not abandoned but I could see why you'd ask, sometimes I have to take a step back from working on it for a short while.

Just to confirm, neither sensor shows up?  They should be named:
-  `binary_sensor.snapshots_stale` (a boolean)
-  `sensor.snapshot_backup` (a json object)

If the add-on is having trouble reaching home assistant, you should see some errors in either the add-on logs (Click LOGS from the add-on web-ui) or the supervisor logs (Hass.io > System > System Logs from the Home Assistant UI).

Home assistant doesn't persist these sensor's states across restarts, so sometimes right after restarting Home Assistant it can take a little bit for the sensors to show up.  The reasons for this are complicated and annoying.  Up to 5 minutes for `binary_sensor.snapshots_stale` and up to 60 minutes for `sensor.snapshot_backup`, though typically much _much_ less.  Do neither of the sensors show up if you wait a while?

**Comment by mokshmridul** [comment]
Hi @sabeechen 
Thank you so much for replying. I'm sorry if i came across as rude, I don't mean to be disrespectful, and i highly appreciate your work on this amazing project.

My HA instance has been one for amount 14 hours now, but the sensors do not show up. I am getting errors in my HassIO Supervisor docker, as shown below:

````

19-07-23 15:54:48 ERROR (MainThread) [hassio.homeassistant] Can't update Home Assistant access token!


19-07-23 15:54:48 ERROR (MainThread) [hassio.api.proxy] Authenticate error on API for request states/binary_sensor.snapshots_stale
````

Any idea how I can resolve this issue?

**Comment by sabeechen** [comment]
Hrm, that would mean for some reason Hass.io thinks the add-on's credentials are invalid.  Thats weird, because Hass.io gave the add-on those credentials in the first place!  Are you running the latest version of the add-on?  I had someone running into a [similar issue](https://github.com/sabeechen/hassio-google-drive-backup/issues/58) but it was fixed soem tiem ago.

Since you've already tried reinstalling the add-on and restarting home Assistant, could you trying restarting the host machine?  Because Hass.io runs everything in virtualized containers, sometimes a machine restart is the only ways to reset things back to normal.

**Comment by mokshmridul** [comment]
Im running the latest version of both Hass.IO and the add-on. Ive also restarted the host machine (Proxmox) numerous times, to no avail. 

Note: If it matters, i performed a restore using the add-on (using the wipe+restore option)

Are there any logs / other information that i can provide to help with diagnosis?

**Comment by sabeechen** [comment]
It looks like Hass.io is getting hung up on [this line](https://github.com/home-assistant/hassio/blob/d262151727f4f498043eb33dd5d619745780fe08/hassio/homeassistant.py#L445), but unfortunately it doesn't look like there is anything we can do to make it say more.  Is there anything in the supervisor logs before or after the message that looks like it might be relevant?

Have you tried reinstalling the add-on since you restored?  Its possible (though just speculation on my part) that some kind of stale credentials got restored along with the add-on.  If that still isn't working I'll have to file an issue with the Hass.io dev, since its really looking like a problem with Hass.io.

**Comment by sabeechen** [comment]
If you do reinstall the add-on, make sure you update your settings before you connect it with Google Drive!

**Comment by mokshmridul** [comment]
Okay, let me try re-installing the add-on before authenticating it with GDrive. Ill report back in a few minutes.

**Comment by mokshmridul** [comment]
These are the steps i just did:

1) Uninstall the Add-ON
2) Restart HassIO
3) Re-install Add-on
4) Change Settings in add-on (while it is stopped) and save settings
5) Start Add-on
6) Authenticate with GDrive

Even after this, the sensor does not show up. The logs are below

````

19-07-23 16:30:01 INFO (SyncWorker_14) [hassio.docker.interface] Stop addon_cebe7a76_hassio_google_drive_backup application


19-07-23 16:30:02 INFO (SyncWorker_14) [hassio.docker.interface] Clean addon_cebe7a76_hassio_google_drive_backup application


19-07-23 16:30:03 INFO (SyncWorker_14) [hassio.docker.interface] Remove image sabeechen/hassio-google-drive-backup-amd64 with latest and 0.97.4


19-07-23 16:30:10 INFO (MainThread) [hassio.addons.addon] Remove add-on data folder /data/addons/data/cebe7a76_hassio_google_drive_backup


19-07-23 16:30:14 INFO (SyncWorker_18) [hassio.docker.interface] Restart homeassistant/qemux86-64-homeassistant


19-07-23 16:30:37 INFO (MainThread) [hassio.homeassistant] Detect a running Home Assistant instance


19-07-23 16:30:51 INFO (MainThread) [hassio.addons] Create Home Assistant add-on data folder /data/addons/data/cebe7a76_hassio_google_drive_backup


19-07-23 16:30:51 INFO (SyncWorker_5) [hassio.docker.interface] Pull image sabeechen/hassio-google-drive-backup-amd64 tag 0.97.4.


19-07-23 16:31:08 INFO (SyncWorker_5) [hassio.docker.interface] Tag image sabeechen/hassio-google-drive-backup-amd64 with version 0.97.4 as latest


19-07-23 16:32:07 INFO (SyncWorker_11) [hassio.docker.addon] Start Docker add-on sabeechen/hassio-google-drive-backup-amd64 with version 0.97.4


19-07-23 16:32:08 ERROR (MainThread) [hassio.homeassistant] Can't update Home Assistant access token!


19-07-23 16:32:08 ERROR (MainThread) [hassio.api.proxy] Authenticate error on API for request states/binary_sensor.snapshots_stale


19-07-23 16:32:08 INFO (MainThread) [hassio.api.security] /homeassistant/info access from cebe7a76_hassio_google_drive_backup


19-07-23 16:32:08 INFO (MainThread) [hassio.api.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup


19-07-23 16:32:08 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup


19-07-23 16:32:08 INFO (MainThread) [hassio.api.security] /snapshots/f5e8fb5e/info access from cebe7a76_hassio_google_drive_backup


19-07-23 16:32:08 INFO (MainThread) [hassio.api.security] /snapshots/1a1de3ed/info access from cebe7a76_hassio_google_drive_backup


19-07-23 16:32:08 INFO (MainThread) [hassio.api.security] /snapshots/58081dc5/info access from cebe7a76_hassio_google_drive_backup


19-07-23 16:32:08 INFO (MainThread) [hassio.api.security] /snapshots/1b1bb702/info access from cebe7a76_hassio_google_drive_backup


19-07-23 16:32:08 INFO (MainThread) [hassio.api.security] /snapshots/6331b48f/info access from cebe7a76_hassio_google_drive_backup


19-07-23 16:32:08 INFO (MainThread) [hassio.api.security] /snapshots/d2ee8e96/info access from cebe7a76_hassio_google_drive_backup


19-07-23 16:32:08 INFO (MainThread) [hassio.api.security] /snapshots/b8779b2a/info access from cebe7a76_hassio_google_drive_backup


19-07-23 16:32:09 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup


19-07-23 16:32:10 WARNING (MainThread) [hassio.addons.addon] cebe7a76_hassio_google_drive_backup already running!


19-07-23 16:32:33 ERROR (MainThread) [hassio.homeassistant] Can't update Home Assistant access token!


19-07-23 16:32:33 ERROR (MainThread) [hassio.api.proxy] Authenticate error on API for request states/binary_sensor.snapshots_stale


19-07-23 16:32:55 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup````

**Comment by sabeechen** [comment]
Thank you for being so thorough, this will help me explain the issue when I file it with Hass.io.  Can you get me the error that shows up in the add-on logs?  It should say something like `Trouble updating Home Assistant sensors` and then print an exception.

**Comment by mokshmridul** [comment]
Im not getting any errors in the add-on logs (as seen in portainer / logs). Im only getting the below:

````
07-23 22:07:30 ERROR Unable to reach Home Assistant.  Is it restarting?
07-23 22:07:30 INFO Starting server on port 8099
07-23 22:07:30 INFO Starting server on port 1627
07-23 22:07:30 INFO Server started
07-23 22:07:30 INFO Syncing Snapshots
07-23 22:07:32 INFO Syncing Snapshots

**Comment by sabeechen** [comment]
Thnaks, that should be enough

**Comment by mokshmridul** [comment]
Hey, hope your doing well.

Were you able to raise a request for this issue with Hass.IO

**Comment by sabeechen** [comment]
Appologies, this dropped off my radar.  I've filed the issue with them [here](https://github.com/home-assistant/hassio/issues/1185).

**Comment by mokshmridul** [comment]
Thanks a ton mate. I also posted in that thread, in case they need or want more information.

**Comment by cogneato** [comment]
@mokshmridul when you uninstall an addon, you should reboot the whole system before installing the same addon again. Is that what you did in your step 2, or did you only restart Home Assistant?

**Comment by mokshmridul** [comment]
@cogneato when I uninstalled the add-on, i restarted the VM which runs docker (and not the proxmox box itself)

**Comment by sabeechen** [comment]
I'm closing this out because I don't think there is anything else I can do from my side.
