### ISSUE TITLE
Feature request: Compression of backups

### ISSUE THREAD

**Issue by marsv0** [sabeechen/hassio-google-drive-backup#794]
Would be nice to have compressed archives ... it will save space on HA and in Google Drive as well

**Comment by sabeechen** [comment]
The archives _are_ compressed.  Inside of the backup ```.tar``` file are abunch of smaller ```.tar.gz``` files, one for each folder and addon in the backup.  Its inefficient to tar the files twice but thats just how Home Assistant does it, this addon doesn't have any control over the backup file format.

**Comment by marsv0** [comment]
thanks for explanation :)
