### ISSUE TITLE
Can't connect to Google (German Account)

### ISSUE THREAD

**Issue by Streammet** [sabeechen/hassio-google-drive-backup#798]
![Screenshot_20230212_232447](https://user-images.githubusercontent.com/23196159/218340931-10fb06ed-a2eb-436d-b448-cf6264826eb5.png)

HA and habackup is up to date

**Comment by Streammet** [comment]
I actually fixed this by setting the language on the shown page to English. (Bottom Left)

**Comment by sabeechen** [comment]
Did you retry the login with German?  I'm hoping this doesn't have anything to do with the language and is just a random temporary failure from Google.  Its the first I've heard of someone having trouble logging in with Google because of their default language.

**Comment by Streammet** [comment]
I tried it multiple times. Also like 2 months ago or so. But it does not matter, because setting the language to English fixed it. But still thanks for the reply and this very useful addon.
