### ISSUE TITLE
Google Drive Credential File

### ISSUE THREAD

**Issue by Cloudenius** [sabeechen/hassio-google-drive-backup#8]
Hi,

Thanks for this add-on! I've found the following file in your repository and I hope the ID and secret in there are dummy:

https://github.com/sabeechen/hassio-google-drive-backup/blob/master/hassio-google-drive-backup/drive_creds.json

If not, I think that the ID and secret can be used to create a token to sign in to your Google Drive. So I recommend to revoke the ID/secret, remove the file from the repository and include the file in your .gitignore.

Thanks.

**Comment by sabeechen** [comment]
Those are the credentials that identify the project using the Google Drive REST API (eg Hass.io Google Drive Backup), not an end user.  Ideally they'd still be kept private since someone could take them, identify as this project, and exhaust all the quota Google has given me for this project, but it doesn't give anyone access to anyone's Drive.  In order to have the add-on make requests to Google, the add-on must have access to this "secret".

**Comment by sabeechen** [comment]
Oh wait actually you're right.  Whoops!

**Comment by Cloudenius** [comment]
@sabeechen, yup I'm pretty sure it's your ID/secret. Did you already revoke it?

I recommend to follow the same approach as for Spotify: ask the user to create the application from their Google account and provide the ID/secret in config: https://www.home-assistant.io/components/media_player.spotify/

**Comment by sabeechen** [comment]
Yup, its revoked.   In the nearer term I plan to delegate the logic for generating the credentials to a server I own so I don't have to store the project credentials in the repo, having people go through a developer console like the spotify add-on is something I'm trying hard to avoid with this project.  Setup for the add-on is simple and idiot proof right now, which is my favorite feature.  Google's dev interface is particularly opaque.
To do that I'll have to write some logic for my server, which will take some time.  I'll keep this open to remind me I have that on my to-do list before I really publicize the project.

**Comment by sabeechen** [comment]
The latest version (v0.6) delegates all the credential handling to another server, so project credentails are no longer stored with the add-on or in source control.  Once I'm confident no one is using the older version, I can delete the old credentials (probably months form now).
