### ISSUE TITLE
A snapshot is already in progress

### ISSUE THREAD

**Issue by danielsjf** [sabeechen/hassio-google-drive-backup#80]
Thanks a lot for your great add-on! 

During my first usage, I ran into a bit of a hickup. I was already running a snapshot on Hassio before I started the add-on the first time. In the interface I got a huge error message (see below). Unfortunately I couldn't close this message. I guess the add-on is well aware when it starts it's own snapshots, but it might not catch errors from mixed hassio/addon snapshots.

Traceback (most recent call last):
  File "/app/backup/coordinator.py", line 102, in _sync
    self._buildModel().sync(self._time.now())
  File "/app/backup/model.py", line 125, in sync
    self.createSnapshot(CreateOptions(now, self.config.get(Setting.SNAPSHOT_NAME)))
  File "/app/backup/model.py", line 150, in createSnapshot
    created = self.source.create(options)
  File "/app/backup/hasource.py", line 146, in create
    raise SnapshotInProgress()
backup.exceptions.SnapshotInProgress

A snapshot is already in progress

**Comment by sabeechen** [comment]
Thanks for the detail.  For the scenario you described this is the expected behavior because Hass.io only allows one snapshot to be in progress at a time, though it isn't a good first experience.  I'll make the dialog for this less obtrusive and more descriptive (eg indicate nothing is actually wrong).  Did the error go away by itself after a few seconds?

**Comment by danielsjf** [comment]
No the error remained there. Could it be that the add-on always tries to start a snapshot anyway on its first use? The hassio snapshot took more than an hour and the error remained there (be it each time a new error or still the same).

**Comment by sabeechen** [comment]
Yeah, it will create one at start if you didn't already have a recent enough snapshot.  The way Hass.io indicates that a snapshot is in progress is by returning an error when you try to make a new one, which causes the error you see.  After that it should have noticed, retried, and just waited for the snapshot to finish (without an error).   I'll need to look into why it didn't.  Did the error eventually go away, ie the add-on is working correctly for you now?

**Comment by danielsjf** [comment]
Yes I didn't wait for the snapshot to end. I checked it again a few hours later and the error is gone now and the snapshot was successfully uploaded. To be clear, everything worked as expected. It was just a bit strange to start with the error message that took half my screen (which was clear though). It didn't disappear immediately and I couldn't find a way to hide it.

**Comment by sabeechen** [comment]
I've added some better messaging for this in the latest version, v0.98.2
