### ISSUE TITLE
Google Backup after finishing a task leve high CPU utilization (around 100%)

### ISSUE THREAD

**Issue by rikpal865** [sabeechen/hassio-google-drive-backup#800]
First of all thank you for this exceptional add-on.
Environment: mac mini OSX Ventura, Oracle VirtualBox 7 and latest version at the date for Home Assistant, Google Backup add-on latest version v0.110.1.
Im getting crazy since starting from midnight the energy consumption of my macmini double from 30W to 50-60W) and the CPU utilization raises from 35%b to 100% or more (my VM has 2 cores and 32MB memory). These measurements are taken from mac os system activities monitor.
To restore the original conditions I've to restart the host VM machine, and everything goes back to normal until the day after. 
I discovered after several days that the CPU utilization remains high after running the google backup: I did the test during the day and it is confirmed.
Restarting the Google Backup add-on does not change anything. The add-on CPU and RAM utilization usage remain low (reading it from the add-on window). 
The only way to go back to normal is shutting down the VM and then restarting it again directly from mac (the command from termina withi hassio 'ha host reboot' is not changing anything).
I'm not sure this was happening also before Jan 9th 2023, with the previous version of the Google Backup add-on I was using.
Thank you in advance for helping.

Here below the log of the test I did during the day (backup and upload) and everything seems to be ok:
------------------------------------
02-15 10:00:21 INFO [backup.ui.uiserver] Starting server on port 8099
02-15 10:00:21 INFO [backup.ui.uiserver] Server started
02-15 10:00:21 DEBUG [backup.model.syncer] Sync requested by Coordinator
02-15 10:00:21 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
02-15 10:00:21 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
02-15 10:00:21 INFO [backup.model.coordinator] Syncing Backups
02-15 10:00:21 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
02-15 12:07:14 INFO [backup.model.coordinator] Syncing Backups
02-15 12:07:14 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
02-15 12:07:23 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
02-15 12:08:00 DEBUG [backup.model.syncer] Sync requested by Coordinator
02-15 12:08:00 INFO [backup.model.coordinator] Syncing Backups
02-15 12:08:00 INFO [backup.ha.hasource] Requesting a new backup
02-15 12:26:44 INFO [backup.watcher] A backup directory file was modified, we'll check for new backups soon.
02-15 12:26:44 INFO [backup.ha.hasource] Backup finished
02-15 12:26:45 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
02-15 12:26:45 INFO [backup.model.coordinator] Syncing Backups
02-15 12:26:46 INFO [backup.ha.hasource] Deleting 'Full Backup 2023-02-03 00:00:00' from Home Assistant
02-15 12:26:46 INFO [backup.drive.drivesource] Uploading 'Full Backup 2023-02-15 12:08:00' to Google Drive
02-15 12:26:46 DEBUG [backup.drive.driverequests] Starting a new upload session with Google Drive
02-15 12:26:46 DEBUG [backup.drive.driverequests] Sending 262144 bytes to Google Drive
02-15 12:26:46 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-02-15 12:08:00 0.01%
02-15 12:26:46 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
02-15 12:26:47 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-02-15 12:08:00 0.43%
02-15 12:26:47 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
02-15 12:26:47 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-02-15 12:08:00 0.84%
02-15 12:26:47 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
02-15 12:26:48 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-02-15 12:08:00 1.26%
...
02-15 12:28:55 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
02-15 12:28:55 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-02-15 12:08:00 99.56%
02-15 12:28:55 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
02-15 12:28:56 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-02-15 12:08:00 99.97%
02-15 12:28:56 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
02-15 12:28:58 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-02-15 12:08:00 100.00%
02-15 12:28:58 INFO [backup.drive.drivesource] Deleting 'Full Backup 2023-02-08 00:00:00' From Google Drive
02-15 12:29:00 DEBUG [backup.watcher] Checking backup source for changes...
02-15 12:29:00 DEBUG [backup.model.syncer] Sync requested by Backup Directory Watcher
02-15 12:29:00 INFO [backup.model.coordinator] Syncing Backups
------------------------------------

**Comment by sabeechen** [comment]
It looks like the addon made a new backup at 12:08 and it finished at 12:26.  Its expected during this time to see high CPU/RAM/Disk/Power usage, the machine is copying and compressing all of its data.  Creating a backup is resource intensive, most people schedule it to happen during a time when the machine isn't doing anything else useful.

Resource usage of the addon is low during this time because the addon doesn't actually create the backup, it just asks Home Assistant to make one.  The addon itself should never have high resource usage.  Similarly restarting the addon will not stop the backup in progress, you'd need to restart the host machine (the Supervisor specifically) to stop it.  If you do this the addon will probably just ask for another backup when it starts up again, because now it is behind schedule.

If I've missed something here, please reopen the issue and let me know how I can help.

**Comment by rikpal865** [comment]
Maybe I wan't able to explain in the right way the issue I'm having.
Normally I run the backup task overnight and I noticed that after this task is finished (normally it takes 20-30 mins), the CPU usage (and the macmini power usage) remains very high.
So, I'm not referring to the time during which the backup is taken by HASS (for which I attached the log of the manual test I did at noon, showing the task is properly done and everything is fine), but I'm referring to the time after finishing the backup task, since I'm experiencing that the CPU usage remains very high forever, until I stop the VM completely and then I restart it again.
This is happening since few days and I'm not sure if it is due to this new version of the google backup add-on, or a new hassio core version update.
What I'm sure is that it is happening only after a backup with google add-on is taken.

**Comment by sabeechen** [comment]
Ah I see, I think you'll probably need to do some debugging to figure out whats going on.  

This addon runs inside a docker container that it can't break out of, and that CPU/RAM usage number you see in Home Assistant shows the usage of the entire container, so if those numbers are low its unlikely something _inside_ the addon is the direct problem.  At least, that _should_ be impossible.  If I were you I'd so the following:

1. Install the "Galnces" add-on and make sure to disable "Protection Mode" before starting it.  This will let it see resource usage system-wide.
2. Let the addon make a backup (manually or on your schedule), wait for it to complete and upload, and then wait for the CPU usage to spike permanently as you describe.
3. Visit the Glances web-ui, and then press "z" show it shows per-processs resource usage.  Hopefully, whatever is causing the problem with stand out like a sore thumb.

At this point you may also be able to get some information about whats causing problems in the Supervisor logs.  you can get to them by:
1. Making sure "Advanced Mode" is enable in your Home Assistant user profile.
2. Navigating to "Settings" > "System" > "Logs" > "Supervisor (top right)

**Comment by sabeechen** [comment]
I'm going to close this for now, but if you think there is something I can to do help please let me know.
