### ISSUE TITLE
Feature Request: Ignore directories

### ISSUE THREAD

**Issue by Code-TT** [sabeechen/hassio-google-drive-backup#801]
This plugin has always done a great job so far. Many thanks for it. 

I recently started using HA with Frigant for camera monitoring. The backups are getting extremely large because of the video recordings. Too big for my internet line. So it would be very nice to be able to exclude some directories from the backup (in my case, containing the videos).

**Comment by sabeechen** [comment]
You can only exclude the top level directories or addons, eg media, ssl, config, share, etc.  This is a Supervisor/Home Assistant backup format limitation and not something I'm able to work around without changes on the Home Assistant side.  What most people do in this situation is store their large files in one of the directories (share for example) and then configure the addon to create a partial backup that excludes that directory.  If there is some other way you think I can help, please re-open this issue and let me know.
