### ISSUE TITLE
Backup that grows so much in size day by day

### ISSUE THREAD

**Issue by cmussoni** [sabeechen/hassio-google-drive-backup#802]
HI,
I was using Home Assistant Google Drive Backup with HA on Virtual Machine on a Win11 pc without any problem. I reinstalled HA on generic x86-64, following the official guide of the Home Assistant site, writing the image directly on the mini pc's ssd. I realized now, making a backup a day, that each backup increases by 300/400 MB per day, a lot.
I saw that it is the home-assistant_v2.db file that grows incrementally.
Do you know what it contains?Can you tell me if it's normal or what can I do to reduce the size?
A thousand thanks.
Claudio

**Comment by sabeechen** [comment]
Its probably your sensor database, unless you have something else making large files (an NVR, media files, etc).  I believe HA stores 10 days by default, so I'd expect it to level off after that.  If so, please see [here](https://github.com/sabeechen/hassio-google-drive-backup#will-this-fill-up-my-google-drive-why-are-my-backups-so-big).

You can also use the MariaDB addon to move the database into an addon and then exclude MariaDB from backups, though then your database wouldn't get backed up.

**Comment by cmussoni** [comment]
Thank you very much, I will try it....
