### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer  . can't backup zigbee2mqtt addons

### ISSUE THREAD

**Issue by Al3inaw** [sabeechen/hassio-google-drive-backup#806]
[home-assistant-google-drive-backup.log](https://github.com/sabeechen/hassio-google-drive-backup/files/10890486/home-assistant-google-drive-backup.log)
 
`03-04 22:00:34 INFO [backup.ui.uiserver] Starting server on port 8099
03-04 22:00:34 INFO [backup.ui.uiserver] Server started
03-04 22:00:34 DEBUG [backup.model.syncer] Sync requested by Coordinator
03-04 22:00:34 INFO [backup.model.coordinator] Syncing Backups
03-04 22:00:34 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
03-05 00:26:33 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
03-05 00:26:33 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
03-05 00:40:01 DEBUG [backup.model.syncer] Sync requested by Coordinator
03-05 00:40:01 INFO [backup.model.coordinator] Syncing Backups
03-05 03:41:02 DEBUG [backup.model.syncer] Sync requested by Coordinator
03-05 03:41:02 INFO [backup.model.coordinator] Syncing Backups
03-05 03:41:02 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
03-05 04:21:02 ERROR [backup.ui.uiserver] Error serving GET http://192.168.0.170:8123/download?slug=df56661e
03-05 04:21:02 ERROR [backup.ui.uiserver]    
  addon/backup/ui/uiserver.py:771 (error_middleware)   
  addon/backup/ui/uiserver.py:629 (download)   
  /site-packages/aiohttp/web_response.py:514 (write)   
  [3 hidden frames]   
  /usr/lib/python3.10/asyncio/selector_events.py:862 (_read_ready__data_received)   
ConnectionResetError: [Errno 104] Connection reset by peer   

03-05 04:25:36 ERROR [backup.ui.uiserver] Error serving GET http://192.168.0.95:8123/download?slug=df5tu87e
03-05 04:25:36 ERROR [backup.ui.uiserver]    
  addon/backup/ui/uiserver.py:771 (error_middleware)   
  addon/backup/ui/uiserver.py:629 (download)   
  /site-packages/aiohttp/web_response.py:111 (write)   
  [3 hidden frames]   
  /usr/lib/python3.10/asyncio/selector_events.py:862 (_read_ready__data_received)   
ConnectionResetError: [Errno 104] Connection reset by peer   

© 2022 Stephen Beechen with love from [Colorado](https://www.openstreetmap.org/search?query=Longmont%2C%20Colorado) - If you like this project, keep it going and
[Buy me a coffee](https://www.buymeacoffee.com/sabeechen)
[+ other ways](https://192.168.0.170:8123/api/hassio_ingress/uVxxx1d-xxxxygrBXXGOixXxXxhHVxXxsPRaXXX/log?format=view#!)`

**Comment by sabeechen** [comment]
Its difficult to tell whats going on here.  The error posted:
```
Error serving GET http://192.168.0.170:8123/download?slug=df56661e
03-05 04:21:02 ERROR [backup.ui.uiserver]
addon/backup/ui/uiserver.py:771 (error_middleware)
addon/backup/ui/uiserver.py:629 (download)
/site-packages/aiohttp/web_response.py:514 (write)
```
makes it look like you're having trouble downloading a backup from the addon, but the title is about backing up zigbee2mqtt.  Could you describe whats going wrong for you?

**Comment by sabeechen** [comment]
I'm going to close this issue for now, but if you think there is something else I can help with please reopen and let me know.
