### ISSUE TITLE
Can't add addon to HA repository

### ISSUE THREAD

**Issue by jjsa99** [sabeechen/hassio-google-drive-backup#81]
I try to add the addon by clicking on add but the button only turns red and doesn't do nothing.
Running the latest version of HA

**Comment by sabeechen** [comment]
Does anything show up in the supervisor log when you try to install?  You can get to the log from the Home Assistant interface by navigating to `Hass.io` > `System` > `System Log`

What platform are you running Hass.io on (ie what kind of device)?

**Comment by sabeechen** [comment]
Closing this for now, but please reopen if you're someone seeing this issue and can provide me with more information.
