### ISSUE TITLE
High CPU (and memory) usage when running addon

### ISSUE THREAD

**Issue by spanzetta** [sabeechen/hassio-google-drive-backup#822]
It's now 3 times that I can reproduce..  
Addon enable.. high CPU usage (about 15%) and after a while it becomes unresponsive..
Addon disabled.. normal CPU usage (about 2/3%) and normal functionality/responsiveness 
Running on Raspberry Pi3+ (32bit)
Any chance to optimize it?
I really like this addon but for me currently it's unusable 
Thanks

**Comment by spanzetta** [comment]
some more info.. 
when running the addon.. besides having the CPU and memory with high usage (see screenshot below where the high level is when addon is running.. when addon is stopped both CPU and memory goes down) I have the following:
- cannot restart HA... even if I run the command (or call the reboot service) nothing happens for minimum 30 minutes.. need to wait a long time and then it restart (I also have the watchdog installed)
- the addon window is not accessible.. so I cannot stop the addon..

![image](https://user-images.githubusercontent.com/49818743/229705240-b419a6f9-0fb6-4852-8b7b-77bb5e6e248e.png)

**Comment by sabeechen** [comment]
Let me start by saying that I've helped with a lot of hardware problems in the past and so far the problem has never been the addon.  I'm not saying that that addon definitely isn't to blame here, its certainly possible I have a bug causing this, but it is unlikely speaking from experience.

The only performance intensive work the addon should be doing is uploading the backup to Google Drive, even creating the backup is actually handled by Home Assistant (the supervisor specifically).

What is most likely the problem in a situation like this is the backup process.  If you have a large backup, you can expect HA to become sluggish during the backup (especially on a pi3).  Moreover the database has to be paused during backups, if you have a large one it will buffer database changes in memory until the backup is done, during which it can consume more and more memory.  The only solutions to this currently are to make smaller backups, use faster hardware, or stop doing backups.

Separately, from your memory graph you are frequently over 90% utilization, which is going to cause a lot of problems.  On a pi3 that means you often have less than 100MB free.  This likely means you are out of RAM and the operating system has to page memory in and out of disk to keep things running, which is *very* slow on an SD card and will cause applications (including Home Assistant) to freeze while the memory is written or read from disk.  I can't be certain this is happening based on the graph, modern memory allocation behavior is very convoluted, bumemory in and out of disk to keep things running, which is *very* slow on an SD card and will cause applications (including Home Assistant) to freeze while the memory is written or read from disk.  I can't be certain this is happening based on the graph, modern memory allocation behavior is very convoluted, but it is likely based on the symptoms you're describing.

To determine what on your system is using up memory I'd recommend:
1.  Turn off every addon you can to free up some memory.
2. Install the Glances addon, turn off "Protection Mode" (ignore the warnings), and start it.
3. Start addons one at a time and observe the impact this has on memoryt it is likely based on the symptoms you're describing.

To determine what on your system is using up memory I'd recommend:
1.  Turn off every addon you can to free up some memory.
2. Install the Glances addon, turn off "Protection Mode" (ignore the warnings), and start it.
3. Start addons one at a time and observe the impact this has on memory

In the glances web interface you'll be able to see memory/cpu stats for the whole system as well as each container.  Every addon, including Home Assistant and the supervisor, run as a separate isolated container.  For example this addon's usage should be visible under "Containers" > "addon_cebe7a76_hassio_google_drive_backup".  If this addon is to blame you should be able to see that there and I can recommend some further debugging.  Its rare for this addon to use more than 70MB of memory and a few percents of CPU for more than a few seconds.  If not then it should indicate what _is_ using memory.  The pi3 only has 1GB of memory, which doesn't leave much overhead.  Just Home Assistant and the supervisor on my home machine use about 750MB together.

**Comment by spanzetta** [comment]
Thanks for your detailed answer  ...
But in my case it's a fact that this addon is causing the performance problem... without it I have no issue at all.. system is totally responsive (Ram usage is below 90%  .. and I reboot it every 3 days with an automation because I noticed that after 3 days memory goes over 90%)

Maybe the issue is definitely the fact that the Ram usage is already at limit (about 90%) without the addon.. so with the addon it goes above.. 

The DB size is around 300Mb so it could not be the issue.. (not as big)

Thanks anyway

**Comment by spanzetta** [comment]
Hi @sabeechen,
I need to clarify something..

I also wrote in my previous post that my system is already running "at limit" .. so maybe the 70MB of your addon is generating the out of RAM (and high CPU usage).. so I am not saying that the addon is the problem in general.. it is on my system because it is too low spec (I am conscious about that) 

But... what I don't explain is that the addon makes the system unstable by simply runnning it.. not during the backup operation..
I mean: I run the addon.. the backup will be done in the next 5 days.. but immediatelly I see  the RAM/CPU usage going up in stable way.. for all the time..
I would understand if the high RAM/CPU usage happens ONLY during the backup operation.. not also during the "sleep/idle" mode of the Addon (because I configured to make the Backup every 5 days)..

I hope I was clear enough..

Thanks
