### ISSUE TITLE
Home Assistant Google Drive Backup is Having Trouble

### ISSUE THREAD

**Issue by gboebel** [sabeechen/hassio-google-drive-backup#826]
Copy the
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```
Been receiving this notification for months now. I've tried reinstalling, clearing all old backups, reauthorizing my drive account, and still get this message daily.

 Addon version: `0.110.3`
 Home Assistant Version: `2023.4.2`
 Supervisor Version: `2023.04.0`
 Supervisor Channel: `stable`
 Hassos Version: `9.5`
 Docker Version: `20.10.22`
 Architecture: `armv7`
 Machine: `raspberrypi3`
 Date: `2023-04-14T22:52:28.420039+00:00`
 Timezone: `America/Los_Angeles`
 Failure Time: `2023-04-14T10:42:36.100793+00:00`
 Last Good Sync: `2023-04-14T22:51:19.355509+00:00`
 Next Sync: `2023-04-15T07:23:38.631649+00:00`
 Next Backup: `2023-04-21T10:00:00+00:00`
 Next Cache Warm: `2023-04-15T07:20:11.845471+00:00`
 Time Offset: `0.0`
 ###### Exception:
 ```
 No error could be identified automatically.
 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 2,
        "retained": 0,
        "deletable": 2,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2023-04-14T22:44:40Z",
        "max": 4,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 3,
        "detail": "",
        "size": "41.0 kB",
        "ignored_size": "61.4 kB",
        "free_space": "18.7 GB"
    },
    "GoogleDrive": {
        "backups": 3,
        "retained": 1,
        "deletable": 2,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2023-03-23T23:31:30Z",
        "max": 4,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "detail": "gboebel@gmail.com",
        "size": "80.0 kB",
        "ignored_size": "0.0 B",
        "free_space": "128.3 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.DAYS_BETWEEN_BACKUPS": 7.0,
    "Setting.IGNORE_OTHER_BACKUPS": true,
    "Setting.BACKUP_TIME_OF_DAY": "03:00",
    "Setting.SEND_ERROR_REPORTS": true,
    "Setting.MAX_SYNC_INTERVAL_SECONDS": 43200.0
}
 ```
 ###### Addon Logs:
 ```
 04-14 03:45:57 INFO [backup.model.coordinator] Syncing Backups
04-14 06:44:34 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
04-14 06:44:35 INFO [backup.model.coordinator] Syncing Backups
04-14 06:44:35 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
04-14 06:44:37 INFO [backup.ha.hasource] Requesting a new backup
04-14 06:45:59 WARNING [backup.ha.hasource] A backup was already in progress
04-14 06:46:00 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
04-14 06:46:00 INFO [backup.model.coordinator] Syncing Backups
04-14 09:44:37 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
04-14 09:44:37 INFO [backup.model.coordinator] Syncing Backups
04-14 09:44:37 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
04-14 09:44:38 INFO [backup.ha.hasource] Requesting a new backup
04-14 09:45:57 WARNING [backup.ha.hasource] A backup was already in progress
04-14 09:45:57 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
04-14 09:45:57 INFO [backup.model.coordinator] Syncing Backups
04-14 12:44:38 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
04-14 12:44:39 INFO [backup.model.coordinator] Syncing Backups
04-14 12:44:39 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
04-14 12:44:40 INFO [backup.ha.hasource] Requesting a new backup
04-14 12:45:59 WARNING [backup.ha.hasource] A backup was already in progress
04-14 12:45:59 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
04-14 12:45:59 INFO [backup.model.coordinator] Syncing Backups
04-14 15:44:40 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
04-14 15:44:40 INFO [backup.model.coordinator] Syncing Backups
04-14 15:44:40 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
04-14 15:44:42 INFO [backup.ha.hasource] Requesting a new backup
04-14 15:46:04 WARNING [backup.ha.hasource] A backup was already in progress
04-14 15:46:04 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
04-14 15:46:04 INFO [backup.model.coordinator] Syncing Backups
04-14 15:51:19 INFO [backup.model.coordinator] Syncing Backups
 ```
 ###### Supervisor Logs:
 ```
 [33m23-04-14 15:46:15 WARNING (MainThread) [supervisor.addons.options] Option 'banned_ips' does not exist in the schema for File editor (core_configurator)[0m
[33m23-04-14 15:46:15 WARNING (MainThread) [supervisor.addons.options] Option 'banlimit' does not exist in the schema for File editor (core_configurator)[0m
[33m23-04-14 15:46:15 WARNING (MainThread) [supervisor.addons.options] Option 'notify_service' does not exist in the schema for File editor (core_configurator)[0m
[33m23-04-14 15:46:15 WARNING (MainThread) [supervisor.addons.options] Unknown option 'enable' for SSH & Web Terminal (a0d7b954_ssh)[0m
[33m23-04-14 15:46:15 WARNING (MainThread) [supervisor.addons.options] Unknown option 'port' for SSH & Web Terminal (a0d7b954_ssh)[0m
[33m23-04-14 15:46:15 WARNING (MainThread) [supervisor.addons.options] Option 'web' does not exist in the schema for SSH & Web Terminal (a0d7b954_ssh)[0m
[33m23-04-14 15:46:15 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)[0m
[32m23-04-14 15:50:08 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-04-14 15:50:08 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-04-14 15:50:08 INFO (MainThread) [supervisor.api.middleware.security] /addons access from cebe7a76_hassio_google_drive_backup[0m
[32m23-04-14 15:51:19 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-04-14 15:51:19 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[33m23-04-14 15:51:19 WARNING (MainThread) [supervisor.addons.options] Option 'username' does not exist in the schema for File editor (core_configurator)[0m
[33m23-04-14 15:51:19 WARNING (MainThread) [supervisor.addons.options] Option 'password' does not exist in the schema for File editor (core_configurator)[0m
[33m23-04-14 15:51:19 WARNING (MainThread) [supervisor.addons.options] Option 'ssl' does not exist in the schema for File editor (core_configurator)[0m
[33m23-04-14 15:51:19 WARNING (MainThread) [supervisor.addons.options] Option 'certfile' does not exist in the schema for File editor (core_configurator)[0m
[33m23-04-14 15:51:19 WARNING (MainThread) [supervisor.addons.options] Option 'keyfile' does not exist in the schema for File editor (core_configurator)[0m
[33m23-04-14 15:51:19 WARNING (MainThread) [supervisor.addons.options] Option 'allowed_networks' does not exist in the schema for File editor (core_configurator)[0m
[33m23-04-14 15:51:19 WARNING (MainThread) [supervisor.addons.options] Option 'banned_ips' does not exist in the schema for File editor (core_configurator)[0m
[33m23-04-14 15:51:19 WARNING (MainThread) [supervisor.addons.options] Option 'banlimit' does not exist in the schema for File editor (core_configurator)[0m
[33m23-04-14 15:51:19 WARNING (MainThread) [supervisor.addons.options] Option 'notify_service' does not exist in the schema for File editor (core_configurator)[0m
[33m23-04-14 15:51:19 WARNING (MainThread) [supervisor.addons.options] Unknown option 'enable' for SSH & Web Terminal (a0d7b954_ssh)[0m
[33m23-04-14 15:51:19 WARNING (MainThread) [supervisor.addons.options] Unknown option 'port' for SSH & Web Terminal (a0d7b954_ssh)[0m
[33m23-04-14 15:51:19 WARNING (MainThread) [supervisor.addons.options] Option 'web' does not exist in the schema for SSH & Web Terminal (a0d7b954_ssh)[0m
[33m23-04-14 15:51:19 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)[0m
[32m23-04-14 15:52:11 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-04-14 15:52:11 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-04-14 15:52:11 INFO (MainThread) [supervisor.api.middleware.security] /addons access from cebe7a76_hassio_google_drive_backup[0m
[32m23-04-14 15:52:28 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.68.12', port=80): Read timed out. (read timeout=10.0)[0m
[33m2023-04-14 11:46:10.919 WARNING (MainThread) [homeassistant.components.media_player] Updating yamaha media_player took longer than the scheduled update interval 0:00:10[0m
[33m2023-04-14 11:46:10.927 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.yamaha_receiver is taking over 10 seconds[0m
[33m2023-04-14 11:46:30.922 WARNING (MainThread) [homeassistant.components.media_player] Updating yamaha media_player took longer than the scheduled update interval 0:00:10[0m
[33m2023-04-14 11:46:30.926 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.yamaha_receiver is taking over 10 seconds[0m
[33m2023-04-14 12:13:59.442 WARNING (Thread-18) [pychromecast.socket_client] [Bedroom TV(192.168.68.100):8009] Heartbeat timeout, resetting connection[0m
[31m2023-04-14 12:14:18.207 ERROR (Thread-18) [pychromecast.socket_client] [Bedroom TV(192.168.68.100):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.68.100', 8009)), retrying in 5.0s[0m
[33m2023-04-14 12:42:23.941 WARNING (Thread-18) [pychromecast.socket_client] [Bedroom TV(192.168.68.100):8009] Heartbeat timeout, resetting connection[0m
[31m2023-04-14 12:42:53.985 ERROR (Thread-18) [pychromecast.socket_client] [Bedroom TV(192.168.68.100):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.68.100', 8009)), retrying in 5.0s[0m
[33m2023-04-14 12:48:22.587 WARNING (Thread-18) [pychromecast.socket_client] [Bedroom TV(192.168.68.100):8009] Heartbeat timeout, resetting connection[0m
[31m2023-04-14 12:48:52.620 ERROR (Thread-18) [pychromecast.socket_client] [Bedroom TV(192.168.68.100):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.68.100', 8009)), retrying in 5.0s[0m
[33m2023-04-14 13:18:16.231 WARNING (Thread-18) [pychromecast.socket_client] [Bedroom TV(192.168.68.100):8009] Heartbeat timeout, resetting connection[0m
[31m2023-04-14 13:18:46.280 ERROR (Thread-18) [pychromecast.socket_client] [Bedroom TV(192.168.68.100):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.68.100', 8009)), retrying in 5.0s[0m
[33m2023-04-14 13:26:41.358 WARNING (Thread-18) [pychromecast.socket_client] [Bedroom TV(192.168.68.100):8009] Heartbeat timeout, resetting connection[0m
[31m2023-04-14 13:27:11.401 ERROR (Thread-18) [pychromecast.socket_client] [Bedroom TV(192.168.68.100):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.68.100', 8009)), retrying in 5.0s[0m
[33m2023-04-14 13:39:28.158 WARNING (Thread-18) [pychromecast.socket_client] [Bedroom TV(192.168.68.100):8009] Heartbeat timeout, resetting connection[0m
[31m2023-04-14 13:39:58.190 ERROR (Thread-18) [pychromecast.socket_client] [Bedroom TV(192.168.68.100):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.68.100', 8009)), retrying in 5.0s[0m
[33m2023-04-14 14:13:51.249 WARNING (Thread-18) [pychromecast.socket_client] [Bedroom TV(192.168.68.100):8009] Heartbeat timeout, resetting connection[0m
[31m2023-04-14 14:14:09.888 ERROR (Thread-18) [pychromecast.socket_client] [Bedroom TV(192.168.68.100):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.68.100', 8009)), retrying in 5.0s[0m
[33m2023-04-14 14:42:08.857 WARNING (Thread-18) [pychromecast.socket_client] [Bedroom TV(192.168.68.100):8009] Heartbeat timeout, resetting connection[0m
[31m2023-04-14 14:42:27.807 ERROR (Thread-18) [pychromecast.socket_client] [Bedroom TV(192.168.68.100):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.68.100', 8009)), retrying in 5.0s[0m
[33m2023-04-14 14:54:12.734 WARNING (Thread-18) [pychromecast.socket_client] [Bedroom TV(192.168.68.100):8009] Heartbeat timeout, resetting connection[0m
[31m2023-04-14 14:54:42.772 ERROR (Thread-18) [pychromecast.socket_client] [Bedroom TV(192.168.68.100):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.68.100', 8009)), retrying in 5.0s[0m
[33m2023-04-14 15:41:34.293 WARNING (MainThread) [frontend.js.latest.202304061] WARNING: Polymer will be removed from window in Home Assistant 2023.5. More info: https://developers.home-assistant.io/blog/2023/04/04/deprecating_polymer[0m
[31m2023-04-14 15:41:34.305 ERROR (MainThread) [frontend.js.latest.202304061] http://192.168.68.99:8123/lovelace/default_view:0:0 Uncaught [0m
[33m2023-04-14 15:46:56.924 WARNING (Thread-18) [pychromecast.socket_client] [Bedroom TV(192.168.68.100):8009] Heartbeat timeout, resetting connection[0m
[31m2023-04-14 15:47:15.808 ERROR (Thread-18) [pychromecast.socket_client] [Bedroom TV(192.168.68.100):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.68.100', 8009)), retrying in 5.0s[0m

 ```
  info from the previous page here

**Comment by sabeechen** [comment]
Sorry it took a while to get back to you.  This looks like either I have a bug or the Home Assistant Supervisor is stuck indefinitely on creating a backup, because its constantly requesting a new backup and for some reason thinks one is in progress.

Could I have you restart the Home Assistant machine.  Don't restart Home Assistant, actually reboot the whole amchine (this is the only way to stop a bugged backup, in case thats the problem).  If that isn't the problem I'll need to try to track down how this could happen.

**Comment by gboebel** [comment]
Thanks for getting back to me! This has been ongoing for a while now and
I've done many full power cycles; still get the same message.

Just did another power cycle and here's the current status of the back up.

[image: image.png]

**Comment by sabeechen** [comment]
Well damn, that means I probably have bug.  This will likely be difficult to track down.  I might need to add more data into the bug report.  Could I trouble you to restart the addon, then quickly go to the logs page (the logs link at the top right of the addon web-ui), download your complete log, and attach it here?

**Comment by gboebel** [comment]
No problem. Log attached.

**Comment by sabeechen** [comment]
I don't think attachments work if you post to a GiHub issue by email (nothing shows up on your post).  you can use https://github.com or just email to me directly stephen@beechens.com

**Comment by gboebel** [comment]
Haha, weird. Here it is again.

**Comment by sabeechen** [comment]
The error doesn't actually look like its showing up there, maybe it takes a couple seconds to manifest?  Ideally the log would capture the period from when the server starts to when it complains about a backup in progress at least once.

**Comment by gboebel** [comment]
Here's what it's got now.

**Comment by sabeechen** [comment]
Thanks, thats perfect

**Comment by sabeechen** [comment]
As expected this has been difficult to debug,  I've been unable to reproduce this situation in my testing.  My best guess is that the supervisor (a part of Home Assistant that makes backups and kinda manages everything) is giving the addon a response it doesn't correctly understand and that is getting interpreted as a backup in progress.

Your original bug report included some supervisor logs, but it got cut off because there are a bunch of warnings about extraneous addon config options.  This isn't a problem, it just pollutes the logs, and I suspect there is a useful warning in the supervisor logs higher up.  Could I have you check if there are any warnings or errors in the Supervisor logs, ignoring all the ones about "...does not exist in the schema..."

If you've never used the supervisor logs, you can get to them by going to:
1. ```Your user profile``` (bottom left of the HA UI) > Enable ```Advanced Mode```
2. Navigate to ```Settings``` > ```System``` > ```Logs``` > ```Supervisor```  (top right drop down)

**Comment by gboebel** [comment]
Here's the log with all of the "does not exist in the schema" errors
removed.


[33m23-04-23 12:07:57 WARNING (MainThread) [supervisor.addons.options]
Unknown option 'enable' for SSH & Web Terminal (a0d7b954_ssh) [0m
[33m23-04-23 12:07:57 WARNING (MainThread) [supervisor.addons.options]
Unknown option 'port' for SSH & Web Terminal (a0d7b954_ssh) [0m
[33m23-04-23 12:13:01 WARNING (MainThread) [supervisor.addons.options]
Unknown option 'enable' for SSH & Web Terminal (a0d7b954_ssh) [0m
[33m23-04-23 12:13:01 WARNING (MainThread) [supervisor.addons.options]
Unknown option 'port' for SSH & Web Terminal (a0d7b954_ssh) [0m
[32m23-04-23 12:13:39 INFO (MainThread)
[supervisor.api.middleware.security] /supervisor/info access from
cebe7a76_hassio_google_drive_backup [0m
[32m23-04-23 12:13:39 INFO (MainThread)
[supervisor.api.middleware.security] /backups access from
cebe7a76_hassio_google_drive_backup [0m
[32m23-04-23 12:13:41 INFO (MainThread)
[supervisor.api.middleware.security] /core/info access from
cebe7a76_hassio_google_drive_backup [0m
[32m23-04-23 12:13:41 INFO (MainThread)
[supervisor.api.middleware.security] /supervisor/info access from
cebe7a76_hassio_google_drive_backup [0m
[32m23-04-23 12:13:41 INFO (MainThread)
[supervisor.api.middleware.security] /addons access from
cebe7a76_hassio_google_drive_backup [0m
[32m23-04-23 12:13:41 INFO (MainThread)
[supervisor.api.middleware.security] /backups/new/full access from
cebe7a76_hassio_google_drive_backup [0m
[32m23-04-23 12:13:41 INFO (MainThread) [supervisor.backups.manager]
Creating new full backup with slug dec782b5 [0m
[32m23-04-23 12:13:41 INFO (MainThread) [supervisor.backups.manager]
Backing up dec782b5 store Add-ons [0m
[32m23-04-23 12:13:41 INFO (MainThread) [supervisor.addons.addon] Building
backup for add-on core_configurator [0m
[32m23-04-23 12:13:41 INFO (MainThread) [supervisor.addons.addon] Finish
backup for addon core_configurator [0m
[32m23-04-23 12:13:41 INFO (MainThread) [supervisor.addons.addon] Building
backup for add-on a0d7b954_ssh [0m
[32m23-04-23 12:13:41 INFO (MainThread) [supervisor.addons.addon] Finish
backup for addon a0d7b954_ssh [0m
[32m23-04-23 12:13:41 INFO (MainThread) [supervisor.addons.addon] Building
backup for add-on core_samba [0m
[32m23-04-23 12:13:41 INFO (MainThread) [supervisor.addons.addon] Finish
backup for addon core_samba [0m
[32m23-04-23 12:13:41 INFO (MainThread) [supervisor.addons.addon] Building
backup for add-on cebe7a76_hassio_google_drive_backup [0m
[32m23-04-23 12:13:41 INFO (MainThread) [supervisor.addons.addon] Finish
backup for addon cebe7a76_hassio_google_drive_backup [0m
[32m23-04-23 12:13:41 INFO (MainThread) [supervisor.homeassistant.module]
Backing up Home Assistant Core config folder [0m
[31m23-04-23 12:15:03 ERROR (MainThread) [supervisor.homeassistant.module]
Can't backup Home Assistant Core config folder: [Errno 5] I/O error [0m
[31m23-04-23 12:15:03 ERROR (MainThread) [supervisor.backups.manager]
Backup dec782b5 error [0m
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/module.py", line 341,
in backup
    await self.sys_run_in_executor(_write_tarfile)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58,
in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/homeassistant/module.py", line 332,
in _write_tarfile
    atomic_contents_add(
  File "/usr/local/lib/python3.10/site-packages/securetar/__init__.py",
line 191, in atomic_contents_add
    tar_file.add(directory_item.as_posix(), arcname=arcpath,
recursive=False)
  File "/usr/local/lib/python3.10/tarfile.py", line 2002, in add
    self.addfile(tarinfo, f)
  File "/usr/local/lib/python3.10/tarfile.py", line 2030, in addfile
    copyfileobj(fileobj, self.fileobj, tarinfo.size, bufsize=bufsize)
  File "/usr/local/lib/python3.10/tarfile.py", line 248, in copyfileobj
    buf = src.read(bufsize)
OSError: [Errno 5] I/O error
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/backups/manager.py", line 167, in
_do_backup
    await backup.store_homeassistant()
  File "/usr/src/supervisor/supervisor/backups/backup.py", line 485, in
store_homeassistant
    await self.sys_homeassistant.backup(homeassistant_file)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 156, in
wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 154, in
wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/homeassistant/module.py", line 344,
in backup
    raise HomeAssistantBackupError(
supervisor.exceptions.HomeAssistantBackupError: Can't backup Home Assistant
Core config folder: [Errno 5] I/O error
[32m23-04-23 12:15:04 INFO (MainThread)
[supervisor.api.middleware.security] /supervisor/info access from
cebe7a76_hassio_google_drive_backup [0m
[32m23-04-23 12:15:04 INFO (MainThread)
[supervisor.api.middleware.security] /backups access from
cebe7a76_hassio_google_drive_backup [0m
[33m23-04-23 12:18:05 WARNING (MainThread) [supervisor.addons.options]
Unknown option 'enable' for SSH & Web Terminal (a0d7b954_ssh) [0m
[33m23-04-23 12:18:05 WARNING (MainThread) [supervisor.addons.options]
Unknown option 'port' for SSH & Web Terminal (a0d7b954_ssh) [0m
[33m23-04-23 12:18:05 WARNING (MainThread) [supervisor.addons.options]
Option 'web' does not exist in the schema for SSH & Web Terminal
(a0d7b954_ssh) [0m
[33m23-04-23 12:23:09 WARNING (MainThread) [supervisor.addons.options]
Unknown option 'enable' for SSH & Web Terminal (a0d7b954_ssh) [0m
[33m23-04-23 12:23:09 WARNING (MainThread) [supervisor.addons.options]
Unknown option 'port' for SSH & Web Terminal (a0d7b954_ssh) [0m

**Comment by sabeechen** [comment]
Sorry it took a while to respond, I've been out of town.

This line is the one that matters:
```
[31m23-04-23 12:15:03 ERROR (MainThread) [supervisor.homeassistant.module] Can't backup Home Assistant Core config folder: [Errno 5] I/O error [0m
```

Home  Assistant is failing to backup your config folder due to a filesystem error, ```[Errno 5]``` and so it gives up.  Due to limitations in how the Home Assistant API works, the addon can't tell the difference between a backup the fails because of an error or because one is already in progress (HA says the same thing back either way) which is why you get the "Backup in progress" error.  I should change the language around  that error.

I couldn't find any solid explanation of what ```[Errno 5]``` means, but it seems the likely causes are:
1. File/directory does not exist
2. Insufficient permissions
3. File is used by another process
4. Corrupted file system or storage device

While any of those reasons are bad, the most frightening and likely one is a corrupted filesystem.  Do you have a good backup you could restore onto a fresh SD card?  Corruption tends to spread once it starts.

**Comment by gboebel** [comment]
Bummer. I should probably just do a clean install at this point. My system
is on an SSD, so it's definitely not a bad SD card at least!

**Comment by sabeechen** [comment]
I wish I could say confidently it was corruption, that error message doesn't give much to go off of.  Since you're using an SSD I assume that have some linux chops and a relatively custom install (most of my users just run an SD card on a pi).

Are you perhaps able to see the syslog of the machine HA runs on?  It may also be worthwhile to just try copying the /config folder off of it and see if it chokes trying to read one of the files.  It would be unfortunate to give up on some hardware without being certain its faulty.

**Comment by gboebel** [comment]
I can't believe it, but I may have solved it! Last night in preparation to do a clean install; I tried to copy the full config via Samba and it errored out as well. It flagged the specific file though! It was staling on "home-assistant_v2.db.corrupt" and I couldn't even delete it via Samba. I was able to delete it via the file editor in HA and BOOM! By this morning a backup had been made! I just tried to manually make another backup and it worked without issue.

Thanks for the guidance!

**Comment by sabeechen** [comment]
How strange!  I've never had someone run into that before, but I'll keep it in mind for the future.  If you ever learn any more about how that file came to be or why it was difficult to delete, I'd be curious to know.  I'm glad you were able to get things running again.
