### ISSUE TITLE
Forgotten password

### ISSUE THREAD

**Issue by migius** [sabeechen/hassio-google-drive-backup#828]
This is not a real issue butt an help request.
If I can't find my backup password is there any way to restore? How can I check if a password was setted up?

**Comment by sabeechen** [comment]
Sorry it took me a while to get back to you.

If you open up the backup in something like [7-zip](https://www.7-zip.org/)  you can see a backup.json file.  It will include a field "protected" that tells you if the backup is encrypted.  IF its encrypted you'll see:
```json
{
  "a bunch of stuff": "..."
  "protected": true,
  "a bunch of other stuff": "..."
}
```

As for the password, unfortunately the point is to keep someone out if they don't have it.  I'm not aware of a way to get it after the fact.

**Comment by migius** [comment]
My problem was that virtual machine doesn't start. 
I maked a copy of HD and mount it on a new virtual machine. The new one doesn't correctly create web server but allowed me to see addons and their properties and I fortunatly found my password.

**Comment by sabeechen** [comment]
I'm glad you were able to find it.  Make sure you keep that password somewhere safe!  I'm partial to [bitwarden](https://bitwarden.com/).
