### ISSUE TITLE
Unable to sync & view the logs

### ISSUE THREAD

**Issue by Eric2612** [sabeechen/hassio-google-drive-backup#830]
![image](https://user-images.githubusercontent.com/126200337/233175896-49a37d51-cc02-4b1a-8a59-da46668c9014.png)
![image](https://user-images.githubusercontent.com/126200337/233175977-67947eac-42ef-4721-8a69-2907c8ebe7f7.png)
 
This comes up when trying to paste in the sync code and viewing the logs. Any Ideas ?

**Comment by sabeechen** [comment]
Sometime some whitespace gets copied with the string, which can mess up its deserialization.  The string you're copying is just a regular base64 encoded json object, so if you're feeling a little bit technical you can use a web-based tool like like this one (https://www.base64decode.org/) to see if something else is getting messed up in it.

Not being able to view the logs is strange, I can't think of a way it'd be related to have trouble parsing the authorization string.  Do you see anything in the logs output that Home Assistant provides (''Settings" > "Addons" > "Home Assistant Google Drive Backup" > "Logs" tab).  That page should have the same info just less detailed.

**Comment by Eric2612** [comment]
Thank you very much IDK why but now it works . I tried on severall Occasions before and it did not work

**Comment by sabeechen** [comment]
Well, let me know if things get weird again.
