### ISSUE TITLE
Works with docker instalation?

### ISSUE THREAD

**Issue by ceinmart** [sabeechen/hassio-google-drive-backup#831]
Hi , 

I have my HA running on docker over a Debian / box tv.
Works fine.
However, I have the limitation of not having direct access to add-ons. 

Is there some way to install this add-on on this environment?
Even if I pull the docker and set up it manually?
If yes, there is any documentation on how to do it?

**Comment by avd706** [comment]
Why not. You can install a supervised version of HA on docker 11.  

Sent from AOL on Android 
 
  On Thu, Apr 20, 2023 at 19:39, ***@***.***> wrote:   


Hi ,

I have my HA running on docker over a Debian / box tv.
Works fine.
However, I have the limitation of not having direct access to add-ons.

Is there some way to install this add-on on this environment?
Even if I pull the docker and set up it manually?
If yes, there is any documentation on how to do it?

**Comment by sabeechen** [comment]
The addon requires the supervisor currently, it can't run without it.  I would like to support this in the future, but I'll need to find  the time as its quite a large change with meaningful ramifications.

Duplicate #586
