### ISSUE TITLE
401: Unauthorized

### ISSUE THREAD

**Issue by IMKKD** [sabeechen/hassio-google-drive-backup#836]
I have installed and configured google drive backup and it works, but if I open the user interface I receive a
401: Unauthorized
I have enabled web interface on additional port and it works outside homeassistant interface.
My homeassistant version is core-2023.3.6, add-on version is 0.110.3
I'm using chrome.

**Comment by sabeechen** [comment]
I just released v0.110.4, which should fix this problem.  It was caused by whitespace present in the authorization text, which Home Assistant no longer allows.  If you continue to see problems after updating to 0.110.4, please let me know.
