### ISSUE TITLE
Add-on reports Google Drive full erroneously

### ISSUE THREAD

**Issue by cansas** [sabeechen/hassio-google-drive-backup#84]
Add-on .98.1 HASSIO .96.5.

Reporting that Google drive is full but Drove is less than half full. Tried another Google Drive account and it failed as well.

**Comment by sabeechen** [comment]
Are your snapshots particularly large? (eg several GB)  Its possible for a single snapshot to be larger than the free space in Google Drive.  When that error comes up, it means Google thinks you don't have enough free space, it isn't something the add-on decides.  Has the addon worked in the past or is this a new install?

**Comment by cansas** [comment]
Addon has been working. I need to double check the screenshot size. I think the issue is in my share folder now that you mention that. Thanks!
