### ISSUE TITLE
Issue: after delete backup file is showed shifted info message

### ISSUE THREAD

**Issue by misa1515** [sabeechen/hassio-google-drive-backup#843]
Hello,
I don´t know where is best place for share issue:

Used HW and SW
- Android application (Home Assistant, all versions, till recent version HA 2023.4.6, supervisor 2023.04.1, OS 10.1, frontend 20230411.1),
- Cell phone Xiaomi 11T Pro (Android version 13 TKQ1.220829.002),

Issue description:
When created backup file (in hassio google drive backup) is opened and click on "delete", then is approved and info message is showed in bottom part of screen, but centering of info message is set to left screens side (for that reason half of info message is visible direct on screen and rest part of info message is outside screen (over left screen side)). 

Thank you.

**Comment by sabeechen** [comment]
Thanks for pointing this out.

Is this how it shows up on your phone, with just a little bit of the text off screen on the bottom left?
![over_text](https://user-images.githubusercontent.com/21026774/235705339-d135e52b-2eaa-49bb-93ac-482022287a71.png)

**Comment by misa1515** [comment]
Thank you.
Yes, it is like you described, but more to left side (less visible from info message).

**Comment by sabeechen** [comment]
I've fixed this in the latest version I just released, v0.111.1
