### ISSUE TITLE
Backup failing on newest HA beta 2023.6.0b2

### ISSUE THREAD

**Issue by Poshy163** [sabeechen/hassio-google-drive-backup#852]
```
 Addon version: `0.110.4`
 Home Assistant Version: `2023.6.0b2`
 Supervisor Version: `2023.06.0`
 Supervisor Channel: `beta`
 Hassos Version: `10.2`
 Docker Version: `23.0.6`
 Architecture: `amd64`
 Machine: `qemux86-64`
 Date: `2023-06-02T14:11:13.375849+00:00`
 Timezone: `Australia/Adelaide`
 Failure Time: `2023-06-02T14:11:03.318124+00:00`
 Last Good Sync: `2023-06-02T14:11:03.270613+00:00`
 Next Sync: `2023-06-02T14:12:23.318124+00:00`
 Next Backup: `2023-06-02T14:30:00+00:00`
 Next Cache Warm: `2023-06-02T14:10:58.136180+00:00`
 Time Offset: `0.0`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:246 (sync)
  addon/backup/drive/drivesource.py:194 (save)
  addon/backup/util/asynchttpgetter.py:228 (__aenter__)
  addon/backup/util/asynchttpgetter.py:61 (setup)
  addon/backup/util/asynchttpgetter.py:167 (_startReadRemoteAt)
  addon/backup/tracing_session.py:39 (_request)
  /site-packages/aiohttp/client.py:560 (_request)
  /site-packages/aiohttp/client_reqrep.py:899 (start)
  /site-packages/aiohttp/streams.py:616 (read)
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 1,
        "retained": 0,
        "deletable": 1,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2023-06-02T14:08:10Z",
        "max": 5,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 4,
        "detail": "",
        "size": "0.0 B",
        "ignored_size": "81.9 kB",
        "free_space": "68.0 GB"
    },
    "GoogleDrive": {
        "backups": 4,
        "retained": 0,
        "deletable": 4,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2023-06-01T14:57:56Z",
        "max": 5,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "detail": "redacted",
        "size": "488.1 MB",
        "ignored_size": "0.0 B",
        "free_space": "78.2 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_BACKUPS_IN_HA": 5,
    "Setting.MAX_BACKUPS_IN_GOOGLE_DRIVE": 5,
    "Setting.DAYS_BETWEEN_BACKUPS": 1.0,
    "Setting.IGNORE_OTHER_BACKUPS": true,
    "Setting.DELETE_BEFORE_NEW_BACKUP": true,
    "Setting.BACKUP_NAME": "REDACTED",
    "Setting.BACKUP_TIME_OF_DAY": "00:00",
    "Setting.DELETE_AFTER_UPLOAD": true,
    "Setting.SEND_ERROR_REPORTS": true
}
 ```
 ###### Addon Logs:
 ```
 06-02 23:37:26 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
06-02 23:37:26 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
06-02 23:37:26 INFO [backup.model.coordinator] Syncing Backups
06-02 23:37:27 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
06-02 23:38:10 INFO [backup.ha.hasource] Requesting a new backup
06-02 23:39:48 INFO [backup.ha.hasource] Backup finished
06-02 23:39:48 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
06-02 23:39:48 INFO [backup.model.coordinator] Syncing Backups
06-02 23:39:48 DEBUG [backup.ha.hasource] Adding a note to ha backup 'Backup'
06-02 23:39:49 INFO [backup.drive.drivesource] Deleting 'Full backup 05/29/23 00:00:00 : v2023.5.4 ' From Google Drive
06-02 23:39:50 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:246 (sync)
  addon/backup/drive/drivesource.py:194 (save)
  addon/backup/util/asynchttpgetter.py:228 (__aenter__)
  addon/backup/util/asynchttpgetter.py:61 (setup)
  addon/backup/util/asynchttpgetter.py:167 (_startReadRemoteAt)
  addon/backup/tracing_session.py:39 (_request)
  /site-packages/aiohttp/client.py:560 (_request)
  /site-packages/aiohttp/client_reqrep.py:899 (start)
  /site-packages/aiohttp/streams.py:616 (read)
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

06-02 23:39:50 INFO [backup.model.coordinator] I'll try again in 0 seconds
06-02 23:39:50 DEBUG [backup.model.syncer] Sync requested by Coordinator
06-02 23:39:50 INFO [backup.model.coordinator] Syncing Backups
06-02 23:39:51 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:246 (sync)
  addon/backup/drive/drivesource.py:194 (save)
  addon/backup/util/asynchttpgetter.py:228 (__aenter__)
  addon/backup/util/asynchttpgetter.py:61 (setup)
  addon/backup/util/asynchttpgetter.py:167 (_startReadRemoteAt)
  addon/backup/tracing_session.py:39 (_request)
  /site-packages/aiohttp/client.py:560 (_request)
  /site-packages/aiohttp/client_reqrep.py:899 (start)
  /site-packages/aiohttp/streams.py:616 (read)
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

06-02 23:39:51 INFO [backup.model.coordinator] I'll try again in 10 seconds
06-02 23:39:58 INFO [backup.debugworker] Sending error report (see settings to disable)
06-02 23:40:01 DEBUG [backup.model.syncer] Sync requested by Coordinator
06-02 23:40:01 INFO [backup.model.coordinator] Syncing Backups
06-02 23:40:02 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:246 (sync)
  addon/backup/drive/drivesource.py:194 (save)
  addon/backup/util/asynchttpgetter.py:228 (__aenter__)
  addon/backup/util/asynchttpgetter.py:61 (setup)
  addon/backup/util/asynchttpgetter.py:167 (_startReadRemoteAt)
  addon/backup/tracing_session.py:39 (_request)
  /site-packages/aiohttp/client.py:560 (_request)
  /site-packages/aiohttp/client_reqrep.py:899 (start)
  /site-packages/aiohttp/streams.py:616 (read)
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

06-02 23:40:02 INFO [backup.model.coordinator] I'll try again in 20 seconds
06-02 23:40:22 DEBUG [backup.model.syncer] Sync requested by Coordinator
06-02 23:40:22 INFO [backup.model.coordinator] Syncing Backups
06-02 23:40:23 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:246 (sync)
  addon/backup/drive/drivesource.py:194 (save)
  addon/backup/util/asynchttpgetter.py:228 (__aenter__)
  addon/backup/util/asynchttpgetter.py:61 (setup)
  addon/backup/util/asynchttpgetter.py:167 (_startReadRemoteAt)
  addon/backup/tracing_session.py:39 (_request)
  /site-packages/aiohttp/client.py:560 (_request)
  /site-packages/aiohttp/client_reqrep.py:899 (start)
  /site-packages/aiohttp/streams.py:616 (read)
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

06-02 23:40:23 INFO [backup.model.coordinator] I'll try again in 40 seconds
06-02 23:40:29 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
06-02 23:41:03 DEBUG [backup.model.syncer] Sync requested by Coordinator
06-02 23:41:03 INFO [backup.model.coordinator] Syncing Backups
06-02 23:41:03 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:246 (sync)
  addon/backup/drive/drivesource.py:194 (save)
  addon/backup/util/asynchttpgetter.py:228 (__aenter__)
  addon/backup/util/asynchttpgetter.py:61 (setup)
  addon/backup/util/asynchttpgetter.py:167 (_startReadRemoteAt)
  addon/backup/tracing_session.py:39 (_request)
  /site-packages/aiohttp/client.py:560 (_request)
  /site-packages/aiohttp/client_reqrep.py:899 (start)
  /site-packages/aiohttp/streams.py:616 (read)
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

06-02 23:41:03 INFO [backup.model.coordinator] I'll try again in 1 minutes, 20 seconds
 ```
 ###### Supervisor Logs:
 ```
   File "/usr/local/lib/python3.11/pathlib.py", line 1013, in stat
    return os.stat(self, follow_symlinks=follow_symlinks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/data/mounts/Woxic/f29743d8.tar'
[32m23-06-02 23:41:03 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-06-02 23:41:03 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m23-06-02 23:41:03 INFO (MainThread) [supervisor.api.middleware.security] /backups/f29743d8/download access from cebe7a76_hassio_google_drive_backup[0m
[32m23-06-02 23:41:03 INFO (MainThread) [supervisor.api.backups] Downloading backup f29743d8[0m
[31m23-06-02 23:41:03 ERROR (MainThread) [aiohttp.server] Unhandled exception[0m
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 512, in start
    resp, reset = await task
                  ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 458, in _handle_request
    reset = await self.finish_response(request, resp, start_time)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 611, in finish_response
    await prepare_meth(request)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_fileresponse.py", line 142, in prepare
    st: os.stat_result = await loop.run_in_executor(None, filepath.stat)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/pathlib.py", line 1013, in stat
    return os.stat(self, follow_symlinks=follow_symlinks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/data/mounts/Woxic/f29743d8.tar'
[32m23-06-02 23:41:13 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
 [33m2023-06-02 23:07:59.801 WARNING (Thread-5) [pychromecast.socket_client] [Kogan tv(192.168.1.222):8009] Heartbeat timeout, resetting connection[0m
[31m2023-06-02 23:17:32.715 ERROR (SyncWorker_5) [homeassistant.components.co2signal] Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/co2signal/__init__.py", line 115, in get_data
    data = CO2Signal.get_latest(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/CO2Signal/co2signal.py", line 38, in get_latest
    .json())
     ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)[0m
[31m2023-06-02 23:17:32.718 ERROR (MainThread) [homeassistant.components.co2signal] Error fetching co2signal data: [0m
[33m2023-06-02 23:24:42.857 WARNING (MainThread) [homeassistant.components.discord.notify] Channel not found for ID: 974948447335620668[0m

 ```

**Comment by sabeechen** [comment]
Based on the timestamps and logs it looks like this is being caused by a problem in the supervisor:
```
[31m23-06-02 23:41:03 ERROR (MainThread) [aiohttp.server] Unhandled exception�[0m
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 512, in start
resp, reset = await task
^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 458, in _handle_request
reset = await self.finish_response(request, resp, start_time)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 611, in finish_response
await prepare_meth(request)
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_fileresponse.py", line 142, in prepare
st: os.stat_result = await loop.run_in_executor(None, filepath.stat)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/pathlib.py", line 1013, in stat
return os.stat(self, follow_symlinks=follow_symlinks)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/data/mounts/Woxic/f29743d8.tar'
```

From the addon's perspective, a ```ServerDisconnectedError``` is whats expected if the supervisor were unable to serve the contents of a backup, which appears to be what happening.  It looks like the backup file isn't in the place the supervisor expects it to be.  The path its reading from ```/data/mounts/Woxic/f29743d8.tar``` looks unusual.  Are you doing anything uncomon with your installation that could make the supervisor confused about where its files should be, or perhaps this is just a bug in the beta channel of the supervisor that needs to get ironed out?

**Comment by Poshy163** [comment]
Seems quite odd as the only thing i've added is that new backup to SMB/external media option. 

Will do some testing later on, but is for sure related inadvertently to one of the new features in the beta

**Comment by Poshy163** [comment]
It appears that when adding backups to a network storage drive (new feature in the recent beta), it doesn't appear to keep any local backups, hence the error, removing the network storage for backups resolved the issue. 

Will contact the dev team to see if this is intended or not, but for now will close this issue.
