### ISSUE TITLE
Add Bitcoin Lightning donate

### ISSUE THREAD

**Issue by iBobik** [sabeechen/hassio-google-drive-backup#858]
Just wanted to send you some sats, but I does not want to spend more for on-chain fees. :-)

**Comment by M5M400** [comment]
send some monero then. Like I just did.

0.00003 XMR fees. not even a cent ;)

**Comment by sabeechen** [comment]
@M5M400  Yikes, just saw your contribution.  Thats the biggest individual donation anyone has made so far.  Thank you, I'll put it to good use.  I try to keep the addon's cloud footprint pretty lean, that'll pay server costs for almost 3 months.

WRT bitcoin lightening I appreciate the suggestion but I think I'm going to avoid it.  It doesn't looks to me like there is a way to use it except with a custodial wallet (deal breaker for me) or to keep a node running 24/7 (also a deal breaker).
