### ISSUE TITLE
2023.6 - network backup

### ISSUE THREAD

**Issue by sushant-here** [sabeechen/hassio-google-drive-backup#868]
As part of Homeassistant 2023.6. I've setup a network storage (on a NAS) for backups. When I create the backup from homeassistant - it backs up to the NAS. However when I create the backup from this plugin - it doesn't. This means my daily backups aren't being copied to my NAS.

Any advice on how to get both NAS and Google drive backups working?

Thanks!

**Comment by sabeechen** [comment]
Duplicate #856 

Right now the addon is unaware of shares, but I'm working on the feature and it should be out in a few days.  With that release it will use the "Default" backup location when backups are made instead of always storing them locally.
