### ISSUE TITLE
Feature request: only backup between certain hours

### ISSUE THREAD

**Issue by haaino** [sabeechen/hassio-google-drive-backup#876]
Hi,

I have a feature request. Would it be possible to add the possibility to only upload to Google between certain time intervals?

Best regards 
Haaino

**Comment by sabeechen** [comment]
Sorry this took me so long to get back to you one, life has been getting in the way of me supporting the addon.  

The easiest way to do this is just start/stop the addon when you do or dont want it to upload, eg:

![image](https://github.com/sabeechen/hassio-google-drive-backup/assets/21026774/d117dbc2-d29d-4479-839b-3fcd21d4a0c7)
