### ISSUE TITLE
No Add-on Store

### ISSUE THREAD

**Issue by oywino** [sabeechen/hassio-google-drive-backup#882]
For those of us who run HA Core in a container and have no add-on store. Can we install this integration through HACS or otherwise?

**Comment by sabeechen** [comment]
It only works through the supervisor, the dependency is much more than superficial ATM.  I'd like to make a version that runs directly in HA, but I'm finding it difficult to make time recently.  There are some technical challenges too, for one HA doesn't give a way for integrations to make "rich" UI's, just lists of entities you can configure.

**Comment by antonyoneill** [comment]
I think it'd be really useful to add a note in the installation steps to explicitly note that this addon only works in the supervisor installation. I had to trawl through the issues here to discover this myself..

**Comment by Mark-Hetherington** [comment]
@antonyoneill It's taken me a while to understand this, but it isn't an issue of this add on specifically, but *all* add-ons. HA Core and HA container do not support add-ons, and while I didn't come across it when originally installing HA container, this is documented at https://www.home-assistant.io/installation/#advanced-installation-methods

**Comment by oywino** [comment]
Most add-on's can be installed and run independently in Docker containers.
