### ISSUE TITLE
Errors on Google Drive Backup Installation

### ISSUE THREAD

**Issue by JohnMacHeli** [sabeechen/hassio-google-drive-backup#894]
I am having problems installing Google Drive Backup per documentation.

I can add it to the repository OK.  I can install it OK.  My problem is Starting it.

After clicking the Start button, it circles for 2 minutes then reverts back to Start.  No link to open UI,  Red dot still in upper right corner (stopped).  No Settings to click.  No Authentication of Google Drive.  But it seems to have tried to Start it based on the Logs.  I hope you can help.  Thanks.

Here are the Logs:

After Start -

Addon log:

07-26 08:20:19 INFO Starting server on port 8099
07-26 08:20:19 INFO Server started
07-26 08:20:19 INFO Syncing Backups

Supervisor log:

23-07-26 08:13:30 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/sabeechen/hassio-google-drive-backup repository
23-07-26 08:13:34 INFO (MainThread) [supervisor.store] Loading add-ons from store: 72 all - 1 new - 0 remove
23-07-26 08:14:26 INFO (MainThread) [supervisor.store.git] Removing custom add-on repository https://github.com/sabeechen/hassio-google-drive-backup
23-07-26 08:14:28 INFO (MainThread) [supervisor.store] Loading add-ons from store: 71 all - 0 new - 1 remove
23-07-26 08:15:52 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/sabeechen/hassio-google-drive-backup repository
23-07-26 08:15:56 INFO (MainThread) [supervisor.store] Loading add-ons from store: 72 all - 1 new - 0 remove
23-07-26 08:16:50 INFO (MainThread) [supervisor.addons] Creating Home Assistant add-on data folder /data/addons/data/cebe7a76_hassio_google_drive_backup
23-07-26 08:16:50 INFO (SyncWorker_3) [supervisor.docker.interface] Downloading docker image sabeechen/hassio-google-drive-backup-aarch64 with tag 0.111.1.
23-07-26 08:18:08 INFO (MainThread) [supervisor.addons] Add-on 'cebe7a76_hassio_google_drive_backup' successfully installed
23-07-26 08:18:30 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-07-26 08:18:30 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
23-07-26 08:18:30 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
23-07-26 08:18:30 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
23-07-26 08:18:30 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository
23-07-26 08:18:35 INFO (MainThread) [supervisor.store] Loading add-ons from store: 72 all - 0 new - 0 remove
23-07-26 08:18:35 INFO (MainThread) [supervisor.store] Loading add-ons from store: 72 all - 0 new - 0 remove
23-07-26 08:20:10 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-07-26 08:20:17 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on sabeechen/hassio-google-drive-backup-aarch64 with version 0.111.1
23-07-26 08:20:19 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from cebe7a76_hassio_google_drive_backup
23-07-26 08:20:19 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
23-07-26 08:20:19 INFO (MainThread) [supervisor.api.middleware.security] /mounts access from cebe7a76_hassio_google_drive_backup
23-07-26 08:20:19 INFO (MainThread) [supervisor.api.middleware.security] /addons access from cebe7a76_hassio_google_drive_backup
23-07-26 08:20:19 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
23-07-26 08:20:19 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
23-07-26 08:20:19 INFO (MainThread) [supervisor.api.middleware.security] /backups/50602fa5/info access from cebe7a76_hassio_google_drive_backup
23-07-26 08:20:19 INFO (MainThread) [supervisor.api.middleware.security] /backups/630aa4bc/info access from cebe7a76_hassio_google_drive_backup
23-07-26 08:20:19 INFO (MainThread) [supervisor.api.middleware.security] /backups/117ce5fa/info access from cebe7a76_hassio_google_drive_backup
23-07-26 08:20:19 INFO (MainThread) [supervisor.api.middleware.security] /backups/61f556bc/info access from cebe7a76_hassio_google_drive_backup
23-07-26 08:20:19 INFO (MainThread) [supervisor.api.middleware.security] /backups/6a87079c/info access from cebe7a76_hassio_google_drive_backup
23-07-26 08:22:17 WARNING (MainThread) [supervisor.addons.addon] Timeout while waiting for addon Home Assistant Google Drive Backup to start, took more then 120 seconds

**Comment by Divide1990** [comment]
Had the exact same issue. What fixed it for me was a complete reset of HA. Reset as in cut the power and start it up again.
Not sure why it happens tho but its working now.

**Comment by JohnMacHeli** [comment]
@Divide1990 Thank you!  I thought I had done this, but was part of a chaotic process to try everything:(
Working fine now.
