### ISSUE TITLE
No personal name in Backups on NAS

### ISSUE THREAD

**Issue by aperezva** [sabeechen/hassio-google-drive-backup#897]
Hi,

Please could you review why when I execute a backup directly to my NAS Synologic with SAMBA from HA, name is not respected and my backups has a random name . If I see this same backup in home Assistant or in Google drive , the name is correct
<img width="1773" alt="Captura de pantalla 2023-08-01 a las 7 57 26" src="https://github.com/sabeechen/hassio-google-drive-backup/assets/58134028/89a7814e-23c8-4aec-9161-9fded95e7b64">

**Comment by sabeechen** [comment]
This is a limitation in Home Assistant.  HA manages the connection to the NAS and decides what the file names are. Currently it always chooses to use what it calls the "slug", which is a random ID.
