### ISSUE TITLE
Purge Old Backups Early doesn't work when Backups in Drive set to 0

### ISSUE THREAD

**Issue by jack5mikemotown** [sabeechen/hassio-google-drive-backup#898]
###### Description:
```
Purge Old Backups Early is not working. When generational backups are removed from the generational cycle, they remain in my Google Drive, rather than being deleted```

 Addon version: `0.111.1`
 Home Assistant Version: `2023.8.0`
 Supervisor Version: `2023.07.1`
 Supervisor Channel: `stable`
 Hassos Version: `10.4`
 Docker Version: `23.0.6`
 Architecture: `amd64`
 Machine: `qemux86-64`
 Date: `2023-08-06T21:18:37.077372+00:00`
 Timezone: `America/New_York`
 Failure Time: `Never`
 Last Good Sync: `2023-08-06T21:17:20.043452+00:00`
 Next Sync: `2023-08-06T23:49:30.341810+00:00`
 Next Backup: `2023-08-07T05:49:08.658097+00:00`
 Next Cache Warm: `2023-08-06T23:40:31.907754+00:00`
 Time Offset: `0.0`
 ###### Exception:
 ```
 No error could be identified automatically.
 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 5,
        "retained": 0,
        "deletable": 5,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2023-08-06T05:49:08Z",
        "max": 5,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 18,
        "detail": "",
        "size": "2.7 GB",
        "ignored_size": "1.1 GB",
        "free_space": "11.5 GB"
    },
    "GoogleDrive": {
        "backups": 31,
        "retained": 0,
        "deletable": 31,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2023-08-06T05:49:08Z",
        "max": 0,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "detail": "hirschbergofficial@gmail.com",
        "size": "12.7 GB",
        "ignored_size": "0.0 B",
        "free_space": "41.8 MB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_BACKUPS_IN_HA": 5,
    "Setting.MAX_BACKUPS_IN_GOOGLE_DRIVE": 0,
    "Setting.DAYS_BETWEEN_BACKUPS": 1.0,
    "Setting.DELETE_IGNORED_AFTER_DAYS": 28.0,
    "Setting.GENERATIONAL_DAYS": 7,
    "Setting.GENERATIONAL_WEEKS": 4,
    "Setting.GENERATIONAL_MONTHS": 12,
    "Setting.GENERATIONAL_YEARS": 10,
    "Setting.GENERATIONAL_DELETE_EARLY": true,
    "Setting.EXCLUDE_FOLDERS": "media",
    "Setting.EXCLUDE_ADDONS": "a0d7b954_influxdb",
    "Setting.SEND_ERROR_REPORTS": true
}
 ```
 ###### Addon Logs:
 ```
 08-06 03:39:04 INFO [backup.model.coordinator] Syncing Backups
08-06 05:35:42 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
08-06 05:35:42 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
08-06 05:42:36 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-06 05:42:36 INFO [backup.model.coordinator] Syncing Backups
08-06 08:02:46 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
08-06 08:02:46 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
08-06 08:12:33 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-06 08:12:33 INFO [backup.model.coordinator] Syncing Backups
08-06 10:49:48 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
08-06 10:49:48 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
08-06 11:03:50 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-06 11:03:50 INFO [backup.model.coordinator] Syncing Backups
08-06 11:10:05 INFO [backup.watcher] A backup directory file was modified, we'll check for new backups soon.
08-06 11:10:15 DEBUG [backup.watcher] Checking backup source for changes...
08-06 13:06:50 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
08-06 13:06:50 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
08-06 13:14:45 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-06 13:14:45 INFO [backup.model.coordinator] Syncing Backups
08-06 15:59:52 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
08-06 15:59:52 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
08-06 16:05:07 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-06 16:05:07 INFO [backup.model.coordinator] Syncing Backups
08-06 16:05:07 INFO [backup.ha.hasource] Deleting 'addon_7094bb28_docker-wyze-bridge_2.3.9' from Home Assistant
08-06 16:05:07 INFO [backup.watcher] A backup directory file was modified, we'll check for new backups soon.
08-06 16:05:17 DEBUG [backup.watcher] Checking backup source for changes...
08-06 16:05:17 DEBUG [backup.model.syncer] Sync requested by Backup Directory Watcher
08-06 16:05:17 INFO [backup.model.coordinator] Syncing Backups
08-06 17:17:20 INFO [backup.model.coordinator] Syncing Backups
08-06 17:17:20 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
 ```
 ###### Supervisor Logs:
 ```
 [32m23-08-06 17:02:33 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m23-08-06 17:02:33 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING[0m
[32m23-08-06 17:02:34 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m23-08-06 17:02:34 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING[0m
[32m23-08-06 17:02:34 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m
[32m23-08-06 17:08:47 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m23-08-06 17:10:10 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
[32m23-08-06 17:14:20 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup/ repository[0m
[32m23-08-06 17:14:20 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository[0m
[32m23-08-06 17:14:20 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sharptools-io/hass-addons.git repository[0m
[32m23-08-06 17:14:20 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository[0m
[32m23-08-06 17:14:21 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/mrlt8/docker-wyze-bridge repository[0m
[32m23-08-06 17:14:21 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository[0m
[32m23-08-06 17:14:21 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository[0m
[32m23-08-06 17:14:21 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/alexbelgium/hassio-addons repository[0m
[32m23-08-06 17:14:21 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/ikifar2012/ha-addons repository[0m
[32m23-08-06 17:14:32 INFO (MainThread) [supervisor.store] Loading add-ons from store: 160 all - 0 new - 0 remove[0m
[32m23-08-06 17:14:32 INFO (MainThread) [supervisor.store] Loading add-ons from store: 160 all - 0 new - 0 remove[0m
[32m23-08-06 17:15:45 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-08-06 17:15:45 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-08-06 17:15:45 INFO (MainThread) [supervisor.api.middleware.security] /mounts access from cebe7a76_hassio_google_drive_backup[0m
[32m23-08-06 17:15:45 INFO (MainThread) [supervisor.api.middleware.security] /addons access from cebe7a76_hassio_google_drive_backup[0m
[32m23-08-06 17:17:20 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-08-06 17:17:20 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m23-08-06 17:17:40 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-08-06 17:17:40 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-08-06 17:17:40 INFO (MainThread) [supervisor.api.middleware.security] /mounts access from cebe7a76_hassio_google_drive_backup[0m
[32m23-08-06 17:17:41 INFO (MainThread) [supervisor.api.middleware.security] /addons access from cebe7a76_hassio_google_drive_backup[0m
[32m23-08-06 17:18:37 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
   File "/config/custom_components/localtuya/pytuya/__init__.py", line 450, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError[0m
[33m2023-08-06 17:18:17.500 WARNING (MainThread) [custom_components.localtuya.common] [213...926] Disconnected - waiting for discovery broadcast[0m
[31m2023-08-06 17:18:22.498 ERROR (MainThread) [custom_components.localtuya.common] [213...926] Failed to set DPs {22: 8}
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/locks.py", line 387, in acquire
    await fut
asyncio.exceptions.CancelledError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 333, in set_dps
    await self._interface.set_dps(states)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 846, in set_dps
    return await self.exchange(CONTROL, dps)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 769, in exchange
    msg = await self.dispatcher.wait_for(seqno, payload.cmd)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 450, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError[0m

 ```

**Comment by jack5mikemotown** [comment]
After messing around a bit, it appears that setting the max backups in drive to 0 disables backup management entirely. I would have assumed that checking Purge Early would allow for an exception for when a generational backup is removed from the generational cycle, but this option appears to be ignored entirely with max backups set to 0.

Unsure if it's intended behavior or not, but imo it makes sense to let Purge Early function when checked, even with backups set to 0.

**Comment by sabeechen** [comment]
Setting backups in drive to 0 disables deleting backups in Drive for any reason, thats the contract for it.  Making it delete sometimes would be confusing for the typical use case.  If you'd like to keep the delete early behavior, I think you can just set "Max Backups in Google Drive" to something ridiculous, like 1000000.
