### ISSUE TITLE
Exclude media folder?

### ISSUE THREAD

**Issue by awilliams84** [sabeechen/hassio-google-drive-backup#899]
How do I exclude the media folder that has made my backups balloon in size from 6-7GB to 60-70GB?

I read this, but I am unclear if I can or cannot exclude the media folder from backup:
> Can I exclude specific sub-folders from my backup?
> The add-on uses the supervisor to create backups, and the supervisor only permits you to include or exclude the 5 main folders (home assistant configuration, share, SSL, media, and local add-ons). Excluding specific subfolders, or only including specific subfolders from a backup isn't possible today.

**Comment by awilliams84** [comment]
I missed the one checkbox where I could schedule the backup and just not check the media folder. Sorry about that.

**Comment by uherting** [comment]
Can someone add  to the docs that one has to activate Partial Backup in order to see the checkbox to exclude the media folder? This would be helpful. I accidentally found out about it as it is not the most obvious way. Thanks! See https://github.com/sabeechen/hassio-google-drive-backup/issues/1162

**Comment by AlecRust** [comment]
@uherting this project is essentially dead, check out the new native backup options in Home Assistant.
