### ISSUE TITLE
Log file is full from snapshot info entries .....

### ISSUE THREAD

**Issue by Obicom** [sabeechen/hassio-google-drive-backup#9]
System log
 19-03-31 02:51:02 INFO (MainThread) [hassio.api.security] /snapshots/32773edf/info access from cebe7a76_hassio_google_drive_backup
19-03-31 02:51:05 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/snapshot_backup.state access from cebe7a76_hassio_google_drive_backup
19-03-31 02:51:05 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/binary_sensor.snapshots_stale access from cebe7a76_hassio_google_drive_backup
19-03-31 03:01:31 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
19-03-31 03:31:31 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
19-03-31 03:51:08 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
19-03-31 03:51:08 INFO (MainThread) [hassio.api.security] /snapshots/b8f41e9f/info access from cebe7a76_hassio_google_drive_backup
19-03-31 03:51:08 INFO (MainThread) [hassio.api.security] /snapshots/d1beaf22/info access from cebe7a76_hassio_google_drive_backup
19-03-31 03:51:08 INFO (MainThread) [hassio.api.security] /snapshots/3f58545f/info access from cebe7a76_hassio_google_drive_backup
19-03-31 03:51:09 INFO (MainThread) [hassio.api.security] /snapshots/32773edf/info access from cebe7a76_hassio_google_drive_backup
19-03-31 03:51:10 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/snapshot_backup.state access from cebe7a76_hassio_google_drive_backup
19-03-31 03:51:10 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/binary_sensor.snapshots_stale access from cebe7a76_hassio_google_drive_backup
19-03-31 04:01:32 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
19-03-31 04:31:32 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
19-03-31 04:51:14 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
19-03-31 04:51:14 INFO (MainThread) [hassio.api.security] /snapshots/b8f41e9f/info access from cebe7a76_hassio_google_drive_backup
19-03-31 04:51:14 INFO (MainThread) [hassio.api.security] /snapshots/d1beaf22/info access from cebe7a76_hassio_google_drive_backup
19-03-31 04:51:14 INFO (MainThread) [hassio.api.security] /snapshots/3f58545f/info access from cebe7a76_hassio_google_drive_backup
19-03-31 04:51:14 INFO (MainThread) [hassio.api.security] /snapshots/32773edf/info access from cebe7a76_hassio_google_drive_backup
19-03-31 04:51:16 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/snapshot_backup.state access from cebe7a76_hassio_google_drive_backup
19-03-31 04:51:16 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/binary_sensor.snapshots_stale access from cebe7a76_hassio_google_drive_backup
19-03-31 05:01:32 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
19-03-31 05:31:32 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
19-03-31 05:51:19 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
19-03-31 05:51:19 INFO (MainThread) [hassio.api.security] /snapshots/b8f41e9f/info access from cebe7a76_hassio_google_drive_backup
19-03-31 05:51:20 INFO (MainThread) [hassio.api.security] /snapshots/d1beaf22/info access from cebe7a76_hassio_google_drive_backup
19-03-31 05:51:20 INFO (MainThread) [hassio.api.security] /snapshots/3f58545f/info access from cebe7a76_hassio_google_drive_backup
19-03-31 05:51:20 INFO (MainThread) [hassio.api.security] /snapshots/32773edf/info access from cebe7a76_hassio_google_drive_backup
19-03-31 05:51:22 INFO (MainThread) [hassio.api.security] /snapshots/new/full access from cebe7a76_hassio_google_drive_backup
19-03-31 05:51:22 INFO (MainThread) [hassio.snapshots] Full-Snapshot 4ab58093 start
19-03-31 05:51:22 INFO (MainThread) [hassio.snapshots] Snapshot 4ab58093 store Add-ons
19-03-31 05:51:22 INFO (MainThread) [hassio.addons.addon] Build snapshot for add-on 15ef4d2f_esphome
19-03-31 05:51:22 INFO (MainThread) [hassio.addons.addon] Build snapshot for add-on a0d7b954_glances
19-03-31 05:51:22 INFO (MainThread) [hassio.addons.addon] Build snapshot for add-on core_duckdns
19-03-31 05:51:22 INFO (MainThread) [hassio.addons.addon] Build snapshot for add-on core_check_config
19-03-31 05:51:22 INFO (MainThread) [hassio.addons.addon] Build snapshot for add-on core_configurator
19-03-31 05:51:22 INFO (MainThread) [hassio.addons.addon] Build snapshot for add-on core_ssh
19-03-31 05:51:22 INFO (MainThread) [hassio.addons.addon] Build snapshot for add-on core_samba
19-03-31 05:51:22 INFO (MainThread) [hassio.addons.addon] Build snapshot for add-on core_mosquitto
19-03-31 05:51:22 INFO (MainThread) [hassio.addons.addon] Build snapshot for add-on cebe7a76_hassio_google_drive_backup
19-03-31 05:51:22 INFO (MainThread) [hassio.addons.addon] Finish snapshot for addon core_check_config
19-03-31 05:51:22 INFO (MainThread) [hassio.addons.addon] Finish snapshot for addon core_configurator
19-03-31 05:51:22 INFO (MainThread) [hassio.addons.addon] Finish snapshot for addon a0d7b954_glances
19-03-31 05:51:22 INFO (MainThread) [hassio.addons.addon] Finish snapshot for addon core_samba
19-03-31 05:51:22 INFO (MainThread) [hassio.addons.addon] Finish snapshot for addon cebe7a76_hassio_google_drive_backup
19-03-31 05:51:22 INFO (MainThread) [hassio.addons.addon] Finish snapshot for addon core_mosquitto
19-03-31 05:51:22 INFO (MainThread) [hassio.addons.addon] Finish snapshot for addon core_ssh
19-03-31 05:51:22 INFO (MainThread) [hassio.addons.addon] Finish snapshot for addon core_duckdns
19-03-31 05:51:32 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/snapshot_backup.state access from cebe7a76_hassio_google_drive_backup
19-03-31 05:51:32 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/binary_sensor.snapshots_stale access from cebe7a76_hassio_google_drive_backup
19-03-31 05:51:40 INFO (SyncWorker_12) [hassio.docker.addon] Export image 62c7908d/armv7-addon-autobackup to /data/tmp/tmpojv0c6fr/image.tar
19-03-31 05:51:41 INFO (MainThread) [hassio.addons.addon] Finish snapshot for addon 15ef4d2f_esphome
19-03-31 05:51:42 INFO (SyncWorker_12) [hassio.docker.addon] Export image 62c7908d/armv7-addon-autobackup done
19-03-31 05:51:42 INFO (MainThread) [hassio.addons.addon] Build snapshot for add-on 62c7908d_autobackup
19-03-31 05:52:54 INFO (MainThread) [hassio.addons.addon] Finish snapshot for addon 62c7908d_autobackup
19-03-31 05:52:54 INFO (MainThread) [hassio.snapshots] Snapshot 4ab58093 store folders
19-03-31 05:52:54 INFO (SyncWorker_4) [hassio.snapshots.snapshot] Snapshot folder addons/local
19-03-31 05:52:54 INFO (SyncWorker_8) [hassio.snapshots.snapshot] Snapshot folder share
19-03-31 05:52:54 INFO (SyncWorker_14) [hassio.snapshots.snapshot] Snapshot folder ssl
19-03-31 05:52:54 INFO (SyncWorker_13) [hassio.snapshots.snapshot] Snapshot folder homeassistant
19-03-31 05:52:54 INFO (SyncWorker_4) [hassio.snapshots.snapshot] Snapshot folder addons/local done
19-03-31 05:52:54 INFO (SyncWorker_8) [hassio.snapshots.snapshot] Snapshot folder share done
19-03-31 05:52:54 INFO (SyncWorker_14) [hassio.snapshots.snapshot] Snapshot folder ssl done
19-03-31 05:57:11 INFO (SyncWorker_13) [hassio.snapshots.snapshot] Snapshot folder homeassistant done
19-03-31 05:57:12 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
19-03-31 05:57:13 INFO (MainThread) [hassio.api.security] /snapshots/b8f41e9f/info access from cebe7a76_hassio_google_drive_backup
19-03-31 05:57:13 INFO (MainThread) [hassio.api.security] /snapshots/d1beaf22/info access from cebe7a76_hassio_google_drive_backup
19-03-31 05:57:13 INFO (MainThread) [hassio.api.security] /snapshots/3f58545f/info access from cebe7a76_hassio_google_drive_backup
19-03-31 05:57:13 INFO (MainThread) [hassio.api.security] /snapshots/32773edf/info access from cebe7a76_hassio_google_drive_backup
19-03-31 05:57:15 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/snapshot_backup.state access from cebe7a76_hassio_google_drive_backup
19-03-31 05:57:29 INFO (MainThread) [hassio.snapshots] Full-Snapshot 4ab58093 done
19-03-31 05:57:35 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
19-03-31 05:57:35 INFO (MainThread) [hassio.api.security] /snapshots/b8f41e9f/info access from cebe7a76_hassio_google_drive_backup
19-03-31 05:57:35 INFO (MainThread) [hassio.api.security] /snapshots/3f58545f/info access from cebe7a76_hassio_google_drive_backup
19-03-31 05:57:35 INFO (MainThread) [hassio.api.security] /snapshots/4ab58093/info access from cebe7a76_hassio_google_drive_backup
19-03-31 05:57:35 INFO (MainThread) [hassio.api.security] /snapshots/d1beaf22/info access from cebe7a76_hassio_google_drive_backup
19-03-31 05:57:35 INFO (MainThread) [hassio.api.security] /snapshots/32773edf/info access from cebe7a76_hassio_google_drive_backup
19-03-31 05:57:37 INFO (MainThread) [hassio.api.security] /snapshots/32773edf/remove access from cebe7a76_hassio_google_drive_backup
19-03-31 05:57:37 INFO (MainThread) [hassio.snapshots] Removed snapshot file 32773edf
19-03-31 05:57:37 INFO (MainThread) [hassio.api.security] /snapshots/4ab58093/download access from cebe7a76_hassio_google_drive_backup
19-03-31 05:57:37 INFO (MainThread) [hassio.api.snapshots] Download snapshot 4ab58093
19-03-31 05:59:53 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/snapshot_backup.state access from cebe7a76_hassio_google_drive_backup
19-03-31 05:59:54 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/binary_sensor.snapshots_stale access from cebe7a76_hassio_google_drive_backup
19-03-31 06:00:04 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
19-03-31 06:00:04 INFO (MainThread) [hassio.api.security] /snapshots/b8f41e9f/info access from cebe7a76_hassio_google_drive_backup
19-03-31 06:00:04 INFO (MainThread) [hassio.api.security] /snapshots/d1beaf22/info access from cebe7a76_hassio_google_drive_backup
19-03-31 06:00:04 INFO (MainThread) [hassio.api.security] /snapshots/4ab58093/info access from cebe7a76_hassio_google_drive_backup
19-03-31 06:00:04 INFO (MainThread) [hassio.api.security] /snapshots/3f58545f/info access from cebe7a76_hassio_google_drive_backup
19-03-31 06:00:05 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/snapshot_backup.state access from cebe7a76_hassio_google_drive_backup
19-03-31 06:00:05 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/binary_sensor.snapshots_stale access from cebe7a76_hassio_google_drive_backup
19-03-31 06:01:32 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
19-03-31 06:31:32 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
19-03-31 07:00:09 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
19-03-31 07:00:09 INFO (MainThread) [hassio.api.security] /snapshots/b8f41e9f/info access from cebe7a76_hassio_google_drive_backup
19-03-31 07:00:09 INFO (MainThread) [hassio.api.security] /snapshots/d1beaf22/info access from cebe7a76_hassio_google_drive_backup
19-03-31 07:00:09 INFO (MainThread) [hassio.api.security] /snapshots/4ab58093/info access from cebe7a76_hassio_google_drive_backup
19-03-31 07:00:09 INFO (MainThread) [hassio.api.security] /snapshots/3f58545f/info access from cebe7a76_hassio_google_drive_backup
19-03-31 07:00:11 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/snapshot_backup.state access from cebe7a76_hassio_google_drive_backup
19-03-31 07:00:11 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/binary_sensor.snapshots_stale access from cebe7a76_hassio_google_drive_backup
19-03-31 07:01:32 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token

**Comment by sabeechen** [comment]
Hass.io prints these out any time an add-on accesses the details about a snapshot.  I don't know why they do, but I don't think there is a way for me to disable it from the add-on side, so the extra hourly supervisor logging kind of comes with this add-on.
You could make it happen less frequently by adding this to your add-on config `"seconds_between_refreshes": 21600`, which will make it show up once every 6 hours (instead of the default 1 hour) or whenever you create a snapshot. The only downside is that you'd have to wait up to 6 hours before it would notice if something changed in Google Drive.
If it **really** bothers you, you could open an issue with the hass.io devs, since they're the only ones who  could get rid of it for good.
