### ISSUE TITLE
Broken Pipe/Maximum Retries for URL

### ISSUE THREAD

**Issue by dragonflyuk** [sabeechen/hassio-google-drive-backup#90]
Backups have been working faultlessly until around 6 days ago, since then I have been gettin a mix of broken Pipe errors and max Retries for URL errors. I do have my motioneye cctv backed up to the same drive account, so I did wonder if it was related to rate limiting. So I paused that along with my rclone script that I used to catch any skipped videos, but the backup still fails. So I then tried reinstating all my cctv stuff, and using rclone to copy the ha backups, which works apart from that way I don't get proper filenames for my backups on gdrive.

I have tried adding lines to the config section for the add-on through hassio for timeout, and alternative dns, but that made no difference.

Any thoughts anyone?

**Comment by dragonflyuk** [comment]
I've been playing in the code, I was going to add a time delay on retries, to see if it was rate limiting, but found you already had code in for that. I tried a mild tweak, and got abit more of the backup uploaded, but still failing just at a higher percentage, so I then used the sledgehammer to crack a nut approach.

# Defines the retry strategy for calls made to Drive
# max # of time to retry and call to Drive
DRIVE_MAX_RETRIES: int = 500
# The initial backoff for drive retries.
DRIVE_RETRY_INITIAL_SECONDS: int = 30
# How uch longer to wait for each Drive service call (Exponential backoff)
DRIVE_EXPONENTIAL_BACKOFF: int = 30

I have now got 2 of my backups uploaded. Lol the first in 5 days. I do wonder if once it has caught up with the backlog, I got back to my mild tweak it might work better. Which was 10,5,5 incidentally.

**Comment by sabeechen** [comment]
What is the text of the exception is the add-on throwing?  You might be able to see more information from the debug logs within the addon (click "LOGS" at the top).  Any detail for the exception and the messages before it would be helpful.  Some possible causes I can think of are:
* Your snapshots are unusually large/slow to upload, and its just unlikely foe the whole upload to complete before some part of it fails.  I'll be able to tell if this is the case If I can see your logs.
* Your Google Drive account is under a lot of contention (eg lots of things are try to read/write form it simultaneously).  You could see if this is the case by creating a new google account and seeing if your snapshot upload there.

I could make those constants you're modifying configurable if it helps solve the problem for you.  If you're still playing with them you'll want to set DRIVE_MAX_RETRIES high while DRIVE_RETRY_INITIAL_SECONDS and DRIVE_EXPONENTIAL_BACKOFF to something low.  They control the logic for how long to wait to retry after a failed request to Google Drive.  After each failure it will wait `DRIVE_RETRY_INITIAL_SECONDS * (failure count) ^ DRIVE_EXPONENTIAL_BACKOFF`seconds before trying again.

**Comment by dragonflyuk** [comment]
From the log file I get 

08-08 04:49:30 DEBUG Ran into trouble reaching Google Drive's servers.  We'll use alternate DNS servers on the next attempt.
08-08 04:49:30 ERROR    
Traceback (most recent call last):   
  File "/app/backup/coordinator.py", line 102, in _sync   
    self._buildModel().sync(self._time.now())   
  File "/app/backup/model.py", line 145, in sync   
    upload.addSource(self.dest.save(upload, self.source.read(upload)))   
  File "/app/backup/drivesource.py", line 117, in save   
    for progress in self.drivebackend.create(bytes, file_metadata, MIME_TYPE):   
  File "/app/backup/driverequests.py", line 192, in create   
    partial = self.retryRequest("PUT", location, headers=headers, data=data, patch_url=False)   
  File "/app/backup/driverequests.py", line 245, in retryRequest   
    raise e   
  File "/app/backup/driverequests.py", line 234, in retryRequest   
    response = self._request_client.request(method, url, headers=send_headers, json=json, timeout=self.config.get(Setting.GOOGLE_DRIVE_TIMEOUT_SECONDS), data=data, stream=stream)   
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request   
    return session.request(method=method, url=url, **kwargs)   
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request   
    resp = self.send(prep, **send_kwargs)   
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send   
    r = adapter.send(request, **kwargs)   
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 498, in send   
    raise ConnectionError(err, request=request)   
requests.exceptions.ConnectionError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))

I am on a 4g connection so I do expect the odd glitch but it is generally quite stable and rclone and motioneye do mostly succeed with their uploads, as did the backup upto a few days ago.

I can use rclone to copy the files without fail, so I don't know if it has better error detection or can resume failed uploads or something.

The upload is just over 500mb at the moment, so large but not hideous.

**Comment by dragonflyuk** [comment]
Got a different sort of error today

08-11 05:12:31 ERROR    
Traceback (most recent call last):   
  File "/app/backup/coordinator.py", line 102, in _sync   
    self._buildModel().sync(self._time.now())   
  File "/app/backup/model.py", line 145, in sync   
    upload.addSource(self.dest.save(upload, self.source.read(upload)))   
  File "/app/backup/drivesource.py", line 117, in save   
    for progress in self.drivebackend.create(bytes, file_metadata, MIME_TYPE):   
  File "/app/backup/driverequests.py", line 192, in create   
    partial = self.retryRequest("PUT", location, headers=headers, data=data, patch_url=False)   
  File "/app/backup/driverequests.py", line 245, in retryRequest   
    raise e   
  File "/app/backup/driverequests.py", line 234, in retryRequest   
    response = self._request_client.request(method, url, headers=send_headers, json=json, timeout=self.config.get(Setting.GOOGLE_DRIVE_TIMEOUT_SECONDS), data=data, stream=stream)   
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request   
    return session.request(method=method, url=url, **kwargs)   
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request   
    resp = self.send(prep, **send_kwargs)   
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send   
    r = adapter.send(request, **kwargs)   
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 514, in send   
    raise SSLError(e, request=request)   
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.googleapis.com', port=443): Max retries exceeded with url: /upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=AEnB2UpTxnMhDgBNN2vPiLvqBulQqtgHaqYM3W3rhdRw9kowBgachJY4bxUwYb37NPuOPmELh83nFUD6YalWx-oTRM1k_kYHOA (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2488)')))   

I also notice that it often gets further after I restart either hassio or the add-on, is it possible that something is not been restarted between attempts?? Or even cached.

**Comment by dragonflyuk** [comment]
After a run of backups getting uploadedwith a day or so, the problem is back, I lay the blame mostly at my 4g connection.

I've setup up an rclone task to backup the files to my gdrive, but obviously these have different names etc. Is it going to cause any issues if these go into the same folder as the synced backups??

Incidentally rclone backed up the 4 snapshots on my hassio in 34min without a glitch, totalling 2.739Gb

**Comment by sabeechen** [comment]
Th addon can only see/modify files it creates, so anything you have rclone put in the folder will just get ignored.  Rclone probably does a much better job than the addon of retrying "transient" failures.  

Right now the addon always attempts to upload a "chunk" of the same size (5mb), and I suspect the problem your installation is running into is that it can't get through that 5mb without interruption.  I'll make it upload smaller chunks after larger ones fail with this error.

**Comment by dragonflyuk** [comment]
If my rclone uploads aren't going to interfere with things, then the only real inconvenience is the non-descript file names, but unfairness simply sorting Google drive by last modified would solve that in seconds.

I already run an rclone script because motioneye doesn't even attempt to retry failed videos, so I run an rclone copy every couple of hours anyway. It's just one more directory in the list.

**Comment by sabeechen** [comment]
I've just release v 0.98.4, which handles resuming failed partial uploads better.  Now it'll pick up where it left off so it can make progress between attempts and adjust the size of each chunk it uploads for spotty connections.   I'm closing this bug now since I think this will let you use the addon instead or rsync (if you still want to), but feel free to reopen the issue if you still run into problems and think I can help.

**Comment by dragonflyuk** [comment]
Thanks for the work, much appreciated, as things were, if I get 2 consecutive backups, in a row it's a good run.LOL. I'll get it installed, and comment in a week or 2 to let you know.

**Comment by dragonflyuk** [comment]
I can confirm, that it was a vast improvement. Looking at the logs, it looks like I get almost the same number of dropped uploads, but we know that is my 4g connection. However they now pickup and carry on. I really wouldn't know about the issues if I didn't go and look at the logs. 

Thanks for the work, much appreciated.
