### ISSUE TITLE
Is there a way to change the sub folder in Google Drive?

### ISSUE THREAD

**Issue by dubhunter** [sabeechen/hassio-google-drive-backup#904]
First off...awesome add-on!!

So hopefully this is easy but I couldn't seem to figure it out on my own or by Googling.

I have two instances of HA using the add-on. They both backup to their own subfolder in "Home Assistant Backups". I have moved and so want to change the name of one of the Subfolders. How can I do this?

Thanks!

**Comment by sabeechen** [comment]
You can just rename or move the folder in Drive, it won't lose track.  You can specify a different folder through the addon's settings.

**Comment by dubhunter** [comment]
Oh cool. I didn't see it in settings, but if I can just move it...that will do it. Thanks for the quick reply!!
