### ISSUE TITLE
Internal Server error

### ISSUE THREAD

**Issue by nagydavid** [sabeechen/hassio-google-drive-backup#905]
HI I would like to report a bug:

Bug:
`Internal Server Error`

Happened out of nowhere, possibly Google Issue, according to the client response.

Version: 0.111.1 
HA Version: 2023.08.02

LOG:
08-14 16:48:39 INFO Starting server on port 8099
08-14 16:48:39 INFO Server started
08-14 16:48:39 INFO Syncing Backups
08-14 16:48:39 ERROR 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:203 (sync)
  addon/backup/model/model.py:317 (_syncBackups)
  addon/backup/ha/hasource.py:270 (get)
  addon/backup/ha/harequests.py:34 (wrap_and_call)
  addon/backup/ha/harequests.py:135 (backups)
  addon/backup/ha/harequests.py:34 (wrap_and_call)
  addon/backup/ha/harequests.py:269 (_getHassioData)
  addon/backup/ha/harequests.py:225 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1005 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('http://supervisor/backups')

**Comment by sabeechen** [comment]
This error is coming from home assistant, when the add-on asks for the current list of backups.  You'll likely see something in the supervisor logs that could explain what's happening.  [See here](https://github.com/sabeechen/hassio-google-drive-backup#im-getting-weird-errors--where-do-i-look-for-more-detils-about-an-error-supervisor-logs) for how to get to them.
