### ISSUE TITLE
[Feature Request] Enable control of Google Drive Upload by Home Assistant

### ISSUE THREAD

**Issue by chrisberesford** [sabeechen/hassio-google-drive-backup#908]
I often have periods where the internet connection is provided by 4G and data is metered. I would like to automatically disable Google Drive uploads during this period to avoid excessive data usage. Home Assistant knows if it's on metered or unmetered internet connection, so exposing the Google Drive upload checkbox as a switch (or similar) to HA would allow me to automate it.

**Comment by sabeechen** [comment]
I actually made a little progress on implementing a "time window" setting where you coudl disable uploads on a daily schedule, but it proved to be a little mroe complicated than I thought.

I think your use case would be betetr served by just turning the addon on and off.  You can do that through, for example this turns off the addon at 4AM every day:
![image](https://github.com/sabeechen/hassio-google-drive-backup/assets/21026774/b4616b18-638d-4e7a-9323-71991aa04138)

similarly you could make an automation that turns it on when you know you can spend the bandwidth
