### ISSUE TITLE
sensor.backup_state exceed maximum size of 16384 bytes

### ISSUE THREAD

**Issue by mauriceatkinson** [sabeechen/hassio-google-drive-backup#922]
I am seeing this error message in the Home Assistant Core log.

The full error is
`State attributes for sensor.backup_state exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
12:51:33 – (WARNING) Recorder - message first occurred at 09:35:35 and shows up 5 times`

The backup service is working.  My config is set to retain 4 local backups and indefinitaly keep the backups in Google Drive.

**Comment by sabeechen** [comment]
It would take quite a few backups, but its certainly possible for the sensor.backup_state sensor that the addon publishes to be over 16kb if its publishing the state of a lot of backups.  You can disable publishing of the sensor in the addon's settings if you'd like the error to go away.

**Comment by emilianogetino** [comment]
I have the same problem, how do I deactivate that sensor? Thank you

**Comment by sabeechen** [comment]
Its in the settings labelled "Enable Backup State Sensor"
