### ISSUE TITLE
An unexpected error occurred: 404 Client Error: Not Found for url

### ISSUE THREAD

**Issue by orion-LY** [sabeechen/hassio-google-drive-backup#94]
Tried rebooting/reinstalling add-on but it's still repeating the same error.

E: Used another google account and it works.

**Comment by orion-LY** [comment]
Issue was that the account had never been to the Google drive so i guess it wasn't a thing yet

**Comment by sabeechen** [comment]
Thanks for reporting this, it's something I'd never considered and I'm glad you were able to get it to work.  I'd like to be able to provide a better error message (and maybe some guidance) for users that run into this in the future, and to do that I'll need to reproduce what you saw.  
We're you able to use the original Google account after you went to Drive with it?

**Comment by orion-LY** [comment]
Yeah once I'd gone into the actual drive at least once everything worked fine with the account that was erroring.
