### ISSUE TITLE
Automatic snapshot created twice each time

### ISSUE THREAD

**Issue by dmatik** [sabeechen/hassio-google-drive-backup#95]
Hi,
I have set to create a backup during the night every 3 days, keep 4 snapshots on Hassio and 10 on Google Drive.
For months it was working fine, however recently I see that each snapshot is being created twice, every time. Not sure when exactly the issue started.

![2019-09-03_11-20-47](https://user-images.githubusercontent.com/5577386/64156868-3e4c6900-ce3e-11e9-8402-a2910f3b65c6.png)

[hassio-google-drive-backup.log](https://github.com/sabeechen/hassio-google-drive-backup/files/3568587/hassio-google-drive-backup.log)

**Comment by sabeechen** [comment]
Sorry it took me so long to get back to you, I had to step away from maintenance of this for a little bit.  I had someone run into this problem once before but wasn't able to solve it.  Having the logs this time is illuminating, so thank you.   There is definitely some kind of race condition happening.

**Comment by sabeechen** [comment]
I think I found the problem, I'll release a minor update with a fix soon.

**Comment by sabeechen** [comment]
I just released 0.98.3, which should fix the race condition causing this.  Please re-open the issue if you still see problems.

**Comment by dmatik** [comment]
Thanks a lot for fixing it. 
I will see in coming weeks how it goes.

**Comment by sabeechen** [comment]
Thank YOU for calling it to my attention!
