### ISSUE TITLE
Choosing Exclude DB from backup not working

### ISSUE THREAD

**Issue by cjramseyer** [sabeechen/hassio-google-drive-backup#955]
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
Addon version: 0.112.1 Home Assistant Version: 2023.11.3 Supervisor Version: 2023.11.6 Supervisor Channel: stable Hassos Version: 11.1 Docker Version: 24.0.6 Architecture: amd64 Machine: qemux86-64 Date: 2023-12-07T20:54:45.478717+00:00 Timezone: America/New_York Failure Time: Never Last Good Sync: 2023-12-07T20:52:36.846327+00:00 Next Sync: 2023-12-07T22:36:14.658127+00:00 Next Backup: 2023-12-08T07:00:00+00:00 Next Cache Warm: 2023-12-07T22:28:34.072496+00:00 Time Offset: 0.0

Exception:
No error could be identified automatically.
Backups:

{
   "HomeAssistant": {
       "backups": 2,
       "retained": 0,
       "deletable": 2,
       "name": "HomeAssistant",
       "title": "Home Assistant",
       "latest": "2023-12-07T20:46:03Z",
       "max": 2,
       "enabled": true,
       "icon": "home-assistant",
       "ignored": 0,
       "detail": "",
       "size": "1.0 GB",
       "ignored_size": "0.0 B"
   },
   "GoogleDrive": {
       "backups": 10,
       "retained": 0,
       "deletable": 10,
       "name": "GoogleDrive",
       "title": "Google Drive",
       "latest": "2023-12-07T07:00:00Z",
       "max": 10,
       "enabled": true,
       "icon": "google-drive",
       "ignored": 0,
       "detail": "hickoryhome19@gmail.com",
       "size": "5.1 GB",
       "ignored_size": "0.0 B",
       "free_space": "9.9 GB"
   }
}
Config:
{
   "Setting.MAX_BACKUPS_IN_HA": 2,
   "Setting.MAX_BACKUPS_IN_GOOGLE_DRIVE": 10,
   "Setting.DAYS_BETWEEN_BACKUPS": 1.0,
   "Setting.DELETE_IGNORED_AFTER_DAYS": 30.0,
   "Setting.BACKUP_TIME_OF_DAY": "02:00",
   "Setting.BACKUP_PASSWORD": "REDACTED",
   "Setting.BACKUP_STORAGE": "Backups",
   "Setting.EXCLUDE_HA_DATABASE": true,
   "Setting.SEND_ERROR_REPORTS": true,
   "Setting.IGNORE_IPV6_ADDRESSES": true
}
Addon Logs:
12-07 15:52:37 DEBUG [backup.drive.driverequests] Starting a new upload session with Google Drive
12-07 15:52:37 DEBUG [backup.drive.driverequests] Sending 256 KB to Google Drive
12-07 15:52:38 DEBUG [backup.drive.drivesource] Uploading Test without DB 0.05%
12-07 15:52:38 DEBUG [backup.drive.driverequests] Sending 5.25 MB to Google Drive
12-07 15:52:46 DEBUG [backup.drive.drivesource] Uploading Test without DB 1.05%
12-07 15:52:46 DEBUG [backup.drive.driverequests] Sending 6.5 MB to Google Drive
12-07 15:52:56 DEBUG [backup.drive.drivesource] Uploading Test without DB 2.30%
12-07 15:52:56 DEBUG [backup.drive.driverequests] Sending 6.5 MB to Google Drive
12-07 15:53:06 DEBUG [backup.drive.drivesource] Uploading Test without DB 3.54%
12-07 15:53:06 DEBUG [backup.drive.driverequests] Sending 6.5 MB to Google Drive
12-07 15:53:16 DEBUG [backup.drive.drivesource] Uploading Test without DB 4.79%
12-07 15:53:16 DEBUG [backup.drive.driverequests] Sending 6.5 MB to Google Drive
12-07 15:53:26 DEBUG [backup.drive.drivesource] Uploading Test without DB 6.03%
12-07 15:53:26 DEBUG [backup.drive.driverequests] Sending 6.5 MB to Google Drive
12-07 15:53:36 DEBUG [backup.drive.drivesource] Uploading Test without DB 7.28%
12-07 15:53:36 DEBUG [backup.drive.driverequests] Sending 6.5 MB to Google Drive
12-07 15:53:46 DEBUG [backup.drive.drivesource] Uploading Test without DB 8.52%
12-07 15:53:46 DEBUG [backup.drive.driverequests] Sending 6.5 MB to Google Drive
12-07 15:53:56 DEBUG [backup.drive.drivesource] Uploading Test without DB 9.77%
12-07 15:53:56 DEBUG [backup.drive.driverequests] Sending 6.25 MB to Google Drive
12-07 15:54:05 DEBUG [backup.drive.drivesource] Uploading Test without DB 10.97%
12-07 15:54:05 DEBUG [backup.drive.driverequests] Sending 6.25 MB to Google Drive
12-07 15:54:15 DEBUG [backup.drive.drivesource] Uploading Test without DB 12.16%
12-07 15:54:15 DEBUG [backup.drive.driverequests] Sending 6.5 MB to Google Drive
12-07 15:54:25 DEBUG [backup.drive.drivesource] Uploading Test without DB 13.41%
12-07 15:54:25 DEBUG [backup.drive.driverequests] Sending 6.5 MB to Google Drive
12-07 15:54:35 DEBUG [backup.drive.drivesource] Uploading Test without DB 14.65%
12-07 15:54:35 DEBUG [backup.drive.driverequests] Sending 6.25 MB to Google Drive
12-07 15:54:44 DEBUG [backup.drive.drivesource] Uploading Test without DB 15.85%
12-07 15:54:45 DEBUG [backup.drive.driverequests] Sending 6.5 MB to Google Drive
Supervisor Logs:
[32m23-12-07 15:50:09 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon ccab4aaf_frigate-proxy[0m
[32m23-12-07 15:50:09 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on 424ccef4_crowdsec[0m
[32m23-12-07 15:50:09 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon 424ccef4_crowdsec[0m
[32m23-12-07 15:50:09 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_wireguard[0m
[32m23-12-07 15:50:09 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon a0d7b954_wireguard[0m
[32m23-12-07 15:50:09 INFO (MainThread) [supervisor.backups.manager] Backup 2d1380e0 starting stage home_assistant[0m
[32m23-12-07 15:50:09 INFO (MainThread) [supervisor.homeassistant.module] Backing up Home Assistant Core config folder[0m
[32m23-12-07 15:50:43 INFO (MainThread) [supervisor.homeassistant.module] Backup Home Assistant Core config folder done[0m
[32m23-12-07 15:50:43 INFO (MainThread) [supervisor.backups.manager] Backup 2d1380e0 starting stage folders[0m
[32m23-12-07 15:50:43 INFO (SyncWorker_0) [supervisor.backups.backup] Backing up folder share[0m
[32m23-12-07 15:50:45 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'pinmap'[0m
[32m23-12-07 15:50:45 INFO (MainThread) [supervisor.auth] Successful login for 'pinmap'[0m
[32m23-12-07 15:51:05 INFO (SyncWorker_0) [supervisor.backups.backup] Backup folder share done[0m
[32m23-12-07 15:51:05 INFO (SyncWorker_2) [supervisor.backups.backup] Backing up folder addons/local[0m
[32m23-12-07 15:51:05 INFO (SyncWorker_2) [supervisor.backups.backup] Backup folder addons/local done[0m
[32m23-12-07 15:51:05 INFO (SyncWorker_5) [supervisor.backups.backup] Backing up folder ssl[0m
[32m23-12-07 15:51:05 INFO (SyncWorker_5) [supervisor.backups.backup] Backup folder ssl done[0m
[32m23-12-07 15:51:05 INFO (SyncWorker_3) [supervisor.backups.backup] Backing up folder media[0m
[32m23-12-07 15:51:05 INFO (SyncWorker_3) [supervisor.backups.backup] Backup folder media done[0m
[32m23-12-07 15:51:05 INFO (MainThread) [supervisor.backups.manager] Backup 2d1380e0 starting stage finishing_file[0m
[32m23-12-07 15:52:36 INFO (MainThread) [supervisor.backups.manager] Creating full backup with slug 2d1380e0 completed[0m
[32m23-12-07 15:52:36 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-12-07 15:52:36 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m23-12-07 15:52:36 INFO (MainThread) [supervisor.api.middleware.security] /backups/2d1380e0/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-12-07 15:52:37 INFO (MainThread) [supervisor.api.middleware.security] /backups/23155446 access from cebe7a76_hassio_google_drive_backup[0m
[32m23-12-07 15:52:37 INFO (MainThread) [supervisor.backups.manager] Removed backup file 23155446[0m
[32m23-12-07 15:52:37 INFO (MainThread) [supervisor.api.middleware.security] /backups/2d1380e0/download access from cebe7a76_hassio_google_drive_backup[0m
[32m23-12-07 15:52:37 INFO (MainThread) [supervisor.api.backups] Downloading backup 2d1380e0[0m
[32m23-12-07 15:54:45 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

Home Assistant Core Logs:
 Unexpected token '<'::[0m
[31m2023-12-07 14:30:24.430 ERROR (MainThread) [frontend.js.latest.202310302] Uncaught error from Chrome 119.0.0.0 on Windows 10
ReferenceError: Polymer is not defined
/hacsfiles/light-entity-row/light-entity-row.js:10:40[0m
[33m2023-12-07 14:44:59.415 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.cj_s22_active_notification_count exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored[0m
[33m2023-12-07 14:45:04.600 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.cj_s22_active_notification_count exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored[0m
[33m2023-12-07 14:52:06.935 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities input_boolean.set_by_calendar are missing or not currently available[0m
[33m2023-12-07 14:52:11.959 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities input_boolean.set_by_calendar are missing or not currently available[0m
[33m2023-12-07 14:52:46.860 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.cj_s22_active_notification_count exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored[0m
[33m2023-12-07 15:06:16.422 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.cj_s22_active_notification_count exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored[0m
[31m2023-12-07 15:08:50.302 ERROR (MainThread) [frontend.js.latest.202310302] Uncaught error from Chrome 119.0.0.0 on Windows 10
SyntaxError: Unexpected token '<'
Unexpected token '<'::[0m
[31m2023-12-07 15:08:50.311 ERROR (MainThread) [frontend.js.latest.202310302] Uncaught error from Chrome 119.0.0.0 on Windows 10
ReferenceError: Polymer is not defined
/hacsfiles/light-entity-row/light-entity-row.js:10:40[0m
[33m2023-12-07 15:12:28.867 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.cj_s22_active_notification_count exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored[0m
[33m2023-12-07 15:12:31.700 WARNING (MainThread) [homeassistant.components.media_player] Error retrieving proxied image from http://10.10.0.16:8060/query/icon/562859[0m
[33m2023-12-07 15:12:44.027 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.cj_s22_active_notification_count exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored[0m
[33m2023-12-07 15:14:08.378 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.cj_s22_active_notification_count exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored[0m
[33m2023-12-07 15:15:55.192 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.cj_s22_active_notification_count exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored[0m
[33m2023-12-07 15:18:31.513 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.cj_s22_active_notification_count exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored[0m
[33m2023-12-07 15:19:51.220 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.cj_s22_active_notification_count exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored[0m
[31m2023-12-07 15:37:46.212 ERROR (MainThread) [frontend.js.latest.202310302] Uncaught error from Chrome 119.0.0.0 on Windows 10
SyntaxError: Unexpected token '<'
Unexpected token '<'::[0m
[31m2023-12-07 15:37:46.217 ERROR (MainThread) [frontend.js.latest.202310302] Uncaught error from Chrome 119.0.0.0 on Windows 10
ReferenceError: Polymer is not defined
/hacsfiles/light-entity-row/light-entity-row.js:10:40[0m

**Comment by sabeechen** [comment]
Is there something happening here?  I don't see any errors related to the addon in the logs you posted.

**Comment by cjramseyer** [comment]
> Is there something happening here? I don't see any errors related to the addon in the logs you posted.

The HA database is not being excluded.  Whether the option is enabled or not, backups for my instance are still 500+ MB.
I don't need the history from theDB, so wanted to exclude it.  The size should go down significantly.

**Comment by sabeechen** [comment]
Sorry, shoudl have read the title closer.  Could you get me a copy of the `backup.json` file inside the backup you created with the database excluded?  Even if the backup is encrypted, you should be able to decompress the backup and retrieve that file.

**Comment by cjramseyer** [comment]
[backup.json](https://github.com/sabeechen/hassio-google-drive-backup/files/13720867/backup.json)

**Comment by sabeechen** [comment]
Sorry this took a while to get back.  In the backup config file I can see that `"exclude_database": true`, so Home Assistant isn't backing up _its internal database_.  You use the MariaDB addon for the database, so to exclude it from backups you'll need to do a "partial" backup and exclude that addon.

**Comment by cjramseyer** [comment]
OK, I will try that. Thank you


On December 26, 2023 10:38:31 AM Stephen Beechen ***@***.***> wrote:

Sorry this took a while to get back. In the backup config file I can see that "exclude_database": true, so Home Assistant isn't backing up its internal database. You use the MariaDB addon for the database, so to exclude it from backups you'll need to do a "partial" backup and exclude that addon.
