### ISSUE TITLE
Feature: Configure backup location in Google Drive

### ISSUE THREAD

**Issue by JeffersonBledsoe** [sabeechen/hassio-google-drive-backup#956]
From what I can see, there's nothing in the Docs about being able to choose where to set the Google Drive location and `FOLDER_NAME` is only ever set to `Home Assistant Backups`. Would it be possible to add an option to change the name of the folder and even the location (e.g. put it in a sub-directory) in Google Drive?

**Comment by sabeechen** [comment]
You can just change the folder name or put it wherever you want after its created.  The way Google Drive's API works, it doesn't matter what the folder is named or where it is.  Backups will always go to that folder.
