### ISSUE TITLE
Sensors

### ISSUE THREAD

**Issue by EnBaldric** [sabeechen/hassio-google-drive-backup#963]
Under Settings, I have deselected the following options:

- Enable Backup Staleness Sensor
- Enable Backup State Sensor

However, both sensors (binary_sensor.backups_stale and sensor.backup_state) remain in my Home Assistant.

**Comment by sabeechen** [comment]
The last published value should stick around until the next time you restart Home Assistant.  Are they still getting published after you disabled them?

**Comment by EnBaldric** [comment]
Sorry, I forgot to restart my Home Assistant. Everything is fine now.

Thank you for your app. It's very useful. And have a happy new year.
