### ISSUE TITLE
Moved HA to larger SSD Drive, Google Drive Backup Not Starting

### ISSUE THREAD

**Issue by MattMake** [sabeechen/hassio-google-drive-backup#964]
I recently upgraded the SSD in my HA server and restored from backup.  I noticed that Google Drive Backup was not starting (looking at add-ons):
![image](https://github.com/sabeechen/hassio-google-drive-backup/assets/39313738/89739b35-043e-47b9-b2ca-9b8099b255d0)

I clicked 'start', and it runs for a few minutes, then goes back to this same screen.  With verbose turned on, I do not see anything out of the ordinary in the add-on logs.
![image](https://github.com/sabeechen/hassio-google-drive-backup/assets/39313738/2bf67e3e-c885-4967-87bd-7d0a7cf74203)

I checked HA supervisor logs, and see what appears to be the add-on starting, but other messages saying it is already running.
![image](https://github.com/sabeechen/hassio-google-drive-backup/assets/39313738/a24351a2-2591-45f1-9c27-c876b39172cb)

I did attempt to uninstall, remove the add-on, and re-add/install it, but getting the same results.  Any guidance would be greatly appreciated!  This add-on has been a time and data lifesaver already!

**Comment by MattMake** [comment]
Just a follow-up, I used the instructions you gave for another request, I ran 'ha su repair', and the add-on started.

**Comment by sabeechen** [comment]
Strange, Id expect a docker error to show up if `ha su repair` fixed it.  I with I knew what was causing this, but I'll have to keep this in mind for future issues.
