### ISSUE TITLE
Aesthetics: stale=false has a "warning" icon in lovelace default dash

### ISSUE THREAD

**Issue by PieBru** [sabeechen/hassio-google-drive-backup#97]
Hi Stephen,
fortunately I never saw a `stale=true` icon :) but the `stale=false` "general warning sign"  icon is a bit alarming to me.
Maybe it shouldn't be so, or am I interpreting it in a wrong way?
Thanks,
Piero

**Comment by sabeechen** [comment]
I think so too, but this is the default way Home Assistant renders "problem" class sensors, which still seems to be the best category for the sensor to fall into.

Curiously, it looks like  "problem" has been removed from the official list of [device classes](https://www.home-assistant.io/components/sensor/#device-class) in Home Assistant, it was definitely there when I implemented it a few months ago.  Maybe I should just change it to the "general" class of sensor, then people can customize the icon in the entity editor if they don't like it?

**Comment by PieBru** [comment]
Yes, IMO it would be nicer to have a generic sensor icon when
problem=false, changing to sensor problem icon when problem=true.
Anyway, thanks for your great add-on.
Piero

Il mar 10 set 2019, 22:27 Stephen Beechen <notifications@github.com> ha
scritto:

**Comment by sabeechen** [comment]
I've removed the "problem" device class in 0.99.0, so it takes on the default class.
