### ISSUE TITLE
Backup not working 

### ISSUE THREAD

**Issue by diver2000** [sabeechen/hassio-google-drive-backup#971]
My Backup is pending but it dont work... 
[home-assistant-google-drive-backup.log.txt](https://github.com/sabeechen/hassio-google-drive-backup/files/13856587/home-assistant-google-drive-backup.log.txt)

**Comment by sabeechen** [comment]
Could you click the details of the pending backup and see what the supervisor logs there say?

**Comment by diver2000** [comment]
I start 3 Times New, now it works.

Am 10.01.2024 03:26 schrieb Stephen Beechen ***@***.***>:

Could you click the details of the pending backup and see what the supervisor logs there say?

**Comment by sabeechen** [comment]
If it happens again, you should be able to click on the pending backup and see the supervisor logs, which usually give a hint about hwy the backup is stuck in the pending state.  The most common reason for it these days is a broken NAS connection, if you store your backups on a NAS.
