### ISSUE TITLE
Failed to start add-on 500 Server Error

### ISSUE THREAD

**Issue by Taldir** [sabeechen/hassio-google-drive-backup#973]
Hi,,
I got an error during addon startup on 0.112.1:
`Failed to start add-on 500 Server Error for http+docker://localhost/v1.43/containers/addon_cebe7a76_hassio_google_drive_backup/json: Internal Server Error ("readlink /mnt/data/docker/overlay2/l/7V5OIBVJFN2HVWEBS3GMZ6GSSA: no such file or directory")`

Reinstallation including removing repo and host restart didn't help.
Previously it worked perfectly to one of the HomeAssistan updates (unfortunatelly I don't know which one).
Last successfull backup is from 05.12.2023.

Any sugestions?

**Comment by sabeechen** [comment]
This is unfortunate.  Most docker errors like this in Home Assistant leave it in an unrecoverable state.  You can read more about it in [this issue](https://github.com/sabeechen/hassio-google-drive-backup/issues/952).  There are some things you can try:

-  Install the "SSH Add-on" and run the command `ha su repair`.  This does some cleanup of the HA docker environment and has a chance of fixing it.
- if you're able to get ssh access to the host (which is usually pretty complicated) you can delete the broken directory and reinstall like the user in the issue above, though this has a chance of corruption.

The only other option is to reinstall HA from scratch and restore a backup.  Its a problem in Home Assistant that I'm unable to do anything about from the Add-on side of things.

**Comment by Taldir** [comment]
Thanks for your advice. The `ha su repair` worked perfectly in my case.

**Comment by sabeechen** [comment]
Glad it was that easy!
