### ISSUE TITLE
Add-on wants to delete a LOT of backups including today's

### ISSUE THREAD

**Issue by thisisbenwoo** [sabeechen/hassio-google-drive-backup#975]
Hello,
I just received the following information:
**Attempting to Delete Multiple Backups**
The add-on attempted to delete 414 backup(s) from Google Drive and 109 backup(s) from Home Assistant. Under normal circumstance, the add-on will only delete one backup at a time (the oldest). This warning is produced to prevent the add-on from accidentally deleting your history of backups. This is normal if you recently lowered the number of backups to keep in Google Drive or Home Assistant.

I have restarted the add-on, I've reauthed with Google. My config is as follows:
```
max_backups_in_ha: 128
max_backups_in_google_drive: 1024
days_between_backups: 1
ignore_upgrade_backups: false
backup_time_of_day: "03:21"
send_error_reports: true
generational_days: 30
generational_weeks: 13
generational_months: 12
generational_years: 3
generational_delete_early: true
max_sync_interval_seconds: 3600
ha_reporting_interval_seconds: 180
```
Backup Statistics as follows:
141 (20.6 GB) in Home Assistant
19.0 GB remaining info
460 (78.8 GB) in Google Drive
47.6 GB remaining info
bwoo@orange.fr

I see no reason why it would want to delete so many including today's. Can you advise what I might be doing wrong?

Thanks

Ben

**Comment by sabeechen** [comment]
Did you change your settings recently, for example to delete gerational backups early?

**Comment by thisisbenwoo** [comment]
I don't remember changing that option. I think I had set it to true from the beginning. The only thing I've been doing is to increase the # of backups since that was a recommended solution, but I've been increasing the # of backups for several weeks now. As you can see, the numbers are quite staggering (1024 backups in Google!) Generally, I like to keep things for a LONG time.

**Comment by sabeechen** [comment]
It doesn't totally make sense if you havent changed that option recently, but given your current settings it should be trying to delete about that many.

The "delete early" option for generational backups instructs the add-on to delete backups that aren't part of the generational schedule, even I'd you haven't hit your limit in HA or Google Drive yet.  So in your case having it turned on means it will keep at most 30+13+12=55 backups (minus schedule overlaps).  I think you just need to turn that off if you want to keep them all.

**Comment by thisisbenwoo** [comment]
Thank you, the # reduced to 13 ...  and does not include today's. thanks again!
```
To be deleted from Google Drive:
To be deleted from Home Assistant:
addon_core_zwave_js_0.1.97
WeeklyBackup: Sunday, November 12, 2023
Full Backup 2023-12-25 03:21:00
AutoBackup: Tue, 12:00 AM (26/12/2023)
DailyBackup: Tuesday, December 26, 2023
AutoBackup: Tue, 3:00 AM (26/12/2023)
Full Backup 2023-12-26 03:21:00
AutoBackup: Tue, 6:00 AM (26/12/2023)
AutoBackup: Tue, 9:00 AM (26/12/2023)
AutoBackup: Tue, 12:00 PM (26/12/2023)
AutoBackup: Tue, 3:00 PM (26/12/2023)
AutoBackup: Tue, 6:00 PM (26/12/2023)
AutoBackup: Wed, 12:00 AM (27/12/2023)
```
