### ISSUE TITLE
Backup Setup - did not start after installation over hacs for the first time (24 hours ago)

### ISSUE THREAD

**Issue by typxxi** [sabeechen/hassio-google-drive-backup#979]
I am not sure what has happened.

I had installed the addon a day ago or so. And nothing happened afterwards. I could not start it, I could not follow the instructions and it did seemto not work at all. The button I pressed did not react at all yesterday evening. 

Today or at least 24 hours later for whatever reason I was working on a development and must have clicked on the side bar cause suddenly goolge drive backup screen appeared for the first time and there was also an icon in the sidebar.

So i gave it another try and now I was able to press the button and get a reaction from google which asked me for access - yesterday nothing like that had happened.

So I set it up properly reading the instructions again I had read yesterday and now everything works as described like excluding my own backups which I wanna save as milestones or deleting after backup or deleting after more than 3 backups uploaded.

I could not believe it cause yesterday everything had been in vain and now it worked.

The only difference might be that I can remember that I had restarted HA fully 10 minutes or so earlier. 
I know my error description is not good cause I was not prepared to write a bug report after I had given up yesterday (which meant I had lost time before for a onedrive solution which had not worked too and then went to google drive), but I hope you have a clue what went wrong cause it can not be the setup cause i have not touched it again for at least 24 hours . 
The big difference was the moment I got a google reply like that it is right that the addon gets access. 
As I said totally suprised and not ready to write down what I had done yesterday or even today until I suddenly realised that it worked like a charme and therefore also checked the upload limit which I had reduced from 5 to 2 or so just to see if such a new backup from minutes ago - I mean at least the oldest would be deleted and if I could see someting in the logs. And yes, it worked fine.

Hats off - great add on. Maybe my fault that I might have missed a full restart as mandatory. But just wanna let you know about my story.

**Comment by sabeechen** [comment]
Home Assistant doesn't always update the addon page after an addon has been installed.  Its difficult to determine from your descriptions but it sounds like thats what happened.  Sometimes, you have to do  "hard refresh" (CTRL+F5) to get the page to update.  I've never been able to figure out why, I think its a bug in HA's UI.  If you see it in the future, the logs from the addon could be useful.
