### ISSUE TITLE
    Timed out communicating with habackup.io

### ISSUE THREAD

**Issue by vinceg0267** [sabeechen/hassio-google-drive-backup#983]
After configuring a Fritz Box as IP Client on a main modem/router I have problems with this addOn. I tried re-authenticating, delete old backup without success. I also tried syncing several times. I have no active firewalls.
[home-assistant-google-drive-backup.log](https://github.com/sabeechen/hassio-google-drive-backup/files/14155580/home-assistant-google-drive-backup.log)

**Comment by sabeechen** [comment]
I don't know anything about fritzbox, but the logs indicate the addon can't communicate with the addon's authentication server at http://habackup.io or any of the alternate backup servers.  Id expect this behaviour if something was preventing it from accessing the internet.  It doesn't do anything special when it talks to the internet.

**Comment by vinceg0267** [comment]
Yes, you are right and I solved it. All I had to do was connect the HA server directly to the fritzbox. Thank you.
