### ISSUE TITLE
Backup file doesn't get expected name

### ISSUE THREAD

**Issue by ahamro** [sabeechen/hassio-google-drive-backup#984]
In the process of switching my cloud storage from Google to S3 I deleted the superb hassio-google-drive-backup add-on. I must have had a very weak moment, after a whole day of trying to get rclone working.

Then I discovered I still needed the hassio-google-drive-backup add-on to automate the daily backups, so I reinstalled it.

It seems to be working OK, but now the resulting file names in the /backup directory don't have the expected format like  "Full_Backup_2024-02-03_07_00_00.tar", but they are just named  9bcea734.tar or  5487249a.tar

What might have gone wrong? How do I correct this?

The log doesn't show a problem:

02-04 11:47:33 INFO [backup.ha.hasource] Requesting a new backup
02-04 12:14:27 INFO [backup.watcher] A backup directory file was modified, we'll check for new backups soon.
02-04 12:14:37 DEBUG [backup.watcher] Checking backup source for changes...
02-04 12:15:03 INFO [backup.watcher] A backup directory file was modified, we'll check for new backups soon.
02-04 12:15:04 INFO [backup.ha.hasource] Backup finished
02-04 12:15:04 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
02-04 12:15:04 INFO [backup.model.coordinator] Syncing Backups
02-04 12:15:04 DEBUG [backup.ha.hasource] Adding a note to ha backup 'Full Backup 2024-02-04 11:47:33'
02-04 12:15:04 INFO [backup.ha.hasource] Deleting 'Full Backup 2024-01-26 07:00:00' from Home Assistant
02-04 12:15:14 DEBUG [backup.watcher] Checking backup source for changes...
02-04 12:15:14 DEBUG [backup.model.syncer] Sync requested by Backup Directory Watcher
02-04 12:15:14 INFO [backup.model.coordinator] Syncing Backups

(I'm running a Home Assistant Blue setup for Home Assistant, everything updated to the most recent versions.)

**Comment by sabeechen** [comment]
This is how Home Assistant names the backup files it creates, there isn't anything the addon can do about it.  The "name" associated with the backup is just metadata that HA embeds in it.  This addon only uses the more readable name when it uploads the file to Drive because it has control over what gets used there.

**Comment by ahamro** [comment]
I think I understand it and I have it working as before now.
Thanks for your prompt and clear answer!
