### ISSUE TITLE
ENHANCEMENT REQUEST: Backup called via Service Call automation (helpful for security motion)

### ISSUE THREAD

**Issue by rhodan412** [sabeechen/hassio-google-drive-backup#988]
A request for an enhancement feature to create and upload backup to Google Drive from an automation.

I know others, myself included, backup security camera motion to HA, and it would be helpful if there was a scenario/automation that could run a call service to create and upload the backup to Google Drive. 

Why this enhancement is useful:
- Imagine someone attempting to break into your house, a HA automation calls an alarm that not only notifies your device, but creates and uploads a backup of these images of the burglar.
- After breaking in, the burglar steals your networking equipment, security cameras' NVR, computers and also the HA hub.
- You come home and find your house ransacked and equipment gone that includes your motion backups of the perpetrator, but then you remember that this doesn't matter, because Google Drive has the images of the guilty party ready for your download.

**Comment by sabeechen** [comment]
You can trigger a backup using services from within home assistant, and the addon will back that up like anything else.  Eg:
![image](https://github.com/sabeechen/hassio-google-drive-backup/assets/21026774/40cfee3a-3c2d-4ac5-89dc-26d1e9852249)
